package com.tlg.prpins.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

/**
 * mantis：CLM0168，處理人員：BI086，需求單編號：CLM0168  區塊鏈查詢、新增及更新攤賠案件排程
 */
@SuppressWarnings("serial")
public class ClaimCompulsoryStatePrices extends IBatisBaseEntity<BigDecimal>{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_STATE_PRICES.OID
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private BigDecimal oid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_STATE_PRICES.OID_CLAIM_COMPULSORY_APPORTION
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private BigDecimal oidClaimCompulsoryApportion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_STATE_PRICES.TYPE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private String type;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_STATE_PRICES.AMOUNT
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private String amount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_STATE_PRICES.CODE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private String code;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_STATE_PRICES.ICREATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private String icreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_STATE_PRICES.DCREATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private Date dcreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_STATE_PRICES.IUPDATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private String iupdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_STATE_PRICES.DUPDATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private Date dupdate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_STATE_PRICES.OID
     *
     * @return the value of CLAIM_COMPULSORY_STATE_PRICES.OID
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public BigDecimal getOid() {
        return oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_STATE_PRICES.OID
     *
     * @param oid the value for CLAIM_COMPULSORY_STATE_PRICES.OID
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setOid(BigDecimal oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_STATE_PRICES.OID_CLAIM_COMPULSORY_APPORTION
     *
     * @return the value of CLAIM_COMPULSORY_STATE_PRICES.OID_CLAIM_COMPULSORY_APPORTION
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public BigDecimal getOidClaimCompulsoryApportion() {
        return oidClaimCompulsoryApportion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_STATE_PRICES.OID_CLAIM_COMPULSORY_APPORTION
     *
     * @param oidClaimCompulsoryApportion the value for CLAIM_COMPULSORY_STATE_PRICES.OID_CLAIM_COMPULSORY_APPORTION
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setOidClaimCompulsoryApportion(BigDecimal oidClaimCompulsoryApportion) {
        this.oidClaimCompulsoryApportion = oidClaimCompulsoryApportion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_STATE_PRICES.TYPE
     *
     * @return the value of CLAIM_COMPULSORY_STATE_PRICES.TYPE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_STATE_PRICES.TYPE
     *
     * @param type the value for CLAIM_COMPULSORY_STATE_PRICES.TYPE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_STATE_PRICES.AMOUNT
     *
     * @return the value of CLAIM_COMPULSORY_STATE_PRICES.AMOUNT
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_STATE_PRICES.AMOUNT
     *
     * @param amount the value for CLAIM_COMPULSORY_STATE_PRICES.AMOUNT
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setAmount(String amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_STATE_PRICES.CODE
     *
     * @return the value of CLAIM_COMPULSORY_STATE_PRICES.CODE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_STATE_PRICES.CODE
     *
     * @param code the value for CLAIM_COMPULSORY_STATE_PRICES.CODE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_STATE_PRICES.ICREATE
     *
     * @return the value of CLAIM_COMPULSORY_STATE_PRICES.ICREATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public String getIcreate() {
        return icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_STATE_PRICES.ICREATE
     *
     * @param icreate the value for CLAIM_COMPULSORY_STATE_PRICES.ICREATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setIcreate(String icreate) {
        this.icreate = icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_STATE_PRICES.DCREATE
     *
     * @return the value of CLAIM_COMPULSORY_STATE_PRICES.DCREATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public Date getDcreate() {
        return dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_STATE_PRICES.DCREATE
     *
     * @param dcreate the value for CLAIM_COMPULSORY_STATE_PRICES.DCREATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setDcreate(Date dcreate) {
        this.dcreate = dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_STATE_PRICES.IUPDATE
     *
     * @return the value of CLAIM_COMPULSORY_STATE_PRICES.IUPDATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public String getIupdate() {
        return iupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_STATE_PRICES.IUPDATE
     *
     * @param iupdate the value for CLAIM_COMPULSORY_STATE_PRICES.IUPDATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setIupdate(String iupdate) {
        this.iupdate = iupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_STATE_PRICES.DUPDATE
     *
     * @return the value of CLAIM_COMPULSORY_STATE_PRICES.DUPDATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public Date getDupdate() {
        return dupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_STATE_PRICES.DUPDATE
     *
     * @param dupdate the value for CLAIM_COMPULSORY_STATE_PRICES.DUPDATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setDupdate(Date dupdate) {
        this.dupdate = dupdate;
    }
}