package com.tlg.prpins.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

/**
 * mantis：CLM0168，處理人員：BI086，需求單編號：CLM0168  區塊鏈查詢、新增及更新攤賠案件排程
 */
@SuppressWarnings("serial")
public class ClaimCompulsoryCase extends IBatisBaseEntity<BigDecimal>{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_CASE.OID
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private BigDecimal oid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_CASE.APPLICANT_ROLE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private String applicantRole;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_CASE.POLICE_NAME
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private String policeName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_CASE.POLICE_UNIT
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private String policeUnit;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_CASE.HIT_ROAD
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private String hitRoad;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_CASE.IN_CAR_NUMBER
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private String inCarNumber;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_CASE.HIT_TIME
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private String hitTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_CASE.APPLICANT_TYPE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private String applicantType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_CASE.CASE_NUMBER
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private String caseNumber;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_CASE.ICREATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private String icreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_CASE.DCREATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private Date dcreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_CASE.IUPDATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private String iupdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_CASE.DUPDATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private Date dupdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_CASE.JOB_OID
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private BigDecimal jobOid;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_CASE.OID
     *
     * @return the value of CLAIM_COMPULSORY_CASE.OID
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public BigDecimal getOid() {
        return oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_CASE.OID
     *
     * @param oid the value for CLAIM_COMPULSORY_CASE.OID
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setOid(BigDecimal oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_CASE.APPLICANT_ROLE
     *
     * @return the value of CLAIM_COMPULSORY_CASE.APPLICANT_ROLE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public String getApplicantRole() {
        return applicantRole;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_CASE.APPLICANT_ROLE
     *
     * @param applicantRole the value for CLAIM_COMPULSORY_CASE.APPLICANT_ROLE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setApplicantRole(String applicantRole) {
        this.applicantRole = applicantRole;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_CASE.POLICE_NAME
     *
     * @return the value of CLAIM_COMPULSORY_CASE.POLICE_NAME
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public String getPoliceName() {
        return policeName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_CASE.POLICE_NAME
     *
     * @param policeName the value for CLAIM_COMPULSORY_CASE.POLICE_NAME
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setPoliceName(String policeName) {
        this.policeName = policeName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_CASE.POLICE_UNIT
     *
     * @return the value of CLAIM_COMPULSORY_CASE.POLICE_UNIT
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public String getPoliceUnit() {
        return policeUnit;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_CASE.POLICE_UNIT
     *
     * @param policeUnit the value for CLAIM_COMPULSORY_CASE.POLICE_UNIT
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setPoliceUnit(String policeUnit) {
        this.policeUnit = policeUnit;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_CASE.HIT_ROAD
     *
     * @return the value of CLAIM_COMPULSORY_CASE.HIT_ROAD
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public String getHitRoad() {
        return hitRoad;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_CASE.HIT_ROAD
     *
     * @param hitRoad the value for CLAIM_COMPULSORY_CASE.HIT_ROAD
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setHitRoad(String hitRoad) {
        this.hitRoad = hitRoad;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_CASE.IN_CAR_NUMBER
     *
     * @return the value of CLAIM_COMPULSORY_CASE.IN_CAR_NUMBER
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public String getInCarNumber() {
        return inCarNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_CASE.IN_CAR_NUMBER
     *
     * @param inCarNumber the value for CLAIM_COMPULSORY_CASE.IN_CAR_NUMBER
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setInCarNumber(String inCarNumber) {
        this.inCarNumber = inCarNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_CASE.HIT_TIME
     *
     * @return the value of CLAIM_COMPULSORY_CASE.HIT_TIME
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public String getHitTime() {
        return hitTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_CASE.HIT_TIME
     *
     * @param hitTime the value for CLAIM_COMPULSORY_CASE.HIT_TIME
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setHitTime(String hitTime) {
        this.hitTime = hitTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_CASE.APPLICANT_TYPE
     *
     * @return the value of CLAIM_COMPULSORY_CASE.APPLICANT_TYPE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public String getApplicantType() {
        return applicantType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_CASE.APPLICANT_TYPE
     *
     * @param applicantType the value for CLAIM_COMPULSORY_CASE.APPLICANT_TYPE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setApplicantType(String applicantType) {
        this.applicantType = applicantType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_CASE.CASE_NUMBER
     *
     * @return the value of CLAIM_COMPULSORY_CASE.CASE_NUMBER
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public String getCaseNumber() {
        return caseNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_CASE.CASE_NUMBER
     *
     * @param caseNumber the value for CLAIM_COMPULSORY_CASE.CASE_NUMBER
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setCaseNumber(String caseNumber) {
        this.caseNumber = caseNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_CASE.ICREATE
     *
     * @return the value of CLAIM_COMPULSORY_CASE.ICREATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public String getIcreate() {
        return icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_CASE.ICREATE
     *
     * @param icreate the value for CLAIM_COMPULSORY_CASE.ICREATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setIcreate(String icreate) {
        this.icreate = icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_CASE.DCREATE
     *
     * @return the value of CLAIM_COMPULSORY_CASE.DCREATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public Date getDcreate() {
        return dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_CASE.DCREATE
     *
     * @param dcreate the value for CLAIM_COMPULSORY_CASE.DCREATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setDcreate(Date dcreate) {
        this.dcreate = dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_CASE.IUPDATE
     *
     * @return the value of CLAIM_COMPULSORY_CASE.IUPDATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public String getIupdate() {
        return iupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_CASE.IUPDATE
     *
     * @param iupdate the value for CLAIM_COMPULSORY_CASE.IUPDATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setIupdate(String iupdate) {
        this.iupdate = iupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_CASE.DUPDATE
     *
     * @return the value of CLAIM_COMPULSORY_CASE.DUPDATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public Date getDupdate() {
        return dupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_CASE.DUPDATE
     *
     * @param dupdate the value for CLAIM_COMPULSORY_CASE.DUPDATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setDupdate(Date dupdate) {
        this.dupdate = dupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_CASE.JOB_OID
     *
     * @return the value of CLAIM_COMPULSORY_CASE.JOB_OID
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public BigDecimal getJobOid() {
        return jobOid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_CASE.JOB_OID
     *
     * @param jobOid the value for CLAIM_COMPULSORY_CASE.JOB_OID
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setJobOid(BigDecimal jobOid) {
        this.jobOid = jobOid;
    }
}