package com.tlg.prpins.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

/**
 * mantis：CLM0168，處理人員：BI086，需求單編號：CLM0168  區塊鏈查詢、新增及更新攤賠案件排程
 */
@SuppressWarnings("serial")
public class ClaimCompulsoryJob extends IBatisBaseEntity<BigDecimal>{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_JOB.OID
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private BigDecimal oid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_JOB.CLAIM_NO
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private String claimNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_JOB.TYPE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private String type;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_JOB.EXECUTE_TIME
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private Date executeTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_JOB.MSG
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private String msg;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_JOB.CODE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private String code;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_JOB.ICREATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private String icreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_JOB.DCREATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private Date dcreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_JOB.IUPDATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private String iupdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CLAIM_COMPULSORY_JOB.DUPDATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    private Date dupdate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_JOB.OID
     *
     * @return the value of CLAIM_COMPULSORY_JOB.OID
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    
    private String caseId;
    
    private String apportionId;
    
    
    public BigDecimal getOid() {
        return oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_JOB.OID
     *
     * @param oid the value for CLAIM_COMPULSORY_JOB.OID
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setOid(BigDecimal oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_JOB.CLAIM_NO
     *
     * @return the value of CLAIM_COMPULSORY_JOB.CLAIM_NO
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public String getClaimNo() {
        return claimNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_JOB.CLAIM_NO
     *
     * @param claimNo the value for CLAIM_COMPULSORY_JOB.CLAIM_NO
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setClaimNo(String claimNo) {
        this.claimNo = claimNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_JOB.TYPE
     *
     * @return the value of CLAIM_COMPULSORY_JOB.TYPE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_JOB.TYPE
     *
     * @param type the value for CLAIM_COMPULSORY_JOB.TYPE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_JOB.EXECUTE_TIME
     *
     * @return the value of CLAIM_COMPULSORY_JOB.EXECUTE_TIME
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public Date getExecuteTime() {
        return executeTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_JOB.EXECUTE_TIME
     *
     * @param executeTime the value for CLAIM_COMPULSORY_JOB.EXECUTE_TIME
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setExecuteTime(Date executeTime) {
        this.executeTime = executeTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_JOB.MSG
     *
     * @return the value of CLAIM_COMPULSORY_JOB.MSG
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_JOB.MSG
     *
     * @param msg the value for CLAIM_COMPULSORY_JOB.MSG
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setMsg(String msg) {
        this.msg = msg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_JOB.CODE
     *
     * @return the value of CLAIM_COMPULSORY_JOB.CODE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_JOB.CODE
     *
     * @param code the value for CLAIM_COMPULSORY_JOB.CODE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_JOB.ICREATE
     *
     * @return the value of CLAIM_COMPULSORY_JOB.ICREATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public String getIcreate() {
        return icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_JOB.ICREATE
     *
     * @param icreate the value for CLAIM_COMPULSORY_JOB.ICREATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setIcreate(String icreate) {
        this.icreate = icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_JOB.DCREATE
     *
     * @return the value of CLAIM_COMPULSORY_JOB.DCREATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public Date getDcreate() {
        return dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_JOB.DCREATE
     *
     * @param dcreate the value for CLAIM_COMPULSORY_JOB.DCREATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setDcreate(Date dcreate) {
        this.dcreate = dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_JOB.IUPDATE
     *
     * @return the value of CLAIM_COMPULSORY_JOB.IUPDATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public String getIupdate() {
        return iupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_JOB.IUPDATE
     *
     * @param iupdate the value for CLAIM_COMPULSORY_JOB.IUPDATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setIupdate(String iupdate) {
        this.iupdate = iupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CLAIM_COMPULSORY_JOB.DUPDATE
     *
     * @return the value of CLAIM_COMPULSORY_JOB.DUPDATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public Date getDupdate() {
        return dupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CLAIM_COMPULSORY_JOB.DUPDATE
     *
     * @param dupdate the value for CLAIM_COMPULSORY_JOB.DUPDATE
     *
     * @ibatorgenerated Tue Mar 05 14:39:59 CST 2024
     */
    public void setDupdate(Date dupdate) {
        this.dupdate = dupdate;
    }

	public String getCaseId() {
		return caseId;
	}

	public void setCaseId(String caseId) {
		this.caseId = caseId;
	}

	public String getApportionId() {
		return apportionId;
	}

	public void setApportionId(String apportionId) {
		this.apportionId = apportionId;
	}
}