package com.tlg.prpins.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

/** mantis：MOB0018，處理人員：BJ085，需求單編號：MOB0018 理賠資料提交及列印作業 */
@SuppressWarnings("serial")
public class Fetclaimmain extends IBatisBaseEntity<BigDecimal>{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.OID
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private BigDecimal oid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA00
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private Integer wda00;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA01
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda01;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA02
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda02;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA03
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda03;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA04
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda04;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA05
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda05;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA06
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda06;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA07
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda07;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA08
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private Integer wda08;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA09
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private Integer wda09;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA10
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private Integer wda10;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA11
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private Integer wda11;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA12
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda12;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA13
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private Integer wda13;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA14
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private Integer wda14;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA15
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda15;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA16
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda16;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA17
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda17;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA18
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda18;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA19
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda19;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA20
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private Integer wda20;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA21
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda21;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA22
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda22;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA23
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda23;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA24
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda24;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA25
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda25;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA26
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda26;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA27
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda27;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA28
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private Long wda28;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA29
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private Integer wda29;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA30
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private Long wda30;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA31
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private Integer wda31;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA32
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda32;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA33
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private Integer wda33;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA34
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private Integer wda34;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA35
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private Long wda35;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA36
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private Long wda36;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA37
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private Integer wda37;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA38
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda38;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA39
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda39;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA40
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda40;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA41
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private Integer wda41;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA42
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda42;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA43
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda43;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA44
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private BigDecimal wda44;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA45
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda45;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA46
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private Integer wda46;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA47
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda47;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA48
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda48;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA49
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda49;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA50
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda50;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA51
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda51;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA52
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda52;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA53
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda53;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA54
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda54;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA55
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda55;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA56
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda56;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA57
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda57;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA58
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda58;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA59
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda59;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA60
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda60;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA61
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda61;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA62
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda62;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA63
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda63;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA64
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private Date wda64;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA65
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda65;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.WDA66
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String wda66;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.DRAWOUTDATE
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private Date drawoutdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.DATASOURCE
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String datasource;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.FLOWID
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String flowid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.REGISTNO
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String registno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.REPORDER
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String reporder;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.NCLAIM
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private String nclaim;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FETCLAIMMAIN.NCLAIMDATE
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    private Date nclaimdate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.OID
     *
     * @return the value of FETCLAIMMAIN.OID
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public BigDecimal getOid() {
        return oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.OID
     *
     * @param oid the value for FETCLAIMMAIN.OID
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setOid(BigDecimal oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA00
     *
     * @return the value of FETCLAIMMAIN.WDA00
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public Integer getWda00() {
        return wda00;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA00
     *
     * @param wda00 the value for FETCLAIMMAIN.WDA00
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda00(Integer wda00) {
        this.wda00 = wda00;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA01
     *
     * @return the value of FETCLAIMMAIN.WDA01
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda01() {
        return wda01;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA01
     *
     * @param wda01 the value for FETCLAIMMAIN.WDA01
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda01(String wda01) {
        this.wda01 = wda01;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA02
     *
     * @return the value of FETCLAIMMAIN.WDA02
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda02() {
        return wda02;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA02
     *
     * @param wda02 the value for FETCLAIMMAIN.WDA02
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda02(String wda02) {
        this.wda02 = wda02;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA03
     *
     * @return the value of FETCLAIMMAIN.WDA03
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda03() {
        return wda03;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA03
     *
     * @param wda03 the value for FETCLAIMMAIN.WDA03
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda03(String wda03) {
        this.wda03 = wda03;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA04
     *
     * @return the value of FETCLAIMMAIN.WDA04
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda04() {
        return wda04;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA04
     *
     * @param wda04 the value for FETCLAIMMAIN.WDA04
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda04(String wda04) {
        this.wda04 = wda04;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA05
     *
     * @return the value of FETCLAIMMAIN.WDA05
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda05() {
        return wda05;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA05
     *
     * @param wda05 the value for FETCLAIMMAIN.WDA05
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda05(String wda05) {
        this.wda05 = wda05;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA06
     *
     * @return the value of FETCLAIMMAIN.WDA06
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda06() {
        return wda06;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA06
     *
     * @param wda06 the value for FETCLAIMMAIN.WDA06
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda06(String wda06) {
        this.wda06 = wda06;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA07
     *
     * @return the value of FETCLAIMMAIN.WDA07
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda07() {
        return wda07;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA07
     *
     * @param wda07 the value for FETCLAIMMAIN.WDA07
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda07(String wda07) {
        this.wda07 = wda07;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA08
     *
     * @return the value of FETCLAIMMAIN.WDA08
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public Integer getWda08() {
        return wda08;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA08
     *
     * @param wda08 the value for FETCLAIMMAIN.WDA08
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda08(Integer wda08) {
        this.wda08 = wda08;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA09
     *
     * @return the value of FETCLAIMMAIN.WDA09
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public Integer getWda09() {
        return wda09;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA09
     *
     * @param wda09 the value for FETCLAIMMAIN.WDA09
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda09(Integer wda09) {
        this.wda09 = wda09;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA10
     *
     * @return the value of FETCLAIMMAIN.WDA10
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public Integer getWda10() {
        return wda10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA10
     *
     * @param wda10 the value for FETCLAIMMAIN.WDA10
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda10(Integer wda10) {
        this.wda10 = wda10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA11
     *
     * @return the value of FETCLAIMMAIN.WDA11
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public Integer getWda11() {
        return wda11;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA11
     *
     * @param wda11 the value for FETCLAIMMAIN.WDA11
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda11(Integer wda11) {
        this.wda11 = wda11;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA12
     *
     * @return the value of FETCLAIMMAIN.WDA12
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda12() {
        return wda12;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA12
     *
     * @param wda12 the value for FETCLAIMMAIN.WDA12
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda12(String wda12) {
        this.wda12 = wda12;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA13
     *
     * @return the value of FETCLAIMMAIN.WDA13
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public Integer getWda13() {
        return wda13;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA13
     *
     * @param wda13 the value for FETCLAIMMAIN.WDA13
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda13(Integer wda13) {
        this.wda13 = wda13;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA14
     *
     * @return the value of FETCLAIMMAIN.WDA14
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public Integer getWda14() {
        return wda14;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA14
     *
     * @param wda14 the value for FETCLAIMMAIN.WDA14
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda14(Integer wda14) {
        this.wda14 = wda14;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA15
     *
     * @return the value of FETCLAIMMAIN.WDA15
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda15() {
        return wda15;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA15
     *
     * @param wda15 the value for FETCLAIMMAIN.WDA15
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda15(String wda15) {
        this.wda15 = wda15;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA16
     *
     * @return the value of FETCLAIMMAIN.WDA16
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda16() {
        return wda16;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA16
     *
     * @param wda16 the value for FETCLAIMMAIN.WDA16
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda16(String wda16) {
        this.wda16 = wda16;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA17
     *
     * @return the value of FETCLAIMMAIN.WDA17
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda17() {
        return wda17;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA17
     *
     * @param wda17 the value for FETCLAIMMAIN.WDA17
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda17(String wda17) {
        this.wda17 = wda17;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA18
     *
     * @return the value of FETCLAIMMAIN.WDA18
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda18() {
        return wda18;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA18
     *
     * @param wda18 the value for FETCLAIMMAIN.WDA18
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda18(String wda18) {
        this.wda18 = wda18;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA19
     *
     * @return the value of FETCLAIMMAIN.WDA19
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda19() {
        return wda19;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA19
     *
     * @param wda19 the value for FETCLAIMMAIN.WDA19
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda19(String wda19) {
        this.wda19 = wda19;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA20
     *
     * @return the value of FETCLAIMMAIN.WDA20
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public Integer getWda20() {
        return wda20;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA20
     *
     * @param wda20 the value for FETCLAIMMAIN.WDA20
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda20(Integer wda20) {
        this.wda20 = wda20;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA21
     *
     * @return the value of FETCLAIMMAIN.WDA21
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda21() {
        return wda21;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA21
     *
     * @param wda21 the value for FETCLAIMMAIN.WDA21
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda21(String wda21) {
        this.wda21 = wda21;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA22
     *
     * @return the value of FETCLAIMMAIN.WDA22
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda22() {
        return wda22;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA22
     *
     * @param wda22 the value for FETCLAIMMAIN.WDA22
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda22(String wda22) {
        this.wda22 = wda22;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA23
     *
     * @return the value of FETCLAIMMAIN.WDA23
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda23() {
        return wda23;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA23
     *
     * @param wda23 the value for FETCLAIMMAIN.WDA23
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda23(String wda23) {
        this.wda23 = wda23;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA24
     *
     * @return the value of FETCLAIMMAIN.WDA24
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda24() {
        return wda24;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA24
     *
     * @param wda24 the value for FETCLAIMMAIN.WDA24
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda24(String wda24) {
        this.wda24 = wda24;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA25
     *
     * @return the value of FETCLAIMMAIN.WDA25
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda25() {
        return wda25;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA25
     *
     * @param wda25 the value for FETCLAIMMAIN.WDA25
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda25(String wda25) {
        this.wda25 = wda25;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA26
     *
     * @return the value of FETCLAIMMAIN.WDA26
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda26() {
        return wda26;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA26
     *
     * @param wda26 the value for FETCLAIMMAIN.WDA26
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda26(String wda26) {
        this.wda26 = wda26;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA27
     *
     * @return the value of FETCLAIMMAIN.WDA27
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda27() {
        return wda27;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA27
     *
     * @param wda27 the value for FETCLAIMMAIN.WDA27
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda27(String wda27) {
        this.wda27 = wda27;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA28
     *
     * @return the value of FETCLAIMMAIN.WDA28
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public Long getWda28() {
        return wda28;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA28
     *
     * @param wda28 the value for FETCLAIMMAIN.WDA28
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda28(Long wda28) {
        this.wda28 = wda28;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA29
     *
     * @return the value of FETCLAIMMAIN.WDA29
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public Integer getWda29() {
        return wda29;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA29
     *
     * @param wda29 the value for FETCLAIMMAIN.WDA29
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda29(Integer wda29) {
        this.wda29 = wda29;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA30
     *
     * @return the value of FETCLAIMMAIN.WDA30
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public Long getWda30() {
        return wda30;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA30
     *
     * @param wda30 the value for FETCLAIMMAIN.WDA30
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda30(Long wda30) {
        this.wda30 = wda30;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA31
     *
     * @return the value of FETCLAIMMAIN.WDA31
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public Integer getWda31() {
        return wda31;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA31
     *
     * @param wda31 the value for FETCLAIMMAIN.WDA31
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda31(Integer wda31) {
        this.wda31 = wda31;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA32
     *
     * @return the value of FETCLAIMMAIN.WDA32
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda32() {
        return wda32;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA32
     *
     * @param wda32 the value for FETCLAIMMAIN.WDA32
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda32(String wda32) {
        this.wda32 = wda32;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA33
     *
     * @return the value of FETCLAIMMAIN.WDA33
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public Integer getWda33() {
        return wda33;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA33
     *
     * @param wda33 the value for FETCLAIMMAIN.WDA33
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda33(Integer wda33) {
        this.wda33 = wda33;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA34
     *
     * @return the value of FETCLAIMMAIN.WDA34
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public Integer getWda34() {
        return wda34;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA34
     *
     * @param wda34 the value for FETCLAIMMAIN.WDA34
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda34(Integer wda34) {
        this.wda34 = wda34;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA35
     *
     * @return the value of FETCLAIMMAIN.WDA35
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public Long getWda35() {
        return wda35;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA35
     *
     * @param wda35 the value for FETCLAIMMAIN.WDA35
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda35(Long wda35) {
        this.wda35 = wda35;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA36
     *
     * @return the value of FETCLAIMMAIN.WDA36
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public Long getWda36() {
        return wda36;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA36
     *
     * @param wda36 the value for FETCLAIMMAIN.WDA36
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda36(Long wda36) {
        this.wda36 = wda36;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA37
     *
     * @return the value of FETCLAIMMAIN.WDA37
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public Integer getWda37() {
        return wda37;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA37
     *
     * @param wda37 the value for FETCLAIMMAIN.WDA37
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda37(Integer wda37) {
        this.wda37 = wda37;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA38
     *
     * @return the value of FETCLAIMMAIN.WDA38
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda38() {
        return wda38;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA38
     *
     * @param wda38 the value for FETCLAIMMAIN.WDA38
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda38(String wda38) {
        this.wda38 = wda38;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA39
     *
     * @return the value of FETCLAIMMAIN.WDA39
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda39() {
        return wda39;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA39
     *
     * @param wda39 the value for FETCLAIMMAIN.WDA39
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda39(String wda39) {
        this.wda39 = wda39;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA40
     *
     * @return the value of FETCLAIMMAIN.WDA40
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda40() {
        return wda40;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA40
     *
     * @param wda40 the value for FETCLAIMMAIN.WDA40
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda40(String wda40) {
        this.wda40 = wda40;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA41
     *
     * @return the value of FETCLAIMMAIN.WDA41
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public Integer getWda41() {
        return wda41;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA41
     *
     * @param wda41 the value for FETCLAIMMAIN.WDA41
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda41(Integer wda41) {
        this.wda41 = wda41;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA42
     *
     * @return the value of FETCLAIMMAIN.WDA42
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda42() {
        return wda42;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA42
     *
     * @param wda42 the value for FETCLAIMMAIN.WDA42
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda42(String wda42) {
        this.wda42 = wda42;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA43
     *
     * @return the value of FETCLAIMMAIN.WDA43
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda43() {
        return wda43;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA43
     *
     * @param wda43 the value for FETCLAIMMAIN.WDA43
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda43(String wda43) {
        this.wda43 = wda43;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA44
     *
     * @return the value of FETCLAIMMAIN.WDA44
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public BigDecimal getWda44() {
        return wda44;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA44
     *
     * @param wda44 the value for FETCLAIMMAIN.WDA44
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda44(BigDecimal wda44) {
        this.wda44 = wda44;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA45
     *
     * @return the value of FETCLAIMMAIN.WDA45
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda45() {
        return wda45;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA45
     *
     * @param wda45 the value for FETCLAIMMAIN.WDA45
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda45(String wda45) {
        this.wda45 = wda45;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA46
     *
     * @return the value of FETCLAIMMAIN.WDA46
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public Integer getWda46() {
        return wda46;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA46
     *
     * @param wda46 the value for FETCLAIMMAIN.WDA46
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda46(Integer wda46) {
        this.wda46 = wda46;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA47
     *
     * @return the value of FETCLAIMMAIN.WDA47
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda47() {
        return wda47;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA47
     *
     * @param wda47 the value for FETCLAIMMAIN.WDA47
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda47(String wda47) {
        this.wda47 = wda47;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA48
     *
     * @return the value of FETCLAIMMAIN.WDA48
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda48() {
        return wda48;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA48
     *
     * @param wda48 the value for FETCLAIMMAIN.WDA48
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda48(String wda48) {
        this.wda48 = wda48;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA49
     *
     * @return the value of FETCLAIMMAIN.WDA49
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda49() {
        return wda49;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA49
     *
     * @param wda49 the value for FETCLAIMMAIN.WDA49
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda49(String wda49) {
        this.wda49 = wda49;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA50
     *
     * @return the value of FETCLAIMMAIN.WDA50
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda50() {
        return wda50;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA50
     *
     * @param wda50 the value for FETCLAIMMAIN.WDA50
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda50(String wda50) {
        this.wda50 = wda50;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA51
     *
     * @return the value of FETCLAIMMAIN.WDA51
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda51() {
        return wda51;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA51
     *
     * @param wda51 the value for FETCLAIMMAIN.WDA51
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda51(String wda51) {
        this.wda51 = wda51;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA52
     *
     * @return the value of FETCLAIMMAIN.WDA52
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda52() {
        return wda52;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA52
     *
     * @param wda52 the value for FETCLAIMMAIN.WDA52
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda52(String wda52) {
        this.wda52 = wda52;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA53
     *
     * @return the value of FETCLAIMMAIN.WDA53
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda53() {
        return wda53;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA53
     *
     * @param wda53 the value for FETCLAIMMAIN.WDA53
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda53(String wda53) {
        this.wda53 = wda53;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA54
     *
     * @return the value of FETCLAIMMAIN.WDA54
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda54() {
        return wda54;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA54
     *
     * @param wda54 the value for FETCLAIMMAIN.WDA54
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda54(String wda54) {
        this.wda54 = wda54;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA55
     *
     * @return the value of FETCLAIMMAIN.WDA55
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda55() {
        return wda55;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA55
     *
     * @param wda55 the value for FETCLAIMMAIN.WDA55
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda55(String wda55) {
        this.wda55 = wda55;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA56
     *
     * @return the value of FETCLAIMMAIN.WDA56
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda56() {
        return wda56;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA56
     *
     * @param wda56 the value for FETCLAIMMAIN.WDA56
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda56(String wda56) {
        this.wda56 = wda56;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA57
     *
     * @return the value of FETCLAIMMAIN.WDA57
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda57() {
        return wda57;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA57
     *
     * @param wda57 the value for FETCLAIMMAIN.WDA57
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda57(String wda57) {
        this.wda57 = wda57;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA58
     *
     * @return the value of FETCLAIMMAIN.WDA58
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda58() {
        return wda58;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA58
     *
     * @param wda58 the value for FETCLAIMMAIN.WDA58
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda58(String wda58) {
        this.wda58 = wda58;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA59
     *
     * @return the value of FETCLAIMMAIN.WDA59
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda59() {
        return wda59;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA59
     *
     * @param wda59 the value for FETCLAIMMAIN.WDA59
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda59(String wda59) {
        this.wda59 = wda59;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA60
     *
     * @return the value of FETCLAIMMAIN.WDA60
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda60() {
        return wda60;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA60
     *
     * @param wda60 the value for FETCLAIMMAIN.WDA60
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda60(String wda60) {
        this.wda60 = wda60;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA61
     *
     * @return the value of FETCLAIMMAIN.WDA61
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda61() {
        return wda61;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA61
     *
     * @param wda61 the value for FETCLAIMMAIN.WDA61
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda61(String wda61) {
        this.wda61 = wda61;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA62
     *
     * @return the value of FETCLAIMMAIN.WDA62
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda62() {
        return wda62;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA62
     *
     * @param wda62 the value for FETCLAIMMAIN.WDA62
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda62(String wda62) {
        this.wda62 = wda62;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA63
     *
     * @return the value of FETCLAIMMAIN.WDA63
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda63() {
        return wda63;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA63
     *
     * @param wda63 the value for FETCLAIMMAIN.WDA63
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda63(String wda63) {
        this.wda63 = wda63;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA64
     *
     * @return the value of FETCLAIMMAIN.WDA64
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public Date getWda64() {
        return wda64;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA64
     *
     * @param wda64 the value for FETCLAIMMAIN.WDA64
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda64(Date wda64) {
        this.wda64 = wda64;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA65
     *
     * @return the value of FETCLAIMMAIN.WDA65
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda65() {
        return wda65;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA65
     *
     * @param wda65 the value for FETCLAIMMAIN.WDA65
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda65(String wda65) {
        this.wda65 = wda65;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.WDA66
     *
     * @return the value of FETCLAIMMAIN.WDA66
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getWda66() {
        return wda66;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.WDA66
     *
     * @param wda66 the value for FETCLAIMMAIN.WDA66
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setWda66(String wda66) {
        this.wda66 = wda66;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.DRAWOUTDATE
     *
     * @return the value of FETCLAIMMAIN.DRAWOUTDATE
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public Date getDrawoutdate() {
        return drawoutdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.DRAWOUTDATE
     *
     * @param drawoutdate the value for FETCLAIMMAIN.DRAWOUTDATE
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setDrawoutdate(Date drawoutdate) {
        this.drawoutdate = drawoutdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.DATASOURCE
     *
     * @return the value of FETCLAIMMAIN.DATASOURCE
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getDatasource() {
        return datasource;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.DATASOURCE
     *
     * @param datasource the value for FETCLAIMMAIN.DATASOURCE
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setDatasource(String datasource) {
        this.datasource = datasource;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.FLOWID
     *
     * @return the value of FETCLAIMMAIN.FLOWID
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getFlowid() {
        return flowid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.FLOWID
     *
     * @param flowid the value for FETCLAIMMAIN.FLOWID
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setFlowid(String flowid) {
        this.flowid = flowid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.REGISTNO
     *
     * @return the value of FETCLAIMMAIN.REGISTNO
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getRegistno() {
        return registno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.REGISTNO
     *
     * @param registno the value for FETCLAIMMAIN.REGISTNO
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setRegistno(String registno) {
        this.registno = registno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.REPORDER
     *
     * @return the value of FETCLAIMMAIN.REPORDER
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getReporder() {
        return reporder;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.REPORDER
     *
     * @param reporder the value for FETCLAIMMAIN.REPORDER
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setReporder(String reporder) {
        this.reporder = reporder;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.NCLAIM
     *
     * @return the value of FETCLAIMMAIN.NCLAIM
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public String getNclaim() {
        return nclaim;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.NCLAIM
     *
     * @param nclaim the value for FETCLAIMMAIN.NCLAIM
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setNclaim(String nclaim) {
        this.nclaim = nclaim;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FETCLAIMMAIN.NCLAIMDATE
     *
     * @return the value of FETCLAIMMAIN.NCLAIMDATE
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public Date getNclaimdate() {
        return nclaimdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FETCLAIMMAIN.NCLAIMDATE
     *
     * @param nclaimdate the value for FETCLAIMMAIN.NCLAIMDATE
     *
     * @ibatorgenerated Fri Jun 02 17:55:11 CST 2023
     */
    public void setNclaimdate(Date nclaimdate) {
        this.nclaimdate = nclaimdate;
    }
}