package com.tlg.prpins.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

/** mantis：FIR0676，處理人員：DP0706，需求單編號：FIR0676_住火_元大續保作業_N+1比對擔保品檔案**/
@SuppressWarnings("serial")
public class FirAgtrnYcbUpload  extends IBatisBaseEntity<BigDecimal>{
	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_YCB_UPLOAD.BATCH_NO
     *
     * @ibatorgenerated Fri Mar 07 10:57:03 CST 2025
     */
    private String batchNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_YCB_UPLOAD.OLDPOLICYNO
     *
     * @ibatorgenerated Fri Mar 07 10:57:03 CST 2025
     */
    private String oldpolicyno;
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_YCB_UPLOAD.COLLATERALNUMBER
     *
     * @ibatorgenerated Fri Mar 07 10:57:03 CST 2025
     */
    private String collateralnumber;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_YCB_UPLOAD.IS_RENEW
     *
     * @ibatorgenerated Fri Mar 07 10:57:03 CST 2025
     */
    private Object isRenew;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_YCB_UPLOAD.ICREATE
     *
     * @ibatorgenerated Fri Mar 07 10:57:03 CST 2025
     */
    private String icreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_YCB_UPLOAD.DCREATE
     *
     * @ibatorgenerated Fri Mar 07 10:57:03 CST 2025
     */
    private Date dcreate;
    
    //mantis：FIR0684，處理人員：DP0706，需求單編號：FIR0684_住火_APS元大續保作業_N+1轉檔新增填寫出單業務員欄位
    private String handleridentifynumber;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_YCB_UPLOAD.COLLATERALNUMBER
     *
     * @return the value of FIR_AGTRN_YCB_UPLOAD.COLLATERALNUMBER
     *
     * @ibatorgenerated Fri Mar 07 10:57:03 CST 2025
     */
    public String getCollateralnumber() {
        return collateralnumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_YCB_UPLOAD.COLLATERALNUMBER
     *
     * @param collateralnumber the value for FIR_AGTRN_YCB_UPLOAD.COLLATERALNUMBER
     *
     * @ibatorgenerated Fri Mar 07 10:57:03 CST 2025
     */
    public void setCollateralnumber(String collateralnumber) {
        this.collateralnumber = collateralnumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_YCB_UPLOAD.IS_RENEW
     *
     * @return the value of FIR_AGTRN_YCB_UPLOAD.IS_RENEW
     *
     * @ibatorgenerated Fri Mar 07 10:57:03 CST 2025
     */
    public Object getIsRenew() {
        return isRenew;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_YCB_UPLOAD.IS_RENEW
     *
     * @param isRenew the value for FIR_AGTRN_YCB_UPLOAD.IS_RENEW
     *
     * @ibatorgenerated Fri Mar 07 10:57:03 CST 2025
     */
    public void setIsRenew(Object isRenew) {
        this.isRenew = isRenew;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_YCB_UPLOAD.ICREATE
     *
     * @return the value of FIR_AGTRN_YCB_UPLOAD.ICREATE
     *
     * @ibatorgenerated Fri Mar 07 10:57:03 CST 2025
     */
    public String getIcreate() {
        return icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_YCB_UPLOAD.ICREATE
     *
     * @param icreate the value for FIR_AGTRN_YCB_UPLOAD.ICREATE
     *
     * @ibatorgenerated Fri Mar 07 10:57:03 CST 2025
     */
    public void setIcreate(String icreate) {
        this.icreate = icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_YCB_UPLOAD.DCREATE
     *
     * @return the value of FIR_AGTRN_YCB_UPLOAD.DCREATE
     *
     * @ibatorgenerated Fri Mar 07 10:57:03 CST 2025
     */
    public Date getDcreate() {
        return dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_YCB_UPLOAD.DCREATE
     *
     * @param dcreate the value for FIR_AGTRN_YCB_UPLOAD.DCREATE
     *
     * @ibatorgenerated Fri Mar 07 10:57:03 CST 2025
     */
    public void setDcreate(Date dcreate) {
        this.dcreate = dcreate;
    }

	public String getBatchNo() {
		return batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	public String getOldpolicyno() {
		return oldpolicyno;
	}

	public void setOldpolicyno(String oldpolicyno) {
		this.oldpolicyno = oldpolicyno;
	}

	//mantis：FIR0684，處理人員：DP0706，需求單編號：FIR0684_住火_APS元大續保作業_N+1轉檔新增填寫出單業務員欄位START
	public String getHandleridentifynumber() {
		return handleridentifynumber;
	}

	public void setHandleridentifynumber(String handleridentifynumber) {
		this.handleridentifynumber = handleridentifynumber;
	}
	//mantis：FIR0684，處理人員：DP0706，需求單編號：FIR0684_住火_APS元大續保作業_N+1轉檔新增填寫出單業務員欄位END
}