package com.tlg.prpins.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

@SuppressWarnings("serial")
public class FirAgtrnBatchMain extends IBatisBaseEntity<BigDecimal>{
	/* mantis：FIR0294，處理人員：BJ085，需求單編號：FIR0294 外銀板信續件移回新核心-資料接收排程 start */
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_BATCH_MAIN.BATCH_NO
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    private String batchNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_BATCH_MAIN.FILENAME
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    private String filename;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_BATCH_MAIN.BUSINESSNATURE
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    private String businessnature;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_BATCH_MAIN.DATAQTY_T
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    private Integer dataqtyT;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_BATCH_MAIN.DATAQTY_S
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    private Integer dataqtyS;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_BATCH_MAIN.DATAQTY_F
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    private Integer dataqtyF;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_BATCH_MAIN.FILE_STATUS
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    private String fileStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_BATCH_MAIN.TRANS_STATUS
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    private String transStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_BATCH_MAIN.DELETE_FLAG
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    private String deleteFlag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_BATCH_MAIN.REMARK
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    private String remark;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_BATCH_MAIN.ICREATE
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    private String icreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_BATCH_MAIN.DCREATE
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    private Date dcreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_BATCH_MAIN.IUPDATE
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    private String iupdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_BATCH_MAIN.DUPDATE
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    private Date dupdate;
    
    // mantis：FIR0621，處理人員：BJ085，需求單編號：FIR0621 住火_臺銀續保作業_續件資料處理作業
    private String rnYyyymm;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_BATCH_MAIN.BATCH_NO
     *
     * @return the value of FIR_AGTRN_BATCH_MAIN.BATCH_NO
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_BATCH_MAIN.BATCH_NO
     *
     * @param batchNo the value for FIR_AGTRN_BATCH_MAIN.BATCH_NO
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_BATCH_MAIN.FILENAME
     *
     * @return the value of FIR_AGTRN_BATCH_MAIN.FILENAME
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_BATCH_MAIN.FILENAME
     *
     * @param filename the value for FIR_AGTRN_BATCH_MAIN.FILENAME
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_BATCH_MAIN.BUSINESSNATURE
     *
     * @return the value of FIR_AGTRN_BATCH_MAIN.BUSINESSNATURE
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    public String getBusinessnature() {
        return businessnature;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_BATCH_MAIN.BUSINESSNATURE
     *
     * @param businessnature the value for FIR_AGTRN_BATCH_MAIN.BUSINESSNATURE
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    public void setBusinessnature(String businessnature) {
        this.businessnature = businessnature;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_BATCH_MAIN.DATAQTY_T
     *
     * @return the value of FIR_AGTRN_BATCH_MAIN.DATAQTY_T
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    public Integer getDataqtyT() {
        return dataqtyT;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_BATCH_MAIN.DATAQTY_T
     *
     * @param dataqtyT the value for FIR_AGTRN_BATCH_MAIN.DATAQTY_T
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    public void setDataqtyT(Integer dataqtyT) {
        this.dataqtyT = dataqtyT;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_BATCH_MAIN.DATAQTY_S
     *
     * @return the value of FIR_AGTRN_BATCH_MAIN.DATAQTY_S
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    public Integer getDataqtyS() {
        return dataqtyS;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_BATCH_MAIN.DATAQTY_S
     *
     * @param dataqtyS the value for FIR_AGTRN_BATCH_MAIN.DATAQTY_S
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    public void setDataqtyS(Integer dataqtyS) {
        this.dataqtyS = dataqtyS;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_BATCH_MAIN.DATAQTY_F
     *
     * @return the value of FIR_AGTRN_BATCH_MAIN.DATAQTY_F
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    public Integer getDataqtyF() {
        return dataqtyF;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_BATCH_MAIN.DATAQTY_F
     *
     * @param dataqtyF the value for FIR_AGTRN_BATCH_MAIN.DATAQTY_F
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    public void setDataqtyF(Integer dataqtyF) {
        this.dataqtyF = dataqtyF;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_BATCH_MAIN.FILE_STATUS
     *
     * @return the value of FIR_AGTRN_BATCH_MAIN.FILE_STATUS
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    public String getFileStatus() {
        return fileStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_BATCH_MAIN.FILE_STATUS
     *
     * @param fileStatus the value for FIR_AGTRN_BATCH_MAIN.FILE_STATUS
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    public void setFileStatus(String fileStatus) {
        this.fileStatus = fileStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_BATCH_MAIN.TRANS_STATUS
     *
     * @return the value of FIR_AGTRN_BATCH_MAIN.TRANS_STATUS
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    public String getTransStatus() {
        return transStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_BATCH_MAIN.TRANS_STATUS
     *
     * @param transStatus the value for FIR_AGTRN_BATCH_MAIN.TRANS_STATUS
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    public void setTransStatus(String transStatus) {
        this.transStatus = transStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_BATCH_MAIN.DELETE_FLAG
     *
     * @return the value of FIR_AGTRN_BATCH_MAIN.DELETE_FLAG
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_BATCH_MAIN.DELETE_FLAG
     *
     * @param deleteFlag the value for FIR_AGTRN_BATCH_MAIN.DELETE_FLAG
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_BATCH_MAIN.REMARK
     *
     * @return the value of FIR_AGTRN_BATCH_MAIN.REMARK
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_BATCH_MAIN.REMARK
     *
     * @param remark the value for FIR_AGTRN_BATCH_MAIN.REMARK
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_BATCH_MAIN.ICREATE
     *
     * @return the value of FIR_AGTRN_BATCH_MAIN.ICREATE
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    public String getIcreate() {
        return icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_BATCH_MAIN.ICREATE
     *
     * @param icreate the value for FIR_AGTRN_BATCH_MAIN.ICREATE
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    public void setIcreate(String icreate) {
        this.icreate = icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_BATCH_MAIN.DCREATE
     *
     * @return the value of FIR_AGTRN_BATCH_MAIN.DCREATE
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    public Date getDcreate() {
        return dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_BATCH_MAIN.DCREATE
     *
     * @param dcreate the value for FIR_AGTRN_BATCH_MAIN.DCREATE
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    public void setDcreate(Date dcreate) {
        this.dcreate = dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_BATCH_MAIN.IUPDATE
     *
     * @return the value of FIR_AGTRN_BATCH_MAIN.IUPDATE
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    public String getIupdate() {
        return iupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_BATCH_MAIN.IUPDATE
     *
     * @param iupdate the value for FIR_AGTRN_BATCH_MAIN.IUPDATE
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    public void setIupdate(String iupdate) {
        this.iupdate = iupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_BATCH_MAIN.DUPDATE
     *
     * @return the value of FIR_AGTRN_BATCH_MAIN.DUPDATE
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    public Date getDupdate() {
        return dupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_BATCH_MAIN.DUPDATE
     *
     * @param dupdate the value for FIR_AGTRN_BATCH_MAIN.DUPDATE
     *
     * @ibatorgenerated Tue May 04 10:40:26 CST 2021
     */
    public void setDupdate(Date dupdate) {
        this.dupdate = dupdate;
    }

    /* mantis：FIR0621，處理人員：BJ085，需求單編號：FIR0621 住火_臺銀續保作業_續件資料處理作業 start*/
	public String getRnYyyymm() {
		return rnYyyymm;
	}

	public void setRnYyyymm(String rnYyyymm) {
		this.rnYyyymm = rnYyyymm;
	}
	/* mantis：FIR0621，處理人員：BJ085，需求單編號：FIR0621 住火_臺銀續保作業_續件資料處理作業 end*/
    
}