package com.tlg.prpins.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

@SuppressWarnings("serial")
public class FirAgtrnTmpBop extends IBatisBaseEntity<BigDecimal>{
	/* mantis：FIR0294，處理人員：BJ085，需求單編號：FIR0294 外銀板信續件移回新核心-資料接收排程 start */
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_TMP_BOP.OID
     *
     * @ibatorgenerated Tue May 04 11:55:42 CST 2021
     */
    private BigDecimal oid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_TMP_BOP.BATCH_NO
     *
     * @ibatorgenerated Tue May 04 11:55:42 CST 2021
     */
    private String batchNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_TMP_BOP.BATCH_SEQ
     *
     * @ibatorgenerated Tue May 04 11:55:42 CST 2021
     */
    private Integer batchSeq;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_TMP_BOP.FILENAME
     *
     * @ibatorgenerated Tue May 04 11:55:42 CST 2021
     */
    private String filename;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_TMP_BOP.RAWDATA
     *
     * @ibatorgenerated Tue May 04 11:55:42 CST 2021
     */
    private String rawdata;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_TMP_BOP.P_STATUS
     *
     * @ibatorgenerated Tue May 04 11:55:42 CST 2021
     */
    private String pStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_TMP_BOP.ICREATE
     *
     * @ibatorgenerated Tue May 04 11:55:42 CST 2021
     */
    private String icreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_TMP_BOP.DCREATE
     *
     * @ibatorgenerated Tue May 04 11:55:42 CST 2021
     */
    private Date dcreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_TMP_BOP.IUPDATE
     *
     * @ibatorgenerated Tue May 04 11:55:42 CST 2021
     */
    private String iupdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_TMP_BOP.DUPDATE
     *
     * @ibatorgenerated Tue May 04 11:55:42 CST 2021
     */
    private Date dupdate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_TMP_BOP.OID
     *
     * @return the value of FIR_AGTRN_TMP_BOP.OID
     *
     * @ibatorgenerated Tue May 04 11:55:42 CST 2021
     */
    public BigDecimal getOid() {
        return oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_TMP_BOP.OID
     *
     * @param oid the value for FIR_AGTRN_TMP_BOP.OID
     *
     * @ibatorgenerated Tue May 04 11:55:42 CST 2021
     */
    public void setOid(BigDecimal oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_TMP_BOP.BATCH_NO
     *
     * @return the value of FIR_AGTRN_TMP_BOP.BATCH_NO
     *
     * @ibatorgenerated Tue May 04 11:55:42 CST 2021
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_TMP_BOP.BATCH_NO
     *
     * @param batchNo the value for FIR_AGTRN_TMP_BOP.BATCH_NO
     *
     * @ibatorgenerated Tue May 04 11:55:42 CST 2021
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_TMP_BOP.BATCH_SEQ
     *
     * @return the value of FIR_AGTRN_TMP_BOP.BATCH_SEQ
     *
     * @ibatorgenerated Tue May 04 11:55:42 CST 2021
     */
    public Integer getBatchSeq() {
        return batchSeq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_TMP_BOP.BATCH_SEQ
     *
     * @param batchSeq the value for FIR_AGTRN_TMP_BOP.BATCH_SEQ
     *
     * @ibatorgenerated Tue May 04 11:55:42 CST 2021
     */
    public void setBatchSeq(Integer batchSeq) {
        this.batchSeq = batchSeq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_TMP_BOP.FILENAME
     *
     * @return the value of FIR_AGTRN_TMP_BOP.FILENAME
     *
     * @ibatorgenerated Tue May 04 11:55:42 CST 2021
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_TMP_BOP.FILENAME
     *
     * @param filename the value for FIR_AGTRN_TMP_BOP.FILENAME
     *
     * @ibatorgenerated Tue May 04 11:55:42 CST 2021
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_TMP_BOP.RAWDATA
     *
     * @return the value of FIR_AGTRN_TMP_BOP.RAWDATA
     *
     * @ibatorgenerated Tue May 04 11:55:42 CST 2021
     */
    public String getRawdata() {
        return rawdata;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_TMP_BOP.RAWDATA
     *
     * @param rawdata the value for FIR_AGTRN_TMP_BOP.RAWDATA
     *
     * @ibatorgenerated Tue May 04 11:55:42 CST 2021
     */
    public void setRawdata(String rawdata) {
        this.rawdata = rawdata;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_TMP_BOP.P_STATUS
     *
     * @return the value of FIR_AGTRN_TMP_BOP.P_STATUS
     *
     * @ibatorgenerated Tue May 04 11:55:42 CST 2021
     */
    public String getpStatus() {
        return pStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_TMP_BOP.P_STATUS
     *
     * @param pStatus the value for FIR_AGTRN_TMP_BOP.P_STATUS
     *
     * @ibatorgenerated Tue May 04 11:55:42 CST 2021
     */
    public void setpStatus(String pStatus) {
        this.pStatus = pStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_TMP_BOP.ICREATE
     *
     * @return the value of FIR_AGTRN_TMP_BOP.ICREATE
     *
     * @ibatorgenerated Tue May 04 11:55:42 CST 2021
     */
    public String getIcreate() {
        return icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_TMP_BOP.ICREATE
     *
     * @param icreate the value for FIR_AGTRN_TMP_BOP.ICREATE
     *
     * @ibatorgenerated Tue May 04 11:55:42 CST 2021
     */
    public void setIcreate(String icreate) {
        this.icreate = icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_TMP_BOP.DCREATE
     *
     * @return the value of FIR_AGTRN_TMP_BOP.DCREATE
     *
     * @ibatorgenerated Tue May 04 11:55:42 CST 2021
     */
    public Date getDcreate() {
        return dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_TMP_BOP.DCREATE
     *
     * @param dcreate the value for FIR_AGTRN_TMP_BOP.DCREATE
     *
     * @ibatorgenerated Tue May 04 11:55:42 CST 2021
     */
    public void setDcreate(Date dcreate) {
        this.dcreate = dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_TMP_BOP.IUPDATE
     *
     * @return the value of FIR_AGTRN_TMP_BOP.IUPDATE
     *
     * @ibatorgenerated Tue May 04 11:55:42 CST 2021
     */
    public String getIupdate() {
        return iupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_TMP_BOP.IUPDATE
     *
     * @param iupdate the value for FIR_AGTRN_TMP_BOP.IUPDATE
     *
     * @ibatorgenerated Tue May 04 11:55:42 CST 2021
     */
    public void setIupdate(String iupdate) {
        this.iupdate = iupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_TMP_BOP.DUPDATE
     *
     * @return the value of FIR_AGTRN_TMP_BOP.DUPDATE
     *
     * @ibatorgenerated Tue May 04 11:55:42 CST 2021
     */
    public Date getDupdate() {
        return dupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_TMP_BOP.DUPDATE
     *
     * @param dupdate the value for FIR_AGTRN_TMP_BOP.DUPDATE
     *
     * @ibatorgenerated Tue May 04 11:55:42 CST 2021
     */
    public void setDupdate(Date dupdate) {
        this.dupdate = dupdate;
    }
}