package com.tlg.prpins.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;
/** mantis：FIR0623，處理人員：CD094，需求單編號：FIR0623_住火_臺銀續保作業_臺銀RD簽屬檔接收排程 **/
public class FirAgtBotFd extends IBatisBaseEntity<BigDecimal> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_BOT_FD.OID
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    private BigDecimal oid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_BOT_FD.BATCH_NO
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    private String batchNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_BOT_FD.FD_TYPE
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    private String fdType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_BOT_FD.ORDERSEQ
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    private String orderseq;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_BOT_FD.FD_DATE
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    private Date fdDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_BOT_FD.STARTDATE_F
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    private Date startdateF;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_BOT_FD.STARTDATE_Q
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    private Date startdateQ;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_BOT_FD.ACCOUNT_NO
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    private String accountNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_BOT_FD.BRANCH_NO
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    private String branchNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_BOT_FD.BANK_SALES
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    private String bankSales;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_BOT_FD.IS_APPROVAL
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    private String isApproval;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_BOT_FD.IS_AUTO_RENEW
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    private String isAutoRenew;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_BOT_FD.STARTDATE_A
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    private Date startdateA;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_BOT_FD.AMOUNT_F
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    private Long amountF;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_BOT_FD.AMOUNT_Q
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    private Long amountQ;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_BOT_FD.AMOUNT_A
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    private Integer amountA;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_BOT_FD.COMPARE_RESULT
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    private String compareResult;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_BOT_FD.REPLACE_FLAG
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    private String replaceFlag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_BOT_FD.REPLACE_LOG1
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    private String replaceLog1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_BOT_FD.REPLACE_LOG2
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    private String replaceLog2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_BOT_FD.REPLACE_USER
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    private String replaceUser;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_BOT_FD.REPLACE_TIME
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    private Date replaceTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_BOT_FD.ICREATE
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    private String icreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_BOT_FD.DCREATE
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    private Date dcreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_BOT_FD.LOANACCOUNT
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    private String loanaccount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_BOT_FD.COMPARE_FLAG
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    private String compareFlag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_BOT_FD.COMPARE_BATCH_NO
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    private String compareBatchNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_BOT_FD.COMPARE_TIME
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    private Date compareTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_BOT_FD.COMPARE_USER
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    private String compareUser;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_BOT_FD.OID
     *
     * @return the value of FIR_AGT_BOT_FD.OID
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public BigDecimal getOid() {
        return oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_BOT_FD.OID
     *
     * @param oid the value for FIR_AGT_BOT_FD.OID
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public void setOid(BigDecimal oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_BOT_FD.BATCH_NO
     *
     * @return the value of FIR_AGT_BOT_FD.BATCH_NO
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_BOT_FD.BATCH_NO
     *
     * @param batchNo the value for FIR_AGT_BOT_FD.BATCH_NO
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_BOT_FD.FD_TYPE
     *
     * @return the value of FIR_AGT_BOT_FD.FD_TYPE
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public String getFdType() {
        return fdType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_BOT_FD.FD_TYPE
     *
     * @param fdType the value for FIR_AGT_BOT_FD.FD_TYPE
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public void setFdType(String fdType) {
        this.fdType = fdType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_BOT_FD.ORDERSEQ
     *
     * @return the value of FIR_AGT_BOT_FD.ORDERSEQ
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public String getOrderseq() {
        return orderseq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_BOT_FD.ORDERSEQ
     *
     * @param orderseq the value for FIR_AGT_BOT_FD.ORDERSEQ
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public void setOrderseq(String orderseq) {
        this.orderseq = orderseq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_BOT_FD.FD_DATE
     *
     * @return the value of FIR_AGT_BOT_FD.FD_DATE
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public Date getFdDate() {
        return fdDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_BOT_FD.FD_DATE
     *
     * @param fdDate the value for FIR_AGT_BOT_FD.FD_DATE
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public void setFdDate(Date fdDate) {
        this.fdDate = fdDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_BOT_FD.STARTDATE_F
     *
     * @return the value of FIR_AGT_BOT_FD.STARTDATE_F
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public Date getStartdateF() {
        return startdateF;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_BOT_FD.STARTDATE_F
     *
     * @param startdateF the value for FIR_AGT_BOT_FD.STARTDATE_F
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public void setStartdateF(Date startdateF) {
        this.startdateF = startdateF;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_BOT_FD.STARTDATE_Q
     *
     * @return the value of FIR_AGT_BOT_FD.STARTDATE_Q
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public Date getStartdateQ() {
        return startdateQ;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_BOT_FD.STARTDATE_Q
     *
     * @param startdateQ the value for FIR_AGT_BOT_FD.STARTDATE_Q
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public void setStartdateQ(Date startdateQ) {
        this.startdateQ = startdateQ;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_BOT_FD.ACCOUNT_NO
     *
     * @return the value of FIR_AGT_BOT_FD.ACCOUNT_NO
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_BOT_FD.ACCOUNT_NO
     *
     * @param accountNo the value for FIR_AGT_BOT_FD.ACCOUNT_NO
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_BOT_FD.BRANCH_NO
     *
     * @return the value of FIR_AGT_BOT_FD.BRANCH_NO
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public String getBranchNo() {
        return branchNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_BOT_FD.BRANCH_NO
     *
     * @param branchNo the value for FIR_AGT_BOT_FD.BRANCH_NO
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public void setBranchNo(String branchNo) {
        this.branchNo = branchNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_BOT_FD.BANK_SALES
     *
     * @return the value of FIR_AGT_BOT_FD.BANK_SALES
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public String getBankSales() {
        return bankSales;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_BOT_FD.BANK_SALES
     *
     * @param bankSales the value for FIR_AGT_BOT_FD.BANK_SALES
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public void setBankSales(String bankSales) {
        this.bankSales = bankSales;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_BOT_FD.IS_APPROVAL
     *
     * @return the value of FIR_AGT_BOT_FD.IS_APPROVAL
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public String getIsApproval() {
        return isApproval;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_BOT_FD.IS_APPROVAL
     *
     * @param isApproval the value for FIR_AGT_BOT_FD.IS_APPROVAL
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public void setIsApproval(String isApproval) {
        this.isApproval = isApproval;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_BOT_FD.IS_AUTO_RENEW
     *
     * @return the value of FIR_AGT_BOT_FD.IS_AUTO_RENEW
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public String getIsAutoRenew() {
        return isAutoRenew;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_BOT_FD.IS_AUTO_RENEW
     *
     * @param isAutoRenew the value for FIR_AGT_BOT_FD.IS_AUTO_RENEW
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public void setIsAutoRenew(String isAutoRenew) {
        this.isAutoRenew = isAutoRenew;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_BOT_FD.STARTDATE_A
     *
     * @return the value of FIR_AGT_BOT_FD.STARTDATE_A
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public Date getStartdateA() {
        return startdateA;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_BOT_FD.STARTDATE_A
     *
     * @param startdateA the value for FIR_AGT_BOT_FD.STARTDATE_A
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public void setStartdateA(Date startdateA) {
        this.startdateA = startdateA;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_BOT_FD.AMOUNT_F
     *
     * @return the value of FIR_AGT_BOT_FD.AMOUNT_F
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public Long getAmountF() {
        return amountF;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_BOT_FD.AMOUNT_F
     *
     * @param amountF the value for FIR_AGT_BOT_FD.AMOUNT_F
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public void setAmountF(Long amountF) {
        this.amountF = amountF;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_BOT_FD.AMOUNT_Q
     *
     * @return the value of FIR_AGT_BOT_FD.AMOUNT_Q
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public Long getAmountQ() {
        return amountQ;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_BOT_FD.AMOUNT_Q
     *
     * @param amountQ the value for FIR_AGT_BOT_FD.AMOUNT_Q
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public void setAmountQ(Long amountQ) {
        this.amountQ = amountQ;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_BOT_FD.AMOUNT_A
     *
     * @return the value of FIR_AGT_BOT_FD.AMOUNT_A
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public Integer getAmountA() {
        return amountA;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_BOT_FD.AMOUNT_A
     *
     * @param amountA the value for FIR_AGT_BOT_FD.AMOUNT_A
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public void setAmountA(Integer amountA) {
        this.amountA = amountA;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_BOT_FD.COMPARE_RESULT
     *
     * @return the value of FIR_AGT_BOT_FD.COMPARE_RESULT
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public String getCompareResult() {
        return compareResult;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_BOT_FD.COMPARE_RESULT
     *
     * @param compareResult the value for FIR_AGT_BOT_FD.COMPARE_RESULT
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public void setCompareResult(String compareResult) {
        this.compareResult = compareResult;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_BOT_FD.REPLACE_FLAG
     *
     * @return the value of FIR_AGT_BOT_FD.REPLACE_FLAG
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public String getReplaceFlag() {
        return replaceFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_BOT_FD.REPLACE_FLAG
     *
     * @param replaceFlag the value for FIR_AGT_BOT_FD.REPLACE_FLAG
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public void setReplaceFlag(String replaceFlag) {
        this.replaceFlag = replaceFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_BOT_FD.REPLACE_LOG1
     *
     * @return the value of FIR_AGT_BOT_FD.REPLACE_LOG1
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public String getReplaceLog1() {
        return replaceLog1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_BOT_FD.REPLACE_LOG1
     *
     * @param replaceLog1 the value for FIR_AGT_BOT_FD.REPLACE_LOG1
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public void setReplaceLog1(String replaceLog1) {
        this.replaceLog1 = replaceLog1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_BOT_FD.REPLACE_LOG2
     *
     * @return the value of FIR_AGT_BOT_FD.REPLACE_LOG2
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public String getReplaceLog2() {
        return replaceLog2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_BOT_FD.REPLACE_LOG2
     *
     * @param replaceLog2 the value for FIR_AGT_BOT_FD.REPLACE_LOG2
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public void setReplaceLog2(String replaceLog2) {
        this.replaceLog2 = replaceLog2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_BOT_FD.REPLACE_USER
     *
     * @return the value of FIR_AGT_BOT_FD.REPLACE_USER
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public String getReplaceUser() {
        return replaceUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_BOT_FD.REPLACE_USER
     *
     * @param replaceUser the value for FIR_AGT_BOT_FD.REPLACE_USER
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public void setReplaceUser(String replaceUser) {
        this.replaceUser = replaceUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_BOT_FD.REPLACE_TIME
     *
     * @return the value of FIR_AGT_BOT_FD.REPLACE_TIME
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public Date getReplaceTime() {
        return replaceTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_BOT_FD.REPLACE_TIME
     *
     * @param replaceTime the value for FIR_AGT_BOT_FD.REPLACE_TIME
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public void setReplaceTime(Date replaceTime) {
        this.replaceTime = replaceTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_BOT_FD.ICREATE
     *
     * @return the value of FIR_AGT_BOT_FD.ICREATE
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public String getIcreate() {
        return icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_BOT_FD.ICREATE
     *
     * @param icreate the value for FIR_AGT_BOT_FD.ICREATE
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public void setIcreate(String icreate) {
        this.icreate = icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_BOT_FD.DCREATE
     *
     * @return the value of FIR_AGT_BOT_FD.DCREATE
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public Date getDcreate() {
        return dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_BOT_FD.DCREATE
     *
     * @param dcreate the value for FIR_AGT_BOT_FD.DCREATE
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public void setDcreate(Date dcreate) {
        this.dcreate = dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_BOT_FD.LOANACCOUNT
     *
     * @return the value of FIR_AGT_BOT_FD.LOANACCOUNT
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public String getLoanaccount() {
        return loanaccount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_BOT_FD.LOANACCOUNT
     *
     * @param loanaccount the value for FIR_AGT_BOT_FD.LOANACCOUNT
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public void setLoanaccount(String loanaccount) {
        this.loanaccount = loanaccount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_BOT_FD.COMPARE_FLAG
     *
     * @return the value of FIR_AGT_BOT_FD.COMPARE_FLAG
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public String getCompareFlag() {
        return compareFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_BOT_FD.COMPARE_FLAG
     *
     * @param compareFlag the value for FIR_AGT_BOT_FD.COMPARE_FLAG
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public void setCompareFlag(String compareFlag) {
        this.compareFlag = compareFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_BOT_FD.COMPARE_BATCH_NO
     *
     * @return the value of FIR_AGT_BOT_FD.COMPARE_BATCH_NO
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public String getCompareBatchNo() {
        return compareBatchNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_BOT_FD.COMPARE_BATCH_NO
     *
     * @param compareBatchNo the value for FIR_AGT_BOT_FD.COMPARE_BATCH_NO
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public void setCompareBatchNo(String compareBatchNo) {
        this.compareBatchNo = compareBatchNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_BOT_FD.COMPARE_TIME
     *
     * @return the value of FIR_AGT_BOT_FD.COMPARE_TIME
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public Date getCompareTime() {
        return compareTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_BOT_FD.COMPARE_TIME
     *
     * @param compareTime the value for FIR_AGT_BOT_FD.COMPARE_TIME
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public void setCompareTime(Date compareTime) {
        this.compareTime = compareTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_BOT_FD.COMPARE_USER
     *
     * @return the value of FIR_AGT_BOT_FD.COMPARE_USER
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public String getCompareUser() {
        return compareUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_BOT_FD.COMPARE_USER
     *
     * @param compareUser the value for FIR_AGT_BOT_FD.COMPARE_USER
     *
     * @ibatorgenerated Fri Jul 26 09:53:47 CST 2024
     */
    public void setCompareUser(String compareUser) {
        this.compareUser = compareUser;
    }
}