package com.tlg.prpins.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

public class FirAgtSalesMapping extends IBatisBaseEntity<BigDecimal>{
	/* mantis：FIR0294，處理人員：BJ085，需求單編號：FIR0294 外銀板信續件移回新核心-資料接收排程 start */
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_SALES_MAPPING.OID
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    private BigDecimal oid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_SALES_MAPPING.BUSINESSNATURE
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    private String businessnature;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_SALES_MAPPING.BRANCH_NO
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    private String branchNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_SALES_MAPPING.BRANCH_NAME
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    private String branchName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_SALES_MAPPING.HANDLER1CODE
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    private String handler1code;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_SALES_MAPPING.REMARK
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    private String remark;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_SALES_MAPPING.DELETE_FLAG
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    private String deleteFlag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_SALES_MAPPING.ICREATE
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    private String icreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_SALES_MAPPING.DCREATE
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    private Date dcreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_SALES_MAPPING.IUPDATE
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    private String iupdate;
    
    private String comcode;
    
    private String validstatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGT_SALES_MAPPING.DUPDATE
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    private Date dupdate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_SALES_MAPPING.OID
     *
     * @return the value of FIR_AGT_SALES_MAPPING.OID
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    public BigDecimal getOid() {
        return oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_SALES_MAPPING.OID
     *
     * @param oid the value for FIR_AGT_SALES_MAPPING.OID
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    public void setOid(BigDecimal oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_SALES_MAPPING.BUSINESSNATURE
     *
     * @return the value of FIR_AGT_SALES_MAPPING.BUSINESSNATURE
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    public String getBusinessnature() {
        return businessnature;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_SALES_MAPPING.BUSINESSNATURE
     *
     * @param businessnature the value for FIR_AGT_SALES_MAPPING.BUSINESSNATURE
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    public void setBusinessnature(String businessnature) {
        this.businessnature = businessnature;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_SALES_MAPPING.BRANCH_NO
     *
     * @return the value of FIR_AGT_SALES_MAPPING.BRANCH_NO
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    public String getBranchNo() {
        return branchNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_SALES_MAPPING.BRANCH_NO
     *
     * @param branchNo the value for FIR_AGT_SALES_MAPPING.BRANCH_NO
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    public void setBranchNo(String branchNo) {
        this.branchNo = branchNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_SALES_MAPPING.BRANCH_NAME
     *
     * @return the value of FIR_AGT_SALES_MAPPING.BRANCH_NAME
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    public String getBranchName() {
        return branchName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_SALES_MAPPING.BRANCH_NAME
     *
     * @param branchName the value for FIR_AGT_SALES_MAPPING.BRANCH_NAME
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_SALES_MAPPING.HANDLER1CODE
     *
     * @return the value of FIR_AGT_SALES_MAPPING.HANDLER1CODE
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    public String getHandler1code() {
        return handler1code;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_SALES_MAPPING.HANDLER1CODE
     *
     * @param handler1code the value for FIR_AGT_SALES_MAPPING.HANDLER1CODE
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    public void setHandler1code(String handler1code) {
        this.handler1code = handler1code;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_SALES_MAPPING.REMARK
     *
     * @return the value of FIR_AGT_SALES_MAPPING.REMARK
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_SALES_MAPPING.REMARK
     *
     * @param remark the value for FIR_AGT_SALES_MAPPING.REMARK
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_SALES_MAPPING.DELETE_FLAG
     *
     * @return the value of FIR_AGT_SALES_MAPPING.DELETE_FLAG
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_SALES_MAPPING.DELETE_FLAG
     *
     * @param deleteFlag the value for FIR_AGT_SALES_MAPPING.DELETE_FLAG
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_SALES_MAPPING.ICREATE
     *
     * @return the value of FIR_AGT_SALES_MAPPING.ICREATE
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    public String getIcreate() {
        return icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_SALES_MAPPING.ICREATE
     *
     * @param icreate the value for FIR_AGT_SALES_MAPPING.ICREATE
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    public void setIcreate(String icreate) {
        this.icreate = icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_SALES_MAPPING.DCREATE
     *
     * @return the value of FIR_AGT_SALES_MAPPING.DCREATE
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    public Date getDcreate() {
        return dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_SALES_MAPPING.DCREATE
     *
     * @param dcreate the value for FIR_AGT_SALES_MAPPING.DCREATE
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    public void setDcreate(Date dcreate) {
        this.dcreate = dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_SALES_MAPPING.IUPDATE
     *
     * @return the value of FIR_AGT_SALES_MAPPING.IUPDATE
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    public String getIupdate() {
        return iupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_SALES_MAPPING.IUPDATE
     *
     * @param iupdate the value for FIR_AGT_SALES_MAPPING.IUPDATE
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    public void setIupdate(String iupdate) {
        this.iupdate = iupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGT_SALES_MAPPING.DUPDATE
     *
     * @return the value of FIR_AGT_SALES_MAPPING.DUPDATE
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    public Date getDupdate() {
        return dupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGT_SALES_MAPPING.DUPDATE
     *
     * @param dupdate the value for FIR_AGT_SALES_MAPPING.DUPDATE
     *
     * @ibatorgenerated Thu May 06 16:49:23 CST 2021
     */
    public void setDupdate(Date dupdate) {
        this.dupdate = dupdate;
    }

	public String getComcode() {
		return comcode;
	}

	public void setComcode(String comcode) {
		this.comcode = comcode;
	}

	public String getValidstatus() {
		return validstatus;
	}

	public void setValidstatus(String validstatus) {
		this.validstatus = validstatus;
	}
}