package com.tlg.prpins.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

/** mantis：FIR0621，處理人員：BJ085，需求單編號：FIR0621 住火_臺銀續保作業_續件資料處理作業 **/
@SuppressWarnings("serial")
public class FirAgtrnBatchBot extends IBatisBaseEntity<BigDecimal>{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_BATCH_BOT.BATCH_NO
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    private String batchNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_BATCH_BOT.RE_USER
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    private String reUser;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_BATCH_BOT.RE_TIME
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    private Date reTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_BATCH_BOT.RE_MEMO
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    private String reMemo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_BATCH_BOT.RE_BNO
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    private String reBno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_BATCH_BOT.RNPRO_USER
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    private String rnproUser;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_BATCH_BOT.RNPRO_TIME
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    private Date rnproTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_BATCH_BOT.RNPRO_MEMO
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    private String rnproMemo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_BATCH_BOT.RNPRO_BNO
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    private String rnproBno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_BATCH_BOT.EN_USER
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    private String enUser;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_BATCH_BOT.EN_TIME
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    private Date enTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_BATCH_BOT.EN_MEMO
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    private String enMemo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_BATCH_BOT.EN_BNO
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    private String enBno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_BATCH_BOT.ICREATE
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    private String icreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_BATCH_BOT.DCREATE
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    private Date dcreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_BATCH_BOT.IUPDATE
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    private String iupdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_AGTRN_BATCH_BOT.DUPDATE
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    private Date dupdate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_BATCH_BOT.BATCH_NO
     *
     * @return the value of FIR_AGTRN_BATCH_BOT.BATCH_NO
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_BATCH_BOT.BATCH_NO
     *
     * @param batchNo the value for FIR_AGTRN_BATCH_BOT.BATCH_NO
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_BATCH_BOT.RE_USER
     *
     * @return the value of FIR_AGTRN_BATCH_BOT.RE_USER
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public String getReUser() {
        return reUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_BATCH_BOT.RE_USER
     *
     * @param reUser the value for FIR_AGTRN_BATCH_BOT.RE_USER
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public void setReUser(String reUser) {
        this.reUser = reUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_BATCH_BOT.RE_TIME
     *
     * @return the value of FIR_AGTRN_BATCH_BOT.RE_TIME
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public Date getReTime() {
        return reTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_BATCH_BOT.RE_TIME
     *
     * @param reTime the value for FIR_AGTRN_BATCH_BOT.RE_TIME
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public void setReTime(Date reTime) {
        this.reTime = reTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_BATCH_BOT.RE_MEMO
     *
     * @return the value of FIR_AGTRN_BATCH_BOT.RE_MEMO
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public String getReMemo() {
        return reMemo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_BATCH_BOT.RE_MEMO
     *
     * @param reMemo the value for FIR_AGTRN_BATCH_BOT.RE_MEMO
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public void setReMemo(String reMemo) {
        this.reMemo = reMemo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_BATCH_BOT.RE_BNO
     *
     * @return the value of FIR_AGTRN_BATCH_BOT.RE_BNO
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public String getReBno() {
        return reBno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_BATCH_BOT.RE_BNO
     *
     * @param reBno the value for FIR_AGTRN_BATCH_BOT.RE_BNO
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public void setReBno(String reBno) {
        this.reBno = reBno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_BATCH_BOT.RNPRO_USER
     *
     * @return the value of FIR_AGTRN_BATCH_BOT.RNPRO_USER
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public String getRnproUser() {
        return rnproUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_BATCH_BOT.RNPRO_USER
     *
     * @param rnproUser the value for FIR_AGTRN_BATCH_BOT.RNPRO_USER
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public void setRnproUser(String rnproUser) {
        this.rnproUser = rnproUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_BATCH_BOT.RNPRO_TIME
     *
     * @return the value of FIR_AGTRN_BATCH_BOT.RNPRO_TIME
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public Date getRnproTime() {
        return rnproTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_BATCH_BOT.RNPRO_TIME
     *
     * @param rnproTime the value for FIR_AGTRN_BATCH_BOT.RNPRO_TIME
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public void setRnproTime(Date rnproTime) {
        this.rnproTime = rnproTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_BATCH_BOT.RNPRO_MEMO
     *
     * @return the value of FIR_AGTRN_BATCH_BOT.RNPRO_MEMO
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public String getRnproMemo() {
        return rnproMemo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_BATCH_BOT.RNPRO_MEMO
     *
     * @param rnproMemo the value for FIR_AGTRN_BATCH_BOT.RNPRO_MEMO
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public void setRnproMemo(String rnproMemo) {
        this.rnproMemo = rnproMemo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_BATCH_BOT.RNPRO_BNO
     *
     * @return the value of FIR_AGTRN_BATCH_BOT.RNPRO_BNO
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public String getRnproBno() {
        return rnproBno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_BATCH_BOT.RNPRO_BNO
     *
     * @param rnproBno the value for FIR_AGTRN_BATCH_BOT.RNPRO_BNO
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public void setRnproBno(String rnproBno) {
        this.rnproBno = rnproBno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_BATCH_BOT.EN_USER
     *
     * @return the value of FIR_AGTRN_BATCH_BOT.EN_USER
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public String getEnUser() {
        return enUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_BATCH_BOT.EN_USER
     *
     * @param enUser the value for FIR_AGTRN_BATCH_BOT.EN_USER
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public void setEnUser(String enUser) {
        this.enUser = enUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_BATCH_BOT.EN_TIME
     *
     * @return the value of FIR_AGTRN_BATCH_BOT.EN_TIME
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public Date getEnTime() {
        return enTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_BATCH_BOT.EN_TIME
     *
     * @param enTime the value for FIR_AGTRN_BATCH_BOT.EN_TIME
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public void setEnTime(Date enTime) {
        this.enTime = enTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_BATCH_BOT.EN_MEMO
     *
     * @return the value of FIR_AGTRN_BATCH_BOT.EN_MEMO
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public String getEnMemo() {
        return enMemo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_BATCH_BOT.EN_MEMO
     *
     * @param enMemo the value for FIR_AGTRN_BATCH_BOT.EN_MEMO
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public void setEnMemo(String enMemo) {
        this.enMemo = enMemo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_BATCH_BOT.EN_BNO
     *
     * @return the value of FIR_AGTRN_BATCH_BOT.EN_BNO
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public String getEnBno() {
        return enBno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_BATCH_BOT.EN_BNO
     *
     * @param enBno the value for FIR_AGTRN_BATCH_BOT.EN_BNO
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public void setEnBno(String enBno) {
        this.enBno = enBno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_BATCH_BOT.ICREATE
     *
     * @return the value of FIR_AGTRN_BATCH_BOT.ICREATE
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public String getIcreate() {
        return icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_BATCH_BOT.ICREATE
     *
     * @param icreate the value for FIR_AGTRN_BATCH_BOT.ICREATE
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public void setIcreate(String icreate) {
        this.icreate = icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_BATCH_BOT.DCREATE
     *
     * @return the value of FIR_AGTRN_BATCH_BOT.DCREATE
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public Date getDcreate() {
        return dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_BATCH_BOT.DCREATE
     *
     * @param dcreate the value for FIR_AGTRN_BATCH_BOT.DCREATE
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public void setDcreate(Date dcreate) {
        this.dcreate = dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_BATCH_BOT.IUPDATE
     *
     * @return the value of FIR_AGTRN_BATCH_BOT.IUPDATE
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public String getIupdate() {
        return iupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_BATCH_BOT.IUPDATE
     *
     * @param iupdate the value for FIR_AGTRN_BATCH_BOT.IUPDATE
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public void setIupdate(String iupdate) {
        this.iupdate = iupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_AGTRN_BATCH_BOT.DUPDATE
     *
     * @return the value of FIR_AGTRN_BATCH_BOT.DUPDATE
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public Date getDupdate() {
        return dupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_AGTRN_BATCH_BOT.DUPDATE
     *
     * @param dupdate the value for FIR_AGTRN_BATCH_BOT.DUPDATE
     *
     * @ibatorgenerated Thu Feb 15 11:05:58 CST 2024
     */
    public void setDupdate(Date dupdate) {
        this.dupdate = dupdate;
    }
}