package com.tlg.prpins.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

/* mantis：FIR0436，處理人員：BJ085，需求單編號：FIR0436 住火-APS保單通訊資料產生及下載作業批次作業 */
public class FirBatchPins01SpMain extends IBatisBaseEntity<BigDecimal>{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_PINS01_SP_MAIN.OID
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    private BigDecimal oid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_PINS01_SP_MAIN.BNO
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    private String bno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_PINS01_SP_MAIN.CLASSNAME
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    private String classname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_PINS01_SP_MAIN.RISKCODE
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    private String riskcode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_PINS01_SP_MAIN.POLICYNO
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    private String policyno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_PINS01_SP_MAIN.UNDERWRITEENDDATE
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    private Date underwriteenddate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_PINS01_SP_MAIN.STARTDATE
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    private Date startdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_PINS01_SP_MAIN.ENDDATE
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    private Date enddate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_PINS01_SP_MAIN.BUSINESSNATURE
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    private String businessnature;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_PINS01_SP_MAIN.HANDLERNAME
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    private String handlername;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_PINS01_SP_MAIN.HANDLER1CODE
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    private String handler1code;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_PINS01_SP_MAIN.HANDLER1NAME
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    private String handler1name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_PINS01_SP_MAIN.COMCODE
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    private String comcode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_PINS01_SP_MAIN.EXTRACOMCODE
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    private String extracomcode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_PINS01_SP_MAIN.LICENSENO
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    private String licenseno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_PINS01_SP_MAIN.ICREATE
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    private String icreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_PINS01_SP_MAIN.DCREATE
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    private Date dcreate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_PINS01_SP_MAIN.OID
     *
     * @return the value of FIR_BATCH_PINS01_SP_MAIN.OID
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public BigDecimal getOid() {
        return oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_PINS01_SP_MAIN.OID
     *
     * @param oid the value for FIR_BATCH_PINS01_SP_MAIN.OID
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public void setOid(BigDecimal oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_PINS01_SP_MAIN.BNO
     *
     * @return the value of FIR_BATCH_PINS01_SP_MAIN.BNO
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public String getBno() {
        return bno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_PINS01_SP_MAIN.BNO
     *
     * @param bno the value for FIR_BATCH_PINS01_SP_MAIN.BNO
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public void setBno(String bno) {
        this.bno = bno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_PINS01_SP_MAIN.CLASSNAME
     *
     * @return the value of FIR_BATCH_PINS01_SP_MAIN.CLASSNAME
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_PINS01_SP_MAIN.CLASSNAME
     *
     * @param classname the value for FIR_BATCH_PINS01_SP_MAIN.CLASSNAME
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public void setClassname(String classname) {
        this.classname = classname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_PINS01_SP_MAIN.RISKCODE
     *
     * @return the value of FIR_BATCH_PINS01_SP_MAIN.RISKCODE
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public String getRiskcode() {
        return riskcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_PINS01_SP_MAIN.RISKCODE
     *
     * @param riskcode the value for FIR_BATCH_PINS01_SP_MAIN.RISKCODE
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public void setRiskcode(String riskcode) {
        this.riskcode = riskcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_PINS01_SP_MAIN.POLICYNO
     *
     * @return the value of FIR_BATCH_PINS01_SP_MAIN.POLICYNO
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public String getPolicyno() {
        return policyno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_PINS01_SP_MAIN.POLICYNO
     *
     * @param policyno the value for FIR_BATCH_PINS01_SP_MAIN.POLICYNO
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public void setPolicyno(String policyno) {
        this.policyno = policyno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_PINS01_SP_MAIN.UNDERWRITEENDDATE
     *
     * @return the value of FIR_BATCH_PINS01_SP_MAIN.UNDERWRITEENDDATE
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public Date getUnderwriteenddate() {
        return underwriteenddate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_PINS01_SP_MAIN.UNDERWRITEENDDATE
     *
     * @param underwriteenddate the value for FIR_BATCH_PINS01_SP_MAIN.UNDERWRITEENDDATE
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public void setUnderwriteenddate(Date underwriteenddate) {
        this.underwriteenddate = underwriteenddate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_PINS01_SP_MAIN.STARTDATE
     *
     * @return the value of FIR_BATCH_PINS01_SP_MAIN.STARTDATE
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_PINS01_SP_MAIN.STARTDATE
     *
     * @param startdate the value for FIR_BATCH_PINS01_SP_MAIN.STARTDATE
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_PINS01_SP_MAIN.ENDDATE
     *
     * @return the value of FIR_BATCH_PINS01_SP_MAIN.ENDDATE
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_PINS01_SP_MAIN.ENDDATE
     *
     * @param enddate the value for FIR_BATCH_PINS01_SP_MAIN.ENDDATE
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_PINS01_SP_MAIN.BUSINESSNATURE
     *
     * @return the value of FIR_BATCH_PINS01_SP_MAIN.BUSINESSNATURE
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public String getBusinessnature() {
        return businessnature;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_PINS01_SP_MAIN.BUSINESSNATURE
     *
     * @param businessnature the value for FIR_BATCH_PINS01_SP_MAIN.BUSINESSNATURE
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public void setBusinessnature(String businessnature) {
        this.businessnature = businessnature;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_PINS01_SP_MAIN.HANDLERNAME
     *
     * @return the value of FIR_BATCH_PINS01_SP_MAIN.HANDLERNAME
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public String getHandlername() {
        return handlername;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_PINS01_SP_MAIN.HANDLERNAME
     *
     * @param handlername the value for FIR_BATCH_PINS01_SP_MAIN.HANDLERNAME
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public void setHandlername(String handlername) {
        this.handlername = handlername;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_PINS01_SP_MAIN.HANDLER1CODE
     *
     * @return the value of FIR_BATCH_PINS01_SP_MAIN.HANDLER1CODE
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public String getHandler1code() {
        return handler1code;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_PINS01_SP_MAIN.HANDLER1CODE
     *
     * @param handler1code the value for FIR_BATCH_PINS01_SP_MAIN.HANDLER1CODE
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public void setHandler1code(String handler1code) {
        this.handler1code = handler1code;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_PINS01_SP_MAIN.HANDLER1NAME
     *
     * @return the value of FIR_BATCH_PINS01_SP_MAIN.HANDLER1NAME
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public String getHandler1name() {
        return handler1name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_PINS01_SP_MAIN.HANDLER1NAME
     *
     * @param handler1name the value for FIR_BATCH_PINS01_SP_MAIN.HANDLER1NAME
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public void setHandler1name(String handler1name) {
        this.handler1name = handler1name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_PINS01_SP_MAIN.COMCODE
     *
     * @return the value of FIR_BATCH_PINS01_SP_MAIN.COMCODE
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public String getComcode() {
        return comcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_PINS01_SP_MAIN.COMCODE
     *
     * @param comcode the value for FIR_BATCH_PINS01_SP_MAIN.COMCODE
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public void setComcode(String comcode) {
        this.comcode = comcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_PINS01_SP_MAIN.EXTRACOMCODE
     *
     * @return the value of FIR_BATCH_PINS01_SP_MAIN.EXTRACOMCODE
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public String getExtracomcode() {
        return extracomcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_PINS01_SP_MAIN.EXTRACOMCODE
     *
     * @param extracomcode the value for FIR_BATCH_PINS01_SP_MAIN.EXTRACOMCODE
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public void setExtracomcode(String extracomcode) {
        this.extracomcode = extracomcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_PINS01_SP_MAIN.LICENSENO
     *
     * @return the value of FIR_BATCH_PINS01_SP_MAIN.LICENSENO
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public String getLicenseno() {
        return licenseno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_PINS01_SP_MAIN.LICENSENO
     *
     * @param licenseno the value for FIR_BATCH_PINS01_SP_MAIN.LICENSENO
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public void setLicenseno(String licenseno) {
        this.licenseno = licenseno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_PINS01_SP_MAIN.ICREATE
     *
     * @return the value of FIR_BATCH_PINS01_SP_MAIN.ICREATE
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public String getIcreate() {
        return icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_PINS01_SP_MAIN.ICREATE
     *
     * @param icreate the value for FIR_BATCH_PINS01_SP_MAIN.ICREATE
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public void setIcreate(String icreate) {
        this.icreate = icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_PINS01_SP_MAIN.DCREATE
     *
     * @return the value of FIR_BATCH_PINS01_SP_MAIN.DCREATE
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public Date getDcreate() {
        return dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_PINS01_SP_MAIN.DCREATE
     *
     * @param dcreate the value for FIR_BATCH_PINS01_SP_MAIN.DCREATE
     *
     * @ibatorgenerated Fri Feb 11 11:15:56 CST 2022
     */
    public void setDcreate(Date dcreate) {
        this.dcreate = dcreate;
    }
}