package com.tlg.prpins.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

/** mantis：FIR0580，處理人員：BJ085，需求單編號：FIR0580 保發中心-住火保批資料回饋檔回存資料庫 */
@SuppressWarnings("serial")
public class FirBatchTiiReturnLog extends IBatisBaseEntity<BigDecimal>{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_RETURN_LOG.OID
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    private BigDecimal oid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_RETURN_LOG.FILE_NAME
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    private String fileName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_RETURN_LOG.DATA_TYPE
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    private String dataType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_RETURN_LOG.ID_NO
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    private String idNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_RETURN_LOG.REMARK
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    private String remark;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_RETURN_LOG.IDENTIFIER
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    private String identifier;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_RETURN_LOG.STATUS_CODE
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    private String statusCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_RETURN_LOG.STATUS_MSG
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    private Object statusMsg;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_RETURN_LOG.ERROR_MSG
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    private Object errorMsg;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_RETURN_LOG.TIMESTAMP
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    private String timestamp;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_RETURN_LOG.ICREATE
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    private String icreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_RETURN_LOG.DCREATE
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    private Date dcreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_RETURN_LOG.IUPDATE
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    private String iupdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_RETURN_LOG.DUPDATE
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    private Date dupdate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_RETURN_LOG.OID
     *
     * @return the value of FIR_BATCH_TII_RETURN_LOG.OID
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    public BigDecimal getOid() {
        return oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_RETURN_LOG.OID
     *
     * @param oid the value for FIR_BATCH_TII_RETURN_LOG.OID
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    public void setOid(BigDecimal oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_RETURN_LOG.FILE_NAME
     *
     * @return the value of FIR_BATCH_TII_RETURN_LOG.FILE_NAME
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_RETURN_LOG.FILE_NAME
     *
     * @param fileName the value for FIR_BATCH_TII_RETURN_LOG.FILE_NAME
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_RETURN_LOG.DATA_TYPE
     *
     * @return the value of FIR_BATCH_TII_RETURN_LOG.DATA_TYPE
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_RETURN_LOG.DATA_TYPE
     *
     * @param dataType the value for FIR_BATCH_TII_RETURN_LOG.DATA_TYPE
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_RETURN_LOG.ID_NO
     *
     * @return the value of FIR_BATCH_TII_RETURN_LOG.ID_NO
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_RETURN_LOG.ID_NO
     *
     * @param idNo the value for FIR_BATCH_TII_RETURN_LOG.ID_NO
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_RETURN_LOG.REMARK
     *
     * @return the value of FIR_BATCH_TII_RETURN_LOG.REMARK
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_RETURN_LOG.REMARK
     *
     * @param remark the value for FIR_BATCH_TII_RETURN_LOG.REMARK
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_RETURN_LOG.IDENTIFIER
     *
     * @return the value of FIR_BATCH_TII_RETURN_LOG.IDENTIFIER
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_RETURN_LOG.IDENTIFIER
     *
     * @param identifier the value for FIR_BATCH_TII_RETURN_LOG.IDENTIFIER
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_RETURN_LOG.STATUS_CODE
     *
     * @return the value of FIR_BATCH_TII_RETURN_LOG.STATUS_CODE
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_RETURN_LOG.STATUS_CODE
     *
     * @param statusCode the value for FIR_BATCH_TII_RETURN_LOG.STATUS_CODE
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    public void setStatusCode(String statusCode) {
        this.statusCode = statusCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_RETURN_LOG.STATUS_MSG
     *
     * @return the value of FIR_BATCH_TII_RETURN_LOG.STATUS_MSG
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    public Object getStatusMsg() {
        return statusMsg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_RETURN_LOG.STATUS_MSG
     *
     * @param statusMsg the value for FIR_BATCH_TII_RETURN_LOG.STATUS_MSG
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    public void setStatusMsg(Object statusMsg) {
        this.statusMsg = statusMsg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_RETURN_LOG.ERROR_MSG
     *
     * @return the value of FIR_BATCH_TII_RETURN_LOG.ERROR_MSG
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    public Object getErrorMsg() {
        return errorMsg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_RETURN_LOG.ERROR_MSG
     *
     * @param errorMsg the value for FIR_BATCH_TII_RETURN_LOG.ERROR_MSG
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    public void setErrorMsg(Object errorMsg) {
        this.errorMsg = errorMsg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_RETURN_LOG.TIMESTAMP
     *
     * @return the value of FIR_BATCH_TII_RETURN_LOG.TIMESTAMP
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_RETURN_LOG.TIMESTAMP
     *
     * @param timestamp the value for FIR_BATCH_TII_RETURN_LOG.TIMESTAMP
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_RETURN_LOG.ICREATE
     *
     * @return the value of FIR_BATCH_TII_RETURN_LOG.ICREATE
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    public String getIcreate() {
        return icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_RETURN_LOG.ICREATE
     *
     * @param icreate the value for FIR_BATCH_TII_RETURN_LOG.ICREATE
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    public void setIcreate(String icreate) {
        this.icreate = icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_RETURN_LOG.DCREATE
     *
     * @return the value of FIR_BATCH_TII_RETURN_LOG.DCREATE
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    public Date getDcreate() {
        return dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_RETURN_LOG.DCREATE
     *
     * @param dcreate the value for FIR_BATCH_TII_RETURN_LOG.DCREATE
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    public void setDcreate(Date dcreate) {
        this.dcreate = dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_RETURN_LOG.IUPDATE
     *
     * @return the value of FIR_BATCH_TII_RETURN_LOG.IUPDATE
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    public String getIupdate() {
        return iupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_RETURN_LOG.IUPDATE
     *
     * @param iupdate the value for FIR_BATCH_TII_RETURN_LOG.IUPDATE
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    public void setIupdate(String iupdate) {
        this.iupdate = iupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_RETURN_LOG.DUPDATE
     *
     * @return the value of FIR_BATCH_TII_RETURN_LOG.DUPDATE
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    public Date getDupdate() {
        return dupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_RETURN_LOG.DUPDATE
     *
     * @param dupdate the value for FIR_BATCH_TII_RETURN_LOG.DUPDATE
     *
     * @ibatorgenerated Mon Jun 19 15:18:44 CST 2023
     */
    public void setDupdate(Date dupdate) {
        this.dupdate = dupdate;
    }
}