package com.tlg.prpins.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

/* mantis：FIR0436，處理人員：BJ085，需求單編號：FIR0436 住火-APS保單通訊資料產生及下載作業批次作業 */
public class FirBatchPins01Detail extends IBatisBaseEntity<BigDecimal>{
	 /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_PINS01_DETAIL.BNO
     *
     * @ibatorgenerated Fri Feb 11 11:16:15 CST 2022
     */
    private String bno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_PINS01_DETAIL.RISKCODE
     *
     * @ibatorgenerated Fri Feb 11 11:16:15 CST 2022
     */
    private String riskcode;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_PINS01_DETAIL.RISKCODECOUNT
     *
     * @ibatorgenerated Fri Feb 11 11:16:15 CST 2022
     */
    private BigDecimal riskcodecount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_PINS01_DETAIL.PARAMBASEDATE
     *
     * @ibatorgenerated Fri Feb 11 11:16:15 CST 2022
     */
    private Date parambasedate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_PINS01_DETAIL.BNO
     *
     * @return the value of FIR_BATCH_PINS01_DETAIL.BNO
     *
     * @ibatorgenerated Fri Feb 11 11:16:15 CST 2022
     */
    public String getBno() {
        return bno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_PINS01_DETAIL.BNO
     *
     * @param bno the value for FIR_BATCH_PINS01_DETAIL.BNO
     *
     * @ibatorgenerated Fri Feb 11 11:16:15 CST 2022
     */
    public void setBno(String bno) {
        this.bno = bno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_PINS01_DETAIL.RISKCODE
     *
     * @return the value of FIR_BATCH_PINS01_DETAIL.RISKCODE
     *
     * @ibatorgenerated Fri Feb 11 11:16:15 CST 2022
     */
    public String getRiskcode() {
        return riskcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_PINS01_DETAIL.RISKCODE
     *
     * @param riskcode the value for FIR_BATCH_PINS01_DETAIL.RISKCODE
     *
     * @ibatorgenerated Fri Feb 11 11:16:15 CST 2022
     */
    public void setRiskcode(String riskcode) {
        this.riskcode = riskcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_PINS01_DETAIL.RISKCODECOUNT
     *
     * @return the value of FIR_BATCH_PINS01_DETAIL.RISKCODECOUNT
     *
     * @ibatorgenerated Fri Feb 11 11:16:15 CST 2022
     */
    public BigDecimal getRiskcodecount() {
        return riskcodecount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_PINS01_DETAIL.RISKCODECOUNT
     *
     * @param riskcodecount the value for FIR_BATCH_PINS01_DETAIL.RISKCODECOUNT
     *
     * @ibatorgenerated Fri Feb 11 11:16:15 CST 2022
     */
    public void setRiskcodecount(BigDecimal riskcodecount) {
        this.riskcodecount = riskcodecount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_PINS01_DETAIL.PARAMBASEDATE
     *
     * @return the value of FIR_BATCH_PINS01_DETAIL.PARAMBASEDATE
     *
     * @ibatorgenerated Fri Feb 11 11:16:15 CST 2022
     */
    public Date getParambasedate() {
        return parambasedate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_PINS01_DETAIL.PARAMBASEDATE
     *
     * @param parambasedate the value for FIR_BATCH_PINS01_DETAIL.PARAMBASEDATE
     *
     * @ibatorgenerated Fri Feb 11 11:16:15 CST 2022
     */
    public void setParambasedate(Date parambasedate) {
        this.parambasedate = parambasedate;
    }
}