package com.tlg.prpins.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

/** mantis：FIR0579，處理人員：BJ085，需求單編號：FIR0579 保發中心-住火保批資料產生排程規格 */
@SuppressWarnings("serial")
public class FirBatchTiiList extends IBatisBaseEntity<BigDecimal>{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.OID
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private BigDecimal oid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.PROC_TYPE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private String procType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.INSCO_CODE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private String inscoCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.BRANCH_CODE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private String branchCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.INSCO_CODE_E
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private String inscoCodeE;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.BRANCH_CODE_E
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private String branchCodeE;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.INS_NO
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private String insNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.INS_NAME
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private String insName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.POLICYNO
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private String policyno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.ENDORSENO
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private String endorseno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.OLDPOLICYNO
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private String oldpolicyno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.DATA_STATUS
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private String dataStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.UNDATE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private Date undate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.INSURED_ID_OLD
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private String insuredIdOld;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.STARTDATE_OLD
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private Date startdateOld;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.SUMAMOUNT
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private Long sumamount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.SUMPREMIUM
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private Long sumpremium;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.STARTDATE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private Date startdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.ENDDATE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private Date enddate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.POLICYNO_STATUS
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private String policynoStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.APPLI_COUNT
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private Short appliCount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.APPLICANT_ID
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private String applicantId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.APPLICANT_NAME
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private String applicantName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.APPLICANT_ADDR
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private String applicantAddr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.INSURED_COUNT
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private Short insuredCount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.INSURED_ID
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private String insuredId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.INSURED_NAME
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private String insuredName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.INSURED_ADDR
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private String insuredAddr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.BANK_COUNT
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private Short bankCount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.BANK_DATA
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private String bankData;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.REMARK
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private String remark;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.ADDR_COUNT
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private Short addrCount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.STARTDATE_E
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private Date startdateE;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.ENDDATE_E
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private Date enddateE;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.ENDOR_TEXT
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private String endorText;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.PROC_DATE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private Date procDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.ICREATE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private String icreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.DCREATE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private Date dcreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.BATCH_NO
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private String batchNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.IUPDATE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private String iupdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.DUPDATE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private Date dupdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.DATA_SOURCE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private String dataSource;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.BATCH_NO_SP
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private String batchNoSp;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCH_TII_LIST.AS400_OID
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    private Long as400Oid;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.OID
     *
     * @return the value of FIR_BATCH_TII_LIST.OID
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public BigDecimal getOid() {
        return oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.OID
     *
     * @param oid the value for FIR_BATCH_TII_LIST.OID
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setOid(BigDecimal oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.PROC_TYPE
     *
     * @return the value of FIR_BATCH_TII_LIST.PROC_TYPE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public String getProcType() {
        return procType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.PROC_TYPE
     *
     * @param procType the value for FIR_BATCH_TII_LIST.PROC_TYPE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setProcType(String procType) {
        this.procType = procType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.INSCO_CODE
     *
     * @return the value of FIR_BATCH_TII_LIST.INSCO_CODE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public String getInscoCode() {
        return inscoCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.INSCO_CODE
     *
     * @param inscoCode the value for FIR_BATCH_TII_LIST.INSCO_CODE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setInscoCode(String inscoCode) {
        this.inscoCode = inscoCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.BRANCH_CODE
     *
     * @return the value of FIR_BATCH_TII_LIST.BRANCH_CODE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public String getBranchCode() {
        return branchCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.BRANCH_CODE
     *
     * @param branchCode the value for FIR_BATCH_TII_LIST.BRANCH_CODE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setBranchCode(String branchCode) {
        this.branchCode = branchCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.INSCO_CODE_E
     *
     * @return the value of FIR_BATCH_TII_LIST.INSCO_CODE_E
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public String getInscoCodeE() {
        return inscoCodeE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.INSCO_CODE_E
     *
     * @param inscoCodeE the value for FIR_BATCH_TII_LIST.INSCO_CODE_E
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setInscoCodeE(String inscoCodeE) {
        this.inscoCodeE = inscoCodeE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.BRANCH_CODE_E
     *
     * @return the value of FIR_BATCH_TII_LIST.BRANCH_CODE_E
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public String getBranchCodeE() {
        return branchCodeE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.BRANCH_CODE_E
     *
     * @param branchCodeE the value for FIR_BATCH_TII_LIST.BRANCH_CODE_E
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setBranchCodeE(String branchCodeE) {
        this.branchCodeE = branchCodeE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.INS_NO
     *
     * @return the value of FIR_BATCH_TII_LIST.INS_NO
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public String getInsNo() {
        return insNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.INS_NO
     *
     * @param insNo the value for FIR_BATCH_TII_LIST.INS_NO
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setInsNo(String insNo) {
        this.insNo = insNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.INS_NAME
     *
     * @return the value of FIR_BATCH_TII_LIST.INS_NAME
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public String getInsName() {
        return insName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.INS_NAME
     *
     * @param insName the value for FIR_BATCH_TII_LIST.INS_NAME
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setInsName(String insName) {
        this.insName = insName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.POLICYNO
     *
     * @return the value of FIR_BATCH_TII_LIST.POLICYNO
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public String getPolicyno() {
        return policyno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.POLICYNO
     *
     * @param policyno the value for FIR_BATCH_TII_LIST.POLICYNO
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setPolicyno(String policyno) {
        this.policyno = policyno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.ENDORSENO
     *
     * @return the value of FIR_BATCH_TII_LIST.ENDORSENO
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public String getEndorseno() {
        return endorseno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.ENDORSENO
     *
     * @param endorseno the value for FIR_BATCH_TII_LIST.ENDORSENO
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setEndorseno(String endorseno) {
        this.endorseno = endorseno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.OLDPOLICYNO
     *
     * @return the value of FIR_BATCH_TII_LIST.OLDPOLICYNO
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public String getOldpolicyno() {
        return oldpolicyno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.OLDPOLICYNO
     *
     * @param oldpolicyno the value for FIR_BATCH_TII_LIST.OLDPOLICYNO
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setOldpolicyno(String oldpolicyno) {
        this.oldpolicyno = oldpolicyno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.DATA_STATUS
     *
     * @return the value of FIR_BATCH_TII_LIST.DATA_STATUS
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public String getDataStatus() {
        return dataStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.DATA_STATUS
     *
     * @param dataStatus the value for FIR_BATCH_TII_LIST.DATA_STATUS
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setDataStatus(String dataStatus) {
        this.dataStatus = dataStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.UNDATE
     *
     * @return the value of FIR_BATCH_TII_LIST.UNDATE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public Date getUndate() {
        return undate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.UNDATE
     *
     * @param undate the value for FIR_BATCH_TII_LIST.UNDATE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setUndate(Date undate) {
        this.undate = undate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.INSURED_ID_OLD
     *
     * @return the value of FIR_BATCH_TII_LIST.INSURED_ID_OLD
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public String getInsuredIdOld() {
        return insuredIdOld;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.INSURED_ID_OLD
     *
     * @param insuredIdOld the value for FIR_BATCH_TII_LIST.INSURED_ID_OLD
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setInsuredIdOld(String insuredIdOld) {
        this.insuredIdOld = insuredIdOld;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.STARTDATE_OLD
     *
     * @return the value of FIR_BATCH_TII_LIST.STARTDATE_OLD
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public Date getStartdateOld() {
        return startdateOld;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.STARTDATE_OLD
     *
     * @param startdateOld the value for FIR_BATCH_TII_LIST.STARTDATE_OLD
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setStartdateOld(Date startdateOld) {
        this.startdateOld = startdateOld;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.SUMAMOUNT
     *
     * @return the value of FIR_BATCH_TII_LIST.SUMAMOUNT
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public Long getSumamount() {
        return sumamount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.SUMAMOUNT
     *
     * @param sumamount the value for FIR_BATCH_TII_LIST.SUMAMOUNT
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setSumamount(Long sumamount) {
        this.sumamount = sumamount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.SUMPREMIUM
     *
     * @return the value of FIR_BATCH_TII_LIST.SUMPREMIUM
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public Long getSumpremium() {
        return sumpremium;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.SUMPREMIUM
     *
     * @param sumpremium the value for FIR_BATCH_TII_LIST.SUMPREMIUM
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setSumpremium(Long sumpremium) {
        this.sumpremium = sumpremium;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.STARTDATE
     *
     * @return the value of FIR_BATCH_TII_LIST.STARTDATE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.STARTDATE
     *
     * @param startdate the value for FIR_BATCH_TII_LIST.STARTDATE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.ENDDATE
     *
     * @return the value of FIR_BATCH_TII_LIST.ENDDATE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.ENDDATE
     *
     * @param enddate the value for FIR_BATCH_TII_LIST.ENDDATE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.POLICYNO_STATUS
     *
     * @return the value of FIR_BATCH_TII_LIST.POLICYNO_STATUS
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public String getPolicynoStatus() {
        return policynoStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.POLICYNO_STATUS
     *
     * @param policynoStatus the value for FIR_BATCH_TII_LIST.POLICYNO_STATUS
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setPolicynoStatus(String policynoStatus) {
        this.policynoStatus = policynoStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.APPLI_COUNT
     *
     * @return the value of FIR_BATCH_TII_LIST.APPLI_COUNT
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public Short getAppliCount() {
        return appliCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.APPLI_COUNT
     *
     * @param appliCount the value for FIR_BATCH_TII_LIST.APPLI_COUNT
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setAppliCount(Short appliCount) {
        this.appliCount = appliCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.APPLICANT_ID
     *
     * @return the value of FIR_BATCH_TII_LIST.APPLICANT_ID
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public String getApplicantId() {
        return applicantId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.APPLICANT_ID
     *
     * @param applicantId the value for FIR_BATCH_TII_LIST.APPLICANT_ID
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setApplicantId(String applicantId) {
        this.applicantId = applicantId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.APPLICANT_NAME
     *
     * @return the value of FIR_BATCH_TII_LIST.APPLICANT_NAME
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public String getApplicantName() {
        return applicantName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.APPLICANT_NAME
     *
     * @param applicantName the value for FIR_BATCH_TII_LIST.APPLICANT_NAME
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setApplicantName(String applicantName) {
        this.applicantName = applicantName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.APPLICANT_ADDR
     *
     * @return the value of FIR_BATCH_TII_LIST.APPLICANT_ADDR
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public String getApplicantAddr() {
        return applicantAddr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.APPLICANT_ADDR
     *
     * @param applicantAddr the value for FIR_BATCH_TII_LIST.APPLICANT_ADDR
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setApplicantAddr(String applicantAddr) {
        this.applicantAddr = applicantAddr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.INSURED_COUNT
     *
     * @return the value of FIR_BATCH_TII_LIST.INSURED_COUNT
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public Short getInsuredCount() {
        return insuredCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.INSURED_COUNT
     *
     * @param insuredCount the value for FIR_BATCH_TII_LIST.INSURED_COUNT
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setInsuredCount(Short insuredCount) {
        this.insuredCount = insuredCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.INSURED_ID
     *
     * @return the value of FIR_BATCH_TII_LIST.INSURED_ID
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public String getInsuredId() {
        return insuredId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.INSURED_ID
     *
     * @param insuredId the value for FIR_BATCH_TII_LIST.INSURED_ID
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setInsuredId(String insuredId) {
        this.insuredId = insuredId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.INSURED_NAME
     *
     * @return the value of FIR_BATCH_TII_LIST.INSURED_NAME
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public String getInsuredName() {
        return insuredName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.INSURED_NAME
     *
     * @param insuredName the value for FIR_BATCH_TII_LIST.INSURED_NAME
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setInsuredName(String insuredName) {
        this.insuredName = insuredName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.INSURED_ADDR
     *
     * @return the value of FIR_BATCH_TII_LIST.INSURED_ADDR
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public String getInsuredAddr() {
        return insuredAddr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.INSURED_ADDR
     *
     * @param insuredAddr the value for FIR_BATCH_TII_LIST.INSURED_ADDR
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setInsuredAddr(String insuredAddr) {
        this.insuredAddr = insuredAddr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.BANK_COUNT
     *
     * @return the value of FIR_BATCH_TII_LIST.BANK_COUNT
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public Short getBankCount() {
        return bankCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.BANK_COUNT
     *
     * @param bankCount the value for FIR_BATCH_TII_LIST.BANK_COUNT
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setBankCount(Short bankCount) {
        this.bankCount = bankCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.BANK_DATA
     *
     * @return the value of FIR_BATCH_TII_LIST.BANK_DATA
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public String getBankData() {
        return bankData;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.BANK_DATA
     *
     * @param bankData the value for FIR_BATCH_TII_LIST.BANK_DATA
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setBankData(String bankData) {
        this.bankData = bankData;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.REMARK
     *
     * @return the value of FIR_BATCH_TII_LIST.REMARK
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.REMARK
     *
     * @param remark the value for FIR_BATCH_TII_LIST.REMARK
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.ADDR_COUNT
     *
     * @return the value of FIR_BATCH_TII_LIST.ADDR_COUNT
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public Short getAddrCount() {
        return addrCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.ADDR_COUNT
     *
     * @param addrCount the value for FIR_BATCH_TII_LIST.ADDR_COUNT
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setAddrCount(Short addrCount) {
        this.addrCount = addrCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.STARTDATE_E
     *
     * @return the value of FIR_BATCH_TII_LIST.STARTDATE_E
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public Date getStartdateE() {
        return startdateE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.STARTDATE_E
     *
     * @param startdateE the value for FIR_BATCH_TII_LIST.STARTDATE_E
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setStartdateE(Date startdateE) {
        this.startdateE = startdateE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.ENDDATE_E
     *
     * @return the value of FIR_BATCH_TII_LIST.ENDDATE_E
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public Date getEnddateE() {
        return enddateE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.ENDDATE_E
     *
     * @param enddateE the value for FIR_BATCH_TII_LIST.ENDDATE_E
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setEnddateE(Date enddateE) {
        this.enddateE = enddateE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.ENDOR_TEXT
     *
     * @return the value of FIR_BATCH_TII_LIST.ENDOR_TEXT
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public String getEndorText() {
        return endorText;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.ENDOR_TEXT
     *
     * @param endorText the value for FIR_BATCH_TII_LIST.ENDOR_TEXT
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setEndorText(String endorText) {
        this.endorText = endorText;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.PROC_DATE
     *
     * @return the value of FIR_BATCH_TII_LIST.PROC_DATE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public Date getProcDate() {
        return procDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.PROC_DATE
     *
     * @param procDate the value for FIR_BATCH_TII_LIST.PROC_DATE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setProcDate(Date procDate) {
        this.procDate = procDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.ICREATE
     *
     * @return the value of FIR_BATCH_TII_LIST.ICREATE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public String getIcreate() {
        return icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.ICREATE
     *
     * @param icreate the value for FIR_BATCH_TII_LIST.ICREATE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setIcreate(String icreate) {
        this.icreate = icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.DCREATE
     *
     * @return the value of FIR_BATCH_TII_LIST.DCREATE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public Date getDcreate() {
        return dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.DCREATE
     *
     * @param dcreate the value for FIR_BATCH_TII_LIST.DCREATE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setDcreate(Date dcreate) {
        this.dcreate = dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.BATCH_NO
     *
     * @return the value of FIR_BATCH_TII_LIST.BATCH_NO
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.BATCH_NO
     *
     * @param batchNo the value for FIR_BATCH_TII_LIST.BATCH_NO
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.IUPDATE
     *
     * @return the value of FIR_BATCH_TII_LIST.IUPDATE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public String getIupdate() {
        return iupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.IUPDATE
     *
     * @param iupdate the value for FIR_BATCH_TII_LIST.IUPDATE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setIupdate(String iupdate) {
        this.iupdate = iupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.DUPDATE
     *
     * @return the value of FIR_BATCH_TII_LIST.DUPDATE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public Date getDupdate() {
        return dupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.DUPDATE
     *
     * @param dupdate the value for FIR_BATCH_TII_LIST.DUPDATE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setDupdate(Date dupdate) {
        this.dupdate = dupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.DATA_SOURCE
     *
     * @return the value of FIR_BATCH_TII_LIST.DATA_SOURCE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public String getDataSource() {
        return dataSource;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.DATA_SOURCE
     *
     * @param dataSource the value for FIR_BATCH_TII_LIST.DATA_SOURCE
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setDataSource(String dataSource) {
        this.dataSource = dataSource;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.BATCH_NO_SP
     *
     * @return the value of FIR_BATCH_TII_LIST.BATCH_NO_SP
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public String getBatchNoSp() {
        return batchNoSp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.BATCH_NO_SP
     *
     * @param batchNoSp the value for FIR_BATCH_TII_LIST.BATCH_NO_SP
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setBatchNoSp(String batchNoSp) {
        this.batchNoSp = batchNoSp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCH_TII_LIST.AS400_OID
     *
     * @return the value of FIR_BATCH_TII_LIST.AS400_OID
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public Long getAs400Oid() {
        return as400Oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCH_TII_LIST.AS400_OID
     *
     * @param as400Oid the value for FIR_BATCH_TII_LIST.AS400_OID
     *
     * @ibatorgenerated Fri Jun 16 19:07:06 CST 2023
     */
    public void setAs400Oid(Long as400Oid) {
        this.as400Oid = as400Oid;
    }
}