package com.tlg.prpins.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;
/* mantis：FIR0369，處理人員：BJ085，需求單編號：FIR0369 增加電子保單不寄送單位業務來源設定 */
@SuppressWarnings("serial")
public class FirBatchmailExcludedata extends IBatisBaseEntity<BigDecimal>{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCHMAIL_EXCLUDEDATA.SNO
     *
     * @ibatorgenerated Thu Sep 16 17:29:10 CST 2021
     */
    private String sno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCHMAIL_EXCLUDEDATA.BUSINESSNATURE
     *
     * @ibatorgenerated Thu Sep 16 17:29:10 CST 2021
     */
    private String businessnature;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCHMAIL_EXCLUDEDATA.EXTRACOMCODE
     *
     * @ibatorgenerated Thu Sep 16 17:29:10 CST 2021
     */
    private String extracomcode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCHMAIL_EXCLUDEDATA.ACTIVE
     *
     * @ibatorgenerated Thu Sep 16 17:29:10 CST 2021
     */
    private String active;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCHMAIL_EXCLUDEDATA.REMARK
     *
     * @ibatorgenerated Thu Sep 16 17:29:10 CST 2021
     */
    private String remark;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCHMAIL_EXCLUDEDATA.ICREATE
     *
     * @ibatorgenerated Thu Sep 16 17:29:10 CST 2021
     */
    private String icreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCHMAIL_EXCLUDEDATA.DCREATE
     *
     * @ibatorgenerated Thu Sep 16 17:29:10 CST 2021
     */
    private Date dcreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCHMAIL_EXCLUDEDATA.IUPDATE
     *
     * @ibatorgenerated Thu Sep 16 17:29:10 CST 2021
     */
    private String iupdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_BATCHMAIL_EXCLUDEDATA.DUPDATE
     *
     * @ibatorgenerated Thu Sep 16 17:29:10 CST 2021
     */
    private Date dupdate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCHMAIL_EXCLUDEDATA.SNO
     *
     * @return the value of FIR_BATCHMAIL_EXCLUDEDATA.SNO
     *
     * @ibatorgenerated Thu Sep 16 17:29:10 CST 2021
     */
    public String getSno() {
        return sno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCHMAIL_EXCLUDEDATA.SNO
     *
     * @param sno the value for FIR_BATCHMAIL_EXCLUDEDATA.SNO
     *
     * @ibatorgenerated Thu Sep 16 17:29:10 CST 2021
     */
    public void setSno(String sno) {
        this.sno = sno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCHMAIL_EXCLUDEDATA.BUSINESSNATURE
     *
     * @return the value of FIR_BATCHMAIL_EXCLUDEDATA.BUSINESSNATURE
     *
     * @ibatorgenerated Thu Sep 16 17:29:10 CST 2021
     */
    public String getBusinessnature() {
        return businessnature;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCHMAIL_EXCLUDEDATA.BUSINESSNATURE
     *
     * @param businessnature the value for FIR_BATCHMAIL_EXCLUDEDATA.BUSINESSNATURE
     *
     * @ibatorgenerated Thu Sep 16 17:29:10 CST 2021
     */
    public void setBusinessnature(String businessnature) {
        this.businessnature = businessnature;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCHMAIL_EXCLUDEDATA.EXTRACOMCODE
     *
     * @return the value of FIR_BATCHMAIL_EXCLUDEDATA.EXTRACOMCODE
     *
     * @ibatorgenerated Thu Sep 16 17:29:10 CST 2021
     */
    public String getExtracomcode() {
        return extracomcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCHMAIL_EXCLUDEDATA.EXTRACOMCODE
     *
     * @param extracomcode the value for FIR_BATCHMAIL_EXCLUDEDATA.EXTRACOMCODE
     *
     * @ibatorgenerated Thu Sep 16 17:29:10 CST 2021
     */
    public void setExtracomcode(String extracomcode) {
        this.extracomcode = extracomcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCHMAIL_EXCLUDEDATA.ACTIVE
     *
     * @return the value of FIR_BATCHMAIL_EXCLUDEDATA.ACTIVE
     *
     * @ibatorgenerated Thu Sep 16 17:29:10 CST 2021
     */
    public String getActive() {
        return active;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCHMAIL_EXCLUDEDATA.ACTIVE
     *
     * @param active the value for FIR_BATCHMAIL_EXCLUDEDATA.ACTIVE
     *
     * @ibatorgenerated Thu Sep 16 17:29:10 CST 2021
     */
    public void setActive(String active) {
        this.active = active;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCHMAIL_EXCLUDEDATA.REMARK
     *
     * @return the value of FIR_BATCHMAIL_EXCLUDEDATA.REMARK
     *
     * @ibatorgenerated Thu Sep 16 17:29:10 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCHMAIL_EXCLUDEDATA.REMARK
     *
     * @param remark the value for FIR_BATCHMAIL_EXCLUDEDATA.REMARK
     *
     * @ibatorgenerated Thu Sep 16 17:29:10 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCHMAIL_EXCLUDEDATA.ICREATE
     *
     * @return the value of FIR_BATCHMAIL_EXCLUDEDATA.ICREATE
     *
     * @ibatorgenerated Thu Sep 16 17:29:10 CST 2021
     */
    public String getIcreate() {
        return icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCHMAIL_EXCLUDEDATA.ICREATE
     *
     * @param icreate the value for FIR_BATCHMAIL_EXCLUDEDATA.ICREATE
     *
     * @ibatorgenerated Thu Sep 16 17:29:10 CST 2021
     */
    public void setIcreate(String icreate) {
        this.icreate = icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCHMAIL_EXCLUDEDATA.DCREATE
     *
     * @return the value of FIR_BATCHMAIL_EXCLUDEDATA.DCREATE
     *
     * @ibatorgenerated Thu Sep 16 17:29:10 CST 2021
     */
    public Date getDcreate() {
        return dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCHMAIL_EXCLUDEDATA.DCREATE
     *
     * @param dcreate the value for FIR_BATCHMAIL_EXCLUDEDATA.DCREATE
     *
     * @ibatorgenerated Thu Sep 16 17:29:10 CST 2021
     */
    public void setDcreate(Date dcreate) {
        this.dcreate = dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCHMAIL_EXCLUDEDATA.IUPDATE
     *
     * @return the value of FIR_BATCHMAIL_EXCLUDEDATA.IUPDATE
     *
     * @ibatorgenerated Thu Sep 16 17:29:10 CST 2021
     */
    public String getIupdate() {
        return iupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCHMAIL_EXCLUDEDATA.IUPDATE
     *
     * @param iupdate the value for FIR_BATCHMAIL_EXCLUDEDATA.IUPDATE
     *
     * @ibatorgenerated Thu Sep 16 17:29:10 CST 2021
     */
    public void setIupdate(String iupdate) {
        this.iupdate = iupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_BATCHMAIL_EXCLUDEDATA.DUPDATE
     *
     * @return the value of FIR_BATCHMAIL_EXCLUDEDATA.DUPDATE
     *
     * @ibatorgenerated Thu Sep 16 17:29:10 CST 2021
     */
    public Date getDupdate() {
        return dupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_BATCHMAIL_EXCLUDEDATA.DUPDATE
     *
     * @param dupdate the value for FIR_BATCHMAIL_EXCLUDEDATA.DUPDATE
     *
     * @ibatorgenerated Thu Sep 16 17:29:10 CST 2021
     */
    public void setDupdate(Date dupdate) {
        this.dupdate = dupdate;
    }
}