package com.tlg.prpins.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

public class FirCtbcRewDontnotice extends IBatisBaseEntity<BigDecimal>{
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_CTBC_REW_DONTNOTICE.BATCH_OID
    *
    * @mbg.generated Thu Feb 25 16:08:25 CST 2021
    */
   private BigDecimal batchOid;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_CTBC_REW_DONTNOTICE.LINENUM
    *
    * @mbg.generated Thu Feb 25 16:08:25 CST 2021
    */
   private Long linenum;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_CTBC_REW_DONTNOTICE.OWNER
     *
     * @mbg.generated Thu Feb 25 16:08:25 CST 2021
     */
    private String owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_CTBC_REW_DONTNOTICE.OWNERID
     *
     * @mbg.generated Thu Feb 25 16:08:25 CST 2021
     */
    private String ownerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_CTBC_REW_DONTNOTICE.ICREATE
     *
     * @mbg.generated Thu Feb 25 16:08:25 CST 2021
     */
    private String icreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_CTBC_REW_DONTNOTICE.DCREATE
     *
     * @mbg.generated Thu Feb 25 16:08:25 CST 2021
     */
    private Date dcreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_CTBC_REW_DONTNOTICE.OWNER
     *
     * @return the value of FIR_CTBC_REW_DONTNOTICE.OWNER
     *
     * @mbg.generated Thu Feb 25 16:08:25 CST 2021
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_CTBC_REW_DONTNOTICE.OWNER
     *
     * @param owner the value for FIR_CTBC_REW_DONTNOTICE.OWNER
     *
     * @mbg.generated Thu Feb 25 16:08:25 CST 2021
     */
    public void setOwner(String owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_CTBC_REW_DONTNOTICE.OWNERID
     *
     * @return the value of FIR_CTBC_REW_DONTNOTICE.OWNERID
     *
     * @mbg.generated Thu Feb 25 16:08:25 CST 2021
     */
    public String getOwnerid() {
        return ownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_CTBC_REW_DONTNOTICE.OWNERID
     *
     * @param ownerid the value for FIR_CTBC_REW_DONTNOTICE.OWNERID
     *
     * @mbg.generated Thu Feb 25 16:08:25 CST 2021
     */
    public void setOwnerid(String ownerid) {
        this.ownerid = ownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_CTBC_REW_DONTNOTICE.ICREATE
     *
     * @return the value of FIR_CTBC_REW_DONTNOTICE.ICREATE
     *
     * @mbg.generated Thu Feb 25 16:08:25 CST 2021
     */
    public String getIcreate() {
        return icreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_CTBC_REW_DONTNOTICE.ICREATE
     *
     * @param icreate the value for FIR_CTBC_REW_DONTNOTICE.ICREATE
     *
     * @mbg.generated Thu Feb 25 16:08:25 CST 2021
     */
    public void setIcreate(String icreate) {
        this.icreate = icreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_CTBC_REW_DONTNOTICE.DCREATE
     *
     * @return the value of FIR_CTBC_REW_DONTNOTICE.DCREATE
     *
     * @mbg.generated Thu Feb 25 16:08:25 CST 2021
     */
    public Date getDcreate() {
        return dcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_CTBC_REW_DONTNOTICE.DCREATE
     *
     * @param dcreate the value for FIR_CTBC_REW_DONTNOTICE.DCREATE
     *
     * @mbg.generated Thu Feb 25 16:08:25 CST 2021
     */
    public void setDcreate(Date dcreate) {
        this.dcreate = dcreate;
    }

	public BigDecimal getBatchOid() {
		return batchOid;
	}

	public void setBatchOid(BigDecimal batchOid) {
		this.batchOid = batchOid;
	}

	public Long getLinenum() {
		return linenum;
	}

	public void setLinenum(Long linenum) {
		this.linenum = linenum;
	}
}