package com.tlg.prpins.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

public class FirCtbcDeptinfo extends IBatisBaseEntity<BigDecimal>{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_CTBC_DEPTINFO.OID
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    private BigDecimal oid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_CTBC_DEPTINFO.BRANCH_NO
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    private String branchNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_CTBC_DEPTINFO.BRANCH_NAME
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    private String branchName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_CTBC_DEPTINFO.RECEIVED_BRANCH
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    private String receivedBranch;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_CTBC_DEPTINFO.RECEIVED_BRANCH_NAME
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    private String receivedBranchName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_CTBC_DEPTINFO.HANDLER1CODE
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    private String handler1code;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_CTBC_DEPTINFO.COMCODE
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    private String comcode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_CTBC_DEPTINFO.REMARK
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    private String remark;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_CTBC_DEPTINFO.DELETE_FLAG
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    private String deleteFlag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_CTBC_DEPTINFO.ICREATE
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    private String icreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_CTBC_DEPTINFO.DCREATE
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    private Date dcreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_CTBC_DEPTINFO.IUPDATE
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    private String iupdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_CTBC_DEPTINFO.DUPDATE
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    private Date dupdate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_CTBC_DEPTINFO.OID
     *
     * @return the value of FIR_CTBC_DEPTINFO.OID
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    public BigDecimal getOid() {
        return oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_CTBC_DEPTINFO.OID
     *
     * @param oid the value for FIR_CTBC_DEPTINFO.OID
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    public void setOid(BigDecimal oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_CTBC_DEPTINFO.BRANCH_NO
     *
     * @return the value of FIR_CTBC_DEPTINFO.BRANCH_NO
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    public String getBranchNo() {
        return branchNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_CTBC_DEPTINFO.BRANCH_NO
     *
     * @param branchNo the value for FIR_CTBC_DEPTINFO.BRANCH_NO
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    public void setBranchNo(String branchNo) {
        this.branchNo = branchNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_CTBC_DEPTINFO.BRANCH_NAME
     *
     * @return the value of FIR_CTBC_DEPTINFO.BRANCH_NAME
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    public String getBranchName() {
        return branchName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_CTBC_DEPTINFO.BRANCH_NAME
     *
     * @param branchName the value for FIR_CTBC_DEPTINFO.BRANCH_NAME
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_CTBC_DEPTINFO.RECEIVED_BRANCH
     *
     * @return the value of FIR_CTBC_DEPTINFO.RECEIVED_BRANCH
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    public String getReceivedBranch() {
        return receivedBranch;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_CTBC_DEPTINFO.RECEIVED_BRANCH
     *
     * @param receivedBranch the value for FIR_CTBC_DEPTINFO.RECEIVED_BRANCH
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    public void setReceivedBranch(String receivedBranch) {
        this.receivedBranch = receivedBranch;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_CTBC_DEPTINFO.RECEIVED_BRANCH_NAME
     *
     * @return the value of FIR_CTBC_DEPTINFO.RECEIVED_BRANCH_NAME
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    public String getReceivedBranchName() {
        return receivedBranchName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_CTBC_DEPTINFO.RECEIVED_BRANCH_NAME
     *
     * @param receivedBranchName the value for FIR_CTBC_DEPTINFO.RECEIVED_BRANCH_NAME
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    public void setReceivedBranchName(String receivedBranchName) {
        this.receivedBranchName = receivedBranchName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_CTBC_DEPTINFO.HANDLER1CODE
     *
     * @return the value of FIR_CTBC_DEPTINFO.HANDLER1CODE
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    public String getHandler1code() {
        return handler1code;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_CTBC_DEPTINFO.HANDLER1CODE
     *
     * @param handler1code the value for FIR_CTBC_DEPTINFO.HANDLER1CODE
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    public void setHandler1code(String handler1code) {
        this.handler1code = handler1code;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_CTBC_DEPTINFO.COMCODE
     *
     * @return the value of FIR_CTBC_DEPTINFO.COMCODE
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    public String getComcode() {
        return comcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_CTBC_DEPTINFO.COMCODE
     *
     * @param comcode the value for FIR_CTBC_DEPTINFO.COMCODE
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    public void setComcode(String comcode) {
        this.comcode = comcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_CTBC_DEPTINFO.REMARK
     *
     * @return the value of FIR_CTBC_DEPTINFO.REMARK
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_CTBC_DEPTINFO.REMARK
     *
     * @param remark the value for FIR_CTBC_DEPTINFO.REMARK
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_CTBC_DEPTINFO.DELETE_FLAG
     *
     * @return the value of FIR_CTBC_DEPTINFO.DELETE_FLAG
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_CTBC_DEPTINFO.DELETE_FLAG
     *
     * @param deleteFlag the value for FIR_CTBC_DEPTINFO.DELETE_FLAG
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_CTBC_DEPTINFO.ICREATE
     *
     * @return the value of FIR_CTBC_DEPTINFO.ICREATE
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    public String getIcreate() {
        return icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_CTBC_DEPTINFO.ICREATE
     *
     * @param icreate the value for FIR_CTBC_DEPTINFO.ICREATE
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    public void setIcreate(String icreate) {
        this.icreate = icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_CTBC_DEPTINFO.DCREATE
     *
     * @return the value of FIR_CTBC_DEPTINFO.DCREATE
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    public Date getDcreate() {
        return dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_CTBC_DEPTINFO.DCREATE
     *
     * @param dcreate the value for FIR_CTBC_DEPTINFO.DCREATE
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    public void setDcreate(Date dcreate) {
        this.dcreate = dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_CTBC_DEPTINFO.IUPDATE
     *
     * @return the value of FIR_CTBC_DEPTINFO.IUPDATE
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    public String getIupdate() {
        return iupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_CTBC_DEPTINFO.IUPDATE
     *
     * @param iupdate the value for FIR_CTBC_DEPTINFO.IUPDATE
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    public void setIupdate(String iupdate) {
        this.iupdate = iupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_CTBC_DEPTINFO.DUPDATE
     *
     * @return the value of FIR_CTBC_DEPTINFO.DUPDATE
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    public Date getDupdate() {
        return dupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_CTBC_DEPTINFO.DUPDATE
     *
     * @param dupdate the value for FIR_CTBC_DEPTINFO.DUPDATE
     *
     * @ibatorgenerated Mon Apr 20 14:34:58 CST 2020
     */
    public void setDupdate(Date dupdate) {
        this.dupdate = dupdate;
    }
}