package com.tlg.prpins.entity;

import java.math.BigDecimal;

import com.tlg.iBatis.IBatisBaseEntity;

public class FirPremcalcTmpdtl extends IBatisBaseEntity<BigDecimal> {
	

	private static final long serialVersionUID = 1L;

    private BigDecimal oid;

    private BigDecimal oidFirPremcalcTmp;
    private String riskcode;
    private String kindcode;
    private String paraType;
    private String para01;
    private String para02;
    private String para03;
    private String para04;
    private String para05;
    private String para06;
    private BigDecimal purePremium;
    private BigDecimal premium;
    private BigDecimal dangerGrade;
    private BigDecimal premRate;
    private BigDecimal purePremRate;
    
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_PREMCALC_TMPDTL.RISKCODE
     *
     * @return the value of FIR_PREMCALC_TMPDTL.RISKCODE
     *
     * @ibatorgenerated Fri Jun 14 15:55:06 CST 2019
     */
    public String getRiskcode() {
        return riskcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_PREMCALC_TMPDTL.RISKCODE
     *
     * @param riskcode the value for FIR_PREMCALC_TMPDTL.RISKCODE
     *
     * @ibatorgenerated Fri Jun 14 15:55:06 CST 2019
     */
    public void setRiskcode(String riskcode) {
        this.riskcode = riskcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_PREMCALC_TMPDTL.KINDCODE
     *
     * @return the value of FIR_PREMCALC_TMPDTL.KINDCODE
     *
     * @ibatorgenerated Fri Jun 14 15:55:06 CST 2019
     */
    public String getKindcode() {
        return kindcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_PREMCALC_TMPDTL.KINDCODE
     *
     * @param kindcode the value for FIR_PREMCALC_TMPDTL.KINDCODE
     *
     * @ibatorgenerated Fri Jun 14 15:55:06 CST 2019
     */
    public void setKindcode(String kindcode) {
        this.kindcode = kindcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_PREMCALC_TMPDTL.PARA_TYPE
     *
     * @return the value of FIR_PREMCALC_TMPDTL.PARA_TYPE
     *
     * @ibatorgenerated Fri Jun 14 15:55:06 CST 2019
     */
    public String getParaType() {
        return paraType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_PREMCALC_TMPDTL.PARA_TYPE
     *
     * @param paraType the value for FIR_PREMCALC_TMPDTL.PARA_TYPE
     *
     * @ibatorgenerated Fri Jun 14 15:55:06 CST 2019
     */
    public void setParaType(String paraType) {
        this.paraType = paraType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_PREMCALC_TMPDTL.PARA_01
     *
     * @return the value of FIR_PREMCALC_TMPDTL.PARA_01
     *
     * @ibatorgenerated Fri Jun 14 15:55:06 CST 2019
     */
    public String getPara01() {
        return para01;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_PREMCALC_TMPDTL.PARA_01
     *
     * @param para01 the value for FIR_PREMCALC_TMPDTL.PARA_01
     *
     * @ibatorgenerated Fri Jun 14 15:55:06 CST 2019
     */
    public void setPara01(String para01) {
        this.para01 = para01;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_PREMCALC_TMPDTL.PARA_02
     *
     * @return the value of FIR_PREMCALC_TMPDTL.PARA_02
     *
     * @ibatorgenerated Fri Jun 14 15:55:06 CST 2019
     */
    public String getPara02() {
        return para02;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_PREMCALC_TMPDTL.PARA_02
     *
     * @param para02 the value for FIR_PREMCALC_TMPDTL.PARA_02
     *
     * @ibatorgenerated Fri Jun 14 15:55:06 CST 2019
     */
    public void setPara02(String para02) {
        this.para02 = para02;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_PREMCALC_TMPDTL.PARA_03
     *
     * @return the value of FIR_PREMCALC_TMPDTL.PARA_03
     *
     * @ibatorgenerated Fri Jun 14 15:55:06 CST 2019
     */
    public String getPara03() {
        return para03;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_PREMCALC_TMPDTL.PARA_03
     *
     * @param para03 the value for FIR_PREMCALC_TMPDTL.PARA_03
     *
     * @ibatorgenerated Fri Jun 14 15:55:06 CST 2019
     */
    public void setPara03(String para03) {
        this.para03 = para03;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_PREMCALC_TMPDTL.PARA_04
     *
     * @return the value of FIR_PREMCALC_TMPDTL.PARA_04
     *
     * @ibatorgenerated Fri Jun 14 15:55:06 CST 2019
     */
    public String getPara04() {
        return para04;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_PREMCALC_TMPDTL.PARA_04
     *
     * @param para04 the value for FIR_PREMCALC_TMPDTL.PARA_04
     *
     * @ibatorgenerated Fri Jun 14 15:55:06 CST 2019
     */
    public void setPara04(String para04) {
        this.para04 = para04;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_PREMCALC_TMPDTL.PARA_05
     *
     * @return the value of FIR_PREMCALC_TMPDTL.PARA_05
     *
     * @ibatorgenerated Fri Jun 14 15:55:06 CST 2019
     */
    public String getPara05() {
        return para05;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_PREMCALC_TMPDTL.PARA_05
     *
     * @param para05 the value for FIR_PREMCALC_TMPDTL.PARA_05
     *
     * @ibatorgenerated Fri Jun 14 15:55:06 CST 2019
     */
    public void setPara05(String para05) {
        this.para05 = para05;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_PREMCALC_TMPDTL.PARA_06
     *
     * @return the value of FIR_PREMCALC_TMPDTL.PARA_06
     *
     * @ibatorgenerated Fri Jun 14 15:55:06 CST 2019
     */
    public String getPara06() {
        return para06;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_PREMCALC_TMPDTL.PARA_06
     *
     * @param para06 the value for FIR_PREMCALC_TMPDTL.PARA_06
     *
     * @ibatorgenerated Fri Jun 14 15:55:06 CST 2019
     */
    public void setPara06(String para06) {
        this.para06 = para06;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_PREMCALC_TMPDTL.PURE_PREMIUM
     *
     * @return the value of FIR_PREMCALC_TMPDTL.PURE_PREMIUM
     *
     * @ibatorgenerated Fri Jun 14 15:55:06 CST 2019
     */
    public BigDecimal getPurePremium() {
        return purePremium;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_PREMCALC_TMPDTL.PURE_PREMIUM
     *
     * @param purePremium the value for FIR_PREMCALC_TMPDTL.PURE_PREMIUM
     *
     * @ibatorgenerated Fri Jun 14 15:55:06 CST 2019
     */
    public void setPurePremium(BigDecimal purePremium) {
        this.purePremium = purePremium;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_PREMCALC_TMPDTL.PREMIUM
     *
     * @return the value of FIR_PREMCALC_TMPDTL.PREMIUM
     *
     * @ibatorgenerated Fri Jun 14 15:55:06 CST 2019
     */
    public BigDecimal getPremium() {
        return premium;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_PREMCALC_TMPDTL.PREMIUM
     *
     * @param premium the value for FIR_PREMCALC_TMPDTL.PREMIUM
     *
     * @ibatorgenerated Fri Jun 14 15:55:06 CST 2019
     */
    public void setPremium(BigDecimal premium) {
        this.premium = premium;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_PREMCALC_TMPDTL.DANGER_GRADE
     *
     * @return the value of FIR_PREMCALC_TMPDTL.DANGER_GRADE
     *
     * @ibatorgenerated Fri Jun 14 15:55:06 CST 2019
     */
    public BigDecimal getDangerGrade() {
        return dangerGrade;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_PREMCALC_TMPDTL.DANGER_GRADE
     *
     * @param dangerGrade the value for FIR_PREMCALC_TMPDTL.DANGER_GRADE
     *
     * @ibatorgenerated Fri Jun 14 15:55:06 CST 2019
     */
    public void setDangerGrade(BigDecimal dangerGrade) {
        this.dangerGrade = dangerGrade;
    }

	public BigDecimal getOid() {
		return oid;
	}

	public void setOid(BigDecimal oid) {
		this.oid = oid;
	}

	public BigDecimal getOidFirPremcalcTmp() {
		return oidFirPremcalcTmp;
	}

	public void setOidFirPremcalcTmp(BigDecimal oidFirPremcalcTmp) {
		this.oidFirPremcalcTmp = oidFirPremcalcTmp;
	}

	public BigDecimal getPremRate() {
		return premRate;
	}

	public void setPremRate(BigDecimal premRate) {
		this.premRate = premRate;
	}

	public BigDecimal getPurePremRate() {
		return purePremRate;
	}

	public void setPurePremRate(BigDecimal purePremRate) {
		this.purePremRate = purePremRate;
	}
    
}