package com.tlg.prpins.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

/* mantis：FIR0565，處理人員：CC009，需求單編號：FIR0565 住火_複保險通知轉檔作業 */
@SuppressWarnings("serial")
public class FirRepeatpolicyBatchMain extends IBatisBaseEntity<BigDecimal> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_REPEATPOLICY_BATCH_MAIN.BATCH_NO
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    private String batchNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_REPEATPOLICY_BATCH_MAIN.RP_YYYYMM
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    private String rpYyyymm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_REPEATPOLICY_BATCH_MAIN.FILENAME
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_REPEATPOLICY_BATCH_MAIN.DATA_QTY
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    private Integer dataQty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_REPEATPOLICY_BATCH_MAIN.FILE_STATUS
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    private String fileStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_REPEATPOLICY_BATCH_MAIN.REMARK
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_REPEATPOLICY_BATCH_MAIN.ICREATE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    private String icreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_REPEATPOLICY_BATCH_MAIN.DCREATE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    private Date dcreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_REPEATPOLICY_BATCH_MAIN.IUPDATE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    private String iupdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_REPEATPOLICY_BATCH_MAIN.DUPDATE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    private Date dupdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_REPEATPOLICY_BATCH_MAIN.BATCH_NO
     *
     * @return the value of FIR_REPEATPOLICY_BATCH_MAIN.BATCH_NO
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_REPEATPOLICY_BATCH_MAIN.BATCH_NO
     *
     * @param batchNo the value for FIR_REPEATPOLICY_BATCH_MAIN.BATCH_NO
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_REPEATPOLICY_BATCH_MAIN.RP_YYYYMM
     *
     * @return the value of FIR_REPEATPOLICY_BATCH_MAIN.RP_YYYYMM
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public String getRpYyyymm() {
        return rpYyyymm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_REPEATPOLICY_BATCH_MAIN.RP_YYYYMM
     *
     * @param rpYyyymm the value for FIR_REPEATPOLICY_BATCH_MAIN.RP_YYYYMM
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public void setRpYyyymm(String rpYyyymm) {
        this.rpYyyymm = rpYyyymm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_REPEATPOLICY_BATCH_MAIN.FILENAME
     *
     * @return the value of FIR_REPEATPOLICY_BATCH_MAIN.FILENAME
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_REPEATPOLICY_BATCH_MAIN.FILENAME
     *
     * @param filename the value for FIR_REPEATPOLICY_BATCH_MAIN.FILENAME
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_REPEATPOLICY_BATCH_MAIN.DATA_QTY
     *
     * @return the value of FIR_REPEATPOLICY_BATCH_MAIN.DATA_QTY
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public Integer getDataQty() {
        return dataQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_REPEATPOLICY_BATCH_MAIN.DATA_QTY
     *
     * @param dataQty the value for FIR_REPEATPOLICY_BATCH_MAIN.DATA_QTY
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public void setDataQty(Integer dataQty) {
        this.dataQty = dataQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_REPEATPOLICY_BATCH_MAIN.FILE_STATUS
     *
     * @return the value of FIR_REPEATPOLICY_BATCH_MAIN.FILE_STATUS
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public String getFileStatus() {
        return fileStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_REPEATPOLICY_BATCH_MAIN.FILE_STATUS
     *
     * @param fileStatus the value for FIR_REPEATPOLICY_BATCH_MAIN.FILE_STATUS
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public void setFileStatus(String fileStatus) {
        this.fileStatus = fileStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_REPEATPOLICY_BATCH_MAIN.REMARK
     *
     * @return the value of FIR_REPEATPOLICY_BATCH_MAIN.REMARK
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_REPEATPOLICY_BATCH_MAIN.REMARK
     *
     * @param remark the value for FIR_REPEATPOLICY_BATCH_MAIN.REMARK
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_REPEATPOLICY_BATCH_MAIN.ICREATE
     *
     * @return the value of FIR_REPEATPOLICY_BATCH_MAIN.ICREATE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public String getIcreate() {
        return icreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_REPEATPOLICY_BATCH_MAIN.ICREATE
     *
     * @param icreate the value for FIR_REPEATPOLICY_BATCH_MAIN.ICREATE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public void setIcreate(String icreate) {
        this.icreate = icreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_REPEATPOLICY_BATCH_MAIN.DCREATE
     *
     * @return the value of FIR_REPEATPOLICY_BATCH_MAIN.DCREATE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public Date getDcreate() {
        return dcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_REPEATPOLICY_BATCH_MAIN.DCREATE
     *
     * @param dcreate the value for FIR_REPEATPOLICY_BATCH_MAIN.DCREATE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public void setDcreate(Date dcreate) {
        this.dcreate = dcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_REPEATPOLICY_BATCH_MAIN.IUPDATE
     *
     * @return the value of FIR_REPEATPOLICY_BATCH_MAIN.IUPDATE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public String getIupdate() {
        return iupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_REPEATPOLICY_BATCH_MAIN.IUPDATE
     *
     * @param iupdate the value for FIR_REPEATPOLICY_BATCH_MAIN.IUPDATE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public void setIupdate(String iupdate) {
        this.iupdate = iupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_REPEATPOLICY_BATCH_MAIN.DUPDATE
     *
     * @return the value of FIR_REPEATPOLICY_BATCH_MAIN.DUPDATE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public Date getDupdate() {
        return dupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_REPEATPOLICY_BATCH_MAIN.DUPDATE
     *
     * @param dupdate the value for FIR_REPEATPOLICY_BATCH_MAIN.DUPDATE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public void setDupdate(Date dupdate) {
        this.dupdate = dupdate;
    }
}