package com.tlg.prpins.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

/*mantis：FIR0570，處理人員：BJ085，需求單編號：FIR0570 住火_APS每月應續件產生排程 */
public class FirRenewList extends IBatisBaseEntity<BigDecimal>{
	
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_RENEW_LIST.BATCH_NO
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    private String batchNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_RENEW_LIST.RN_YYMM
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    private String rnYymm;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_RENEW_LIST.DATAQTY
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    private Integer dataqty;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_RENEW_LIST.FILENAME
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    private String filename;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_RENEW_LIST.FILEDATE
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    private Date filedate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_RENEW_LIST.DELETE_FLAG
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    private String deleteFlag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_RENEW_LIST.QCAMT_FLAG
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    private String qcamtFlag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_RENEW_LIST.FCAMT_FLAG
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    private String fcamtFlag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_RENEW_LIST.REMARK
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    //mantis：FIR0571，處理人員：BJ085，需求單編號：FIR0571 住火_APS到期通知處理作業-新增印刷廠產檔作業規格
    private String remark;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_RENEW_LIST.ICREATE
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    private String icreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_RENEW_LIST.DCREATE
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    private Date dcreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_RENEW_LIST.IUPDATE
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    private String iupdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIR_RENEW_LIST.DUPDATE
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    private Date dupdate;
    
    /*mantis：FIR0571，處理人員：BJ085，需求單編號：FIR0571 住火_APS到期通知處理作業-新增印刷廠產檔作業規格 start*/
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FIR_RENEW_LIST.I99050_USER
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	private String i99050User;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FIR_RENEW_LIST.I99050_TIME
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	private Date i99050Time;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FIR_RENEW_LIST.I99050_MEMO
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	private String i99050Memo;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FIR_RENEW_LIST.I99050_BNO
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	private String i99050Bno;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FIR_RENEW_LIST.NCORE_USER
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	private String ncoreUser;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FIR_RENEW_LIST.NCORE_TIME
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	private Date ncoreTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FIR_RENEW_LIST.NCORE_MEMO
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	private String ncoreMemo;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FIR_RENEW_LIST.NCORE_BNO
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	private String ncoreBno;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FIR_RENEW_LIST.NCOREA_USER
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	private String ncoreaUser;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FIR_RENEW_LIST.NCOREA_TIME
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	private Date ncoreaTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FIR_RENEW_LIST.NCOREA_MEMO
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	private String ncoreaMemo;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column FIR_RENEW_LIST.NCOREA_BNO
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	private String ncoreaBno;
	
	private String i99065User;
	private Date i99065Time;
	private String i99065Memo;
	private String i99065Bno;
	private String i00107User;
	private Date i00107Time;
	private String i00107Memo;
	private String i00107Bno;
	/*mantis：FIR0571，處理人員：BJ085，需求單編號：FIR0571 住火_APS到期通知處理作業-新增印刷廠產檔作業規格 end*/
	// mantis：FIR0638，處理人員：DP0714，住火_APS到期續保要保書處理 -- start
	private String frnproUser;
	private Date frnproTime;
	private String frnproMemo;
	private String frnproBno; 
	
	/*mantis： FIR0685 ，處理人員：CF048，住火_APS續保通知檔案產生作業_原產生核心續件到期通知-無附加險_新增I40503勤業通路產檔格式 start */
	private String i40503User;
	private Date i40503Time;
	private String i40503Memo;
	private String i40503Bno;
	/*mantis： FIR0685 ，處理人員：CF048，住火_APS續保通知檔案產生作業_原產生核心續件到期通知-無附加險_新增I40503勤業通路產檔格式 end */
	
    public String getFrnproUser() {
		return frnproUser;
	}

	public void setFrnproUser(String frnproUser) {
		this.frnproUser = frnproUser;
	}

	public Date getFrnproTime() {
		return frnproTime;
	}

	public void setFrnproTime(Date frnproTime) {
		this.frnproTime = frnproTime;
	}

	public String getFrnproMemo() {
		return frnproMemo;
	}

	public void setFrnproMemo(String frnproMemo) {
		this.frnproMemo = frnproMemo;
	}

	public String getFrnproBno() {
		return frnproBno;
	}

	public void setFrnproBno(String frnproBno) {
		this.frnproBno = frnproBno;
	}
	// mantis：FIR0638，處理人員：DP0714，住火_APS到期續保要保書處理 -- end

	/**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_RENEW_LIST.BATCH_NO
     *
     * @return the value of FIR_RENEW_LIST.BATCH_NO
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_RENEW_LIST.BATCH_NO
     *
     * @param batchNo the value for FIR_RENEW_LIST.BATCH_NO
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_RENEW_LIST.RN_YYMM
     *
     * @return the value of FIR_RENEW_LIST.RN_YYMM
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    public String getRnYymm() {
        return rnYymm;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_RENEW_LIST.RN_YYMM
     *
     * @param rnYymm the value for FIR_RENEW_LIST.RN_YYMM
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    public void setRnYymm(String rnYymm) {
        this.rnYymm = rnYymm;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_RENEW_LIST.DATAQTY
     *
     * @return the value of FIR_RENEW_LIST.DATAQTY
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    public Integer getDataqty() {
        return dataqty;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_RENEW_LIST.DATAQTY
     *
     * @param dataqty the value for FIR_RENEW_LIST.DATAQTY
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    public void setDataqty(Integer dataqty) {
        this.dataqty = dataqty;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_RENEW_LIST.FILENAME
     *
     * @return the value of FIR_RENEW_LIST.FILENAME
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_RENEW_LIST.FILENAME
     *
     * @param filename the value for FIR_RENEW_LIST.FILENAME
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_RENEW_LIST.FILEDATE
     *
     * @return the value of FIR_RENEW_LIST.FILEDATE
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    public Date getFiledate() {
        return filedate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_RENEW_LIST.FILEDATE
     *
     * @param filedate the value for FIR_RENEW_LIST.FILEDATE
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    public void setFiledate(Date filedate) {
        this.filedate = filedate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_RENEW_LIST.DELETE_FLAG
     *
     * @return the value of FIR_RENEW_LIST.DELETE_FLAG
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_RENEW_LIST.DELETE_FLAG
     *
     * @param deleteFlag the value for FIR_RENEW_LIST.DELETE_FLAG
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_RENEW_LIST.QCAMT_FLAG
     *
     * @return the value of FIR_RENEW_LIST.QCAMT_FLAG
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    public String getQcamtFlag() {
        return qcamtFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_RENEW_LIST.QCAMT_FLAG
     *
     * @param qcamtFlag the value for FIR_RENEW_LIST.QCAMT_FLAG
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    public void setQcamtFlag(String qcamtFlag) {
        this.qcamtFlag = qcamtFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_RENEW_LIST.FCAMT_FLAG
     *
     * @return the value of FIR_RENEW_LIST.FCAMT_FLAG
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    public String getFcamtFlag() {
        return fcamtFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_RENEW_LIST.FCAMT_FLAG
     *
     * @param fcamtFlag the value for FIR_RENEW_LIST.FCAMT_FLAG
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    public void setFcamtFlag(String fcamtFlag) {
        this.fcamtFlag = fcamtFlag;
    }

    /*mantis：FIR0571，處理人員：BJ085，需求單編號：FIR0571 住火_APS到期通知處理作業-新增印刷廠產檔作業規格 start*/
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_RENEW_LIST.REMARK
     *
     * @return the value of FIR_RENEW_LIST.REMARK
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_RENEW_LIST.REMARK
     *
     * @param remark the value for FIR_RENEW_LIST.REMARK
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
    /*mantis：FIR0571，處理人員：BJ085，需求單編號：FIR0571 住火_APS到期通知處理作業-新增印刷廠產檔作業規格 end*/

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_RENEW_LIST.ICREATE
     *
     * @return the value of FIR_RENEW_LIST.ICREATE
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    public String getIcreate() {
        return icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_RENEW_LIST.ICREATE
     *
     * @param icreate the value for FIR_RENEW_LIST.ICREATE
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    public void setIcreate(String icreate) {
        this.icreate = icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_RENEW_LIST.DCREATE
     *
     * @return the value of FIR_RENEW_LIST.DCREATE
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    public Date getDcreate() {
        return dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_RENEW_LIST.DCREATE
     *
     * @param dcreate the value for FIR_RENEW_LIST.DCREATE
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    public void setDcreate(Date dcreate) {
        this.dcreate = dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_RENEW_LIST.IUPDATE
     *
     * @return the value of FIR_RENEW_LIST.IUPDATE
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    public String getIupdate() {
        return iupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_RENEW_LIST.IUPDATE
     *
     * @param iupdate the value for FIR_RENEW_LIST.IUPDATE
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    public void setIupdate(String iupdate) {
        this.iupdate = iupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIR_RENEW_LIST.DUPDATE
     *
     * @return the value of FIR_RENEW_LIST.DUPDATE
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    public Date getDupdate() {
        return dupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIR_RENEW_LIST.DUPDATE
     *
     * @param dupdate the value for FIR_RENEW_LIST.DUPDATE
     *
     * @ibatorgenerated Wed Apr 26 15:57:45 CST 2023
     */
    public void setDupdate(Date dupdate) {
        this.dupdate = dupdate;
    }
    
    /*mantis：FIR0571，處理人員：BJ085，需求單編號：FIR0571 住火_APS到期通知處理作業-新增印刷廠產檔作業規格 start*/
	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FIR_RENEW_LIST.I99050_USER
	 * @return  the value of FIR_RENEW_LIST.I99050_USER
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	public String getI99050User() {
		return i99050User;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FIR_RENEW_LIST.I99050_USER
	 * @param i99050User  the value for FIR_RENEW_LIST.I99050_USER
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	public void setI99050User(String i99050User) {
		this.i99050User = i99050User;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FIR_RENEW_LIST.I99050_TIME
	 * @return  the value of FIR_RENEW_LIST.I99050_TIME
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	public Date getI99050Time() {
		return i99050Time;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FIR_RENEW_LIST.I99050_TIME
	 * @param i99050Time  the value for FIR_RENEW_LIST.I99050_TIME
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	public void setI99050Time(Date i99050Time) {
		this.i99050Time = i99050Time;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FIR_RENEW_LIST.I99050_MEMO
	 * @return  the value of FIR_RENEW_LIST.I99050_MEMO
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	public String getI99050Memo() {
		return i99050Memo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FIR_RENEW_LIST.I99050_MEMO
	 * @param i99050Memo  the value for FIR_RENEW_LIST.I99050_MEMO
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	public void setI99050Memo(String i99050Memo) {
		this.i99050Memo = i99050Memo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FIR_RENEW_LIST.I99050_BNO
	 * @return  the value of FIR_RENEW_LIST.I99050_BNO
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	public String getI99050Bno() {
		return i99050Bno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FIR_RENEW_LIST.I99050_BNO
	 * @param i99050Bno  the value for FIR_RENEW_LIST.I99050_BNO
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	public void setI99050Bno(String i99050Bno) {
		this.i99050Bno = i99050Bno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FIR_RENEW_LIST.NCORE_USER
	 * @return  the value of FIR_RENEW_LIST.NCORE_USER
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	public String getNcoreUser() {
		return ncoreUser;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FIR_RENEW_LIST.NCORE_USER
	 * @param ncoreUser  the value for FIR_RENEW_LIST.NCORE_USER
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	public void setNcoreUser(String ncoreUser) {
		this.ncoreUser = ncoreUser;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FIR_RENEW_LIST.NCORE_TIME
	 * @return  the value of FIR_RENEW_LIST.NCORE_TIME
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	public Date getNcoreTime() {
		return ncoreTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FIR_RENEW_LIST.NCORE_TIME
	 * @param ncoreTime  the value for FIR_RENEW_LIST.NCORE_TIME
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	public void setNcoreTime(Date ncoreTime) {
		this.ncoreTime = ncoreTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FIR_RENEW_LIST.NCORE_MEMO
	 * @return  the value of FIR_RENEW_LIST.NCORE_MEMO
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	public String getNcoreMemo() {
		return ncoreMemo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FIR_RENEW_LIST.NCORE_MEMO
	 * @param ncoreMemo  the value for FIR_RENEW_LIST.NCORE_MEMO
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	public void setNcoreMemo(String ncoreMemo) {
		this.ncoreMemo = ncoreMemo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FIR_RENEW_LIST.NCORE_BNO
	 * @return  the value of FIR_RENEW_LIST.NCORE_BNO
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	public String getNcoreBno() {
		return ncoreBno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FIR_RENEW_LIST.NCORE_BNO
	 * @param ncoreBno  the value for FIR_RENEW_LIST.NCORE_BNO
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	public void setNcoreBno(String ncoreBno) {
		this.ncoreBno = ncoreBno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FIR_RENEW_LIST.NCOREA_USER
	 * @return  the value of FIR_RENEW_LIST.NCOREA_USER
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	public String getNcoreaUser() {
		return ncoreaUser;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FIR_RENEW_LIST.NCOREA_USER
	 * @param ncoreaUser  the value for FIR_RENEW_LIST.NCOREA_USER
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	public void setNcoreaUser(String ncoreaUser) {
		this.ncoreaUser = ncoreaUser;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FIR_RENEW_LIST.NCOREA_TIME
	 * @return  the value of FIR_RENEW_LIST.NCOREA_TIME
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	public Date getNcoreaTime() {
		return ncoreaTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FIR_RENEW_LIST.NCOREA_TIME
	 * @param ncoreaTime  the value for FIR_RENEW_LIST.NCOREA_TIME
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	public void setNcoreaTime(Date ncoreaTime) {
		this.ncoreaTime = ncoreaTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FIR_RENEW_LIST.NCOREA_MEMO
	 * @return  the value of FIR_RENEW_LIST.NCOREA_MEMO
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	public String getNcoreaMemo() {
		return ncoreaMemo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FIR_RENEW_LIST.NCOREA_MEMO
	 * @param ncoreaMemo  the value for FIR_RENEW_LIST.NCOREA_MEMO
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	public void setNcoreaMemo(String ncoreaMemo) {
		this.ncoreaMemo = ncoreaMemo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column FIR_RENEW_LIST.NCOREA_BNO
	 * @return  the value of FIR_RENEW_LIST.NCOREA_BNO
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	public String getNcoreaBno() {
		return ncoreaBno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column FIR_RENEW_LIST.NCOREA_BNO
	 * @param ncoreaBno  the value for FIR_RENEW_LIST.NCOREA_BNO
	 * @ibatorgenerated  Tue Jun 20 15:36:19 CST 2023
	 */
	public void setNcoreaBno(String ncoreaBno) {
		this.ncoreaBno = ncoreaBno;
	}
	public String getI99065User() {
		return i99065User;
	}

	public void setI99065User(String i99065User) {
		this.i99065User = i99065User;
	}

	public Date getI99065Time() {
		return i99065Time;
	}

	public void setI99065Time(Date i99065Time) {
		this.i99065Time = i99065Time;
	}

	public String getI99065Memo() {
		return i99065Memo;
	}

	public void setI99065Memo(String i99065Memo) {
		this.i99065Memo = i99065Memo;
	}

	public String getI99065Bno() {
		return i99065Bno;
	}

	public void setI99065Bno(String i99065Bno) {
		this.i99065Bno = i99065Bno;
	}

	public String getI00107User() {
		return i00107User;
	}

	public void setI00107User(String i00107User) {
		this.i00107User = i00107User;
	}

	public Date getI00107Time() {
		return i00107Time;
	}

	public void setI00107Time(Date i00107Time) {
		this.i00107Time = i00107Time;
	}

	public String getI00107Memo() {
		return i00107Memo;
	}

	public void setI00107Memo(String i00107Memo) {
		this.i00107Memo = i00107Memo;
	}

	public String getI00107Bno() {
		return i00107Bno;
	}

	public void setI00107Bno(String i00107Bno) {
		this.i00107Bno = i00107Bno;
	}
	/*mantis：FIR0571，處理人員：BJ085，需求單編號：FIR0571 住火_APS到期通知處理作業-新增印刷廠產檔作業規格 end*/
 
	/*mantis： FIR0685 ，處理人員：CF048，住火_APS續保通知檔案產生作業_原產生核心續件到期通知-無附加險_新增I40503勤業通路產檔格式 start */
	public String getI40503User() {
		return i40503User;
	}

	public void setI40503User(String i40503User) {
		this.i40503User = i40503User;
	}

	public Date getI40503Time() {
		return i40503Time;
	}

	public void setI40503Time(Date i40503Time) {
		this.i40503Time = i40503Time;
	}

	public String getI40503Memo() {
		return i40503Memo;
	}

	public void setI40503Memo(String i40503Memo) {
		this.i40503Memo = i40503Memo;
	}

	public String getI40503Bno() {
		return i40503Bno;
	}

	public void setI40503Bno(String i40503Bno) {
		this.i40503Bno = i40503Bno;
	}
	
	/*mantis： FIR0685 ，處理人員：CF048，住火_APS續保通知檔案產生作業_原產生核心續件到期通知-無附加險_新增I40503勤業通路產檔格式 end */
	
	
}