package com.tlg.prpins.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

/* mantis：FIR0565，處理人員：CC009，需求單編號：FIR0565 住火_複保險通知轉檔作業 */
@SuppressWarnings("serial")
public class FirRepeatpolicyBatchDtl extends IBatisBaseEntity<BigDecimal> {
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_REPEATPOLICY_BATCH_DTL.BATCH_NO
    *
    * @mbg.generated Tue Mar 21 11:23:37 CST 2023
    */
   private String batchNo;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_REPEATPOLICY_BATCH_DTL.POLICYNO
    *
    * @mbg.generated Tue Mar 21 11:23:37 CST 2023
    */
   private String policyno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_REPEATPOLICY_BATCH_DTL.IS_ENDOR
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    private String isEndor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_REPEATPOLICY_BATCH_DTL.APPLY_NAME
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    private String applyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_REPEATPOLICY_BATCH_DTL.INSURED_NAME
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    private String insuredName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_REPEATPOLICY_BATCH_DTL.INSURED_ID
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    private String insuredId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_REPEATPOLICY_BATCH_DTL.APPLY_POSTCODE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    private String applyPostcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_REPEATPOLICY_BATCH_DTL.APPLY_ADDRESS
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    private String applyAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_REPEATPOLICY_BATCH_DTL.ADDRESS_CODE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    private String addressCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_REPEATPOLICY_BATCH_DTL.ADDRESSDETAILINFO
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    private String addressdetailinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_REPEATPOLICY_BATCH_DTL.MORTGAGEEPEOPLE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    private String mortgageepeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_REPEATPOLICY_BATCH_DTL.LOANSDEPARTMENT
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    private String loansdepartment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_REPEATPOLICY_BATCH_DTL.STARTDATE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    private Date startdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_REPEATPOLICY_BATCH_DTL.ENDDATE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    private Date enddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_REPEATPOLICY_BATCH_DTL.REPEAT_COMPANY
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    private String repeatCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_REPEATPOLICY_BATCH_DTL.REPEAT_POLICYNO
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    private String repeatPolicyno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_REPEATPOLICY_BATCH_DTL.REPEAT_SDATE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    private Date repeatSdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_REPEATPOLICY_BATCH_DTL.REPEAT_EDATE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    private Date repeatEdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_REPEATPOLICY_BATCH_DTL.CONTACT_NUMBER
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    private String contactNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_REPEATPOLICY_BATCH_DTL.ICREATE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    private String icreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIR_REPEATPOLICY_BATCH_DTL.DCREATE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    private Date dcreate;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_REPEATPOLICY_BATCH_DTL.BATCH_NO
     *
     * @return the value of FIR_REPEATPOLICY_BATCH_DTL.BATCH_NO
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_REPEATPOLICY_BATCH_DTL.BATCH_NO
     *
     * @param batchNo the value for FIR_REPEATPOLICY_BATCH_DTL.BATCH_NO
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_REPEATPOLICY_BATCH_DTL.POLICYNO
     *
     * @return the value of FIR_REPEATPOLICY_BATCH_DTL.POLICYNO
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public String getPolicyno() {
        return policyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_REPEATPOLICY_BATCH_DTL.POLICYNO
     *
     * @param policyno the value for FIR_REPEATPOLICY_BATCH_DTL.POLICYNO
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public void setPolicyno(String policyno) {
        this.policyno = policyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_REPEATPOLICY_BATCH_DTL.IS_ENDOR
     *
     * @return the value of FIR_REPEATPOLICY_BATCH_DTL.IS_ENDOR
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public String getIsEndor() {
        return isEndor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_REPEATPOLICY_BATCH_DTL.IS_ENDOR
     *
     * @param isEndor the value for FIR_REPEATPOLICY_BATCH_DTL.IS_ENDOR
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public void setIsEndor(String isEndor) {
        this.isEndor = isEndor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_REPEATPOLICY_BATCH_DTL.APPLY_NAME
     *
     * @return the value of FIR_REPEATPOLICY_BATCH_DTL.APPLY_NAME
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public String getApplyName() {
        return applyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_REPEATPOLICY_BATCH_DTL.APPLY_NAME
     *
     * @param applyName the value for FIR_REPEATPOLICY_BATCH_DTL.APPLY_NAME
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public void setApplyName(String applyName) {
        this.applyName = applyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_REPEATPOLICY_BATCH_DTL.INSURED_NAME
     *
     * @return the value of FIR_REPEATPOLICY_BATCH_DTL.INSURED_NAME
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public String getInsuredName() {
        return insuredName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_REPEATPOLICY_BATCH_DTL.INSURED_NAME
     *
     * @param insuredName the value for FIR_REPEATPOLICY_BATCH_DTL.INSURED_NAME
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public void setInsuredName(String insuredName) {
        this.insuredName = insuredName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_REPEATPOLICY_BATCH_DTL.INSURED_ID
     *
     * @return the value of FIR_REPEATPOLICY_BATCH_DTL.INSURED_ID
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public String getInsuredId() {
        return insuredId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_REPEATPOLICY_BATCH_DTL.INSURED_ID
     *
     * @param insuredId the value for FIR_REPEATPOLICY_BATCH_DTL.INSURED_ID
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public void setInsuredId(String insuredId) {
        this.insuredId = insuredId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_REPEATPOLICY_BATCH_DTL.APPLY_POSTCODE
     *
     * @return the value of FIR_REPEATPOLICY_BATCH_DTL.APPLY_POSTCODE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public String getApplyPostcode() {
        return applyPostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_REPEATPOLICY_BATCH_DTL.APPLY_POSTCODE
     *
     * @param applyPostcode the value for FIR_REPEATPOLICY_BATCH_DTL.APPLY_POSTCODE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public void setApplyPostcode(String applyPostcode) {
        this.applyPostcode = applyPostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_REPEATPOLICY_BATCH_DTL.APPLY_ADDRESS
     *
     * @return the value of FIR_REPEATPOLICY_BATCH_DTL.APPLY_ADDRESS
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public String getApplyAddress() {
        return applyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_REPEATPOLICY_BATCH_DTL.APPLY_ADDRESS
     *
     * @param applyAddress the value for FIR_REPEATPOLICY_BATCH_DTL.APPLY_ADDRESS
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public void setApplyAddress(String applyAddress) {
        this.applyAddress = applyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_REPEATPOLICY_BATCH_DTL.ADDRESS_CODE
     *
     * @return the value of FIR_REPEATPOLICY_BATCH_DTL.ADDRESS_CODE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public String getAddressCode() {
        return addressCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_REPEATPOLICY_BATCH_DTL.ADDRESS_CODE
     *
     * @param addressCode the value for FIR_REPEATPOLICY_BATCH_DTL.ADDRESS_CODE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public void setAddressCode(String addressCode) {
        this.addressCode = addressCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_REPEATPOLICY_BATCH_DTL.ADDRESSDETAILINFO
     *
     * @return the value of FIR_REPEATPOLICY_BATCH_DTL.ADDRESSDETAILINFO
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public String getAddressdetailinfo() {
        return addressdetailinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_REPEATPOLICY_BATCH_DTL.ADDRESSDETAILINFO
     *
     * @param addressdetailinfo the value for FIR_REPEATPOLICY_BATCH_DTL.ADDRESSDETAILINFO
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public void setAddressdetailinfo(String addressdetailinfo) {
        this.addressdetailinfo = addressdetailinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_REPEATPOLICY_BATCH_DTL.MORTGAGEEPEOPLE
     *
     * @return the value of FIR_REPEATPOLICY_BATCH_DTL.MORTGAGEEPEOPLE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public String getMortgageepeople() {
        return mortgageepeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_REPEATPOLICY_BATCH_DTL.MORTGAGEEPEOPLE
     *
     * @param mortgageepeople the value for FIR_REPEATPOLICY_BATCH_DTL.MORTGAGEEPEOPLE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public void setMortgageepeople(String mortgageepeople) {
        this.mortgageepeople = mortgageepeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_REPEATPOLICY_BATCH_DTL.LOANSDEPARTMENT
     *
     * @return the value of FIR_REPEATPOLICY_BATCH_DTL.LOANSDEPARTMENT
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public String getLoansdepartment() {
        return loansdepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_REPEATPOLICY_BATCH_DTL.LOANSDEPARTMENT
     *
     * @param loansdepartment the value for FIR_REPEATPOLICY_BATCH_DTL.LOANSDEPARTMENT
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public void setLoansdepartment(String loansdepartment) {
        this.loansdepartment = loansdepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_REPEATPOLICY_BATCH_DTL.STARTDATE
     *
     * @return the value of FIR_REPEATPOLICY_BATCH_DTL.STARTDATE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_REPEATPOLICY_BATCH_DTL.STARTDATE
     *
     * @param startdate the value for FIR_REPEATPOLICY_BATCH_DTL.STARTDATE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_REPEATPOLICY_BATCH_DTL.ENDDATE
     *
     * @return the value of FIR_REPEATPOLICY_BATCH_DTL.ENDDATE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_REPEATPOLICY_BATCH_DTL.ENDDATE
     *
     * @param enddate the value for FIR_REPEATPOLICY_BATCH_DTL.ENDDATE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_REPEATPOLICY_BATCH_DTL.REPEAT_COMPANY
     *
     * @return the value of FIR_REPEATPOLICY_BATCH_DTL.REPEAT_COMPANY
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public String getRepeatCompany() {
        return repeatCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_REPEATPOLICY_BATCH_DTL.REPEAT_COMPANY
     *
     * @param repeatCompany the value for FIR_REPEATPOLICY_BATCH_DTL.REPEAT_COMPANY
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public void setRepeatCompany(String repeatCompany) {
        this.repeatCompany = repeatCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_REPEATPOLICY_BATCH_DTL.REPEAT_POLICYNO
     *
     * @return the value of FIR_REPEATPOLICY_BATCH_DTL.REPEAT_POLICYNO
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public String getRepeatPolicyno() {
        return repeatPolicyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_REPEATPOLICY_BATCH_DTL.REPEAT_POLICYNO
     *
     * @param repeatPolicyno the value for FIR_REPEATPOLICY_BATCH_DTL.REPEAT_POLICYNO
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public void setRepeatPolicyno(String repeatPolicyno) {
        this.repeatPolicyno = repeatPolicyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_REPEATPOLICY_BATCH_DTL.REPEAT_SDATE
     *
     * @return the value of FIR_REPEATPOLICY_BATCH_DTL.REPEAT_SDATE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public Date getRepeatSdate() {
        return repeatSdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_REPEATPOLICY_BATCH_DTL.REPEAT_SDATE
     *
     * @param repeatSdate the value for FIR_REPEATPOLICY_BATCH_DTL.REPEAT_SDATE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public void setRepeatSdate(Date repeatSdate) {
        this.repeatSdate = repeatSdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_REPEATPOLICY_BATCH_DTL.REPEAT_EDATE
     *
     * @return the value of FIR_REPEATPOLICY_BATCH_DTL.REPEAT_EDATE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public Date getRepeatEdate() {
        return repeatEdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_REPEATPOLICY_BATCH_DTL.REPEAT_EDATE
     *
     * @param repeatEdate the value for FIR_REPEATPOLICY_BATCH_DTL.REPEAT_EDATE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public void setRepeatEdate(Date repeatEdate) {
        this.repeatEdate = repeatEdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_REPEATPOLICY_BATCH_DTL.CONTACT_NUMBER
     *
     * @return the value of FIR_REPEATPOLICY_BATCH_DTL.CONTACT_NUMBER
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public String getContactNumber() {
        return contactNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_REPEATPOLICY_BATCH_DTL.CONTACT_NUMBER
     *
     * @param contactNumber the value for FIR_REPEATPOLICY_BATCH_DTL.CONTACT_NUMBER
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_REPEATPOLICY_BATCH_DTL.ICREATE
     *
     * @return the value of FIR_REPEATPOLICY_BATCH_DTL.ICREATE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public String getIcreate() {
        return icreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_REPEATPOLICY_BATCH_DTL.ICREATE
     *
     * @param icreate the value for FIR_REPEATPOLICY_BATCH_DTL.ICREATE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public void setIcreate(String icreate) {
        this.icreate = icreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIR_REPEATPOLICY_BATCH_DTL.DCREATE
     *
     * @return the value of FIR_REPEATPOLICY_BATCH_DTL.DCREATE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public Date getDcreate() {
        return dcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIR_REPEATPOLICY_BATCH_DTL.DCREATE
     *
     * @param dcreate the value for FIR_REPEATPOLICY_BATCH_DTL.DCREATE
     *
     * @mbg.generated Tue Mar 21 11:23:37 CST 2023
     */
    public void setDcreate(Date dcreate) {
        this.dcreate = dcreate;
    }
}