package com.tlg.prpins.entity;

import java.math.BigDecimal;

import com.tlg.iBatis.IBatisBaseEntity;
/** mantis：HAS0215，處理人員：CD094，需求單編號：HAS0215 TA雄獅回饋檔*/
@SuppressWarnings("serial")
public class HasAgtLionCM extends IBatisBaseEntity<BigDecimal>{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_AGT_LION_CM.OID
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    private BigDecimal oid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_AGT_LION_CM.BATCH_NO
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    private String batchNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_AGT_LION_CM.COMPANYNO
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    private String companyno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_AGT_LION_CM.PECTYPE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    private String pectype;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_AGT_LION_CM.RISKCODE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    private String riskcode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_AGT_LION_CM.AGENTORDERSEQ
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    private String agentorderseq;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_AGT_LION_CM.POLICYNO
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    private String policyno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_AGT_LION_CM.ENDORSENO
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    private String endorseno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_AGT_LION_CM.OPERATEDATE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    private String operatedate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_AGT_LION_CM.STARTDATE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    private String startdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_AGT_LION_CM.ENDDATE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    private String enddate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_AGT_LION_CM.APPLINAME
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    private String appliname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_AGT_LION_CM.APPLICODE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    private String applicode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_AGT_LION_CM.INSUREDNAME
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    private String insuredname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_AGT_LION_CM.INSUREDCODE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    private String insuredcode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_AGT_LION_CM.SUBBUSINESSNATURE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    private String subbusinessnature;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_AGT_LION_CM.SUBBUSINESSNATURENAME
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    private String subbusinessnaturename;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_AGT_LION_CM.HANDLER1CODE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    private String handler1code;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_AGT_LION_CM.HANDLER1NAME
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    private String handler1name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_AGT_LION_CM.SUMPREMIUM
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    private BigDecimal sumpremium;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_AGT_LION_CM.RATE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    private BigDecimal rate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_AGT_LION_CM.SUMDISCOUNT
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    private BigDecimal sumdiscount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_AGT_LION_CM.FYCFEE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    private BigDecimal fycfee;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_AGT_LION_CM.SERVICEFEE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    private BigDecimal servicefee;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_AGT_LION_CM.REMARK
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    private String remark;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_AGT_LION_CM.INFC15
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    private String infc15;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_AGT_LION_CM.FYCMONTH
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    private String fycmonth;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_AGT_LION_CM.CREDITCARDNO
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    private String creditcardno;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_AGT_LION_CM.OID
     *
     * @return the value of HAS_AGT_LION_CM.OID
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public BigDecimal getOid() {
        return oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_AGT_LION_CM.OID
     *
     * @param oid the value for HAS_AGT_LION_CM.OID
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public void setOid(BigDecimal oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_AGT_LION_CM.BATCH_NO
     *
     * @return the value of HAS_AGT_LION_CM.BATCH_NO
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_AGT_LION_CM.BATCH_NO
     *
     * @param batchNo the value for HAS_AGT_LION_CM.BATCH_NO
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_AGT_LION_CM.COMPANYNO
     *
     * @return the value of HAS_AGT_LION_CM.COMPANYNO
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public String getCompanyno() {
        return companyno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_AGT_LION_CM.COMPANYNO
     *
     * @param companyno the value for HAS_AGT_LION_CM.COMPANYNO
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public void setCompanyno(String companyno) {
        this.companyno = companyno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_AGT_LION_CM.PECTYPE
     *
     * @return the value of HAS_AGT_LION_CM.PECTYPE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public String getPectype() {
        return pectype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_AGT_LION_CM.PECTYPE
     *
     * @param pectype the value for HAS_AGT_LION_CM.PECTYPE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public void setPectype(String pectype) {
        this.pectype = pectype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_AGT_LION_CM.RISKCODE
     *
     * @return the value of HAS_AGT_LION_CM.RISKCODE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public String getRiskcode() {
        return riskcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_AGT_LION_CM.RISKCODE
     *
     * @param riskcode the value for HAS_AGT_LION_CM.RISKCODE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public void setRiskcode(String riskcode) {
        this.riskcode = riskcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_AGT_LION_CM.AGENTORDERSEQ
     *
     * @return the value of HAS_AGT_LION_CM.AGENTORDERSEQ
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public String getAgentorderseq() {
        return agentorderseq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_AGT_LION_CM.AGENTORDERSEQ
     *
     * @param agentorderseq the value for HAS_AGT_LION_CM.AGENTORDERSEQ
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public void setAgentorderseq(String agentorderseq) {
        this.agentorderseq = agentorderseq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_AGT_LION_CM.POLICYNO
     *
     * @return the value of HAS_AGT_LION_CM.POLICYNO
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public String getPolicyno() {
        return policyno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_AGT_LION_CM.POLICYNO
     *
     * @param policyno the value for HAS_AGT_LION_CM.POLICYNO
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public void setPolicyno(String policyno) {
        this.policyno = policyno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_AGT_LION_CM.ENDORSENO
     *
     * @return the value of HAS_AGT_LION_CM.ENDORSENO
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public String getEndorseno() {
        return endorseno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_AGT_LION_CM.ENDORSENO
     *
     * @param endorseno the value for HAS_AGT_LION_CM.ENDORSENO
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public void setEndorseno(String endorseno) {
        this.endorseno = endorseno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_AGT_LION_CM.OPERATEDATE
     *
     * @return the value of HAS_AGT_LION_CM.OPERATEDATE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public String getOperatedate() {
        return operatedate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_AGT_LION_CM.OPERATEDATE
     *
     * @param operatedate the value for HAS_AGT_LION_CM.OPERATEDATE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public void setOperatedate(String operatedate) {
        this.operatedate = operatedate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_AGT_LION_CM.STARTDATE
     *
     * @return the value of HAS_AGT_LION_CM.STARTDATE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public String getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_AGT_LION_CM.STARTDATE
     *
     * @param startdate the value for HAS_AGT_LION_CM.STARTDATE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public void setStartdate(String startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_AGT_LION_CM.ENDDATE
     *
     * @return the value of HAS_AGT_LION_CM.ENDDATE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public String getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_AGT_LION_CM.ENDDATE
     *
     * @param enddate the value for HAS_AGT_LION_CM.ENDDATE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public void setEnddate(String enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_AGT_LION_CM.APPLINAME
     *
     * @return the value of HAS_AGT_LION_CM.APPLINAME
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public String getAppliname() {
        return appliname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_AGT_LION_CM.APPLINAME
     *
     * @param appliname the value for HAS_AGT_LION_CM.APPLINAME
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public void setAppliname(String appliname) {
        this.appliname = appliname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_AGT_LION_CM.APPLICODE
     *
     * @return the value of HAS_AGT_LION_CM.APPLICODE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public String getApplicode() {
        return applicode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_AGT_LION_CM.APPLICODE
     *
     * @param applicode the value for HAS_AGT_LION_CM.APPLICODE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public void setApplicode(String applicode) {
        this.applicode = applicode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_AGT_LION_CM.INSUREDNAME
     *
     * @return the value of HAS_AGT_LION_CM.INSUREDNAME
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public String getInsuredname() {
        return insuredname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_AGT_LION_CM.INSUREDNAME
     *
     * @param insuredname the value for HAS_AGT_LION_CM.INSUREDNAME
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public void setInsuredname(String insuredname) {
        this.insuredname = insuredname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_AGT_LION_CM.INSUREDCODE
     *
     * @return the value of HAS_AGT_LION_CM.INSUREDCODE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public String getInsuredcode() {
        return insuredcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_AGT_LION_CM.INSUREDCODE
     *
     * @param insuredcode the value for HAS_AGT_LION_CM.INSUREDCODE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public void setInsuredcode(String insuredcode) {
        this.insuredcode = insuredcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_AGT_LION_CM.SUBBUSINESSNATURE
     *
     * @return the value of HAS_AGT_LION_CM.SUBBUSINESSNATURE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public String getSubbusinessnature() {
        return subbusinessnature;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_AGT_LION_CM.SUBBUSINESSNATURE
     *
     * @param subbusinessnature the value for HAS_AGT_LION_CM.SUBBUSINESSNATURE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public void setSubbusinessnature(String subbusinessnature) {
        this.subbusinessnature = subbusinessnature;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_AGT_LION_CM.SUBBUSINESSNATURENAME
     *
     * @return the value of HAS_AGT_LION_CM.SUBBUSINESSNATURENAME
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public String getSubbusinessnaturename() {
        return subbusinessnaturename;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_AGT_LION_CM.SUBBUSINESSNATURENAME
     *
     * @param subbusinessnaturename the value for HAS_AGT_LION_CM.SUBBUSINESSNATURENAME
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public void setSubbusinessnaturename(String subbusinessnaturename) {
        this.subbusinessnaturename = subbusinessnaturename;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_AGT_LION_CM.HANDLER1CODE
     *
     * @return the value of HAS_AGT_LION_CM.HANDLER1CODE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public String getHandler1code() {
        return handler1code;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_AGT_LION_CM.HANDLER1CODE
     *
     * @param handler1code the value for HAS_AGT_LION_CM.HANDLER1CODE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public void setHandler1code(String handler1code) {
        this.handler1code = handler1code;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_AGT_LION_CM.HANDLER1NAME
     *
     * @return the value of HAS_AGT_LION_CM.HANDLER1NAME
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public String getHandler1name() {
        return handler1name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_AGT_LION_CM.HANDLER1NAME
     *
     * @param handler1name the value for HAS_AGT_LION_CM.HANDLER1NAME
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public void setHandler1name(String handler1name) {
        this.handler1name = handler1name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_AGT_LION_CM.SUMPREMIUM
     *
     * @return the value of HAS_AGT_LION_CM.SUMPREMIUM
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public BigDecimal getSumpremium() {
        return sumpremium;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_AGT_LION_CM.SUMPREMIUM
     *
     * @param sumpremium the value for HAS_AGT_LION_CM.SUMPREMIUM
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public void setSumpremium(BigDecimal sumpremium) {
        this.sumpremium = sumpremium;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_AGT_LION_CM.RATE
     *
     * @return the value of HAS_AGT_LION_CM.RATE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_AGT_LION_CM.RATE
     *
     * @param rate the value for HAS_AGT_LION_CM.RATE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_AGT_LION_CM.SUMDISCOUNT
     *
     * @return the value of HAS_AGT_LION_CM.SUMDISCOUNT
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public BigDecimal getSumdiscount() {
        return sumdiscount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_AGT_LION_CM.SUMDISCOUNT
     *
     * @param sumdiscount the value for HAS_AGT_LION_CM.SUMDISCOUNT
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public void setSumdiscount(BigDecimal sumdiscount) {
        this.sumdiscount = sumdiscount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_AGT_LION_CM.FYCFEE
     *
     * @return the value of HAS_AGT_LION_CM.FYCFEE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public BigDecimal getFycfee() {
        return fycfee;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_AGT_LION_CM.FYCFEE
     *
     * @param fycfee the value for HAS_AGT_LION_CM.FYCFEE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public void setFycfee(BigDecimal fycfee) {
        this.fycfee = fycfee;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_AGT_LION_CM.SERVICEFEE
     *
     * @return the value of HAS_AGT_LION_CM.SERVICEFEE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public BigDecimal getServicefee() {
        return servicefee;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_AGT_LION_CM.SERVICEFEE
     *
     * @param servicefee the value for HAS_AGT_LION_CM.SERVICEFEE
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public void setServicefee(BigDecimal servicefee) {
        this.servicefee = servicefee;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_AGT_LION_CM.REMARK
     *
     * @return the value of HAS_AGT_LION_CM.REMARK
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_AGT_LION_CM.REMARK
     *
     * @param remark the value for HAS_AGT_LION_CM.REMARK
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_AGT_LION_CM.INFC15
     *
     * @return the value of HAS_AGT_LION_CM.INFC15
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public String getInfc15() {
        return infc15;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_AGT_LION_CM.INFC15
     *
     * @param infc15 the value for HAS_AGT_LION_CM.INFC15
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public void setInfc15(String infc15) {
        this.infc15 = infc15;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_AGT_LION_CM.FYCMONTH
     *
     * @return the value of HAS_AGT_LION_CM.FYCMONTH
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public String getFycmonth() {
        return fycmonth;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_AGT_LION_CM.FYCMONTH
     *
     * @param fycmonth the value for HAS_AGT_LION_CM.FYCMONTH
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public void setFycmonth(String fycmonth) {
        this.fycmonth = fycmonth;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_AGT_LION_CM.CREDITCARDNO
     *
     * @return the value of HAS_AGT_LION_CM.CREDITCARDNO
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public String getCreditcardno() {
        return creditcardno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_AGT_LION_CM.CREDITCARDNO
     *
     * @param creditcardno the value for HAS_AGT_LION_CM.CREDITCARDNO
     *
     * @ibatorgenerated Tue Jan 02 11:21:22 CST 2024
     */
    public void setCreditcardno(String creditcardno) {
        this.creditcardno = creditcardno;
    }
}