package com.tlg.prpins.entity;

import java.math.BigDecimal;

import com.tlg.iBatis.IBatisBaseEntity;
/**
 * mantis：HAS0284，處理人員：DP0706，需求單編號：HAS0284_遠傳優化需求-比對同要保人但生日或姓名不同
 */
@SuppressWarnings("serial")
public class HasBatchMatchFet extends IBatisBaseEntity<BigDecimal> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_BATCH_MATCH_FET.BATCH_NO
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    private String batchNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_BATCH_MATCH_FET.POLICYNO
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    private String policyno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_BATCH_MATCH_FET.INPUTDATE
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    private String inputdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_BATCH_MATCH_FET.OWNERID
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    private String ownerid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_BATCH_MATCH_FET.OWNERNAME
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    private String ownername;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_BATCH_MATCH_FET.OWNERBIRTH
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    private String ownerbirth;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_BATCH_MATCH_FET.OWNERADDR
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    private String owneraddr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_BATCH_MATCH_FET.OWNERMOBILE
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    private String ownermobile;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_BATCH_MATCH_FET.OWNEREMAIL
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    private String owneremail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_BATCH_MATCH_FET.INSID
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    private String insid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_BATCH_MATCH_FET.INSNAME
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    private String insname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_BATCH_MATCH_FET.INSBIRTH
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    private String insbirth;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_BATCH_MATCH_FET.INSADDR
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    private String insaddr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_BATCH_MATCH_FET.SUMAMOUNT
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    private Long sumamount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_BATCH_MATCH_FET.SUMPREMIUM
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    private Integer sumpremium;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_BATCH_MATCH_FET.STARTDATE
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    private String startdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_BATCH_MATCH_FET.ENDDATE
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    private String enddate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_BATCH_MATCH_FET.MAILDATE
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    private String maildate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_BATCH_MATCH_FET.UNDERWRITEENDDATE
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    private String underwriteenddate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_BATCH_MATCH_FET.BATCH_NO
     *
     * @return the value of HAS_BATCH_MATCH_FET.BATCH_NO
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_BATCH_MATCH_FET.BATCH_NO
     *
     * @param batchNo the value for HAS_BATCH_MATCH_FET.BATCH_NO
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_BATCH_MATCH_FET.POLICYNO
     *
     * @return the value of HAS_BATCH_MATCH_FET.POLICYNO
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public String getPolicyno() {
        return policyno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_BATCH_MATCH_FET.POLICYNO
     *
     * @param policyno the value for HAS_BATCH_MATCH_FET.POLICYNO
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public void setPolicyno(String policyno) {
        this.policyno = policyno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_BATCH_MATCH_FET.INPUTDATE
     *
     * @return the value of HAS_BATCH_MATCH_FET.INPUTDATE
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public String getInputdate() {
        return inputdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_BATCH_MATCH_FET.INPUTDATE
     *
     * @param inputdate the value for HAS_BATCH_MATCH_FET.INPUTDATE
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public void setInputdate(String inputdate) {
        this.inputdate = inputdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_BATCH_MATCH_FET.OWNERID
     *
     * @return the value of HAS_BATCH_MATCH_FET.OWNERID
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public String getOwnerid() {
        return ownerid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_BATCH_MATCH_FET.OWNERID
     *
     * @param ownerid the value for HAS_BATCH_MATCH_FET.OWNERID
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public void setOwnerid(String ownerid) {
        this.ownerid = ownerid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_BATCH_MATCH_FET.OWNERNAME
     *
     * @return the value of HAS_BATCH_MATCH_FET.OWNERNAME
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public String getOwnername() {
        return ownername;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_BATCH_MATCH_FET.OWNERNAME
     *
     * @param ownername the value for HAS_BATCH_MATCH_FET.OWNERNAME
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public void setOwnername(String ownername) {
        this.ownername = ownername;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_BATCH_MATCH_FET.OWNERBIRTH
     *
     * @return the value of HAS_BATCH_MATCH_FET.OWNERBIRTH
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public String getOwnerbirth() {
        return ownerbirth;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_BATCH_MATCH_FET.OWNERBIRTH
     *
     * @param ownerbirth the value for HAS_BATCH_MATCH_FET.OWNERBIRTH
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public void setOwnerbirth(String ownerbirth) {
        this.ownerbirth = ownerbirth;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_BATCH_MATCH_FET.OWNERADDR
     *
     * @return the value of HAS_BATCH_MATCH_FET.OWNERADDR
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public String getOwneraddr() {
        return owneraddr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_BATCH_MATCH_FET.OWNERADDR
     *
     * @param owneraddr the value for HAS_BATCH_MATCH_FET.OWNERADDR
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public void setOwneraddr(String owneraddr) {
        this.owneraddr = owneraddr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_BATCH_MATCH_FET.OWNERMOBILE
     *
     * @return the value of HAS_BATCH_MATCH_FET.OWNERMOBILE
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public String getOwnermobile() {
        return ownermobile;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_BATCH_MATCH_FET.OWNERMOBILE
     *
     * @param ownermobile the value for HAS_BATCH_MATCH_FET.OWNERMOBILE
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public void setOwnermobile(String ownermobile) {
        this.ownermobile = ownermobile;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_BATCH_MATCH_FET.OWNEREMAIL
     *
     * @return the value of HAS_BATCH_MATCH_FET.OWNEREMAIL
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public String getOwneremail() {
        return owneremail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_BATCH_MATCH_FET.OWNEREMAIL
     *
     * @param owneremail the value for HAS_BATCH_MATCH_FET.OWNEREMAIL
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public void setOwneremail(String owneremail) {
        this.owneremail = owneremail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_BATCH_MATCH_FET.INSID
     *
     * @return the value of HAS_BATCH_MATCH_FET.INSID
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public String getInsid() {
        return insid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_BATCH_MATCH_FET.INSID
     *
     * @param insid the value for HAS_BATCH_MATCH_FET.INSID
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public void setInsid(String insid) {
        this.insid = insid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_BATCH_MATCH_FET.INSNAME
     *
     * @return the value of HAS_BATCH_MATCH_FET.INSNAME
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public String getInsname() {
        return insname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_BATCH_MATCH_FET.INSNAME
     *
     * @param insname the value for HAS_BATCH_MATCH_FET.INSNAME
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public void setInsname(String insname) {
        this.insname = insname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_BATCH_MATCH_FET.INSBIRTH
     *
     * @return the value of HAS_BATCH_MATCH_FET.INSBIRTH
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public String getInsbirth() {
        return insbirth;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_BATCH_MATCH_FET.INSBIRTH
     *
     * @param insbirth the value for HAS_BATCH_MATCH_FET.INSBIRTH
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public void setInsbirth(String insbirth) {
        this.insbirth = insbirth;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_BATCH_MATCH_FET.INSADDR
     *
     * @return the value of HAS_BATCH_MATCH_FET.INSADDR
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public String getInsaddr() {
        return insaddr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_BATCH_MATCH_FET.INSADDR
     *
     * @param insaddr the value for HAS_BATCH_MATCH_FET.INSADDR
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public void setInsaddr(String insaddr) {
        this.insaddr = insaddr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_BATCH_MATCH_FET.SUMAMOUNT
     *
     * @return the value of HAS_BATCH_MATCH_FET.SUMAMOUNT
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public Long getSumamount() {
        return sumamount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_BATCH_MATCH_FET.SUMAMOUNT
     *
     * @param sumamount the value for HAS_BATCH_MATCH_FET.SUMAMOUNT
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public void setSumamount(Long sumamount) {
        this.sumamount = sumamount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_BATCH_MATCH_FET.SUMPREMIUM
     *
     * @return the value of HAS_BATCH_MATCH_FET.SUMPREMIUM
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public Integer getSumpremium() {
        return sumpremium;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_BATCH_MATCH_FET.SUMPREMIUM
     *
     * @param sumpremium the value for HAS_BATCH_MATCH_FET.SUMPREMIUM
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public void setSumpremium(Integer sumpremium) {
        this.sumpremium = sumpremium;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_BATCH_MATCH_FET.STARTDATE
     *
     * @return the value of HAS_BATCH_MATCH_FET.STARTDATE
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public String getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_BATCH_MATCH_FET.STARTDATE
     *
     * @param startdate the value for HAS_BATCH_MATCH_FET.STARTDATE
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public void setStartdate(String startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_BATCH_MATCH_FET.ENDDATE
     *
     * @return the value of HAS_BATCH_MATCH_FET.ENDDATE
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public String getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_BATCH_MATCH_FET.ENDDATE
     *
     * @param enddate the value for HAS_BATCH_MATCH_FET.ENDDATE
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public void setEnddate(String enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_BATCH_MATCH_FET.MAILDATE
     *
     * @return the value of HAS_BATCH_MATCH_FET.MAILDATE
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public String getMaildate() {
        return maildate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_BATCH_MATCH_FET.MAILDATE
     *
     * @param maildate the value for HAS_BATCH_MATCH_FET.MAILDATE
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public void setMaildate(String maildate) {
        this.maildate = maildate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_BATCH_MATCH_FET.UNDERWRITEENDDATE
     *
     * @return the value of HAS_BATCH_MATCH_FET.UNDERWRITEENDDATE
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public String getUnderwriteenddate() {
        return underwriteenddate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_BATCH_MATCH_FET.UNDERWRITEENDDATE
     *
     * @param underwriteenddate the value for HAS_BATCH_MATCH_FET.UNDERWRITEENDDATE
     *
     * @ibatorgenerated Thu Jun 19 13:50:19 CST 2025
     */
    public void setUnderwriteenddate(String underwriteenddate) {
        this.underwriteenddate = underwriteenddate;
    }
}