package com.tlg.prpins.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;
/** mantis：HAS0215，處理人員：CD094，需求單編號：HAS0215 TA雄獅回饋檔*/
@SuppressWarnings("serial")
public class HasBatchLog extends IBatisBaseEntity<BigDecimal> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_BATCH_LOG.OID
     *
     * @ibatorgenerated Mon Dec 25 16:18:32 CST 2023
     */
    private BigDecimal oid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_BATCH_LOG.BATCH_NO
     *
     * @ibatorgenerated Mon Dec 25 16:18:32 CST 2023
     */
    private String batchNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_BATCH_LOG.PRG_ID
     *
     * @ibatorgenerated Mon Dec 25 16:18:32 CST 2023
     */
    private String prgId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_BATCH_LOG.STATUS
     *
     * @ibatorgenerated Mon Dec 25 16:18:32 CST 2023
     */
    private String status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_BATCH_LOG.REMARK
     *
     * @ibatorgenerated Mon Dec 25 16:18:32 CST 2023
     */
    private String remark;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_BATCH_LOG.ICREATE
     *
     * @ibatorgenerated Mon Dec 25 16:18:32 CST 2023
     */
    private String icreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_BATCH_LOG.DCREATE
     *
     * @ibatorgenerated Mon Dec 25 16:18:32 CST 2023
     */
    private Date dcreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_BATCH_LOG.IUPDATE
     *
     * @ibatorgenerated Mon Dec 25 16:18:32 CST 2023
     */
    private String iupdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HAS_BATCH_LOG.DUPDATE
     *
     * @ibatorgenerated Mon Dec 25 16:18:32 CST 2023
     */
    private Date dupdate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_BATCH_LOG.OID
     *
     * @return the value of HAS_BATCH_LOG.OID
     *
     * @ibatorgenerated Mon Dec 25 16:18:32 CST 2023
     */
    public BigDecimal getOid() {
        return oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_BATCH_LOG.OID
     *
     * @param oid the value for HAS_BATCH_LOG.OID
     *
     * @ibatorgenerated Mon Dec 25 16:18:32 CST 2023
     */
    public void setOid(BigDecimal oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_BATCH_LOG.BATCH_NO
     *
     * @return the value of HAS_BATCH_LOG.BATCH_NO
     *
     * @ibatorgenerated Mon Dec 25 16:18:32 CST 2023
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_BATCH_LOG.BATCH_NO
     *
     * @param batchNo the value for HAS_BATCH_LOG.BATCH_NO
     *
     * @ibatorgenerated Mon Dec 25 16:18:32 CST 2023
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_BATCH_LOG.PRG_ID
     *
     * @return the value of HAS_BATCH_LOG.PRG_ID
     *
     * @ibatorgenerated Mon Dec 25 16:18:32 CST 2023
     */
    public String getPrgId() {
        return prgId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_BATCH_LOG.PRG_ID
     *
     * @param prgId the value for HAS_BATCH_LOG.PRG_ID
     *
     * @ibatorgenerated Mon Dec 25 16:18:32 CST 2023
     */
    public void setPrgId(String prgId) {
        this.prgId = prgId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_BATCH_LOG.STATUS
     *
     * @return the value of HAS_BATCH_LOG.STATUS
     *
     * @ibatorgenerated Mon Dec 25 16:18:32 CST 2023
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_BATCH_LOG.STATUS
     *
     * @param status the value for HAS_BATCH_LOG.STATUS
     *
     * @ibatorgenerated Mon Dec 25 16:18:32 CST 2023
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_BATCH_LOG.REMARK
     *
     * @return the value of HAS_BATCH_LOG.REMARK
     *
     * @ibatorgenerated Mon Dec 25 16:18:32 CST 2023
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_BATCH_LOG.REMARK
     *
     * @param remark the value for HAS_BATCH_LOG.REMARK
     *
     * @ibatorgenerated Mon Dec 25 16:18:32 CST 2023
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_BATCH_LOG.ICREATE
     *
     * @return the value of HAS_BATCH_LOG.ICREATE
     *
     * @ibatorgenerated Mon Dec 25 16:18:32 CST 2023
     */
    public String getIcreate() {
        return icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_BATCH_LOG.ICREATE
     *
     * @param icreate the value for HAS_BATCH_LOG.ICREATE
     *
     * @ibatorgenerated Mon Dec 25 16:18:32 CST 2023
     */
    public void setIcreate(String icreate) {
        this.icreate = icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_BATCH_LOG.DCREATE
     *
     * @return the value of HAS_BATCH_LOG.DCREATE
     *
     * @ibatorgenerated Mon Dec 25 16:18:32 CST 2023
     */
    public Date getDcreate() {
        return dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_BATCH_LOG.DCREATE
     *
     * @param dcreate the value for HAS_BATCH_LOG.DCREATE
     *
     * @ibatorgenerated Mon Dec 25 16:18:32 CST 2023
     */
    public void setDcreate(Date dcreate) {
        this.dcreate = dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_BATCH_LOG.IUPDATE
     *
     * @return the value of HAS_BATCH_LOG.IUPDATE
     *
     * @ibatorgenerated Mon Dec 25 16:18:32 CST 2023
     */
    public String getIupdate() {
        return iupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_BATCH_LOG.IUPDATE
     *
     * @param iupdate the value for HAS_BATCH_LOG.IUPDATE
     *
     * @ibatorgenerated Mon Dec 25 16:18:32 CST 2023
     */
    public void setIupdate(String iupdate) {
        this.iupdate = iupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HAS_BATCH_LOG.DUPDATE
     *
     * @return the value of HAS_BATCH_LOG.DUPDATE
     *
     * @ibatorgenerated Mon Dec 25 16:18:32 CST 2023
     */
    public Date getDupdate() {
        return dupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HAS_BATCH_LOG.DUPDATE
     *
     * @param dupdate the value for HAS_BATCH_LOG.DUPDATE
     *
     * @ibatorgenerated Mon Dec 25 16:18:32 CST 2023
     */
    public void setDupdate(Date dupdate) {
        this.dupdate = dupdate;
    }
}