package com.tlg.prpins.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

@SuppressWarnings("serial")
public class MetaAmlResultMain extends IBatisBaseEntity<BigDecimal>{
	/* mantis：OTH0065，處理人員：BJ085，需求單編號：OTH0065 建置AML洗錢查詢畫面 start */
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column METALAML_RESULT_MAIN.OID
     *
     * @ibatorgenerated Tue Oct 20 19:43:01 CST 2020
     */
    private BigDecimal oid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column METALAML_RESULT_MAIN.SCREEN_CODE
     *
     * @ibatorgenerated Tue Oct 20 19:43:01 CST 2020
     */
    private String screenCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column METALAML_RESULT_MAIN.SCREEN_MESSAGE
     *
     * @ibatorgenerated Tue Oct 20 19:43:01 CST 2020
     */
    private String screenMessage;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column METALAML_RESULT_MAIN.WLF_SCREEN_ENTRYID
     *
     * @ibatorgenerated Tue Oct 20 19:43:01 CST 2020
     */
    private String wlfScreenEntryid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column METALAML_RESULT_MAIN.WLF_SCREEN_DATE
     *
     * @ibatorgenerated Tue Oct 20 19:43:01 CST 2020
     */
    private String wlfScreenDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column METALAML_RESULT_MAIN.WLF_CASE_ID
     *
     * @ibatorgenerated Tue Oct 20 19:43:01 CST 2020
     */
    private String wlfCaseId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column METALAML_RESULT_MAIN.WLF_CASE_AFFILIATE
     *
     * @ibatorgenerated Tue Oct 20 19:43:01 CST 2020
     */
    private String wlfCaseAffiliate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column METALAML_RESULT_MAIN.WLF_CASE_USER
     *
     * @ibatorgenerated Tue Oct 20 19:43:01 CST 2020
     */
    private String wlfCaseUser;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column METALAML_RESULT_MAIN.WLF_CASE_RESULT
     *
     * @ibatorgenerated Tue Oct 20 19:43:01 CST 2020
     */
    private String wlfCaseResult;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column METALAML_RESULT_MAIN.WLF_CASE_STATUS
     *
     * @ibatorgenerated Tue Oct 20 19:43:01 CST 2020
     */
    private String wlfCaseStatus;
    
    private Date createtime;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column METALAML_RESULT_MAIN.OID
     *
     * @return the value of METALAML_RESULT_MAIN.OID
     *
     * @ibatorgenerated Tue Oct 20 19:43:01 CST 2020
     */
    
    
    private String workStatus;
	//SanStatus 制裁狀態 =>對應萊斯拒限保 (會議結論改成是否命中制裁名單與金控名單)
    private String refuseLimitInsurance;
	//INSCrrResult 保單風險 =>對應萊斯風險評級
    private String riskRating;
	//HitStatus 命中狀態 =>對應萊斯名單檢測
    private String listDetection;
    
	private String classCode;
	/**
	 * 險種代碼
	 */
	private String riskCode;
	
	private String comCode;

	private String type;

	private String appCode;

	private String businessNo;
	
	private BigDecimal oidAmlQueryObjMain;
    
    public BigDecimal getOid() {
        return oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column METALAML_RESULT_MAIN.OID
     *
     * @param oid the value for METALAML_RESULT_MAIN.OID
     *
     * @ibatorgenerated Tue Oct 20 19:43:01 CST 2020
     */
    public void setOid(BigDecimal oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column METALAML_RESULT_MAIN.SCREEN_CODE
     *
     * @return the value of METALAML_RESULT_MAIN.SCREEN_CODE
     *
     * @ibatorgenerated Tue Oct 20 19:43:01 CST 2020
     */
    public String getScreenCode() {
        return screenCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column METALAML_RESULT_MAIN.SCREEN_CODE
     *
     * @param screenCode the value for METALAML_RESULT_MAIN.SCREEN_CODE
     *
     * @ibatorgenerated Tue Oct 20 19:43:01 CST 2020
     */
    public void setScreenCode(String screenCode) {
        this.screenCode = screenCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column METALAML_RESULT_MAIN.SCREEN_MESSAGE
     *
     * @return the value of METALAML_RESULT_MAIN.SCREEN_MESSAGE
     *
     * @ibatorgenerated Tue Oct 20 19:43:01 CST 2020
     */
    public String getScreenMessage() {
        return screenMessage;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column METALAML_RESULT_MAIN.SCREEN_MESSAGE
     *
     * @param screenMessage the value for METALAML_RESULT_MAIN.SCREEN_MESSAGE
     *
     * @ibatorgenerated Tue Oct 20 19:43:01 CST 2020
     */
    public void setScreenMessage(String screenMessage) {
        this.screenMessage = screenMessage;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column METALAML_RESULT_MAIN.WLF_SCREEN_ENTRYID
     *
     * @return the value of METALAML_RESULT_MAIN.WLF_SCREEN_ENTRYID
     *
     * @ibatorgenerated Tue Oct 20 19:43:01 CST 2020
     */
    public String getWlfScreenEntryid() {
        return wlfScreenEntryid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column METALAML_RESULT_MAIN.WLF_SCREEN_ENTRYID
     *
     * @param wlfScreenEntryid the value for METALAML_RESULT_MAIN.WLF_SCREEN_ENTRYID
     *
     * @ibatorgenerated Tue Oct 20 19:43:01 CST 2020
     */
    public void setWlfScreenEntryid(String wlfScreenEntryid) {
        this.wlfScreenEntryid = wlfScreenEntryid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column METALAML_RESULT_MAIN.WLF_SCREEN_DATE
     *
     * @return the value of METALAML_RESULT_MAIN.WLF_SCREEN_DATE
     *
     * @ibatorgenerated Tue Oct 20 19:43:01 CST 2020
     */
    public String getWlfScreenDate() {
        return wlfScreenDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column METALAML_RESULT_MAIN.WLF_SCREEN_DATE
     *
     * @param wlfScreenDate the value for METALAML_RESULT_MAIN.WLF_SCREEN_DATE
     *
     * @ibatorgenerated Tue Oct 20 19:43:01 CST 2020
     */
    public void setWlfScreenDate(String wlfScreenDate) {
        this.wlfScreenDate = wlfScreenDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column METALAML_RESULT_MAIN.WLF_CASE_ID
     *
     * @return the value of METALAML_RESULT_MAIN.WLF_CASE_ID
     *
     * @ibatorgenerated Tue Oct 20 19:43:01 CST 2020
     */
    public String getWlfCaseId() {
        return wlfCaseId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column METALAML_RESULT_MAIN.WLF_CASE_ID
     *
     * @param wlfCaseId the value for METALAML_RESULT_MAIN.WLF_CASE_ID
     *
     * @ibatorgenerated Tue Oct 20 19:43:01 CST 2020
     */
    public void setWlfCaseId(String wlfCaseId) {
        this.wlfCaseId = wlfCaseId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column METALAML_RESULT_MAIN.WLF_CASE_AFFILIATE
     *
     * @return the value of METALAML_RESULT_MAIN.WLF_CASE_AFFILIATE
     *
     * @ibatorgenerated Tue Oct 20 19:43:01 CST 2020
     */
    public String getWlfCaseAffiliate() {
        return wlfCaseAffiliate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column METALAML_RESULT_MAIN.WLF_CASE_AFFILIATE
     *
     * @param wlfCaseAffiliate the value for METALAML_RESULT_MAIN.WLF_CASE_AFFILIATE
     *
     * @ibatorgenerated Tue Oct 20 19:43:01 CST 2020
     */
    public void setWlfCaseAffiliate(String wlfCaseAffiliate) {
        this.wlfCaseAffiliate = wlfCaseAffiliate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column METALAML_RESULT_MAIN.WLF_CASE_USER
     *
     * @return the value of METALAML_RESULT_MAIN.WLF_CASE_USER
     *
     * @ibatorgenerated Tue Oct 20 19:43:01 CST 2020
     */
    public String getWlfCaseUser() {
        return wlfCaseUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column METALAML_RESULT_MAIN.WLF_CASE_USER
     *
     * @param wlfCaseUser the value for METALAML_RESULT_MAIN.WLF_CASE_USER
     *
     * @ibatorgenerated Tue Oct 20 19:43:01 CST 2020
     */
    public void setWlfCaseUser(String wlfCaseUser) {
        this.wlfCaseUser = wlfCaseUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column METALAML_RESULT_MAIN.WLF_CASE_RESULT
     *
     * @return the value of METALAML_RESULT_MAIN.WLF_CASE_RESULT
     *
     * @ibatorgenerated Tue Oct 20 19:43:01 CST 2020
     */
    public String getWlfCaseResult() {
        return wlfCaseResult;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column METALAML_RESULT_MAIN.WLF_CASE_RESULT
     *
     * @param wlfCaseResult the value for METALAML_RESULT_MAIN.WLF_CASE_RESULT
     *
     * @ibatorgenerated Tue Oct 20 19:43:01 CST 2020
     */
    public void setWlfCaseResult(String wlfCaseResult) {
        this.wlfCaseResult = wlfCaseResult;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column METALAML_RESULT_MAIN.WLF_CASE_STATUS
     *
     * @return the value of METALAML_RESULT_MAIN.WLF_CASE_STATUS
     *
     * @ibatorgenerated Tue Oct 20 19:43:01 CST 2020
     */
    public String getWlfCaseStatus() {
        return wlfCaseStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column METALAML_RESULT_MAIN.WLF_CASE_STATUS
     *
     * @param wlfCaseStatus the value for METALAML_RESULT_MAIN.WLF_CASE_STATUS
     *
     * @ibatorgenerated Tue Oct 20 19:43:01 CST 2020
     */
    public void setWlfCaseStatus(String wlfCaseStatus) {
        this.wlfCaseStatus = wlfCaseStatus;
    }

	public Date getCreatetime() {
		return createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getWorkStatus() {
		return workStatus;
	}

	public void setWorkStatus(String workStatus) {
		this.workStatus = workStatus;
	}

	public String getRefuseLimitInsurance() {
		return refuseLimitInsurance;
	}

	public void setRefuseLimitInsurance(String refuseLimitInsurance) {
		this.refuseLimitInsurance = refuseLimitInsurance;
	}

	public String getRiskRating() {
		return riskRating;
	}

	public void setRiskRating(String riskRating) {
		this.riskRating = riskRating;
	}

	public String getListDetection() {
		return listDetection;
	}

	public void setListDetection(String listDetection) {
		this.listDetection = listDetection;
	}

	public String getClassCode() {
		return classCode;
	}

	public void setClassCode(String classCode) {
		this.classCode = classCode;
	}

	public String getComCode() {
		return comCode;
	}

	public void setComCode(String comCode) {
		this.comCode = comCode;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getAppCode() {
		return appCode;
	}

	public void setAppCode(String appCode) {
		this.appCode = appCode;
	}

	public String getBusinessNo() {
		return businessNo;
	}

	public void setBusinessNo(String businessNo) {
		this.businessNo = businessNo;
	}

	public String getRiskCode() {
		return riskCode;
	}

	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}

	public BigDecimal getOidAmlQueryObjMain() {
		return oidAmlQueryObjMain;
	}

	public void setOidAmlQueryObjMain(BigDecimal oidAmlQueryObjMain) {
		this.oidAmlQueryObjMain = oidAmlQueryObjMain;
	}
}