package com.tlg.prpins.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

/* mantis：OTH0127，處理人員：CC009，需求單編號：OTH0127 保發中心_保單存摺產生排程規格 */
@SuppressWarnings("serial")
public class OthBatchPassbookList extends IBatisBaseEntity<BigDecimal> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_LIST.OID
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    private BigDecimal oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_LIST.PROC_TYPE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    private String procType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_LIST.RISKCODE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    private String riskcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_LIST.POLICYNO
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    private String policyno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_LIST.SEND_CODE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    private String sendCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_LIST.INSCO_CODE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    private String inscoCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_LIST.DATA_STATUS
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    private String dataStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_LIST.INSURED_ID_OLD
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    private String insuredIdOld;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_LIST.STARTDATE_OLD
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    private Date startdateOld;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_LIST.APPLICANT_ID
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    private String applicantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_LIST.APPLICANT_NAME
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    private String applicantName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_LIST.INSURED_ID
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    private String insuredId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_LIST.INSURED_NAME
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    private String insuredName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_LIST.STARTDATE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    private Date startdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_LIST.ENDDATE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    private Date enddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_LIST.RISKCODE_TII
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    private String riskcodeTii;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_LIST.TARGET
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    private String target;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_LIST.UNDERWRITEENDDATE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    private Date underwriteenddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_LIST.REMARK
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_LIST.TII_TMP
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    private String tiiTmp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_LIST.ENDORSENO
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    private String endorseno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_LIST.ICREATE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    private String icreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_LIST.DCREATE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    private Date dcreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_LIST.BATCH_NO
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    private String batchNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_LIST.IUPDATE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    private String iupdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_LIST.DUPDATE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    private Date dupdate;
    
    private String dataSource;
    
    private String batchNoNc;
    
    private String endortype;
    
	private Date validdate;
	
	private BigDecimal kindCount;

	private BigDecimal as400Oid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_LIST.OID
     *
     * @return the value of OTH_BATCH_PASSBOOK_LIST.OID
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public BigDecimal getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_LIST.OID
     *
     * @param oid the value for OTH_BATCH_PASSBOOK_LIST.OID
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public void setOid(BigDecimal oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_LIST.PROC_TYPE
     *
     * @return the value of OTH_BATCH_PASSBOOK_LIST.PROC_TYPE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public String getProcType() {
        return procType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_LIST.PROC_TYPE
     *
     * @param procType the value for OTH_BATCH_PASSBOOK_LIST.PROC_TYPE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public void setProcType(String procType) {
        this.procType = procType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_LIST.RISKCODE
     *
     * @return the value of OTH_BATCH_PASSBOOK_LIST.RISKCODE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public String getRiskcode() {
        return riskcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_LIST.RISKCODE
     *
     * @param riskcode the value for OTH_BATCH_PASSBOOK_LIST.RISKCODE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public void setRiskcode(String riskcode) {
        this.riskcode = riskcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_LIST.POLICYNO
     *
     * @return the value of OTH_BATCH_PASSBOOK_LIST.POLICYNO
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public String getPolicyno() {
        return policyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_LIST.POLICYNO
     *
     * @param policyno the value for OTH_BATCH_PASSBOOK_LIST.POLICYNO
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public void setPolicyno(String policyno) {
        this.policyno = policyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_LIST.SEND_CODE
     *
     * @return the value of OTH_BATCH_PASSBOOK_LIST.SEND_CODE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public String getSendCode() {
        return sendCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_LIST.SEND_CODE
     *
     * @param sendCode the value for OTH_BATCH_PASSBOOK_LIST.SEND_CODE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public void setSendCode(String sendCode) {
        this.sendCode = sendCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_LIST.INSCO_CODE
     *
     * @return the value of OTH_BATCH_PASSBOOK_LIST.INSCO_CODE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public String getInscoCode() {
        return inscoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_LIST.INSCO_CODE
     *
     * @param inscoCode the value for OTH_BATCH_PASSBOOK_LIST.INSCO_CODE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public void setInscoCode(String inscoCode) {
        this.inscoCode = inscoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_LIST.DATA_STATUS
     *
     * @return the value of OTH_BATCH_PASSBOOK_LIST.DATA_STATUS
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public String getDataStatus() {
        return dataStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_LIST.DATA_STATUS
     *
     * @param dataStatus the value for OTH_BATCH_PASSBOOK_LIST.DATA_STATUS
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public void setDataStatus(String dataStatus) {
        this.dataStatus = dataStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_LIST.INSURED_ID_OLD
     *
     * @return the value of OTH_BATCH_PASSBOOK_LIST.INSURED_ID_OLD
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public String getInsuredIdOld() {
        return insuredIdOld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_LIST.INSURED_ID_OLD
     *
     * @param insuredIdOld the value for OTH_BATCH_PASSBOOK_LIST.INSURED_ID_OLD
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public void setInsuredIdOld(String insuredIdOld) {
        this.insuredIdOld = insuredIdOld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_LIST.STARTDATE_OLD
     *
     * @return the value of OTH_BATCH_PASSBOOK_LIST.STARTDATE_OLD
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public Date getStartdateOld() {
        return startdateOld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_LIST.STARTDATE_OLD
     *
     * @param startdateOld the value for OTH_BATCH_PASSBOOK_LIST.STARTDATE_OLD
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public void setStartdateOld(Date startdateOld) {
        this.startdateOld = startdateOld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_LIST.APPLICANT_ID
     *
     * @return the value of OTH_BATCH_PASSBOOK_LIST.APPLICANT_ID
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public String getApplicantId() {
        return applicantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_LIST.APPLICANT_ID
     *
     * @param applicantId the value for OTH_BATCH_PASSBOOK_LIST.APPLICANT_ID
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public void setApplicantId(String applicantId) {
        this.applicantId = applicantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_LIST.APPLICANT_NAME
     *
     * @return the value of OTH_BATCH_PASSBOOK_LIST.APPLICANT_NAME
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public String getApplicantName() {
        return applicantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_LIST.APPLICANT_NAME
     *
     * @param applicantName the value for OTH_BATCH_PASSBOOK_LIST.APPLICANT_NAME
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public void setApplicantName(String applicantName) {
        this.applicantName = applicantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_LIST.INSURED_ID
     *
     * @return the value of OTH_BATCH_PASSBOOK_LIST.INSURED_ID
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public String getInsuredId() {
        return insuredId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_LIST.INSURED_ID
     *
     * @param insuredId the value for OTH_BATCH_PASSBOOK_LIST.INSURED_ID
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public void setInsuredId(String insuredId) {
        this.insuredId = insuredId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_LIST.INSURED_NAME
     *
     * @return the value of OTH_BATCH_PASSBOOK_LIST.INSURED_NAME
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public String getInsuredName() {
        return insuredName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_LIST.INSURED_NAME
     *
     * @param insuredName the value for OTH_BATCH_PASSBOOK_LIST.INSURED_NAME
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public void setInsuredName(String insuredName) {
        this.insuredName = insuredName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_LIST.STARTDATE
     *
     * @return the value of OTH_BATCH_PASSBOOK_LIST.STARTDATE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_LIST.STARTDATE
     *
     * @param startdate the value for OTH_BATCH_PASSBOOK_LIST.STARTDATE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_LIST.ENDDATE
     *
     * @return the value of OTH_BATCH_PASSBOOK_LIST.ENDDATE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_LIST.ENDDATE
     *
     * @param enddate the value for OTH_BATCH_PASSBOOK_LIST.ENDDATE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_LIST.RISKCODE_TII
     *
     * @return the value of OTH_BATCH_PASSBOOK_LIST.RISKCODE_TII
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public String getRiskcodeTii() {
        return riskcodeTii;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_LIST.RISKCODE_TII
     *
     * @param riskcodeTii the value for OTH_BATCH_PASSBOOK_LIST.RISKCODE_TII
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public void setRiskcodeTii(String riskcodeTii) {
        this.riskcodeTii = riskcodeTii;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_LIST.TARGET
     *
     * @return the value of OTH_BATCH_PASSBOOK_LIST.TARGET
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_LIST.TARGET
     *
     * @param target the value for OTH_BATCH_PASSBOOK_LIST.TARGET
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public void setTarget(String target) {
        this.target = target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_LIST.UNDERWRITEENDDATE
     *
     * @return the value of OTH_BATCH_PASSBOOK_LIST.UNDERWRITEENDDATE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public Date getUnderwriteenddate() {
        return underwriteenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_LIST.UNDERWRITEENDDATE
     *
     * @param underwriteenddate the value for OTH_BATCH_PASSBOOK_LIST.UNDERWRITEENDDATE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public void setUnderwriteenddate(Date underwriteenddate) {
        this.underwriteenddate = underwriteenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_LIST.REMARK
     *
     * @return the value of OTH_BATCH_PASSBOOK_LIST.REMARK
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_LIST.REMARK
     *
     * @param remark the value for OTH_BATCH_PASSBOOK_LIST.REMARK
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_LIST.TII_TMP
     *
     * @return the value of OTH_BATCH_PASSBOOK_LIST.TII_TMP
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public String getTiiTmp() {
        return tiiTmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_LIST.TII_TMP
     *
     * @param tiiTmp the value for OTH_BATCH_PASSBOOK_LIST.TII_TMP
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public void setTiiTmp(String tiiTmp) {
        this.tiiTmp = tiiTmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_LIST.ENDORSENO
     *
     * @return the value of OTH_BATCH_PASSBOOK_LIST.ENDORSENO
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public String getEndorseno() {
        return endorseno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_LIST.ENDORSENO
     *
     * @param endorseno the value for OTH_BATCH_PASSBOOK_LIST.ENDORSENO
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public void setEndorseno(String endorseno) {
        this.endorseno = endorseno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_LIST.ICREATE
     *
     * @return the value of OTH_BATCH_PASSBOOK_LIST.ICREATE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public String getIcreate() {
        return icreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_LIST.ICREATE
     *
     * @param icreate the value for OTH_BATCH_PASSBOOK_LIST.ICREATE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public void setIcreate(String icreate) {
        this.icreate = icreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_LIST.DCREATE
     *
     * @return the value of OTH_BATCH_PASSBOOK_LIST.DCREATE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public Date getDcreate() {
        return dcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_LIST.DCREATE
     *
     * @param dcreate the value for OTH_BATCH_PASSBOOK_LIST.DCREATE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public void setDcreate(Date dcreate) {
        this.dcreate = dcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_LIST.BATCH_NO
     *
     * @return the value of OTH_BATCH_PASSBOOK_LIST.BATCH_NO
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_LIST.BATCH_NO
     *
     * @param batchNo the value for OTH_BATCH_PASSBOOK_LIST.BATCH_NO
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_LIST.IUPDATE
     *
     * @return the value of OTH_BATCH_PASSBOOK_LIST.IUPDATE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public String getIupdate() {
        return iupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_LIST.IUPDATE
     *
     * @param iupdate the value for OTH_BATCH_PASSBOOK_LIST.IUPDATE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public void setIupdate(String iupdate) {
        this.iupdate = iupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_LIST.DUPDATE
     *
     * @return the value of OTH_BATCH_PASSBOOK_LIST.DUPDATE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public Date getDupdate() {
        return dupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_LIST.DUPDATE
     *
     * @param dupdate the value for OTH_BATCH_PASSBOOK_LIST.DUPDATE
     *
     * @mbg.generated Tue Jul 26 14:10:44 CST 2022
     */
    public void setDupdate(Date dupdate) {
        this.dupdate = dupdate;
    }

	public String getDataSource() {
		return dataSource;
	}

	public void setDataSource(String dataSource) {
		this.dataSource = dataSource;
	}

	public String getBatchNoNc() {
		return batchNoNc;
	}

	public void setBatchNoNc(String batchNoNc) {
		this.batchNoNc = batchNoNc;
	}

	public String getEndortype() {
		return endortype;
	}

	public void setEndortype(String endortype) {
		this.endortype = endortype;
	}

	public Date getValiddate() {
		return validdate;
	}

	public void setValiddate(Date validdate) {
		this.validdate = validdate;
	}

	public BigDecimal getKindCount() {
		return kindCount;
	}

	public void setKindCount(BigDecimal kindCount) {
		this.kindCount = kindCount;
	}

	public BigDecimal getAs400Oid() {
		return as400Oid;
	}

	public void setAs400Oid(BigDecimal as400Oid) {
		this.as400Oid = as400Oid;
	}
	
}