package com.tlg.prpins.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

/** mantis：OTH0131，處理人員：BJ085，需求單編號：OTH0131 保發中心-保單存摺各險寫入中介Table作業 */
@SuppressWarnings("serial")
public class OthBatchPassbookNcData extends IBatisBaseEntity<BigDecimal>{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_NC_DATA.BATCH_SERIAL
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    private String batchSerial;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_NC_DATA.BATCH_NO
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    private String batchNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_NC_DATA.RISKCODE
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    private String riskcode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_NC_DATA.PROC_TYPE
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    private String procType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_NC_DATA.STATUS
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    private String status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_NC_DATA.QTY
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    private Long qty;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_NC_DATA.FILENAME
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    private String filename;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_NC_DATA.REMARK
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    private String remark;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_NC_DATA.ICREATE
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    private String icreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_NC_DATA.DCREATE
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    private Date dcreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column OTH_BATCH_PASSBOOK_NC_DATA.DUPDATE
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    private Date dupdate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_NC_DATA.BATCH_SERIAL
     *
     * @return the value of OTH_BATCH_PASSBOOK_NC_DATA.BATCH_SERIAL
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    public String getBatchSerial() {
        return batchSerial;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_NC_DATA.BATCH_SERIAL
     *
     * @param batchSerial the value for OTH_BATCH_PASSBOOK_NC_DATA.BATCH_SERIAL
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    public void setBatchSerial(String batchSerial) {
        this.batchSerial = batchSerial;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_NC_DATA.BATCH_NO
     *
     * @return the value of OTH_BATCH_PASSBOOK_NC_DATA.BATCH_NO
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_NC_DATA.BATCH_NO
     *
     * @param batchNo the value for OTH_BATCH_PASSBOOK_NC_DATA.BATCH_NO
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_NC_DATA.RISKCODE
     *
     * @return the value of OTH_BATCH_PASSBOOK_NC_DATA.RISKCODE
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    public String getRiskcode() {
        return riskcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_NC_DATA.RISKCODE
     *
     * @param riskcode the value for OTH_BATCH_PASSBOOK_NC_DATA.RISKCODE
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    public void setRiskcode(String riskcode) {
        this.riskcode = riskcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_NC_DATA.PROC_TYPE
     *
     * @return the value of OTH_BATCH_PASSBOOK_NC_DATA.PROC_TYPE
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    public String getProcType() {
        return procType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_NC_DATA.PROC_TYPE
     *
     * @param procType the value for OTH_BATCH_PASSBOOK_NC_DATA.PROC_TYPE
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    public void setProcType(String procType) {
        this.procType = procType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_NC_DATA.STATUS
     *
     * @return the value of OTH_BATCH_PASSBOOK_NC_DATA.STATUS
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_NC_DATA.STATUS
     *
     * @param status the value for OTH_BATCH_PASSBOOK_NC_DATA.STATUS
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_NC_DATA.QTY
     *
     * @return the value of OTH_BATCH_PASSBOOK_NC_DATA.QTY
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    public Long getQty() {
        return qty;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_NC_DATA.QTY
     *
     * @param qty the value for OTH_BATCH_PASSBOOK_NC_DATA.QTY
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    public void setQty(Long qty) {
        this.qty = qty;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_NC_DATA.FILENAME
     *
     * @return the value of OTH_BATCH_PASSBOOK_NC_DATA.FILENAME
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_NC_DATA.FILENAME
     *
     * @param filename the value for OTH_BATCH_PASSBOOK_NC_DATA.FILENAME
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_NC_DATA.REMARK
     *
     * @return the value of OTH_BATCH_PASSBOOK_NC_DATA.REMARK
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_NC_DATA.REMARK
     *
     * @param remark the value for OTH_BATCH_PASSBOOK_NC_DATA.REMARK
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_NC_DATA.ICREATE
     *
     * @return the value of OTH_BATCH_PASSBOOK_NC_DATA.ICREATE
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    public String getIcreate() {
        return icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_NC_DATA.ICREATE
     *
     * @param icreate the value for OTH_BATCH_PASSBOOK_NC_DATA.ICREATE
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    public void setIcreate(String icreate) {
        this.icreate = icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_NC_DATA.DCREATE
     *
     * @return the value of OTH_BATCH_PASSBOOK_NC_DATA.DCREATE
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    public Date getDcreate() {
        return dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_NC_DATA.DCREATE
     *
     * @param dcreate the value for OTH_BATCH_PASSBOOK_NC_DATA.DCREATE
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    public void setDcreate(Date dcreate) {
        this.dcreate = dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column OTH_BATCH_PASSBOOK_NC_DATA.DUPDATE
     *
     * @return the value of OTH_BATCH_PASSBOOK_NC_DATA.DUPDATE
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    public Date getDupdate() {
        return dupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column OTH_BATCH_PASSBOOK_NC_DATA.DUPDATE
     *
     * @param dupdate the value for OTH_BATCH_PASSBOOK_NC_DATA.DUPDATE
     *
     * @ibatorgenerated Fri Jul 29 14:39:37 CST 2022
     */
    public void setDupdate(Date dupdate) {
        this.dupdate = dupdate;
    }
}