package com.tlg.prpins.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

public class PbCklistGroup extends IBatisBaseEntity<BigDecimal>{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_CKLIST_GROUP.OID
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private BigDecimal oid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_CKLIST_GROUP.GROUP_NO
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private String groupNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_CKLIST_GROUP.GROUP_NAME
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private String groupName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_CKLIST_GROUP.GROUP_LIMIT_UPPER
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private BigDecimal groupLimitUpper;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_CKLIST_GROUP.GROUP_LIMIT_LOWER
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private BigDecimal groupLimitLower;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_CKLIST_GROUP.VALID_DATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private Date validDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_CKLIST_GROUP.INVALID_DATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private Date invalidDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_CKLIST_GROUP.VALID_FALG
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private String validFalg;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_CKLIST_GROUP.ICREATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private String icreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_CKLIST_GROUP.DCREATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private Date dcreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_CKLIST_GROUP.IUPDATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private String iupdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_CKLIST_GROUP.DUPDATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private Date dupdate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_CKLIST_GROUP.OID
     *
     * @return the value of PB_CKLIST_GROUP.OID
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public BigDecimal getOid() {
        return oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_CKLIST_GROUP.OID
     *
     * @param oid the value for PB_CKLIST_GROUP.OID
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setOid(BigDecimal oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_CKLIST_GROUP.GROUP_NO
     *
     * @return the value of PB_CKLIST_GROUP.GROUP_NO
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public String getGroupNo() {
        return groupNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_CKLIST_GROUP.GROUP_NO
     *
     * @param groupNo the value for PB_CKLIST_GROUP.GROUP_NO
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setGroupNo(String groupNo) {
        this.groupNo = groupNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_CKLIST_GROUP.GROUP_NAME
     *
     * @return the value of PB_CKLIST_GROUP.GROUP_NAME
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_CKLIST_GROUP.GROUP_NAME
     *
     * @param groupName the value for PB_CKLIST_GROUP.GROUP_NAME
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_CKLIST_GROUP.GROUP_LIMIT_UPPER
     *
     * @return the value of PB_CKLIST_GROUP.GROUP_LIMIT_UPPER
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public BigDecimal getGroupLimitUpper() {
        return groupLimitUpper;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_CKLIST_GROUP.GROUP_LIMIT_UPPER
     *
     * @param groupLimitUpper the value for PB_CKLIST_GROUP.GROUP_LIMIT_UPPER
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setGroupLimitUpper(BigDecimal groupLimitUpper) {
        this.groupLimitUpper = groupLimitUpper;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_CKLIST_GROUP.GROUP_LIMIT_LOWER
     *
     * @return the value of PB_CKLIST_GROUP.GROUP_LIMIT_LOWER
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public BigDecimal getGroupLimitLower() {
        return groupLimitLower;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_CKLIST_GROUP.GROUP_LIMIT_LOWER
     *
     * @param groupLimitLower the value for PB_CKLIST_GROUP.GROUP_LIMIT_LOWER
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setGroupLimitLower(BigDecimal groupLimitLower) {
        this.groupLimitLower = groupLimitLower;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_CKLIST_GROUP.VALID_DATE
     *
     * @return the value of PB_CKLIST_GROUP.VALID_DATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public Date getValidDate() {
        return validDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_CKLIST_GROUP.VALID_DATE
     *
     * @param validDate the value for PB_CKLIST_GROUP.VALID_DATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setValidDate(Date validDate) {
        this.validDate = validDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_CKLIST_GROUP.INVALID_DATE
     *
     * @return the value of PB_CKLIST_GROUP.INVALID_DATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public Date getInvalidDate() {
        return invalidDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_CKLIST_GROUP.INVALID_DATE
     *
     * @param invalidDate the value for PB_CKLIST_GROUP.INVALID_DATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setInvalidDate(Date invalidDate) {
        this.invalidDate = invalidDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_CKLIST_GROUP.VALID_FALG
     *
     * @return the value of PB_CKLIST_GROUP.VALID_FALG
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public String getValidFalg() {
        return validFalg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_CKLIST_GROUP.VALID_FALG
     *
     * @param validFalg the value for PB_CKLIST_GROUP.VALID_FALG
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setValidFalg(String validFalg) {
        this.validFalg = validFalg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_CKLIST_GROUP.ICREATE
     *
     * @return the value of PB_CKLIST_GROUP.ICREATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public String getIcreate() {
        return icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_CKLIST_GROUP.ICREATE
     *
     * @param icreate the value for PB_CKLIST_GROUP.ICREATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setIcreate(String icreate) {
        this.icreate = icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_CKLIST_GROUP.DCREATE
     *
     * @return the value of PB_CKLIST_GROUP.DCREATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public Date getDcreate() {
        return dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_CKLIST_GROUP.DCREATE
     *
     * @param dcreate the value for PB_CKLIST_GROUP.DCREATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setDcreate(Date dcreate) {
        this.dcreate = dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_CKLIST_GROUP.IUPDATE
     *
     * @return the value of PB_CKLIST_GROUP.IUPDATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public String getIupdate() {
        return iupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_CKLIST_GROUP.IUPDATE
     *
     * @param iupdate the value for PB_CKLIST_GROUP.IUPDATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setIupdate(String iupdate) {
        this.iupdate = iupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_CKLIST_GROUP.DUPDATE
     *
     * @return the value of PB_CKLIST_GROUP.DUPDATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public Date getDupdate() {
        return dupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_CKLIST_GROUP.DUPDATE
     *
     * @param dupdate the value for PB_CKLIST_GROUP.DUPDATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setDupdate(Date dupdate) {
        this.dupdate = dupdate;
    }
}