package com.tlg.prpins.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

public class PbDangerGrade extends IBatisBaseEntity<BigDecimal>{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_DANGER_GRADE.OID
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private BigDecimal oid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_DANGER_GRADE.RISKCODE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private String riskcode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_DANGER_GRADE.KINDCODE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private String kindcode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_DANGER_GRADE.PARA_TYPE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private String paraType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_DANGER_GRADE.CHANNEL_TYPE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private String channelType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_DANGER_GRADE.DANGER_GRADE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private BigDecimal dangerGrade;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_DANGER_GRADE.VALID_DATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private Date validDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_DANGER_GRADE.INVALID_DATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private Date invalidDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_DANGER_GRADE.VALID_FALG
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private String validFalg;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_DANGER_GRADE.ICREATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private String icreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_DANGER_GRADE.DCREATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private Date dcreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_DANGER_GRADE.IUPDATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private String iupdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_DANGER_GRADE.DUPDATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private Date dupdate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_DANGER_GRADE.OID
     *
     * @return the value of PB_DANGER_GRADE.OID
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public BigDecimal getOid() {
        return oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_DANGER_GRADE.OID
     *
     * @param oid the value for PB_DANGER_GRADE.OID
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setOid(BigDecimal oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_DANGER_GRADE.RISKCODE
     *
     * @return the value of PB_DANGER_GRADE.RISKCODE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public String getRiskcode() {
        return riskcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_DANGER_GRADE.RISKCODE
     *
     * @param riskcode the value for PB_DANGER_GRADE.RISKCODE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setRiskcode(String riskcode) {
        this.riskcode = riskcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_DANGER_GRADE.KINDCODE
     *
     * @return the value of PB_DANGER_GRADE.KINDCODE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public String getKindcode() {
        return kindcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_DANGER_GRADE.KINDCODE
     *
     * @param kindcode the value for PB_DANGER_GRADE.KINDCODE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setKindcode(String kindcode) {
        this.kindcode = kindcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_DANGER_GRADE.PARA_TYPE
     *
     * @return the value of PB_DANGER_GRADE.PARA_TYPE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public String getParaType() {
        return paraType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_DANGER_GRADE.PARA_TYPE
     *
     * @param paraType the value for PB_DANGER_GRADE.PARA_TYPE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setParaType(String paraType) {
        this.paraType = paraType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_DANGER_GRADE.CHANNEL_TYPE
     *
     * @return the value of PB_DANGER_GRADE.CHANNEL_TYPE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public String getChannelType() {
        return channelType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_DANGER_GRADE.CHANNEL_TYPE
     *
     * @param channelType the value for PB_DANGER_GRADE.CHANNEL_TYPE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setChannelType(String channelType) {
        this.channelType = channelType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_DANGER_GRADE.DANGER_GRADE
     *
     * @return the value of PB_DANGER_GRADE.DANGER_GRADE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public BigDecimal getDangerGrade() {
        return dangerGrade;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_DANGER_GRADE.DANGER_GRADE
     *
     * @param dangerGrade the value for PB_DANGER_GRADE.DANGER_GRADE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setDangerGrade(BigDecimal dangerGrade) {
        this.dangerGrade = dangerGrade;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_DANGER_GRADE.VALID_DATE
     *
     * @return the value of PB_DANGER_GRADE.VALID_DATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public Date getValidDate() {
        return validDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_DANGER_GRADE.VALID_DATE
     *
     * @param validDate the value for PB_DANGER_GRADE.VALID_DATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setValidDate(Date validDate) {
        this.validDate = validDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_DANGER_GRADE.INVALID_DATE
     *
     * @return the value of PB_DANGER_GRADE.INVALID_DATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public Date getInvalidDate() {
        return invalidDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_DANGER_GRADE.INVALID_DATE
     *
     * @param invalidDate the value for PB_DANGER_GRADE.INVALID_DATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setInvalidDate(Date invalidDate) {
        this.invalidDate = invalidDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_DANGER_GRADE.VALID_FALG
     *
     * @return the value of PB_DANGER_GRADE.VALID_FALG
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public String getValidFalg() {
        return validFalg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_DANGER_GRADE.VALID_FALG
     *
     * @param validFalg the value for PB_DANGER_GRADE.VALID_FALG
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setValidFalg(String validFalg) {
        this.validFalg = validFalg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_DANGER_GRADE.ICREATE
     *
     * @return the value of PB_DANGER_GRADE.ICREATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public String getIcreate() {
        return icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_DANGER_GRADE.ICREATE
     *
     * @param icreate the value for PB_DANGER_GRADE.ICREATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setIcreate(String icreate) {
        this.icreate = icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_DANGER_GRADE.DCREATE
     *
     * @return the value of PB_DANGER_GRADE.DCREATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public Date getDcreate() {
        return dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_DANGER_GRADE.DCREATE
     *
     * @param dcreate the value for PB_DANGER_GRADE.DCREATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setDcreate(Date dcreate) {
        this.dcreate = dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_DANGER_GRADE.IUPDATE
     *
     * @return the value of PB_DANGER_GRADE.IUPDATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public String getIupdate() {
        return iupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_DANGER_GRADE.IUPDATE
     *
     * @param iupdate the value for PB_DANGER_GRADE.IUPDATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setIupdate(String iupdate) {
        this.iupdate = iupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_DANGER_GRADE.DUPDATE
     *
     * @return the value of PB_DANGER_GRADE.DUPDATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public Date getDupdate() {
        return dupdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_DANGER_GRADE.DUPDATE
     *
     * @param dupdate the value for PB_DANGER_GRADE.DUPDATE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setDupdate(Date dupdate) {
        this.dupdate = dupdate;
    }
}