package com.tlg.prpins.entity;

import java.math.BigDecimal;

import com.tlg.iBatis.IBatisBaseEntity;

public class PbPremcalcClause extends IBatisBaseEntity<BigDecimal>{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_PREMCALC_CLAUSE.OID
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private BigDecimal oid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_PREMCALC_CLAUSE.OID_FIR_PREMCALC_TMP
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private BigDecimal oidFirPremcalcTmp;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_PREMCALC_CLAUSE.RISKCODE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private String riskcode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_PREMCALC_CLAUSE.KINDCODE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private String kindcode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_PREMCALC_CLAUSE.CLAUSECODE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private String clausecode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_PREMCALC_CLAUSE.AMOUNT_01
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private String amount01;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_PREMCALC_CLAUSE.DEDUCTION_01
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private String deduction01;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_PREMCALC_CLAUSE.ADD_PROPORTION
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private BigDecimal addProportion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_PREMCALC_CLAUSE.ADD_PREM
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private BigDecimal addPrem;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PB_PREMCALC_CLAUSE.ADD_PURE_PREM
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    private BigDecimal addPurePrem;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_PREMCALC_CLAUSE.OID
     *
     * @return the value of PB_PREMCALC_CLAUSE.OID
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public BigDecimal getOid() {
        return oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_PREMCALC_CLAUSE.OID
     *
     * @param oid the value for PB_PREMCALC_CLAUSE.OID
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setOid(BigDecimal oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_PREMCALC_CLAUSE.OID_FIR_PREMCALC_TMP
     *
     * @return the value of PB_PREMCALC_CLAUSE.OID_FIR_PREMCALC_TMP
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public BigDecimal getOidFirPremcalcTmp() {
        return oidFirPremcalcTmp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_PREMCALC_CLAUSE.OID_FIR_PREMCALC_TMP
     *
     * @param oidFirPremcalcTmp the value for PB_PREMCALC_CLAUSE.OID_FIR_PREMCALC_TMP
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setOidFirPremcalcTmp(BigDecimal oidFirPremcalcTmp) {
        this.oidFirPremcalcTmp = oidFirPremcalcTmp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_PREMCALC_CLAUSE.RISKCODE
     *
     * @return the value of PB_PREMCALC_CLAUSE.RISKCODE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public String getRiskcode() {
        return riskcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_PREMCALC_CLAUSE.RISKCODE
     *
     * @param riskcode the value for PB_PREMCALC_CLAUSE.RISKCODE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setRiskcode(String riskcode) {
        this.riskcode = riskcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_PREMCALC_CLAUSE.KINDCODE
     *
     * @return the value of PB_PREMCALC_CLAUSE.KINDCODE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public String getKindcode() {
        return kindcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_PREMCALC_CLAUSE.KINDCODE
     *
     * @param kindcode the value for PB_PREMCALC_CLAUSE.KINDCODE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setKindcode(String kindcode) {
        this.kindcode = kindcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_PREMCALC_CLAUSE.CLAUSECODE
     *
     * @return the value of PB_PREMCALC_CLAUSE.CLAUSECODE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public String getClausecode() {
        return clausecode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_PREMCALC_CLAUSE.CLAUSECODE
     *
     * @param clausecode the value for PB_PREMCALC_CLAUSE.CLAUSECODE
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setClausecode(String clausecode) {
        this.clausecode = clausecode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_PREMCALC_CLAUSE.AMOUNT_01
     *
     * @return the value of PB_PREMCALC_CLAUSE.AMOUNT_01
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public String getAmount01() {
        return amount01;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_PREMCALC_CLAUSE.AMOUNT_01
     *
     * @param amount01 the value for PB_PREMCALC_CLAUSE.AMOUNT_01
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setAmount01(String amount01) {
        this.amount01 = amount01;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_PREMCALC_CLAUSE.DEDUCTION_01
     *
     * @return the value of PB_PREMCALC_CLAUSE.DEDUCTION_01
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public String getDeduction01() {
        return deduction01;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_PREMCALC_CLAUSE.DEDUCTION_01
     *
     * @param deduction01 the value for PB_PREMCALC_CLAUSE.DEDUCTION_01
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setDeduction01(String deduction01) {
        this.deduction01 = deduction01;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_PREMCALC_CLAUSE.ADD_PROPORTION
     *
     * @return the value of PB_PREMCALC_CLAUSE.ADD_PROPORTION
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public BigDecimal getAddProportion() {
        return addProportion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_PREMCALC_CLAUSE.ADD_PROPORTION
     *
     * @param addProportion the value for PB_PREMCALC_CLAUSE.ADD_PROPORTION
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setAddProportion(BigDecimal addProportion) {
        this.addProportion = addProportion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_PREMCALC_CLAUSE.ADD_PREM
     *
     * @return the value of PB_PREMCALC_CLAUSE.ADD_PREM
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public BigDecimal getAddPrem() {
        return addPrem;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_PREMCALC_CLAUSE.ADD_PREM
     *
     * @param addPrem the value for PB_PREMCALC_CLAUSE.ADD_PREM
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setAddPrem(BigDecimal addPrem) {
        this.addPrem = addPrem;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PB_PREMCALC_CLAUSE.ADD_PURE_PREM
     *
     * @return the value of PB_PREMCALC_CLAUSE.ADD_PURE_PREM
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public BigDecimal getAddPurePrem() {
        return addPurePrem;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PB_PREMCALC_CLAUSE.ADD_PURE_PREM
     *
     * @param addPurePrem the value for PB_PREMCALC_CLAUSE.ADD_PURE_PREM
     *
     * @ibatorgenerated Tue Nov 26 20:12:12 CST 2019
     */
    public void setAddPurePrem(BigDecimal addPurePrem) {
        this.addPurePrem = addPurePrem;
    }
}