package com.tlg.prpins.entity;

import java.math.BigDecimal;

import com.tlg.iBatis.IBatisBaseEntity;

/*mantis：FIR0570，處理人員：BJ085，需求單編號：FIR0570 住火_APS每月應續件產生排程 */
public class Prpcpayment extends IBatisBaseEntity<BigDecimal>{
	
	private static final long serialVersionUID = 1L;
	
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPAYMENT.POLICYNO
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    private String policyno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPAYMENT.RISKCODE
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    private String riskcode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPAYMENT.FLAG
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    private String flag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPAYMENT.PAYWAY
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    private String payway;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPAYMENT.CREDITNO
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    private String creditno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPAYMENT.CREDITDATE
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    private String creditdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPAYMENT.PAYER_NAME
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    private String payerName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPAYMENT.PAYER_ID
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    private String payerId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPAYMENT.PAYER_TYPE
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    private String payerType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPAYMENT.PAYER_RELATION
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    private String payerRelation;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPAYMENT.RELATION_DOC
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    private String relationDoc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPAYMENT.RN_PAYWAY
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    private String rnPayway;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPAYMENT.RN_CREDITNO
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    private String rnCreditno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPAYMENT.RN_CREDITDATE
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    private String rnCreditdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPAYMENT.RN_PAYER_NAME
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    private String rnPayerName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPAYMENT.RN_PAYER_ID
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    private String rnPayerId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPAYMENT.RN_PAYER_TYPE
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    private String rnPayerType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPAYMENT.RN_PAYER_RELATION
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    private String rnPayerRelation;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPAYMENT.RN_RELATION_DOC
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    private String rnRelationDoc;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PRPCPAYMENT.POLICYNO
     *
     * @return the value of PRPCPAYMENT.POLICYNO
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public String getPolicyno() {
        return policyno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PRPCPAYMENT.POLICYNO
     *
     * @param policyno the value for PRPCPAYMENT.POLICYNO
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public void setPolicyno(String policyno) {
        this.policyno = policyno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PRPCPAYMENT.RISKCODE
     *
     * @return the value of PRPCPAYMENT.RISKCODE
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public String getRiskcode() {
        return riskcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PRPCPAYMENT.RISKCODE
     *
     * @param riskcode the value for PRPCPAYMENT.RISKCODE
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public void setRiskcode(String riskcode) {
        this.riskcode = riskcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PRPCPAYMENT.FLAG
     *
     * @return the value of PRPCPAYMENT.FLAG
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PRPCPAYMENT.FLAG
     *
     * @param flag the value for PRPCPAYMENT.FLAG
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public void setFlag(String flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PRPCPAYMENT.PAYWAY
     *
     * @return the value of PRPCPAYMENT.PAYWAY
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public String getPayway() {
        return payway;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PRPCPAYMENT.PAYWAY
     *
     * @param payway the value for PRPCPAYMENT.PAYWAY
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public void setPayway(String payway) {
        this.payway = payway;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PRPCPAYMENT.CREDITNO
     *
     * @return the value of PRPCPAYMENT.CREDITNO
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public String getCreditno() {
        return creditno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PRPCPAYMENT.CREDITNO
     *
     * @param creditno the value for PRPCPAYMENT.CREDITNO
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public void setCreditno(String creditno) {
        this.creditno = creditno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PRPCPAYMENT.CREDITDATE
     *
     * @return the value of PRPCPAYMENT.CREDITDATE
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public String getCreditdate() {
        return creditdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PRPCPAYMENT.CREDITDATE
     *
     * @param creditdate the value for PRPCPAYMENT.CREDITDATE
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public void setCreditdate(String creditdate) {
        this.creditdate = creditdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PRPCPAYMENT.PAYER_NAME
     *
     * @return the value of PRPCPAYMENT.PAYER_NAME
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public String getPayerName() {
        return payerName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PRPCPAYMENT.PAYER_NAME
     *
     * @param payerName the value for PRPCPAYMENT.PAYER_NAME
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public void setPayerName(String payerName) {
        this.payerName = payerName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PRPCPAYMENT.PAYER_ID
     *
     * @return the value of PRPCPAYMENT.PAYER_ID
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public String getPayerId() {
        return payerId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PRPCPAYMENT.PAYER_ID
     *
     * @param payerId the value for PRPCPAYMENT.PAYER_ID
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public void setPayerId(String payerId) {
        this.payerId = payerId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PRPCPAYMENT.PAYER_TYPE
     *
     * @return the value of PRPCPAYMENT.PAYER_TYPE
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public String getPayerType() {
        return payerType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PRPCPAYMENT.PAYER_TYPE
     *
     * @param payerType the value for PRPCPAYMENT.PAYER_TYPE
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public void setPayerType(String payerType) {
        this.payerType = payerType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PRPCPAYMENT.PAYER_RELATION
     *
     * @return the value of PRPCPAYMENT.PAYER_RELATION
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public String getPayerRelation() {
        return payerRelation;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PRPCPAYMENT.PAYER_RELATION
     *
     * @param payerRelation the value for PRPCPAYMENT.PAYER_RELATION
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public void setPayerRelation(String payerRelation) {
        this.payerRelation = payerRelation;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PRPCPAYMENT.RELATION_DOC
     *
     * @return the value of PRPCPAYMENT.RELATION_DOC
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public String getRelationDoc() {
        return relationDoc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PRPCPAYMENT.RELATION_DOC
     *
     * @param relationDoc the value for PRPCPAYMENT.RELATION_DOC
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public void setRelationDoc(String relationDoc) {
        this.relationDoc = relationDoc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PRPCPAYMENT.RN_PAYWAY
     *
     * @return the value of PRPCPAYMENT.RN_PAYWAY
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public String getRnPayway() {
        return rnPayway;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PRPCPAYMENT.RN_PAYWAY
     *
     * @param rnPayway the value for PRPCPAYMENT.RN_PAYWAY
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public void setRnPayway(String rnPayway) {
        this.rnPayway = rnPayway;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PRPCPAYMENT.RN_CREDITNO
     *
     * @return the value of PRPCPAYMENT.RN_CREDITNO
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public String getRnCreditno() {
        return rnCreditno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PRPCPAYMENT.RN_CREDITNO
     *
     * @param rnCreditno the value for PRPCPAYMENT.RN_CREDITNO
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public void setRnCreditno(String rnCreditno) {
        this.rnCreditno = rnCreditno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PRPCPAYMENT.RN_CREDITDATE
     *
     * @return the value of PRPCPAYMENT.RN_CREDITDATE
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public String getRnCreditdate() {
        return rnCreditdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PRPCPAYMENT.RN_CREDITDATE
     *
     * @param rnCreditdate the value for PRPCPAYMENT.RN_CREDITDATE
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public void setRnCreditdate(String rnCreditdate) {
        this.rnCreditdate = rnCreditdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PRPCPAYMENT.RN_PAYER_NAME
     *
     * @return the value of PRPCPAYMENT.RN_PAYER_NAME
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public String getRnPayerName() {
        return rnPayerName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PRPCPAYMENT.RN_PAYER_NAME
     *
     * @param rnPayerName the value for PRPCPAYMENT.RN_PAYER_NAME
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public void setRnPayerName(String rnPayerName) {
        this.rnPayerName = rnPayerName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PRPCPAYMENT.RN_PAYER_ID
     *
     * @return the value of PRPCPAYMENT.RN_PAYER_ID
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public String getRnPayerId() {
        return rnPayerId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PRPCPAYMENT.RN_PAYER_ID
     *
     * @param rnPayerId the value for PRPCPAYMENT.RN_PAYER_ID
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public void setRnPayerId(String rnPayerId) {
        this.rnPayerId = rnPayerId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PRPCPAYMENT.RN_PAYER_TYPE
     *
     * @return the value of PRPCPAYMENT.RN_PAYER_TYPE
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public String getRnPayerType() {
        return rnPayerType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PRPCPAYMENT.RN_PAYER_TYPE
     *
     * @param rnPayerType the value for PRPCPAYMENT.RN_PAYER_TYPE
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public void setRnPayerType(String rnPayerType) {
        this.rnPayerType = rnPayerType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PRPCPAYMENT.RN_PAYER_RELATION
     *
     * @return the value of PRPCPAYMENT.RN_PAYER_RELATION
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public String getRnPayerRelation() {
        return rnPayerRelation;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PRPCPAYMENT.RN_PAYER_RELATION
     *
     * @param rnPayerRelation the value for PRPCPAYMENT.RN_PAYER_RELATION
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public void setRnPayerRelation(String rnPayerRelation) {
        this.rnPayerRelation = rnPayerRelation;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PRPCPAYMENT.RN_RELATION_DOC
     *
     * @return the value of PRPCPAYMENT.RN_RELATION_DOC
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public String getRnRelationDoc() {
        return rnRelationDoc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PRPCPAYMENT.RN_RELATION_DOC
     *
     * @param rnRelationDoc the value for PRPCPAYMENT.RN_RELATION_DOC
     *
     * @ibatorgenerated Thu Apr 27 15:05:34 CST 2023
     */
    public void setRnRelationDoc(String rnRelationDoc) {
        this.rnRelationDoc = rnRelationDoc;
    }
}