package com.tlg.prpins.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

@SuppressWarnings("serial")
public class Prpcplan extends IBatisBaseEntity<BigDecimal>{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPLAN.POLICYNO
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    private String policyno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPLAN.SERIALNO
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    private Long serialno;
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPLAN.ENDORSENO
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    private String endorseno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPLAN.PAYNO
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    private Integer payno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPLAN.PAYREASON
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    private String payreason;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPLAN.PLANDATE
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    private Date plandate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPLAN.CURRENCY
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    private String currency;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPLAN.PLANFEE
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    private BigDecimal planfee;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPLAN.DELINQUENTFEE
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    private BigDecimal delinquentfee;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPLAN.FLAG
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    private String flag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPLAN.PLANSTARTDATE
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    private Date planstartdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPLAN.CURRENCY2
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    private String currency2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPLAN.EXCHANGERATECNY
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    private BigDecimal exchangeratecny;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PRPCPLAN.PLANFEE2
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    private BigDecimal planfee2;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PRPCPLAN.ENDORSENO
     *
     * @return the value of PRPCPLAN.ENDORSENO
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    public String getEndorseno() {
        return endorseno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PRPCPLAN.ENDORSENO
     *
     * @param endorseno the value for PRPCPLAN.ENDORSENO
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    public void setEndorseno(String endorseno) {
        this.endorseno = endorseno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PRPCPLAN.PAYNO
     *
     * @return the value of PRPCPLAN.PAYNO
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    public Integer getPayno() {
        return payno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PRPCPLAN.PAYNO
     *
     * @param payno the value for PRPCPLAN.PAYNO
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    public void setPayno(Integer payno) {
        this.payno = payno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PRPCPLAN.PAYREASON
     *
     * @return the value of PRPCPLAN.PAYREASON
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    public String getPayreason() {
        return payreason;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PRPCPLAN.PAYREASON
     *
     * @param payreason the value for PRPCPLAN.PAYREASON
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    public void setPayreason(String payreason) {
        this.payreason = payreason;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PRPCPLAN.PLANDATE
     *
     * @return the value of PRPCPLAN.PLANDATE
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    public Date getPlandate() {
        return plandate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PRPCPLAN.PLANDATE
     *
     * @param plandate the value for PRPCPLAN.PLANDATE
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    public void setPlandate(Date plandate) {
        this.plandate = plandate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PRPCPLAN.CURRENCY
     *
     * @return the value of PRPCPLAN.CURRENCY
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PRPCPLAN.CURRENCY
     *
     * @param currency the value for PRPCPLAN.CURRENCY
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PRPCPLAN.PLANFEE
     *
     * @return the value of PRPCPLAN.PLANFEE
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    public BigDecimal getPlanfee() {
        return planfee;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PRPCPLAN.PLANFEE
     *
     * @param planfee the value for PRPCPLAN.PLANFEE
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    public void setPlanfee(BigDecimal planfee) {
        this.planfee = planfee;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PRPCPLAN.DELINQUENTFEE
     *
     * @return the value of PRPCPLAN.DELINQUENTFEE
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    public BigDecimal getDelinquentfee() {
        return delinquentfee;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PRPCPLAN.DELINQUENTFEE
     *
     * @param delinquentfee the value for PRPCPLAN.DELINQUENTFEE
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    public void setDelinquentfee(BigDecimal delinquentfee) {
        this.delinquentfee = delinquentfee;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PRPCPLAN.FLAG
     *
     * @return the value of PRPCPLAN.FLAG
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PRPCPLAN.FLAG
     *
     * @param flag the value for PRPCPLAN.FLAG
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    public void setFlag(String flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PRPCPLAN.PLANSTARTDATE
     *
     * @return the value of PRPCPLAN.PLANSTARTDATE
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    public Date getPlanstartdate() {
        return planstartdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PRPCPLAN.PLANSTARTDATE
     *
     * @param planstartdate the value for PRPCPLAN.PLANSTARTDATE
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    public void setPlanstartdate(Date planstartdate) {
        this.planstartdate = planstartdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PRPCPLAN.CURRENCY2
     *
     * @return the value of PRPCPLAN.CURRENCY2
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    public String getCurrency2() {
        return currency2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PRPCPLAN.CURRENCY2
     *
     * @param currency2 the value for PRPCPLAN.CURRENCY2
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    public void setCurrency2(String currency2) {
        this.currency2 = currency2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PRPCPLAN.EXCHANGERATECNY
     *
     * @return the value of PRPCPLAN.EXCHANGERATECNY
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    public BigDecimal getExchangeratecny() {
        return exchangeratecny;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PRPCPLAN.EXCHANGERATECNY
     *
     * @param exchangeratecny the value for PRPCPLAN.EXCHANGERATECNY
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    public void setExchangeratecny(BigDecimal exchangeratecny) {
        this.exchangeratecny = exchangeratecny;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PRPCPLAN.PLANFEE2
     *
     * @return the value of PRPCPLAN.PLANFEE2
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    public BigDecimal getPlanfee2() {
        return planfee2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PRPCPLAN.PLANFEE2
     *
     * @param planfee2 the value for PRPCPLAN.PLANFEE2
     *
     * @ibatorgenerated Wed Jun 07 11:10:16 CST 2023
     */
    public void setPlanfee2(BigDecimal planfee2) {
        this.planfee2 = planfee2;
    }

	public String getPolicyno() {
		return policyno;
	}

	public void setPolicyno(String policyno) {
		this.policyno = policyno;
	}

	public Long getSerialno() {
		return serialno;
	}

	public void setSerialno(Long serialno) {
		this.serialno = serialno;
	}
}