package com.tlg.prpins.entity;

import java.math.BigDecimal;

import com.tlg.iBatis.IBatisBaseEntity;

public class Prpdcode extends IBatisBaseEntity<BigDecimal> {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column PRPDCODE.CODECODE
	 * @ibatorgenerated  Mon Aug 21 14:12:12 CST 2023
	 */
	private String codecode;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column PRPDCODE.CODETYPE
	 * @ibatorgenerated  Mon Aug 21 14:12:12 CST 2023
	 */
	private String codetype;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column PRPDCODE.CODECNAME
	 * @ibatorgenerated  Mon Aug 21 14:12:12 CST 2023
	 */
	private String codecname;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column PRPDCODE.CODEENAME
	 * @ibatorgenerated  Mon Aug 21 14:12:12 CST 2023
	 */
	private String codeename;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column PRPDCODE.NEWCODECODE
	 * @ibatorgenerated  Mon Aug 21 14:12:12 CST 2023
	 */
	private String newcodecode;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column PRPDCODE.VALIDSTATUS
	 * @ibatorgenerated  Mon Aug 21 14:12:12 CST 2023
	 */
	private String validstatus;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column PRPDCODE.FLAG
	 * @ibatorgenerated  Mon Aug 21 14:12:12 CST 2023
	 */
	private String flag;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column PRPDCODE.UPPERCODE
	 * @ibatorgenerated  Mon Aug 21 14:12:12 CST 2023
	 */
	private String uppercode;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column PRPDCODE.CODECNAME
	 * @return  the value of PRPDCODE.CODECNAME
	 * @ibatorgenerated  Mon Aug 21 14:12:12 CST 2023
	 */
	public String getCodecname() {
		return codecname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column PRPDCODE.CODECNAME
	 * @param codecname  the value for PRPDCODE.CODECNAME
	 * @ibatorgenerated  Mon Aug 21 14:12:12 CST 2023
	 */
	public void setCodecname(String codecname) {
		this.codecname = codecname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column PRPDCODE.CODEENAME
	 * @return  the value of PRPDCODE.CODEENAME
	 * @ibatorgenerated  Mon Aug 21 14:12:12 CST 2023
	 */
	public String getCodeename() {
		return codeename;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column PRPDCODE.CODEENAME
	 * @param codeename  the value for PRPDCODE.CODEENAME
	 * @ibatorgenerated  Mon Aug 21 14:12:12 CST 2023
	 */
	public void setCodeename(String codeename) {
		this.codeename = codeename;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column PRPDCODE.NEWCODECODE
	 * @return  the value of PRPDCODE.NEWCODECODE
	 * @ibatorgenerated  Mon Aug 21 14:12:12 CST 2023
	 */
	public String getNewcodecode() {
		return newcodecode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column PRPDCODE.NEWCODECODE
	 * @param newcodecode  the value for PRPDCODE.NEWCODECODE
	 * @ibatorgenerated  Mon Aug 21 14:12:12 CST 2023
	 */
	public void setNewcodecode(String newcodecode) {
		this.newcodecode = newcodecode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column PRPDCODE.VALIDSTATUS
	 * @return  the value of PRPDCODE.VALIDSTATUS
	 * @ibatorgenerated  Mon Aug 21 14:12:12 CST 2023
	 */
	public String getValidstatus() {
		return validstatus;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column PRPDCODE.VALIDSTATUS
	 * @param validstatus  the value for PRPDCODE.VALIDSTATUS
	 * @ibatorgenerated  Mon Aug 21 14:12:12 CST 2023
	 */
	public void setValidstatus(String validstatus) {
		this.validstatus = validstatus;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column PRPDCODE.FLAG
	 * @return  the value of PRPDCODE.FLAG
	 * @ibatorgenerated  Mon Aug 21 14:12:12 CST 2023
	 */
	public String getFlag() {
		return flag;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column PRPDCODE.FLAG
	 * @param flag  the value for PRPDCODE.FLAG
	 * @ibatorgenerated  Mon Aug 21 14:12:12 CST 2023
	 */
	public void setFlag(String flag) {
		this.flag = flag;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column PRPDCODE.UPPERCODE
	 * @return  the value of PRPDCODE.UPPERCODE
	 * @ibatorgenerated  Mon Aug 21 14:12:12 CST 2023
	 */
	public String getUppercode() {
		return uppercode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column PRPDCODE.UPPERCODE
	 * @param uppercode  the value for PRPDCODE.UPPERCODE
	 * @ibatorgenerated  Mon Aug 21 14:12:12 CST 2023
	 */
	public void setUppercode(String uppercode) {
		this.uppercode = uppercode;
	}

	public String getCodecode() {
		return codecode;
	}

	public void setCodecode(String codecode) {
		this.codecode = codecode;
	}

	public String getCodetype() {
		return codetype;
	}

	public void setCodetype(String codetype) {
		this.codetype = codetype;
	}
}