package com.tlg.prpins.entity;

import java.math.BigDecimal;

import com.tlg.iBatis.IBatisBaseEntity;

public class ReinsInwardInsData extends IBatisBaseEntity<BigDecimal>{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column REINS_INWARD_INS_DATA.OID
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	private BigDecimal oid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column REINS_INWARD_INS_DATA.OID_REINS_INWARD_MAIN_DATA
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	private BigDecimal oidReinsInwardMainData;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column REINS_INWARD_INS_DATA.PONAME
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	private String poname;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column REINS_INWARD_INS_DATA.UWINS
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	private String uwins;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column REINS_INWARD_INS_DATA.POINS
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	private String poins;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column REINS_INWARD_INS_DATA.INSCODE
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	private String inscode;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column REINS_INWARD_INS_DATA.ACTINS
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	private String actins;
	
	private String typAmountRate;
	
	private String typPremRate;
	
	private String earthAmountRate;
	
	private String earthPremRate;
	
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column REINS_INWARD_INS_DATA.DEDUCTIBLE_NATURE
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	private String deductibleNature;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column REINS_INWARD_INS_DATA.DEDUCTIBLE_NONNATURE
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	private String deductibleNonnature;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column REINS_INWARD_INS_DATA.ORI_CURR_AMOUNT
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	private String oriCurrAmount;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column REINS_INWARD_INS_DATA.ORI_CURR_PREM
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	private String oriCurrPrem;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column REINS_INWARD_INS_DATA.NT_AMOUNT
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	private String ntAmount;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column REINS_INWARD_INS_DATA.NT_PREM
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	private String ntPrem;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column REINS_INWARD_INS_DATA.ORI_CURR_MAX_AMOUNT
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	private String oriCurrMaxAmount;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column REINS_INWARD_INS_DATA.NT_MAX_AMOUNT
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	private String ntMaxAmount;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column REINS_INWARD_INS_DATA.ORI_CURR_INWARD_AMOUNT
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	private String oriCurrInwardAmount;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column REINS_INWARD_INS_DATA.ORI_CURR_INWARD_PREM
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	private String oriCurrInwardPrem;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column REINS_INWARD_INS_DATA.NT_INWARD_AMOUNT
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	private String ntInwardAmount;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column REINS_INWARD_INS_DATA.NT_INWARD_PREM
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	private String ntInwardPrem;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column REINS_INWARD_INS_DATA.ORI_CURR_INWARD_MAX_AMOUNT
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	private String oriCurrInwardMaxAmount;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column REINS_INWARD_INS_DATA.NT_INWARD_MAX_AMOUNT
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	private String ntInwardMaxAmount;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column REINS_INWARD_INS_DATA.COMMISSION_RATE
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	private BigDecimal commissionRate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column REINS_INWARD_INS_DATA.ORI_CURR_COMMISSION
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	private String oriCurrCommission;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column REINS_INWARD_INS_DATA.NT_COMMISSION
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	private String ntCommission;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column REINS_INWARD_INS_DATA.CREATER
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	private String creater;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column REINS_INWARD_INS_DATA.CREATE_DATE
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	private String createDate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column REINS_INWARD_INS_DATA.MODIFIER
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	private String modifier;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column REINS_INWARD_INS_DATA.MODIFY_DATE
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	private String modifyDate;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column REINS_INWARD_INS_DATA.OID
	 * @return  the value of REINS_INWARD_INS_DATA.OID
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public BigDecimal getOid() {
		return oid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column REINS_INWARD_INS_DATA.OID
	 * @param oid  the value for REINS_INWARD_INS_DATA.OID
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public void setOid(BigDecimal oid) {
		this.oid = oid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column REINS_INWARD_INS_DATA.OID_REINS_INWARD_MAIN_DATA
	 * @return  the value of REINS_INWARD_INS_DATA.OID_REINS_INWARD_MAIN_DATA
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public BigDecimal getOidReinsInwardMainData() {
		return oidReinsInwardMainData;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column REINS_INWARD_INS_DATA.OID_REINS_INWARD_MAIN_DATA
	 * @param oidReinsInwardMainData  the value for REINS_INWARD_INS_DATA.OID_REINS_INWARD_MAIN_DATA
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public void setOidReinsInwardMainData(BigDecimal oidReinsInwardMainData) {
		this.oidReinsInwardMainData = oidReinsInwardMainData;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column REINS_INWARD_INS_DATA.PONAME
	 * @return  the value of REINS_INWARD_INS_DATA.PONAME
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public String getPoname() {
		return poname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column REINS_INWARD_INS_DATA.PONAME
	 * @param poname  the value for REINS_INWARD_INS_DATA.PONAME
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public void setPoname(String poname) {
		this.poname = poname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column REINS_INWARD_INS_DATA.UWINS
	 * @return  the value of REINS_INWARD_INS_DATA.UWINS
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public String getUwins() {
		return uwins;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column REINS_INWARD_INS_DATA.UWINS
	 * @param uwins  the value for REINS_INWARD_INS_DATA.UWINS
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public void setUwins(String uwins) {
		this.uwins = uwins;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column REINS_INWARD_INS_DATA.POINS
	 * @return  the value of REINS_INWARD_INS_DATA.POINS
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public String getPoins() {
		return poins;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column REINS_INWARD_INS_DATA.POINS
	 * @param poins  the value for REINS_INWARD_INS_DATA.POINS
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public void setPoins(String poins) {
		this.poins = poins;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column REINS_INWARD_INS_DATA.INSCODE
	 * @return  the value of REINS_INWARD_INS_DATA.INSCODE
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public String getInscode() {
		return inscode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column REINS_INWARD_INS_DATA.INSCODE
	 * @param inscode  the value for REINS_INWARD_INS_DATA.INSCODE
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public void setInscode(String inscode) {
		this.inscode = inscode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column REINS_INWARD_INS_DATA.ACTINS
	 * @return  the value of REINS_INWARD_INS_DATA.ACTINS
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public String getActins() {
		return actins;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column REINS_INWARD_INS_DATA.ACTINS
	 * @param actins  the value for REINS_INWARD_INS_DATA.ACTINS
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public void setActins(String actins) {
		this.actins = actins;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column REINS_INWARD_INS_DATA.DEDUCTIBLE_NATURE
	 * @return  the value of REINS_INWARD_INS_DATA.DEDUCTIBLE_NATURE
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public String getDeductibleNature() {
		return deductibleNature;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column REINS_INWARD_INS_DATA.DEDUCTIBLE_NATURE
	 * @param deductibleNature  the value for REINS_INWARD_INS_DATA.DEDUCTIBLE_NATURE
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public void setDeductibleNature(String deductibleNature) {
		this.deductibleNature = deductibleNature;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column REINS_INWARD_INS_DATA.DEDUCTIBLE_NONNATURE
	 * @return  the value of REINS_INWARD_INS_DATA.DEDUCTIBLE_NONNATURE
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public String getDeductibleNonnature() {
		return deductibleNonnature;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column REINS_INWARD_INS_DATA.DEDUCTIBLE_NONNATURE
	 * @param deductibleNonnature  the value for REINS_INWARD_INS_DATA.DEDUCTIBLE_NONNATURE
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public void setDeductibleNonnature(String deductibleNonnature) {
		this.deductibleNonnature = deductibleNonnature;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column REINS_INWARD_INS_DATA.ORI_CURR_AMOUNT
	 * @return  the value of REINS_INWARD_INS_DATA.ORI_CURR_AMOUNT
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public String getOriCurrAmount() {
		return oriCurrAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column REINS_INWARD_INS_DATA.ORI_CURR_AMOUNT
	 * @param oriCurrAmount  the value for REINS_INWARD_INS_DATA.ORI_CURR_AMOUNT
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public void setOriCurrAmount(String oriCurrAmount) {
		this.oriCurrAmount = oriCurrAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column REINS_INWARD_INS_DATA.ORI_CURR_PREM
	 * @return  the value of REINS_INWARD_INS_DATA.ORI_CURR_PREM
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public String getOriCurrPrem() {
		return oriCurrPrem;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column REINS_INWARD_INS_DATA.ORI_CURR_PREM
	 * @param oriCurrPrem  the value for REINS_INWARD_INS_DATA.ORI_CURR_PREM
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public void setOriCurrPrem(String oriCurrPrem) {
		this.oriCurrPrem = oriCurrPrem;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column REINS_INWARD_INS_DATA.NT_AMOUNT
	 * @return  the value of REINS_INWARD_INS_DATA.NT_AMOUNT
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public String getNtAmount() {
		return ntAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column REINS_INWARD_INS_DATA.NT_AMOUNT
	 * @param ntAmount  the value for REINS_INWARD_INS_DATA.NT_AMOUNT
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public void setNtAmount(String ntAmount) {
		this.ntAmount = ntAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column REINS_INWARD_INS_DATA.NT_PREM
	 * @return  the value of REINS_INWARD_INS_DATA.NT_PREM
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public String getNtPrem() {
		return ntPrem;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column REINS_INWARD_INS_DATA.NT_PREM
	 * @param ntPrem  the value for REINS_INWARD_INS_DATA.NT_PREM
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public void setNtPrem(String ntPrem) {
		this.ntPrem = ntPrem;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column REINS_INWARD_INS_DATA.ORI_CURR_MAX_AMOUNT
	 * @return  the value of REINS_INWARD_INS_DATA.ORI_CURR_MAX_AMOUNT
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public String getOriCurrMaxAmount() {
		return oriCurrMaxAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column REINS_INWARD_INS_DATA.ORI_CURR_MAX_AMOUNT
	 * @param oriCurrMaxAmount  the value for REINS_INWARD_INS_DATA.ORI_CURR_MAX_AMOUNT
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public void setOriCurrMaxAmount(String oriCurrMaxAmount) {
		this.oriCurrMaxAmount = oriCurrMaxAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column REINS_INWARD_INS_DATA.NT_MAX_AMOUNT
	 * @return  the value of REINS_INWARD_INS_DATA.NT_MAX_AMOUNT
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public String getNtMaxAmount() {
		return ntMaxAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column REINS_INWARD_INS_DATA.NT_MAX_AMOUNT
	 * @param ntMaxAmount  the value for REINS_INWARD_INS_DATA.NT_MAX_AMOUNT
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public void setNtMaxAmount(String ntMaxAmount) {
		this.ntMaxAmount = ntMaxAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column REINS_INWARD_INS_DATA.ORI_CURR_INWARD_AMOUNT
	 * @return  the value of REINS_INWARD_INS_DATA.ORI_CURR_INWARD_AMOUNT
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public String getOriCurrInwardAmount() {
		return oriCurrInwardAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column REINS_INWARD_INS_DATA.ORI_CURR_INWARD_AMOUNT
	 * @param oriCurrInwardAmount  the value for REINS_INWARD_INS_DATA.ORI_CURR_INWARD_AMOUNT
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public void setOriCurrInwardAmount(String oriCurrInwardAmount) {
		this.oriCurrInwardAmount = oriCurrInwardAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column REINS_INWARD_INS_DATA.ORI_CURR_INWARD_PREM
	 * @return  the value of REINS_INWARD_INS_DATA.ORI_CURR_INWARD_PREM
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public String getOriCurrInwardPrem() {
		return oriCurrInwardPrem;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column REINS_INWARD_INS_DATA.ORI_CURR_INWARD_PREM
	 * @param oriCurrInwardPrem  the value for REINS_INWARD_INS_DATA.ORI_CURR_INWARD_PREM
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public void setOriCurrInwardPrem(String oriCurrInwardPrem) {
		this.oriCurrInwardPrem = oriCurrInwardPrem;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column REINS_INWARD_INS_DATA.NT_INWARD_AMOUNT
	 * @return  the value of REINS_INWARD_INS_DATA.NT_INWARD_AMOUNT
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public String getNtInwardAmount() {
		return ntInwardAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column REINS_INWARD_INS_DATA.NT_INWARD_AMOUNT
	 * @param ntInwardAmount  the value for REINS_INWARD_INS_DATA.NT_INWARD_AMOUNT
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public void setNtInwardAmount(String ntInwardAmount) {
		this.ntInwardAmount = ntInwardAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column REINS_INWARD_INS_DATA.NT_INWARD_PREM
	 * @return  the value of REINS_INWARD_INS_DATA.NT_INWARD_PREM
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public String getNtInwardPrem() {
		return ntInwardPrem;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column REINS_INWARD_INS_DATA.NT_INWARD_PREM
	 * @param ntInwardPrem  the value for REINS_INWARD_INS_DATA.NT_INWARD_PREM
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public void setNtInwardPrem(String ntInwardPrem) {
		this.ntInwardPrem = ntInwardPrem;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column REINS_INWARD_INS_DATA.ORI_CURR_INWARD_MAX_AMOUNT
	 * @return  the value of REINS_INWARD_INS_DATA.ORI_CURR_INWARD_MAX_AMOUNT
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public String getOriCurrInwardMaxAmount() {
		return oriCurrInwardMaxAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column REINS_INWARD_INS_DATA.ORI_CURR_INWARD_MAX_AMOUNT
	 * @param oriCurrInwardMaxAmount  the value for REINS_INWARD_INS_DATA.ORI_CURR_INWARD_MAX_AMOUNT
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public void setOriCurrInwardMaxAmount(String oriCurrInwardMaxAmount) {
		this.oriCurrInwardMaxAmount = oriCurrInwardMaxAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column REINS_INWARD_INS_DATA.NT_INWARD_MAX_AMOUNT
	 * @return  the value of REINS_INWARD_INS_DATA.NT_INWARD_MAX_AMOUNT
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public String getNtInwardMaxAmount() {
		return ntInwardMaxAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column REINS_INWARD_INS_DATA.NT_INWARD_MAX_AMOUNT
	 * @param ntInwardMaxAmount  the value for REINS_INWARD_INS_DATA.NT_INWARD_MAX_AMOUNT
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public void setNtInwardMaxAmount(String ntInwardMaxAmount) {
		this.ntInwardMaxAmount = ntInwardMaxAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column REINS_INWARD_INS_DATA.COMMISSION_RATE
	 * @return  the value of REINS_INWARD_INS_DATA.COMMISSION_RATE
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public BigDecimal getCommissionRate() {
		return commissionRate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column REINS_INWARD_INS_DATA.COMMISSION_RATE
	 * @param commissionRate  the value for REINS_INWARD_INS_DATA.COMMISSION_RATE
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public void setCommissionRate(BigDecimal commissionRate) {
		this.commissionRate = commissionRate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column REINS_INWARD_INS_DATA.ORI_CURR_COMMISSION
	 * @return  the value of REINS_INWARD_INS_DATA.ORI_CURR_COMMISSION
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public String getOriCurrCommission() {
		return oriCurrCommission;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column REINS_INWARD_INS_DATA.ORI_CURR_COMMISSION
	 * @param oriCurrCommission  the value for REINS_INWARD_INS_DATA.ORI_CURR_COMMISSION
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public void setOriCurrCommission(String oriCurrCommission) {
		this.oriCurrCommission = oriCurrCommission;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column REINS_INWARD_INS_DATA.NT_COMMISSION
	 * @return  the value of REINS_INWARD_INS_DATA.NT_COMMISSION
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public String getNtCommission() {
		return ntCommission;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column REINS_INWARD_INS_DATA.NT_COMMISSION
	 * @param ntCommission  the value for REINS_INWARD_INS_DATA.NT_COMMISSION
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public void setNtCommission(String ntCommission) {
		this.ntCommission = ntCommission;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column REINS_INWARD_INS_DATA.CREATER
	 * @return  the value of REINS_INWARD_INS_DATA.CREATER
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public String getCreater() {
		return creater;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column REINS_INWARD_INS_DATA.CREATER
	 * @param creater  the value for REINS_INWARD_INS_DATA.CREATER
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public void setCreater(String creater) {
		this.creater = creater;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column REINS_INWARD_INS_DATA.CREATE_DATE
	 * @return  the value of REINS_INWARD_INS_DATA.CREATE_DATE
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public String getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column REINS_INWARD_INS_DATA.CREATE_DATE
	 * @param createDate  the value for REINS_INWARD_INS_DATA.CREATE_DATE
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column REINS_INWARD_INS_DATA.MODIFIER
	 * @return  the value of REINS_INWARD_INS_DATA.MODIFIER
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public String getModifier() {
		return modifier;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column REINS_INWARD_INS_DATA.MODIFIER
	 * @param modifier  the value for REINS_INWARD_INS_DATA.MODIFIER
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column REINS_INWARD_INS_DATA.MODIFY_DATE
	 * @return  the value of REINS_INWARD_INS_DATA.MODIFY_DATE
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public String getModifyDate() {
		return modifyDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column REINS_INWARD_INS_DATA.MODIFY_DATE
	 * @param modifyDate  the value for REINS_INWARD_INS_DATA.MODIFY_DATE
	 * @ibatorgenerated  Tue Jul 05 10:50:15 CST 2022
	 */
	public void setModifyDate(String modifyDate) {
		this.modifyDate = modifyDate;
	}

	public String getTypAmountRate() {
		return typAmountRate;
	}

	public void setTypAmountRate(String typAmountRate) {
		this.typAmountRate = typAmountRate;
	}

	public String getTypPremRate() {
		return typPremRate;
	}

	public void setTypPremRate(String typPremRate) {
		this.typPremRate = typPremRate;
	}

	public String getEarthAmountRate() {
		return earthAmountRate;
	}

	public void setEarthAmountRate(String earthAmountRate) {
		this.earthAmountRate = earthAmountRate;
	}

	public String getEarthPremRate() {
		return earthPremRate;
	}

	public void setEarthPremRate(String earthPremRate) {
		this.earthPremRate = earthPremRate;
	}
}