package com.tlg.prpins.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

/*mantis：CAR0417，處理人員：BJ085，需求單編號：CAR0417 機車強制車險重新投保發對接功能 */
public class Renewalnotice extends IBatisBaseEntity<BigDecimal>{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RENEWALNOTICE.POLICYNO
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    private String policyno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RENEWALNOTICE.USENATURECODE
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    private String usenaturecode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RENEWALNOTICE.ENDDATE
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    private Date enddate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RENEWALNOTICE.NOTICETIMES
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    private String noticetimes;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RENEWALNOTICE.TCOL
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    private String tcol;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RENEWALNOTICE.TCOL2
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    private String tcol2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RENEWALNOTICE.OPERATEDATE
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    private Date operatedate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RENEWALNOTICE.FILENAME
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    private String filename;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RENEWALNOTICE.BUSINESSNATURE
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    private String businessnature;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RENEWALNOTICE.HANDLERCODE
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    private String handlercode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RENEWALNOTICE.PRINTNO
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    private String printno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RENEWALNOTICE.BATCHNO
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    private String batchno;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RENEWALNOTICE.POLICYNO
     *
     * @return the value of RENEWALNOTICE.POLICYNO
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    public String getPolicyno() {
        return policyno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RENEWALNOTICE.POLICYNO
     *
     * @param policyno the value for RENEWALNOTICE.POLICYNO
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    public void setPolicyno(String policyno) {
        this.policyno = policyno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RENEWALNOTICE.USENATURECODE
     *
     * @return the value of RENEWALNOTICE.USENATURECODE
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    public String getUsenaturecode() {
        return usenaturecode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RENEWALNOTICE.USENATURECODE
     *
     * @param usenaturecode the value for RENEWALNOTICE.USENATURECODE
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    public void setUsenaturecode(String usenaturecode) {
        this.usenaturecode = usenaturecode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RENEWALNOTICE.ENDDATE
     *
     * @return the value of RENEWALNOTICE.ENDDATE
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RENEWALNOTICE.ENDDATE
     *
     * @param enddate the value for RENEWALNOTICE.ENDDATE
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RENEWALNOTICE.NOTICETIMES
     *
     * @return the value of RENEWALNOTICE.NOTICETIMES
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    public String getNoticetimes() {
        return noticetimes;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RENEWALNOTICE.NOTICETIMES
     *
     * @param noticetimes the value for RENEWALNOTICE.NOTICETIMES
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    public void setNoticetimes(String noticetimes) {
        this.noticetimes = noticetimes;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RENEWALNOTICE.TCOL
     *
     * @return the value of RENEWALNOTICE.TCOL
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    public String getTcol() {
        return tcol;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RENEWALNOTICE.TCOL
     *
     * @param tcol the value for RENEWALNOTICE.TCOL
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    public void setTcol(String tcol) {
        this.tcol = tcol;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RENEWALNOTICE.TCOL2
     *
     * @return the value of RENEWALNOTICE.TCOL2
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    public String getTcol2() {
        return tcol2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RENEWALNOTICE.TCOL2
     *
     * @param tcol2 the value for RENEWALNOTICE.TCOL2
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    public void setTcol2(String tcol2) {
        this.tcol2 = tcol2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RENEWALNOTICE.OPERATEDATE
     *
     * @return the value of RENEWALNOTICE.OPERATEDATE
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    public Date getOperatedate() {
        return operatedate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RENEWALNOTICE.OPERATEDATE
     *
     * @param operatedate the value for RENEWALNOTICE.OPERATEDATE
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    public void setOperatedate(Date operatedate) {
        this.operatedate = operatedate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RENEWALNOTICE.FILENAME
     *
     * @return the value of RENEWALNOTICE.FILENAME
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RENEWALNOTICE.FILENAME
     *
     * @param filename the value for RENEWALNOTICE.FILENAME
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RENEWALNOTICE.BUSINESSNATURE
     *
     * @return the value of RENEWALNOTICE.BUSINESSNATURE
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    public String getBusinessnature() {
        return businessnature;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RENEWALNOTICE.BUSINESSNATURE
     *
     * @param businessnature the value for RENEWALNOTICE.BUSINESSNATURE
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    public void setBusinessnature(String businessnature) {
        this.businessnature = businessnature;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RENEWALNOTICE.HANDLERCODE
     *
     * @return the value of RENEWALNOTICE.HANDLERCODE
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    public String getHandlercode() {
        return handlercode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RENEWALNOTICE.HANDLERCODE
     *
     * @param handlercode the value for RENEWALNOTICE.HANDLERCODE
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    public void setHandlercode(String handlercode) {
        this.handlercode = handlercode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RENEWALNOTICE.PRINTNO
     *
     * @return the value of RENEWALNOTICE.PRINTNO
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    public String getPrintno() {
        return printno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RENEWALNOTICE.PRINTNO
     *
     * @param printno the value for RENEWALNOTICE.PRINTNO
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    public void setPrintno(String printno) {
        this.printno = printno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RENEWALNOTICE.BATCHNO
     *
     * @return the value of RENEWALNOTICE.BATCHNO
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    public String getBatchno() {
        return batchno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RENEWALNOTICE.BATCHNO
     *
     * @param batchno the value for RENEWALNOTICE.BATCHNO
     *
     * @ibatorgenerated Thu Feb 24 16:15:46 CST 2022
     */
    public void setBatchno(String batchno) {
        this.batchno = batchno;
    }
}