package com.tlg.prpins.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

/** mantis：CAR0504，處理人員：CC009，需求單編號：CAR0504 微型電動二輪車【已領牌&未領牌】資料交換作業 */
@SuppressWarnings("serial")
public class TiiTvmetp extends IBatisBaseEntity<BigDecimal>{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TII_TVMETP.OID
     *
     * @mbg.generated Mon Dec 26 09:51:36 CST 2022
     */
    private BigDecimal oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TII_TVMETP.CARNO
     *
     * @mbg.generated Mon Dec 26 09:51:36 CST 2022
     */
    private String carno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TII_TVMETP.BODYNO
     *
     * @mbg.generated Mon Dec 26 09:51:36 CST 2022
     */
    private String bodyno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TII_TVMETP.CARNODATE
     *
     * @mbg.generated Mon Dec 26 09:51:36 CST 2022
     */
    private String carnodate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TII_TVMETP.INSUREDCARDNO
     *
     * @mbg.generated Mon Dec 26 09:51:36 CST 2022
     */
    private String insuredcardno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TII_TVMETP.CITIZENID
     *
     * @mbg.generated Mon Dec 26 09:51:36 CST 2022
     */
    private String citizenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TII_TVMETP.ISEXISTFLAG
     *
     * @mbg.generated Mon Dec 26 09:51:36 CST 2022
     */
    private String isexistflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TII_TVMETP.INSBEGINDATE
     *
     * @mbg.generated Mon Dec 26 09:51:36 CST 2022
     */
    private String insbegindate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TII_TVMETP.OPERATEDATE
     *
     * @mbg.generated Mon Dec 26 09:51:36 CST 2022
     */
    private Date operatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TII_TVMETP.FILENAME
     *
     * @mbg.generated Mon Dec 26 09:51:36 CST 2022
     */
    private String filename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TII_TVMETP.OID
     *
     * @return the value of TII_TVMETP.OID
     *
     * @mbg.generated Mon Dec 26 09:51:36 CST 2022
     */
    public BigDecimal getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TII_TVMETP.OID
     *
     * @param oid the value for TII_TVMETP.OID
     *
     * @mbg.generated Mon Dec 26 09:51:36 CST 2022
     */
    public void setOid(BigDecimal oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TII_TVMETP.CARNO
     *
     * @return the value of TII_TVMETP.CARNO
     *
     * @mbg.generated Mon Dec 26 09:51:36 CST 2022
     */
    public String getCarno() {
        return carno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TII_TVMETP.CARNO
     *
     * @param carno the value for TII_TVMETP.CARNO
     *
     * @mbg.generated Mon Dec 26 09:51:36 CST 2022
     */
    public void setCarno(String carno) {
        this.carno = carno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TII_TVMETP.BODYNO
     *
     * @return the value of TII_TVMETP.BODYNO
     *
     * @mbg.generated Mon Dec 26 09:51:36 CST 2022
     */
    public String getBodyno() {
        return bodyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TII_TVMETP.BODYNO
     *
     * @param bodyno the value for TII_TVMETP.BODYNO
     *
     * @mbg.generated Mon Dec 26 09:51:36 CST 2022
     */
    public void setBodyno(String bodyno) {
        this.bodyno = bodyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TII_TVMETP.CARNODATE
     *
     * @return the value of TII_TVMETP.CARNODATE
     *
     * @mbg.generated Mon Dec 26 09:51:36 CST 2022
     */
    public String getCarnodate() {
        return carnodate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TII_TVMETP.CARNODATE
     *
     * @param carnodate the value for TII_TVMETP.CARNODATE
     *
     * @mbg.generated Mon Dec 26 09:51:36 CST 2022
     */
    public void setCarnodate(String carnodate) {
        this.carnodate = carnodate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TII_TVMETP.INSUREDCARDNO
     *
     * @return the value of TII_TVMETP.INSUREDCARDNO
     *
     * @mbg.generated Mon Dec 26 09:51:36 CST 2022
     */
    public String getInsuredcardno() {
        return insuredcardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TII_TVMETP.INSUREDCARDNO
     *
     * @param insuredcardno the value for TII_TVMETP.INSUREDCARDNO
     *
     * @mbg.generated Mon Dec 26 09:51:36 CST 2022
     */
    public void setInsuredcardno(String insuredcardno) {
        this.insuredcardno = insuredcardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TII_TVMETP.CITIZENID
     *
     * @return the value of TII_TVMETP.CITIZENID
     *
     * @mbg.generated Mon Dec 26 09:51:36 CST 2022
     */
    public String getCitizenid() {
        return citizenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TII_TVMETP.CITIZENID
     *
     * @param citizenid the value for TII_TVMETP.CITIZENID
     *
     * @mbg.generated Mon Dec 26 09:51:36 CST 2022
     */
    public void setCitizenid(String citizenid) {
        this.citizenid = citizenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TII_TVMETP.ISEXISTFLAG
     *
     * @return the value of TII_TVMETP.ISEXISTFLAG
     *
     * @mbg.generated Mon Dec 26 09:51:36 CST 2022
     */
    public String getIsexistflag() {
        return isexistflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TII_TVMETP.ISEXISTFLAG
     *
     * @param isexistflag the value for TII_TVMETP.ISEXISTFLAG
     *
     * @mbg.generated Mon Dec 26 09:51:36 CST 2022
     */
    public void setIsexistflag(String isexistflag) {
        this.isexistflag = isexistflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TII_TVMETP.INSBEGINDATE
     *
     * @return the value of TII_TVMETP.INSBEGINDATE
     *
     * @mbg.generated Mon Dec 26 09:51:36 CST 2022
     */
    public String getInsbegindate() {
        return insbegindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TII_TVMETP.INSBEGINDATE
     *
     * @param insbegindate the value for TII_TVMETP.INSBEGINDATE
     *
     * @mbg.generated Mon Dec 26 09:51:36 CST 2022
     */
    public void setInsbegindate(String insbegindate) {
        this.insbegindate = insbegindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TII_TVMETP.OPERATEDATE
     *
     * @return the value of TII_TVMETP.OPERATEDATE
     *
     * @mbg.generated Mon Dec 26 09:51:36 CST 2022
     */
    public Date getOperatedate() {
        return operatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TII_TVMETP.OPERATEDATE
     *
     * @param operatedate the value for TII_TVMETP.OPERATEDATE
     *
     * @mbg.generated Mon Dec 26 09:51:36 CST 2022
     */
    public void setOperatedate(Date operatedate) {
        this.operatedate = operatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TII_TVMETP.FILENAME
     *
     * @return the value of TII_TVMETP.FILENAME
     *
     * @mbg.generated Mon Dec 26 09:51:36 CST 2022
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TII_TVMETP.FILENAME
     *
     * @param filename the value for TII_TVMETP.FILENAME
     *
     * @mbg.generated Mon Dec 26 09:51:36 CST 2022
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }
}