package com.tlg.prpins.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

/** mantis：MOB0018，處理人員：BJ085，需求單編號：MOB0018 理賠資料提交及列印作業 */
@SuppressWarnings("serial")
public class Tmpfetclaimpay extends IBatisBaseEntity<BigDecimal>{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMPAY.OID
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    private BigDecimal oid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMPAY.WDE00
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    private Integer wde00;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMPAY.WDE01
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    private String wde01;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMPAY.WDE02
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    private String wde02;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMPAY.WDE03
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    private String wde03;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMPAY.WDE04
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    private Integer wde04;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMPAY.WDE05
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    private String wde05;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMPAY.WDE06
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    private String wde06;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMPAY.WDE07
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    private String wde07;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMPAY.WDE08
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    private String wde08;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMPAY.WDE09
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    private String wde09;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMPAY.WDE10
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    private String wde10;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMPAY.WDE11
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    private String wde11;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMPAY.WDE12
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    private String wde12;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMPAY.WDE13
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    private String wde13;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMPAY.WDE14
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    private String wde14;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMPAY.WDE15
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    private String wde15;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMPAY.WDE16
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    private String wde16;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMPAY.WDE17
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    private String wde17;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMPAY.WDE18
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    private String wde18;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMPAY.WDE19
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    private String wde19;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMPAY.WDE21
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    private Date wde21;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMPAY.WDE22
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    private Long wde22;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMPAY.DRAWOUTDATE
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    private Date drawoutdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMPAY.DATASOURCE
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    private String datasource;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMPAY.FLOWID
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    private String flowid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMPAY.REGISTNO
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    private String registno;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMPAY.OID
     *
     * @return the value of TMPFETCLAIMPAY.OID
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public BigDecimal getOid() {
        return oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMPAY.OID
     *
     * @param oid the value for TMPFETCLAIMPAY.OID
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public void setOid(BigDecimal oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMPAY.WDE00
     *
     * @return the value of TMPFETCLAIMPAY.WDE00
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public Integer getWde00() {
        return wde00;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMPAY.WDE00
     *
     * @param wde00 the value for TMPFETCLAIMPAY.WDE00
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public void setWde00(Integer wde00) {
        this.wde00 = wde00;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMPAY.WDE01
     *
     * @return the value of TMPFETCLAIMPAY.WDE01
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public String getWde01() {
        return wde01;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMPAY.WDE01
     *
     * @param wde01 the value for TMPFETCLAIMPAY.WDE01
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public void setWde01(String wde01) {
        this.wde01 = wde01;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMPAY.WDE02
     *
     * @return the value of TMPFETCLAIMPAY.WDE02
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public String getWde02() {
        return wde02;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMPAY.WDE02
     *
     * @param wde02 the value for TMPFETCLAIMPAY.WDE02
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public void setWde02(String wde02) {
        this.wde02 = wde02;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMPAY.WDE03
     *
     * @return the value of TMPFETCLAIMPAY.WDE03
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public String getWde03() {
        return wde03;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMPAY.WDE03
     *
     * @param wde03 the value for TMPFETCLAIMPAY.WDE03
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public void setWde03(String wde03) {
        this.wde03 = wde03;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMPAY.WDE04
     *
     * @return the value of TMPFETCLAIMPAY.WDE04
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public Integer getWde04() {
        return wde04;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMPAY.WDE04
     *
     * @param wde04 the value for TMPFETCLAIMPAY.WDE04
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public void setWde04(Integer wde04) {
        this.wde04 = wde04;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMPAY.WDE05
     *
     * @return the value of TMPFETCLAIMPAY.WDE05
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public String getWde05() {
        return wde05;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMPAY.WDE05
     *
     * @param wde05 the value for TMPFETCLAIMPAY.WDE05
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public void setWde05(String wde05) {
        this.wde05 = wde05;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMPAY.WDE06
     *
     * @return the value of TMPFETCLAIMPAY.WDE06
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public String getWde06() {
        return wde06;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMPAY.WDE06
     *
     * @param wde06 the value for TMPFETCLAIMPAY.WDE06
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public void setWde06(String wde06) {
        this.wde06 = wde06;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMPAY.WDE07
     *
     * @return the value of TMPFETCLAIMPAY.WDE07
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public String getWde07() {
        return wde07;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMPAY.WDE07
     *
     * @param wde07 the value for TMPFETCLAIMPAY.WDE07
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public void setWde07(String wde07) {
        this.wde07 = wde07;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMPAY.WDE08
     *
     * @return the value of TMPFETCLAIMPAY.WDE08
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public String getWde08() {
        return wde08;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMPAY.WDE08
     *
     * @param wde08 the value for TMPFETCLAIMPAY.WDE08
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public void setWde08(String wde08) {
        this.wde08 = wde08;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMPAY.WDE09
     *
     * @return the value of TMPFETCLAIMPAY.WDE09
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public String getWde09() {
        return wde09;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMPAY.WDE09
     *
     * @param wde09 the value for TMPFETCLAIMPAY.WDE09
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public void setWde09(String wde09) {
        this.wde09 = wde09;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMPAY.WDE10
     *
     * @return the value of TMPFETCLAIMPAY.WDE10
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public String getWde10() {
        return wde10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMPAY.WDE10
     *
     * @param wde10 the value for TMPFETCLAIMPAY.WDE10
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public void setWde10(String wde10) {
        this.wde10 = wde10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMPAY.WDE11
     *
     * @return the value of TMPFETCLAIMPAY.WDE11
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public String getWde11() {
        return wde11;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMPAY.WDE11
     *
     * @param wde11 the value for TMPFETCLAIMPAY.WDE11
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public void setWde11(String wde11) {
        this.wde11 = wde11;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMPAY.WDE12
     *
     * @return the value of TMPFETCLAIMPAY.WDE12
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public String getWde12() {
        return wde12;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMPAY.WDE12
     *
     * @param wde12 the value for TMPFETCLAIMPAY.WDE12
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public void setWde12(String wde12) {
        this.wde12 = wde12;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMPAY.WDE13
     *
     * @return the value of TMPFETCLAIMPAY.WDE13
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public String getWde13() {
        return wde13;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMPAY.WDE13
     *
     * @param wde13 the value for TMPFETCLAIMPAY.WDE13
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public void setWde13(String wde13) {
        this.wde13 = wde13;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMPAY.WDE14
     *
     * @return the value of TMPFETCLAIMPAY.WDE14
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public String getWde14() {
        return wde14;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMPAY.WDE14
     *
     * @param wde14 the value for TMPFETCLAIMPAY.WDE14
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public void setWde14(String wde14) {
        this.wde14 = wde14;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMPAY.WDE15
     *
     * @return the value of TMPFETCLAIMPAY.WDE15
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public String getWde15() {
        return wde15;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMPAY.WDE15
     *
     * @param wde15 the value for TMPFETCLAIMPAY.WDE15
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public void setWde15(String wde15) {
        this.wde15 = wde15;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMPAY.WDE16
     *
     * @return the value of TMPFETCLAIMPAY.WDE16
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public String getWde16() {
        return wde16;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMPAY.WDE16
     *
     * @param wde16 the value for TMPFETCLAIMPAY.WDE16
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public void setWde16(String wde16) {
        this.wde16 = wde16;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMPAY.WDE17
     *
     * @return the value of TMPFETCLAIMPAY.WDE17
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public String getWde17() {
        return wde17;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMPAY.WDE17
     *
     * @param wde17 the value for TMPFETCLAIMPAY.WDE17
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public void setWde17(String wde17) {
        this.wde17 = wde17;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMPAY.WDE18
     *
     * @return the value of TMPFETCLAIMPAY.WDE18
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public String getWde18() {
        return wde18;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMPAY.WDE18
     *
     * @param wde18 the value for TMPFETCLAIMPAY.WDE18
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public void setWde18(String wde18) {
        this.wde18 = wde18;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMPAY.WDE19
     *
     * @return the value of TMPFETCLAIMPAY.WDE19
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public String getWde19() {
        return wde19;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMPAY.WDE19
     *
     * @param wde19 the value for TMPFETCLAIMPAY.WDE19
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public void setWde19(String wde19) {
        this.wde19 = wde19;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMPAY.WDE21
     *
     * @return the value of TMPFETCLAIMPAY.WDE21
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public Date getWde21() {
        return wde21;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMPAY.WDE21
     *
     * @param wde21 the value for TMPFETCLAIMPAY.WDE21
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public void setWde21(Date wde21) {
        this.wde21 = wde21;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMPAY.WDE22
     *
     * @return the value of TMPFETCLAIMPAY.WDE22
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public Long getWde22() {
        return wde22;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMPAY.WDE22
     *
     * @param wde22 the value for TMPFETCLAIMPAY.WDE22
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public void setWde22(Long wde22) {
        this.wde22 = wde22;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMPAY.DRAWOUTDATE
     *
     * @return the value of TMPFETCLAIMPAY.DRAWOUTDATE
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public Date getDrawoutdate() {
        return drawoutdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMPAY.DRAWOUTDATE
     *
     * @param drawoutdate the value for TMPFETCLAIMPAY.DRAWOUTDATE
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public void setDrawoutdate(Date drawoutdate) {
        this.drawoutdate = drawoutdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMPAY.DATASOURCE
     *
     * @return the value of TMPFETCLAIMPAY.DATASOURCE
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public String getDatasource() {
        return datasource;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMPAY.DATASOURCE
     *
     * @param datasource the value for TMPFETCLAIMPAY.DATASOURCE
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public void setDatasource(String datasource) {
        this.datasource = datasource;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMPAY.FLOWID
     *
     * @return the value of TMPFETCLAIMPAY.FLOWID
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public String getFlowid() {
        return flowid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMPAY.FLOWID
     *
     * @param flowid the value for TMPFETCLAIMPAY.FLOWID
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public void setFlowid(String flowid) {
        this.flowid = flowid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMPAY.REGISTNO
     *
     * @return the value of TMPFETCLAIMPAY.REGISTNO
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public String getRegistno() {
        return registno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMPAY.REGISTNO
     *
     * @param registno the value for TMPFETCLAIMPAY.REGISTNO
     *
     * @ibatorgenerated Fri Jun 02 17:54:48 CST 2023
     */
    public void setRegistno(String registno) {
        this.registno = registno;
    }
}