package com.tlg.prpins.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

/** mantis：MOB0018，處理人員：BJ085，需求單編號：MOB0018 理賠資料提交及列印作業 */
@SuppressWarnings("serial")
public class Tmpfetclaimkind extends IBatisBaseEntity<BigDecimal>{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMKIND.OID
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    private BigDecimal oid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMKIND.WDC00
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    private Integer wdc00;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMKIND.WDC01
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    private String wdc01;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMKIND.WDC02
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    private String wdc02;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMKIND.WDC03
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    private String wdc03;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMKIND.WDC04
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    private String wdc04;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMKIND.WDC05
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    private Integer wdc05;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMKIND.WDC06
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    private Long wdc06;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMKIND.WDC07
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    private Long wdc07;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMKIND.WDC08
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    private Long wdc08;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMKIND.WDC09
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    private Long wdc09;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMKIND.WDC10
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    private Integer wdc10;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMKIND.WDC11
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    private String wdc11;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMKIND.WDC12
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    private String wdc12;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMKIND.WDC13
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    private String wdc13;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMKIND.WDC14
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    private Date wdc14;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMKIND.DRAWOUTDATE
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    private Date drawoutdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMKIND.DATASOURCE
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    private String datasource;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMKIND.FLOWID
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    private String flowid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TMPFETCLAIMKIND.REGISTNO
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    private String registno;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMKIND.OID
     *
     * @return the value of TMPFETCLAIMKIND.OID
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public BigDecimal getOid() {
        return oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMKIND.OID
     *
     * @param oid the value for TMPFETCLAIMKIND.OID
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public void setOid(BigDecimal oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMKIND.WDC00
     *
     * @return the value of TMPFETCLAIMKIND.WDC00
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public Integer getWdc00() {
        return wdc00;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMKIND.WDC00
     *
     * @param wdc00 the value for TMPFETCLAIMKIND.WDC00
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public void setWdc00(Integer wdc00) {
        this.wdc00 = wdc00;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMKIND.WDC01
     *
     * @return the value of TMPFETCLAIMKIND.WDC01
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public String getWdc01() {
        return wdc01;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMKIND.WDC01
     *
     * @param wdc01 the value for TMPFETCLAIMKIND.WDC01
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public void setWdc01(String wdc01) {
        this.wdc01 = wdc01;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMKIND.WDC02
     *
     * @return the value of TMPFETCLAIMKIND.WDC02
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public String getWdc02() {
        return wdc02;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMKIND.WDC02
     *
     * @param wdc02 the value for TMPFETCLAIMKIND.WDC02
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public void setWdc02(String wdc02) {
        this.wdc02 = wdc02;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMKIND.WDC03
     *
     * @return the value of TMPFETCLAIMKIND.WDC03
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public String getWdc03() {
        return wdc03;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMKIND.WDC03
     *
     * @param wdc03 the value for TMPFETCLAIMKIND.WDC03
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public void setWdc03(String wdc03) {
        this.wdc03 = wdc03;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMKIND.WDC04
     *
     * @return the value of TMPFETCLAIMKIND.WDC04
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public String getWdc04() {
        return wdc04;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMKIND.WDC04
     *
     * @param wdc04 the value for TMPFETCLAIMKIND.WDC04
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public void setWdc04(String wdc04) {
        this.wdc04 = wdc04;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMKIND.WDC05
     *
     * @return the value of TMPFETCLAIMKIND.WDC05
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public Integer getWdc05() {
        return wdc05;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMKIND.WDC05
     *
     * @param wdc05 the value for TMPFETCLAIMKIND.WDC05
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public void setWdc05(Integer wdc05) {
        this.wdc05 = wdc05;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMKIND.WDC06
     *
     * @return the value of TMPFETCLAIMKIND.WDC06
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public Long getWdc06() {
        return wdc06;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMKIND.WDC06
     *
     * @param wdc06 the value for TMPFETCLAIMKIND.WDC06
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public void setWdc06(Long wdc06) {
        this.wdc06 = wdc06;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMKIND.WDC07
     *
     * @return the value of TMPFETCLAIMKIND.WDC07
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public Long getWdc07() {
        return wdc07;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMKIND.WDC07
     *
     * @param wdc07 the value for TMPFETCLAIMKIND.WDC07
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public void setWdc07(Long wdc07) {
        this.wdc07 = wdc07;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMKIND.WDC08
     *
     * @return the value of TMPFETCLAIMKIND.WDC08
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public Long getWdc08() {
        return wdc08;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMKIND.WDC08
     *
     * @param wdc08 the value for TMPFETCLAIMKIND.WDC08
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public void setWdc08(Long wdc08) {
        this.wdc08 = wdc08;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMKIND.WDC09
     *
     * @return the value of TMPFETCLAIMKIND.WDC09
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public Long getWdc09() {
        return wdc09;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMKIND.WDC09
     *
     * @param wdc09 the value for TMPFETCLAIMKIND.WDC09
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public void setWdc09(Long wdc09) {
        this.wdc09 = wdc09;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMKIND.WDC10
     *
     * @return the value of TMPFETCLAIMKIND.WDC10
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public Integer getWdc10() {
        return wdc10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMKIND.WDC10
     *
     * @param wdc10 the value for TMPFETCLAIMKIND.WDC10
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public void setWdc10(Integer wdc10) {
        this.wdc10 = wdc10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMKIND.WDC11
     *
     * @return the value of TMPFETCLAIMKIND.WDC11
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public String getWdc11() {
        return wdc11;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMKIND.WDC11
     *
     * @param wdc11 the value for TMPFETCLAIMKIND.WDC11
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public void setWdc11(String wdc11) {
        this.wdc11 = wdc11;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMKIND.WDC12
     *
     * @return the value of TMPFETCLAIMKIND.WDC12
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public String getWdc12() {
        return wdc12;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMKIND.WDC12
     *
     * @param wdc12 the value for TMPFETCLAIMKIND.WDC12
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public void setWdc12(String wdc12) {
        this.wdc12 = wdc12;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMKIND.WDC13
     *
     * @return the value of TMPFETCLAIMKIND.WDC13
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public String getWdc13() {
        return wdc13;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMKIND.WDC13
     *
     * @param wdc13 the value for TMPFETCLAIMKIND.WDC13
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public void setWdc13(String wdc13) {
        this.wdc13 = wdc13;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMKIND.WDC14
     *
     * @return the value of TMPFETCLAIMKIND.WDC14
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public Date getWdc14() {
        return wdc14;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMKIND.WDC14
     *
     * @param wdc14 the value for TMPFETCLAIMKIND.WDC14
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public void setWdc14(Date wdc14) {
        this.wdc14 = wdc14;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMKIND.DRAWOUTDATE
     *
     * @return the value of TMPFETCLAIMKIND.DRAWOUTDATE
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public Date getDrawoutdate() {
        return drawoutdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMKIND.DRAWOUTDATE
     *
     * @param drawoutdate the value for TMPFETCLAIMKIND.DRAWOUTDATE
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public void setDrawoutdate(Date drawoutdate) {
        this.drawoutdate = drawoutdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMKIND.DATASOURCE
     *
     * @return the value of TMPFETCLAIMKIND.DATASOURCE
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public String getDatasource() {
        return datasource;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMKIND.DATASOURCE
     *
     * @param datasource the value for TMPFETCLAIMKIND.DATASOURCE
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public void setDatasource(String datasource) {
        this.datasource = datasource;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMKIND.FLOWID
     *
     * @return the value of TMPFETCLAIMKIND.FLOWID
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public String getFlowid() {
        return flowid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMKIND.FLOWID
     *
     * @param flowid the value for TMPFETCLAIMKIND.FLOWID
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public void setFlowid(String flowid) {
        this.flowid = flowid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TMPFETCLAIMKIND.REGISTNO
     *
     * @return the value of TMPFETCLAIMKIND.REGISTNO
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public String getRegistno() {
        return registno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TMPFETCLAIMKIND.REGISTNO
     *
     * @param registno the value for TMPFETCLAIMKIND.REGISTNO
     *
     * @ibatorgenerated Fri Jun 02 17:54:54 CST 2023
     */
    public void setRegistno(String registno) {
        this.registno = registno;
    }
}