# Deployment ComCode
#modify by duanfa 20110726 start 总公司改为31000000
#deployCom=00000000
deployCom=31000000
#modify by duanfa 20110726 end

# Online     ComCode
onlineCom=21000000

# Data Clearing Switch (1,open;0,close)
syncflag=0

# Synchronous Switch of the second generation tools library(1,open;0,close)
utilityflag=0

# Cross-sell Clearing Switch(1,open;0,close)
CrossSendFlag=1

# Cross-sell WebService Url 
crosswebserviceurl=http\://11.137.110.128\:8080/DataExchangePlatform/ServiceProxy.jws

# Cross-sell WebService Function Name
crosswebservicefun=execute

# Sales and dispatcher  downsend Service Url
crossuserforwardurl=http\://11.137.76.143\:8003/ims/CrossSellWebService.jws

# Sales and dispatcher  downsend  Service Function Name
crossuserforwardfun=execute

# database type informix to oracle
database=oracle

