#drools agent
drools.agent.newInstance=false
drools.agent.scanDirectories=true
#drools.agent.changeset=http://localhost:8080/drools-guvnor/org.drools.guvnor.Guvnor/package/defaultPackage/LATEST/ChangeSet.xml

#drools resource
drools.resource.scanner.interval=500
drools.resource.urlcache=c:/temp

