package com.tlg.xchg.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

public class AssocRcvAncmt extends IBatisBaseEntity<BigDecimal>{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.ID
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private BigDecimal id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.ADDDATE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String adddate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.ASKBIRDATE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String askbirdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.ASKIDNO
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String askidno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.ASKNAME
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String askname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.ASKTYPE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String asktype;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.BAMTTYPE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String bamttype;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.BIRDATE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String birdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.CMPNO
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String cmpno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.CMPTYPE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String cmptype;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.CON
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String con;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.CONDATE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String condate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.DATAERRORMSG
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String dataerrormsg;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.FILECVDATE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private Date filecvdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.FILENAME
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String filename;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.IDNO
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String idno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.INSCLASS
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String insclass;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.INSITEM
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String insitem;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.INSKIND
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String inskind;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.INSNO
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String insno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.ITEMA
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private BigDecimal itema;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.ITEMB
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private BigDecimal itemb;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.ITEMC
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private BigDecimal itemc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.ITEMD
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private BigDecimal itemd;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.ITEME
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private BigDecimal iteme;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.ITEMF
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private BigDecimal itemf;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.ITEMG
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private BigDecimal itemg;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.ITEMH
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private BigDecimal itemh;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.ITEMI
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private BigDecimal itemi;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.ITEMJ
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private BigDecimal itemj;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.ITEMK
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private BigDecimal itemk;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.ITEML
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private BigDecimal iteml;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.ITEMM
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private BigDecimal itemm;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.ITEMN
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private BigDecimal itemn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.ITEMO
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private BigDecimal itemo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.ITEMP
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private BigDecimal itemp;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.MESSAGE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String message;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.NAME
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.OVRDATE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String ovrdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.PRM
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private BigDecimal prm;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.RECORDTIME
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private Date recordtime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.RETURNCODE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String returncode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.SEX
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String sex;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.SOURCE_REMARK
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String sourceRemark;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.VALDATE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String valdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.SN
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.INSNOM
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String insnom;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.ORIGIN
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String origin;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.CHANNEL
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String channel;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.PRDCODE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String prdcode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.PAYTYPE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String paytype;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.ITEMQ
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private BigDecimal itemq;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.ITEMR
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private BigDecimal itemr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.ITEMS
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private BigDecimal items;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.VALTIME
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String valtime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.OVRTIME
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String ovrtime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.PRMYEARS
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String prmyears;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.CONTIME
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String contime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.FILLDATE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String filldate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.BROKTYPE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String broktype;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ASSOC_RCV_ANCMT.TO_LIA_FLAG
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    private String toLiaFlag;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.ID
     *
     * @return the value of ASSOC_RCV_ANCMT.ID
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.ID
     *
     * @param id the value for ASSOC_RCV_ANCMT.ID
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.ADDDATE
     *
     * @return the value of ASSOC_RCV_ANCMT.ADDDATE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getAdddate() {
        return adddate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.ADDDATE
     *
     * @param adddate the value for ASSOC_RCV_ANCMT.ADDDATE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setAdddate(String adddate) {
        this.adddate = adddate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.ASKBIRDATE
     *
     * @return the value of ASSOC_RCV_ANCMT.ASKBIRDATE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getAskbirdate() {
        return askbirdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.ASKBIRDATE
     *
     * @param askbirdate the value for ASSOC_RCV_ANCMT.ASKBIRDATE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setAskbirdate(String askbirdate) {
        this.askbirdate = askbirdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.ASKIDNO
     *
     * @return the value of ASSOC_RCV_ANCMT.ASKIDNO
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getAskidno() {
        return askidno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.ASKIDNO
     *
     * @param askidno the value for ASSOC_RCV_ANCMT.ASKIDNO
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setAskidno(String askidno) {
        this.askidno = askidno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.ASKNAME
     *
     * @return the value of ASSOC_RCV_ANCMT.ASKNAME
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getAskname() {
        return askname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.ASKNAME
     *
     * @param askname the value for ASSOC_RCV_ANCMT.ASKNAME
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setAskname(String askname) {
        this.askname = askname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.ASKTYPE
     *
     * @return the value of ASSOC_RCV_ANCMT.ASKTYPE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getAsktype() {
        return asktype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.ASKTYPE
     *
     * @param asktype the value for ASSOC_RCV_ANCMT.ASKTYPE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setAsktype(String asktype) {
        this.asktype = asktype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.BAMTTYPE
     *
     * @return the value of ASSOC_RCV_ANCMT.BAMTTYPE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getBamttype() {
        return bamttype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.BAMTTYPE
     *
     * @param bamttype the value for ASSOC_RCV_ANCMT.BAMTTYPE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setBamttype(String bamttype) {
        this.bamttype = bamttype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.BIRDATE
     *
     * @return the value of ASSOC_RCV_ANCMT.BIRDATE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getBirdate() {
        return birdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.BIRDATE
     *
     * @param birdate the value for ASSOC_RCV_ANCMT.BIRDATE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setBirdate(String birdate) {
        this.birdate = birdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.CMPNO
     *
     * @return the value of ASSOC_RCV_ANCMT.CMPNO
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getCmpno() {
        return cmpno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.CMPNO
     *
     * @param cmpno the value for ASSOC_RCV_ANCMT.CMPNO
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setCmpno(String cmpno) {
        this.cmpno = cmpno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.CMPTYPE
     *
     * @return the value of ASSOC_RCV_ANCMT.CMPTYPE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getCmptype() {
        return cmptype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.CMPTYPE
     *
     * @param cmptype the value for ASSOC_RCV_ANCMT.CMPTYPE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setCmptype(String cmptype) {
        this.cmptype = cmptype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.CON
     *
     * @return the value of ASSOC_RCV_ANCMT.CON
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getCon() {
        return con;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.CON
     *
     * @param con the value for ASSOC_RCV_ANCMT.CON
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setCon(String con) {
        this.con = con;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.CONDATE
     *
     * @return the value of ASSOC_RCV_ANCMT.CONDATE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getCondate() {
        return condate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.CONDATE
     *
     * @param condate the value for ASSOC_RCV_ANCMT.CONDATE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setCondate(String condate) {
        this.condate = condate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.DATAERRORMSG
     *
     * @return the value of ASSOC_RCV_ANCMT.DATAERRORMSG
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getDataerrormsg() {
        return dataerrormsg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.DATAERRORMSG
     *
     * @param dataerrormsg the value for ASSOC_RCV_ANCMT.DATAERRORMSG
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setDataerrormsg(String dataerrormsg) {
        this.dataerrormsg = dataerrormsg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.FILECVDATE
     *
     * @return the value of ASSOC_RCV_ANCMT.FILECVDATE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public Date getFilecvdate() {
        return filecvdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.FILECVDATE
     *
     * @param filecvdate the value for ASSOC_RCV_ANCMT.FILECVDATE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setFilecvdate(Date filecvdate) {
        this.filecvdate = filecvdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.FILENAME
     *
     * @return the value of ASSOC_RCV_ANCMT.FILENAME
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.FILENAME
     *
     * @param filename the value for ASSOC_RCV_ANCMT.FILENAME
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.IDNO
     *
     * @return the value of ASSOC_RCV_ANCMT.IDNO
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getIdno() {
        return idno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.IDNO
     *
     * @param idno the value for ASSOC_RCV_ANCMT.IDNO
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setIdno(String idno) {
        this.idno = idno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.INSCLASS
     *
     * @return the value of ASSOC_RCV_ANCMT.INSCLASS
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getInsclass() {
        return insclass;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.INSCLASS
     *
     * @param insclass the value for ASSOC_RCV_ANCMT.INSCLASS
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setInsclass(String insclass) {
        this.insclass = insclass;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.INSITEM
     *
     * @return the value of ASSOC_RCV_ANCMT.INSITEM
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getInsitem() {
        return insitem;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.INSITEM
     *
     * @param insitem the value for ASSOC_RCV_ANCMT.INSITEM
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setInsitem(String insitem) {
        this.insitem = insitem;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.INSKIND
     *
     * @return the value of ASSOC_RCV_ANCMT.INSKIND
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getInskind() {
        return inskind;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.INSKIND
     *
     * @param inskind the value for ASSOC_RCV_ANCMT.INSKIND
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setInskind(String inskind) {
        this.inskind = inskind;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.INSNO
     *
     * @return the value of ASSOC_RCV_ANCMT.INSNO
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getInsno() {
        return insno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.INSNO
     *
     * @param insno the value for ASSOC_RCV_ANCMT.INSNO
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setInsno(String insno) {
        this.insno = insno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.ITEMA
     *
     * @return the value of ASSOC_RCV_ANCMT.ITEMA
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public BigDecimal getItema() {
        return itema;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.ITEMA
     *
     * @param itema the value for ASSOC_RCV_ANCMT.ITEMA
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setItema(BigDecimal itema) {
        this.itema = itema;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.ITEMB
     *
     * @return the value of ASSOC_RCV_ANCMT.ITEMB
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public BigDecimal getItemb() {
        return itemb;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.ITEMB
     *
     * @param itemb the value for ASSOC_RCV_ANCMT.ITEMB
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setItemb(BigDecimal itemb) {
        this.itemb = itemb;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.ITEMC
     *
     * @return the value of ASSOC_RCV_ANCMT.ITEMC
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public BigDecimal getItemc() {
        return itemc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.ITEMC
     *
     * @param itemc the value for ASSOC_RCV_ANCMT.ITEMC
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setItemc(BigDecimal itemc) {
        this.itemc = itemc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.ITEMD
     *
     * @return the value of ASSOC_RCV_ANCMT.ITEMD
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public BigDecimal getItemd() {
        return itemd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.ITEMD
     *
     * @param itemd the value for ASSOC_RCV_ANCMT.ITEMD
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setItemd(BigDecimal itemd) {
        this.itemd = itemd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.ITEME
     *
     * @return the value of ASSOC_RCV_ANCMT.ITEME
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public BigDecimal getIteme() {
        return iteme;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.ITEME
     *
     * @param iteme the value for ASSOC_RCV_ANCMT.ITEME
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setIteme(BigDecimal iteme) {
        this.iteme = iteme;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.ITEMF
     *
     * @return the value of ASSOC_RCV_ANCMT.ITEMF
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public BigDecimal getItemf() {
        return itemf;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.ITEMF
     *
     * @param itemf the value for ASSOC_RCV_ANCMT.ITEMF
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setItemf(BigDecimal itemf) {
        this.itemf = itemf;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.ITEMG
     *
     * @return the value of ASSOC_RCV_ANCMT.ITEMG
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public BigDecimal getItemg() {
        return itemg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.ITEMG
     *
     * @param itemg the value for ASSOC_RCV_ANCMT.ITEMG
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setItemg(BigDecimal itemg) {
        this.itemg = itemg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.ITEMH
     *
     * @return the value of ASSOC_RCV_ANCMT.ITEMH
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public BigDecimal getItemh() {
        return itemh;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.ITEMH
     *
     * @param itemh the value for ASSOC_RCV_ANCMT.ITEMH
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setItemh(BigDecimal itemh) {
        this.itemh = itemh;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.ITEMI
     *
     * @return the value of ASSOC_RCV_ANCMT.ITEMI
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public BigDecimal getItemi() {
        return itemi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.ITEMI
     *
     * @param itemi the value for ASSOC_RCV_ANCMT.ITEMI
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setItemi(BigDecimal itemi) {
        this.itemi = itemi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.ITEMJ
     *
     * @return the value of ASSOC_RCV_ANCMT.ITEMJ
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public BigDecimal getItemj() {
        return itemj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.ITEMJ
     *
     * @param itemj the value for ASSOC_RCV_ANCMT.ITEMJ
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setItemj(BigDecimal itemj) {
        this.itemj = itemj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.ITEMK
     *
     * @return the value of ASSOC_RCV_ANCMT.ITEMK
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public BigDecimal getItemk() {
        return itemk;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.ITEMK
     *
     * @param itemk the value for ASSOC_RCV_ANCMT.ITEMK
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setItemk(BigDecimal itemk) {
        this.itemk = itemk;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.ITEML
     *
     * @return the value of ASSOC_RCV_ANCMT.ITEML
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public BigDecimal getIteml() {
        return iteml;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.ITEML
     *
     * @param iteml the value for ASSOC_RCV_ANCMT.ITEML
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setIteml(BigDecimal iteml) {
        this.iteml = iteml;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.ITEMM
     *
     * @return the value of ASSOC_RCV_ANCMT.ITEMM
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public BigDecimal getItemm() {
        return itemm;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.ITEMM
     *
     * @param itemm the value for ASSOC_RCV_ANCMT.ITEMM
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setItemm(BigDecimal itemm) {
        this.itemm = itemm;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.ITEMN
     *
     * @return the value of ASSOC_RCV_ANCMT.ITEMN
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public BigDecimal getItemn() {
        return itemn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.ITEMN
     *
     * @param itemn the value for ASSOC_RCV_ANCMT.ITEMN
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setItemn(BigDecimal itemn) {
        this.itemn = itemn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.ITEMO
     *
     * @return the value of ASSOC_RCV_ANCMT.ITEMO
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public BigDecimal getItemo() {
        return itemo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.ITEMO
     *
     * @param itemo the value for ASSOC_RCV_ANCMT.ITEMO
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setItemo(BigDecimal itemo) {
        this.itemo = itemo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.ITEMP
     *
     * @return the value of ASSOC_RCV_ANCMT.ITEMP
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public BigDecimal getItemp() {
        return itemp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.ITEMP
     *
     * @param itemp the value for ASSOC_RCV_ANCMT.ITEMP
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setItemp(BigDecimal itemp) {
        this.itemp = itemp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.MESSAGE
     *
     * @return the value of ASSOC_RCV_ANCMT.MESSAGE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.MESSAGE
     *
     * @param message the value for ASSOC_RCV_ANCMT.MESSAGE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.NAME
     *
     * @return the value of ASSOC_RCV_ANCMT.NAME
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.NAME
     *
     * @param name the value for ASSOC_RCV_ANCMT.NAME
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.OVRDATE
     *
     * @return the value of ASSOC_RCV_ANCMT.OVRDATE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getOvrdate() {
        return ovrdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.OVRDATE
     *
     * @param ovrdate the value for ASSOC_RCV_ANCMT.OVRDATE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setOvrdate(String ovrdate) {
        this.ovrdate = ovrdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.PRM
     *
     * @return the value of ASSOC_RCV_ANCMT.PRM
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public BigDecimal getPrm() {
        return prm;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.PRM
     *
     * @param prm the value for ASSOC_RCV_ANCMT.PRM
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setPrm(BigDecimal prm) {
        this.prm = prm;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.RECORDTIME
     *
     * @return the value of ASSOC_RCV_ANCMT.RECORDTIME
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public Date getRecordtime() {
        return recordtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.RECORDTIME
     *
     * @param recordtime the value for ASSOC_RCV_ANCMT.RECORDTIME
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setRecordtime(Date recordtime) {
        this.recordtime = recordtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.RETURNCODE
     *
     * @return the value of ASSOC_RCV_ANCMT.RETURNCODE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getReturncode() {
        return returncode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.RETURNCODE
     *
     * @param returncode the value for ASSOC_RCV_ANCMT.RETURNCODE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setReturncode(String returncode) {
        this.returncode = returncode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.SEX
     *
     * @return the value of ASSOC_RCV_ANCMT.SEX
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.SEX
     *
     * @param sex the value for ASSOC_RCV_ANCMT.SEX
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.SOURCE_REMARK
     *
     * @return the value of ASSOC_RCV_ANCMT.SOURCE_REMARK
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getSourceRemark() {
        return sourceRemark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.SOURCE_REMARK
     *
     * @param sourceRemark the value for ASSOC_RCV_ANCMT.SOURCE_REMARK
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setSourceRemark(String sourceRemark) {
        this.sourceRemark = sourceRemark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.VALDATE
     *
     * @return the value of ASSOC_RCV_ANCMT.VALDATE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getValdate() {
        return valdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.VALDATE
     *
     * @param valdate the value for ASSOC_RCV_ANCMT.VALDATE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setValdate(String valdate) {
        this.valdate = valdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.SN
     *
     * @return the value of ASSOC_RCV_ANCMT.SN
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.SN
     *
     * @param sn the value for ASSOC_RCV_ANCMT.SN
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setSn(String sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.INSNOM
     *
     * @return the value of ASSOC_RCV_ANCMT.INSNOM
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getInsnom() {
        return insnom;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.INSNOM
     *
     * @param insnom the value for ASSOC_RCV_ANCMT.INSNOM
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setInsnom(String insnom) {
        this.insnom = insnom;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.ORIGIN
     *
     * @return the value of ASSOC_RCV_ANCMT.ORIGIN
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.ORIGIN
     *
     * @param origin the value for ASSOC_RCV_ANCMT.ORIGIN
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setOrigin(String origin) {
        this.origin = origin;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.CHANNEL
     *
     * @return the value of ASSOC_RCV_ANCMT.CHANNEL
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.CHANNEL
     *
     * @param channel the value for ASSOC_RCV_ANCMT.CHANNEL
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setChannel(String channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.PRDCODE
     *
     * @return the value of ASSOC_RCV_ANCMT.PRDCODE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getPrdcode() {
        return prdcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.PRDCODE
     *
     * @param prdcode the value for ASSOC_RCV_ANCMT.PRDCODE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setPrdcode(String prdcode) {
        this.prdcode = prdcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.PAYTYPE
     *
     * @return the value of ASSOC_RCV_ANCMT.PAYTYPE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.PAYTYPE
     *
     * @param paytype the value for ASSOC_RCV_ANCMT.PAYTYPE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setPaytype(String paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.ITEMQ
     *
     * @return the value of ASSOC_RCV_ANCMT.ITEMQ
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public BigDecimal getItemq() {
        return itemq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.ITEMQ
     *
     * @param itemq the value for ASSOC_RCV_ANCMT.ITEMQ
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setItemq(BigDecimal itemq) {
        this.itemq = itemq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.ITEMR
     *
     * @return the value of ASSOC_RCV_ANCMT.ITEMR
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public BigDecimal getItemr() {
        return itemr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.ITEMR
     *
     * @param itemr the value for ASSOC_RCV_ANCMT.ITEMR
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setItemr(BigDecimal itemr) {
        this.itemr = itemr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.ITEMS
     *
     * @return the value of ASSOC_RCV_ANCMT.ITEMS
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public BigDecimal getItems() {
        return items;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.ITEMS
     *
     * @param items the value for ASSOC_RCV_ANCMT.ITEMS
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setItems(BigDecimal items) {
        this.items = items;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.VALTIME
     *
     * @return the value of ASSOC_RCV_ANCMT.VALTIME
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getValtime() {
        return valtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.VALTIME
     *
     * @param valtime the value for ASSOC_RCV_ANCMT.VALTIME
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setValtime(String valtime) {
        this.valtime = valtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.OVRTIME
     *
     * @return the value of ASSOC_RCV_ANCMT.OVRTIME
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getOvrtime() {
        return ovrtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.OVRTIME
     *
     * @param ovrtime the value for ASSOC_RCV_ANCMT.OVRTIME
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setOvrtime(String ovrtime) {
        this.ovrtime = ovrtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.PRMYEARS
     *
     * @return the value of ASSOC_RCV_ANCMT.PRMYEARS
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getPrmyears() {
        return prmyears;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.PRMYEARS
     *
     * @param prmyears the value for ASSOC_RCV_ANCMT.PRMYEARS
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setPrmyears(String prmyears) {
        this.prmyears = prmyears;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.CONTIME
     *
     * @return the value of ASSOC_RCV_ANCMT.CONTIME
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getContime() {
        return contime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.CONTIME
     *
     * @param contime the value for ASSOC_RCV_ANCMT.CONTIME
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setContime(String contime) {
        this.contime = contime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.FILLDATE
     *
     * @return the value of ASSOC_RCV_ANCMT.FILLDATE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getFilldate() {
        return filldate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.FILLDATE
     *
     * @param filldate the value for ASSOC_RCV_ANCMT.FILLDATE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setFilldate(String filldate) {
        this.filldate = filldate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.BROKTYPE
     *
     * @return the value of ASSOC_RCV_ANCMT.BROKTYPE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getBroktype() {
        return broktype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.BROKTYPE
     *
     * @param broktype the value for ASSOC_RCV_ANCMT.BROKTYPE
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setBroktype(String broktype) {
        this.broktype = broktype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ASSOC_RCV_ANCMT.TO_LIA_FLAG
     *
     * @return the value of ASSOC_RCV_ANCMT.TO_LIA_FLAG
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public String getToLiaFlag() {
        return toLiaFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ASSOC_RCV_ANCMT.TO_LIA_FLAG
     *
     * @param toLiaFlag the value for ASSOC_RCV_ANCMT.TO_LIA_FLAG
     *
     * @ibatorgenerated Fri Jan 22 15:57:09 CST 2021
     */
    public void setToLiaFlag(String toLiaFlag) {
        this.toLiaFlag = toLiaFlag;
    }
}