#邮件服务器地�?
mail.smtpurl=smtp.163.com
#服务器端�?
mail.port=25
#邮件服务器名�?
mail.smtpusername=tsbclaimsend@163.com
#邮件服务器密�?
mail.smtppassword=tsbclaimsend123
#邮件地址
mail.username=tsbclaimsend@163.com
#邮件昵称
mail.nickname=tsbclaim
#模板路径
mail.velocityFilePath=/com/sinosoft/claim/email/vm/mail.vm
#Socket I/O超时值，单位毫秒，缺省�?不超时�? 
mail.smtp.timeout=25000
# 如果邮件服务器需要认证，则需确保设为true,不然控制台会报错 
mail.smtp.auth=true

#附件地址（暂不使用）
mail.attachip=F:/
#附件根目录（暂不使用�?
mail.rootpath=/sigps
#文件导出地址（暂不使用）
mail.exportPath=/weblogic/webapps/autoExcel/
#文件压缩地址（暂不使用）
mail.compressPath=/weblogic/webapps/ZipAutoExcel/
#文件压缩地址及名称（暂不使用�?
mail.compressName=/weblogic/webapps/ZipAutoExcel/excel.zip
#系统地址（暂不使用）
mail.localhost=http\://10.10.163.175\:7001/ewps

#管理员账�?收件人地�?
mail.admin1=
mail.admin2=
mail.admin3=tsbclaim@163.com
mail.admin4=