package com.sinosoft.undwrt.common.model;

// Generated 2013-1-28 20:37:15 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PrpDExpenseDetail generated by hbm2java.
 */
@Entity(name = "PRPDEXPENSEDETAIL_UNDWRT")
@Table(name = "PRPDEXPENSEDETAIL")
public class PrpDExpenseDetail implements java.io.Serializable {

	/** 屬性The sinosoft id. */
	private PrpDExpenseDetailId id;

	/**
	 * Instantiates a new prp d expense detail.
	 */
	public PrpDExpenseDetail() {
	}

	/**
	 * Instantiates a new prp d expense detail.
	 * 
	 * @param id
	 *            the id
	 */
	public PrpDExpenseDetail(PrpDExpenseDetailId id) {
		this.id = id;
	}

	/**
	 * 獲取屬性the sinosoft id.
	 * 
	 * @return 屬性the sinosoft id的值
	 */
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "certitype", column = @Column(name = "CERTITYPE", nullable = false, length = 1)),
			@AttributeOverride(name = "certino", column = @Column(name = "CERTINO", nullable = false, length = 25)),
			@AttributeOverride(name = "policyno", column = @Column(name = "POLICYNO", nullable = false, length = 22)),
			@AttributeOverride(name = "classcode", column = @Column(name = "CLASSCODE", length = 2)),
			@AttributeOverride(name = "riskcode", column = @Column(name = "RISKCODE", length = 4)),
			@AttributeOverride(name = "productcode", column = @Column(name = "PRODUCTCODE", length = 8)),
			@AttributeOverride(name = "sumamount", column = @Column(name = "SUMAMOUNT", precision = 14)),
			@AttributeOverride(name = "sumpremium", column = @Column(name = "SUMPREMIUM", precision = 14)),
			@AttributeOverride(name = "maxusablefee", column = @Column(name = "MAXUSABLEFEE", precision = 20)),
			@AttributeOverride(name = "brokerfee", column = @Column(name = "BROKERFEE", precision = 20)),
			@AttributeOverride(name = "agentfee", column = @Column(name = "AGENTFEE", precision = 20)),
			@AttributeOverride(name = "orgfee", column = @Column(name = "ORGFEE", precision = 20)),
			@AttributeOverride(name = "breakevenfee", column = @Column(name = "BREAKEVENFEE", precision = 20)),
			@AttributeOverride(name = "ext3fee", column = @Column(name = "EXT3FEE", precision = 20)),
			@AttributeOverride(name = "ext2fee", column = @Column(name = "EXT2FEE", precision = 20)),
			@AttributeOverride(name = "ext1fee", column = @Column(name = "EXT1FEE", precision = 20)),
			@AttributeOverride(name = "comcode", column = @Column(name = "COMCODE", nullable = false, length = 10)),
			@AttributeOverride(name = "operatorcode", column = @Column(name = "OPERATORCODE", nullable = false, length = 10)),
			@AttributeOverride(name = "operatetime", column = @Column(name = "OPERATETIME", nullable = false, length = 19)),
			@AttributeOverride(name = "flag", column = @Column(name = "FLAG", length = 2)) })
	public PrpDExpenseDetailId getId() {
		return this.id;
	}

	/**
	 * 設置屬性the sinosoft id.
	 * 
	 * @param id
	 *            待設置的the sinosoft id的值
	 */
	public void setId(PrpDExpenseDetailId id) {
		this.id = id;
	}

}
