package com.sinosoft.undwrt.common.model;

// Generated 2012-12-29 17:02:41 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PrpDcompany generated by hbm2java.
 */
@Entity(name = "PRPDCOMPANY_UNDWRT")
@Table(name = "PRPDCOMPANY")
public class PrpDcompany implements java.io.Serializable {

	/** 屬性機構代碼. */
	private String comCode;
	
	/** 屬性The sinosoft prp dcompany. */
	private PrpDcompany prpDcompany;
	
	/** 屬性機構中文名稱. */
	private String comCName;
	
	/** 屬性The sinosoft com e name. */
	private String comEName;
	
	/** 屬性The sinosoft address c name. */
	private String addressCName;
	
	/** 屬性The sinosoft address e name. */
	private String addressEName;
	
	/** 屬性The sinosoft post code. */
	private String postCode;
	
	/** 屬性The sinosoft phone number. */
	private String phoneNumber;
	
	/** 屬性The sinosoft tax number. */
	private String taxNumber;
	
	/** 屬性The sinosoft fax number. */
	private String faxNumber;
	
	/** 屬性The sinosoft insurer name. */
	private String insurerName;
	
	/** 屬性The sinosoft com attribute. */
	private String comAttribute;
	
	/** 屬性The sinosoft com type. */
	private String comType;
	
	/** 屬性The sinosoft com level. */
	private String comLevel;
	
	/** 屬性The sinosoft manager. */
	private String manager;
	
	/** 屬性The sinosoft account leader. */
	private String accountLeader;
	
	/** 屬性The sinosoft cashier. */
	private String cashier;
	
	/** 屬性The sinosoft account ant. */
	private String accountAnt;
	
	/** 屬性The sinosoft remark. */
	private String remark;
	
	/** 屬性The sinosoft new com code. */
	private String newComCode;
	
	/** 屬性The sinosoft valid status. */
	private String validStatus;
	
	/** 屬性The sinosoft acnt unit. */
	private String acntUnit;
	
	/** 屬性The sinosoft article code. */
	private String articleCode;
	
	/** 屬性The sinosoft acc code. */
	private String accCode;
	
	/** 屬性The sinosoft center flag. */
	private String centerFlag;
	
	/** 屬性The sinosoft outer pay code. */
	private String outerPayCode;
	
	/** 屬性The sinosoft inner pay code. */
	private String innerPayCode;
	
	/** 屬性標志. */
	private String flag;
	
	/** 屬性The sinosoft web address. */
	private String webAddress;
	
	/** 屬性The sinosoft service phone. */
	private String servicePhone;
	
	/** 屬性The sinosoft report phone. */
	private String reportPhone;
	
	/** 屬性The sinosoft agent code. */
	private String agentCode;
	
	/** 屬性The sinosoft agreement no. */
	private String agreementNo;
	
	/** 屬性The sinosoft sys area code. */
	private String sysAreaCode;
	
	/** 屬性The sinosoft comb visit rate. */
	private Double combVisitRate;
	
	/** 屬性The sinosoft print com name. */
	private String printComName;
	
	/** 屬性The sinosoft print address. */
	private String printAddress;
	
	/** 屬性The sinosoft pring post code. */
	private String pringPostCode;
	
	/** 屬性The sinosoft upper claim com code. */
	private String upperClaimComCode;
	
	/** 屬性The sinosoft sap com code. */
	private String sapComCode;
	
	/** 屬性The sinosoft cost center code. */
	private String costCenterCode;
	
	/** 屬性The sinosoft group nature. */
	private String groupNature;
	
	/** 屬性The sinosoft group level. */
	private String groupLevel;
	
	/** 屬性The sinosoft sales channel code. */
	private String salesChannelCode;
	
	/** 屬性The sinosoft group nature detail. */
	private String groupNatureDetail;
	
	/** 屬性The sinosoft taxi den no. */
	private String taxiDenNo;
	
	/** 屬性The sinosoft prp dusers for make com. */
	private Set<PrpDuser> prpDusersForMakeCom = new HashSet<PrpDuser>(0);
	
	/** 屬性The sinosoft prp dcompanies. */
	private Set<PrpDcompany> prpDcompanies = new HashSet<PrpDcompany>(0);
	
	/** 屬性The sinosoft prp dusers for com code. */
	private Set<PrpDuser> prpDusersForComCode = new HashSet<PrpDuser>(0);

	/**
	 * Instantiates a new prp dcompany.
	 */
	public PrpDcompany() {
	}

	/**
	 * Instantiates a new prp dcompany.
	 * 
	 * @param comCode
	 *            the com code
	 * @param prpDcompany
	 *            the prp dcompany
	 * @param comCName
	 *            the com c name
	 * @param newComCode
	 *            the new com code
	 * @param validStatus
	 *            the valid status
	 */
	public PrpDcompany(String comCode, PrpDcompany prpDcompany,
			String comCName, String newComCode, String validStatus) {
		this.comCode = comCode;
		this.prpDcompany = prpDcompany;
		this.comCName = comCName;
		this.newComCode = newComCode;
		this.validStatus = validStatus;
	}



	/**
	 * Instantiates a new prp dcompany.
	 * 
	 * @param comCode
	 *            the com code
	 * @param prpDcompany
	 *            the prp dcompany
	 * @param comCName
	 *            the com c name
	 * @param comEName
	 *            the com e name
	 * @param addressCName
	 *            the address c name
	 * @param addressEName
	 *            the address e name
	 * @param postCode
	 *            the post code
	 * @param phoneNumber
	 *            the phone number
	 * @param taxNumber
	 *            the tax number
	 * @param faxNumber
	 *            the fax number
	 * @param insurerName
	 *            the insurer name
	 * @param comAttribute
	 *            the com attribute
	 * @param comType
	 *            the com type
	 * @param comLevel
	 *            the com level
	 * @param manager
	 *            the manager
	 * @param accountLeader
	 *            the account leader
	 * @param cashier
	 *            the cashier
	 * @param accountAnt
	 *            the account ant
	 * @param remark
	 *            the remark
	 * @param newComCode
	 *            the new com code
	 * @param validStatus
	 *            the valid status
	 * @param acntUnit
	 *            the acnt unit
	 * @param articleCode
	 *            the article code
	 * @param accCode
	 *            the acc code
	 * @param centerFlag
	 *            the center flag
	 * @param outerPayCode
	 *            the outer pay code
	 * @param innerPayCode
	 *            the inner pay code
	 * @param flag
	 *            the flag
	 * @param webAddress
	 *            the web address
	 * @param servicePhone
	 *            the service phone
	 * @param reportPhone
	 *            the report phone
	 * @param agentCode
	 *            the agent code
	 * @param agreementNo
	 *            the agreement no
	 * @param sysAreaCode
	 *            the sys area code
	 * @param combVisitRate
	 *            the comb visit rate
	 * @param printComName
	 *            the print com name
	 * @param printAddress
	 *            the print address
	 * @param pringPostCode
	 *            the pring post code
	 * @param upperClaimComCode
	 *            the upper claim com code
	 * @param sapComCode
	 *            the sap com code
	 * @param costCenterCode
	 *            the cost center code
	 * @param groupNature
	 *            the group nature
	 * @param groupLevel
	 *            the group level
	 * @param salesChannelCode
	 *            the sales channel code
	 * @param groupNatureDetail
	 *            the group nature detail
	 * @param taxiDenNo
	 *            the taxi den no
	 * @param prpDusersForMakeCom
	 *            the prp dusers for make com
	 * @param prpDcompanies
	 *            the prp dcompanies
	 * @param prpDusersForComCode
	 *            the prp dusers for com code
	 */
	public PrpDcompany(String comCode, PrpDcompany prpDcompany,
			String comCName, String comEName, String addressCName,
			String addressEName, String postCode, String phoneNumber,
			String taxNumber, String faxNumber, String insurerName,
			String comAttribute, String comType, String comLevel,
			String manager, String accountLeader, String cashier,
			String accountAnt, String remark, String newComCode,
			String validStatus, String acntUnit, String articleCode,
			String accCode, String centerFlag, String outerPayCode,
			String innerPayCode, String flag, String webAddress,
			String servicePhone, String reportPhone, String agentCode,
			String agreementNo, String sysAreaCode, Double combVisitRate,
			String printComName, String printAddress, String pringPostCode,
			String upperClaimComCode, String sapComCode, String costCenterCode,
			String groupNature, String groupLevel, String salesChannelCode,
			String groupNatureDetail, String taxiDenNo,
			Set<PrpDuser> prpDusersForMakeCom, Set<PrpDcompany> prpDcompanies,
			Set<PrpDuser> prpDusersForComCode) {
		this.comCode = comCode;
		this.prpDcompany = prpDcompany;
		this.comCName = comCName;
		this.comEName = comEName;
		this.addressCName = addressCName;
		this.addressEName = addressEName;
		this.postCode = postCode;
		this.phoneNumber = phoneNumber;
		this.taxNumber = taxNumber;
		this.faxNumber = faxNumber;
		this.insurerName = insurerName;
		this.comAttribute = comAttribute;
		this.comType = comType;
		this.comLevel = comLevel;
		manager = manager;
		this.accountLeader = accountLeader;
		cashier = cashier;
		this.accountAnt = accountAnt;
		this.remark = remark;
		this.newComCode = newComCode;
		this.validStatus = validStatus;
		this.acntUnit = acntUnit;
		this.articleCode = articleCode;
		this.accCode = accCode;
		this.centerFlag = centerFlag;
		this.outerPayCode = outerPayCode;
		this.innerPayCode = innerPayCode;
		flag = flag;
		this.webAddress = webAddress;
		this.servicePhone = servicePhone;
		this.reportPhone = reportPhone;
		this.agentCode = agentCode;
		this.agreementNo = agreementNo;
		this.sysAreaCode = sysAreaCode;
		this.combVisitRate = combVisitRate;
		this.printComName = printComName;
		this.printAddress = printAddress;
		this.pringPostCode = pringPostCode;
		this.upperClaimComCode = upperClaimComCode;
		this.sapComCode = sapComCode;
		this.costCenterCode = costCenterCode;
		this.groupNature = groupNature;
		this.groupLevel = groupLevel;
		this.salesChannelCode = salesChannelCode;
		this.groupNatureDetail = groupNatureDetail;
		this.taxiDenNo = taxiDenNo;
		this.prpDusersForMakeCom = prpDusersForMakeCom;
		this.prpDcompanies = prpDcompanies;
		this.prpDusersForComCode = prpDusersForComCode;
	}

	/**
	 * 獲取屬性機構代碼.
	 * 
	 * @return 屬性機構代碼的值
	 */
	@Id
	@Column(name = "COMCODE", unique = true, nullable = false, length = 10)
	public String getComCode() {
		return this.comCode;
	}

	/**
	 * 設置屬性機構代碼.
	 * 
	 * @param comCode
	 *            待設置的機構代碼的值
	 */
	public void setComCode(String comCode) {
		this.comCode = comCode;
	}

	/**
	 * 獲取屬性the sinosoft prp dcompany.
	 * 
	 * @return 屬性the sinosoft prp dcompany的值
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPPERCOMCODE", nullable = false)
	public PrpDcompany getPrpDcompany() {
		return this.prpDcompany;
	}

	/**
	 * 設置屬性the sinosoft prp dcompany.
	 * 
	 * @param prpDcompany
	 *            待設置的the sinosoft prp dcompany的值
	 */
	public void setPrpDcompany(PrpDcompany prpDcompany) {
		this.prpDcompany = prpDcompany;
	}

	/**
	 * 獲取屬性機構中文名稱.
	 * 
	 * @return 屬性機構中文名稱的值
	 */
	@Column(name = "COMCNAME", nullable = false, length = 200)
	public String getComCName() {
		return this.comCName;
	}

	/**
	 * 設置屬性機構中文名稱.
	 * 
	 * @param comCName
	 *            待設置的機構中文名稱的值
	 */
	public void setComCName(String comCName) {
		this.comCName = comCName;
	}

	/**
	 * 獲取屬性the sinosoft com e name.
	 * 
	 * @return 屬性the sinosoft com e name的值
	 */
	@Column(name = "COMENAME", length = 80)
	public String getComEName() {
		return this.comEName;
	}

	/**
	 * 設置屬性the sinosoft com e name.
	 * 
	 * @param comEName
	 *            待設置的the sinosoft com e name的值
	 */
	public void setComEName(String comEName) {
		this.comEName = comEName;
	}

	/**
	 * 獲取屬性the sinosoft address c name.
	 * 
	 * @return 屬性the sinosoft address c name的值
	 */
	@Column(name = "ADDRESSCNAME", length = 60)
	public String getAddressCName() {
		return this.addressCName;
	}

	/**
	 * 設置屬性the sinosoft address c name.
	 * 
	 * @param addressCName
	 *            待設置的the sinosoft address c name的值
	 */
	public void setAddressCName(String addressCName) {
		this.addressCName = addressCName;
	}

	/**
	 * 獲取屬性the sinosoft address e name.
	 * 
	 * @return 屬性the sinosoft address e name的值
	 */
	@Column(name = "ADDRESSENAME", length = 80)
	public String getAddressEName() {
		return this.addressEName;
	}

	/**
	 * 設置屬性the sinosoft address e name.
	 * 
	 * @param addressEName
	 *            待設置的the sinosoft address e name的值
	 */
	public void setAddressEName(String addressEName) {
		this.addressEName = addressEName;
	}

	/**
	 * 獲取屬性the sinosoft post code.
	 * 
	 * @return 屬性the sinosoft post code的值
	 */
	@Column(name = "POSTCODE", length = 6)
	public String getPostCode() {
		return this.postCode;
	}

	/**
	 * 設置屬性the sinosoft post code.
	 * 
	 * @param postCode
	 *            待設置的the sinosoft post code的值
	 */
	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	/**
	 * 獲取屬性the sinosoft phone number.
	 * 
	 * @return 屬性the sinosoft phone number的值
	 */
	@Column(name = "PHONENUMBER", length = 30)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	/**
	 * 設置屬性the sinosoft phone number.
	 * 
	 * @param phoneNumber
	 *            待設置的the sinosoft phone number的值
	 */
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	/**
	 * 獲取屬性the sinosoft tax number.
	 * 
	 * @return 屬性the sinosoft tax number的值
	 */
	@Column(name = "TAXNUMBER", length = 30)
	public String getTaxNumber() {
		return this.taxNumber;
	}

	/**
	 * 設置屬性the sinosoft tax number.
	 * 
	 * @param taxNumber
	 *            待設置的the sinosoft tax number的值
	 */
	public void setTaxNumber(String taxNumber) {
		this.taxNumber = taxNumber;
	}

	/**
	 * 獲取屬性the sinosoft fax number.
	 * 
	 * @return 屬性the sinosoft fax number的值
	 */
	@Column(name = "FAXNUMBER", length = 20)
	public String getFaxNumber() {
		return this.faxNumber;
	}

	/**
	 * 設置屬性the sinosoft fax number.
	 * 
	 * @param faxNumber
	 *            待設置的the sinosoft fax number的值
	 */
	public void setFaxNumber(String faxNumber) {
		this.faxNumber = faxNumber;
	}

	/**
	 * 獲取屬性the sinosoft insurer name.
	 * 
	 * @return 屬性the sinosoft insurer name的值
	 */
	@Column(name = "INSURERNAME", length = 80)
	public String getInsurerName() {
		return this.insurerName;
	}

	/**
	 * 設置屬性the sinosoft insurer name.
	 * 
	 * @param insurerName
	 *            待設置的the sinosoft insurer name的值
	 */
	public void setInsurerName(String insurerName) {
		this.insurerName = insurerName;
	}

	/**
	 * 獲取屬性the sinosoft com attribute.
	 * 
	 * @return 屬性the sinosoft com attribute的值
	 */
	@Column(name = "COMATTRIBUTE", length = 1)
	public String getComAttribute() {
		return this.comAttribute;
	}

	/**
	 * 設置屬性the sinosoft com attribute.
	 * 
	 * @param comAttribute
	 *            待設置的the sinosoft com attribute的值
	 */
	public void setComAttribute(String comAttribute) {
		this.comAttribute = comAttribute;
	}

	/**
	 * 獲取屬性the sinosoft com type.
	 * 
	 * @return 屬性the sinosoft com type的值
	 */
	@Column(name = "COMTYPE", length = 10)
	public String getComType() {
		return this.comType;
	}

	/**
	 * 設置屬性the sinosoft com type.
	 * 
	 * @param comType
	 *            待設置的the sinosoft com type的值
	 */
	public void setComType(String comType) {
		this.comType = comType;
	}

	/**
	 * 獲取屬性the sinosoft com level.
	 * 
	 * @return 屬性the sinosoft com level的值
	 */
	@Column(name = "COMLEVEL", length = 1)
	public String getComLevel() {
		return this.comLevel;
	}

	/**
	 * 設置屬性the sinosoft com level.
	 * 
	 * @param comLevel
	 *            待設置的the sinosoft com level的值
	 */
	public void setComLevel(String comLevel) {
		this.comLevel = comLevel;
	}

	/**
	 * 獲取屬性the sinosoft manager.
	 * 
	 * @return 屬性the sinosoft manager的值
	 */
	@Column(name = "MANAGER", length = 18)
	public String getManager() {
		return this.manager;
	}

	/**
	 * 設置屬性the sinosoft manager.
	 * 
	 * @param manager
	 *            待設置的the sinosoft manager的值
	 */
	public void setManager(String manager) {
		this.manager = manager;
	}

	/**
	 * 獲取屬性the sinosoft account leader.
	 * 
	 * @return 屬性the sinosoft account leader的值
	 */
	@Column(name = "ACCOUNTLEADER", length = 8)
	public String getAccountLeader() {
		return this.accountLeader;
	}

	/**
	 * 設置屬性the sinosoft account leader.
	 * 
	 * @param accountLeader
	 *            待設置的the sinosoft account leader的值
	 */
	public void setAccountLeader(String accountLeader) {
		this.accountLeader = accountLeader;
	}

	/**
	 * 獲取屬性the sinosoft cashier.
	 * 
	 * @return 屬性the sinosoft cashier的值
	 */
	@Column(name = "CASHIER", length = 8)
	public String getCashier() {
		return this.cashier;
	}

	/**
	 * 設置屬性the sinosoft cashier.
	 * 
	 * @param cashier
	 *            待設置的the sinosoft cashier的值
	 */
	public void setCashier(String cashier) {
		this.cashier = cashier;
	}

	/**
	 * 獲取屬性the sinosoft account ant.
	 * 
	 * @return 屬性the sinosoft account ant的值
	 */
	@Column(name = "ACCOUNTANT", length = 8)
	public String getAccountAnt() {
		return this.accountAnt;
	}

	/**
	 * 設置屬性the sinosoft account ant.
	 * 
	 * @param accountAnt
	 *            待設置的the sinosoft account ant的值
	 */
	public void setAccountAnt(String accountAnt) {
		this.accountAnt = accountAnt;
	}

	/**
	 * 獲取屬性the sinosoft remark.
	 * 
	 * @return 屬性the sinosoft remark的值
	 */
	@Column(name = "REMARK", length = 500)
	public String getRemark() {
		return this.remark;
	}

	/**
	 * 設置屬性the sinosoft remark.
	 * 
	 * @param remark
	 *            待設置的the sinosoft remark的值
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * 獲取屬性the sinosoft new com code.
	 * 
	 * @return 屬性the sinosoft new com code的值
	 */
	@Column(name = "NEWCOMCODE", nullable = false, length = 10)
	public String getNewComCode() {
		return this.newComCode;
	}

	/**
	 * 設置屬性the sinosoft new com code.
	 * 
	 * @param newComCode
	 *            待設置的the sinosoft new com code的值
	 */
	public void setNewComCode(String newComCode) {
		this.newComCode = newComCode;
	}

	/**
	 * 獲取屬性the sinosoft valid status.
	 * 
	 * @return 屬性the sinosoft valid status的值
	 */
	@Column(name = "VALIDSTATUS", nullable = false, length = 1)
	public String getValidStatus() {
		return this.validStatus;
	}

	/**
	 * 設置屬性the sinosoft valid status.
	 * 
	 * @param validStatus
	 *            待設置的the sinosoft valid status的值
	 */
	public void setValidStatus(String validStatus) {
		this.validStatus = validStatus;
	}

	/**
	 * 獲取屬性the sinosoft acnt unit.
	 * 
	 * @return 屬性the sinosoft acnt unit的值
	 */
	@Column(name = "ACNTUNIT", length = 8)
	public String getAcntUnit() {
		return this.acntUnit;
	}

	/**
	 * 設置屬性the sinosoft acnt unit.
	 * 
	 * @param acntUnit
	 *            待設置的the sinosoft acnt unit的值
	 */
	public void setAcntUnit(String acntUnit) {
		this.acntUnit = acntUnit;
	}

	/**
	 * 獲取屬性the sinosoft article code.
	 * 
	 * @return 屬性the sinosoft article code的值
	 */
	@Column(name = "ARTICLECODE", length = 12)
	public String getArticleCode() {
		return this.articleCode;
	}

	/**
	 * 設置屬性the sinosoft article code.
	 * 
	 * @param articleCode
	 *            待設置的the sinosoft article code的值
	 */
	public void setArticleCode(String articleCode) {
		this.articleCode = articleCode;
	}

	/**
	 * 獲取屬性the sinosoft acc code.
	 * 
	 * @return 屬性the sinosoft acc code的值
	 */
	@Column(name = "ACCCODE", length = 6)
	public String getAccCode() {
		return this.accCode;
	}

	/**
	 * 設置屬性the sinosoft acc code.
	 * 
	 * @param accCode
	 *            待設置的the sinosoft acc code的值
	 */
	public void setAccCode(String accCode) {
		this.accCode = accCode;
	}

	/**
	 * 獲取屬性the sinosoft center flag.
	 * 
	 * @return 屬性the sinosoft center flag的值
	 */
	@Column(name = "CENTERFLAG", length = 1)
	public String getCenterFlag() {
		return this.centerFlag;
	}

	/**
	 * 設置屬性the sinosoft center flag.
	 * 
	 * @param centerFlag
	 *            待設置的the sinosoft center flag的值
	 */
	public void setCenterFlag(String centerFlag) {
		this.centerFlag = centerFlag;
	}

	/**
	 * 獲取屬性the sinosoft outer pay code.
	 * 
	 * @return 屬性the sinosoft outer pay code的值
	 */
	@Column(name = "OUTERPAYCODE", length = 8)
	public String getOuterPayCode() {
		return this.outerPayCode;
	}

	/**
	 * 設置屬性the sinosoft outer pay code.
	 * 
	 * @param outerPayCode
	 *            待設置的the sinosoft outer pay code的值
	 */
	public void setOuterPayCode(String outerPayCode) {
		this.outerPayCode = outerPayCode;
	}

	/**
	 * 獲取屬性the sinosoft inner pay code.
	 * 
	 * @return 屬性the sinosoft inner pay code的值
	 */
	@Column(name = "INNERPAYCODE", length = 8)
	public String getInnerPayCode() {
		return this.innerPayCode;
	}

	/**
	 * 設置屬性the sinosoft inner pay code.
	 * 
	 * @param innerPayCode
	 *            待設置的the sinosoft inner pay code的值
	 */
	public void setInnerPayCode(String innerPayCode) {
		this.innerPayCode = innerPayCode;
	}

	/**
	 * 獲取屬性標志.
	 * 
	 * @return 屬性標志的值
	 */
	@Column(name = "FLAG", length = 2)
	public String getFlag() {
		return this.flag;
	}

	/**
	 * 設置屬性標志.
	 * 
	 * @param flag
	 *            待設置的標志的值
	 */
	public void setFlag(String flag) {
		this.flag = flag;
	}

	/**
	 * 獲取屬性the sinosoft web address.
	 * 
	 * @return 屬性the sinosoft web address的值
	 */
	@Column(name = "WEBADDRESS", length = 30)
	public String getWebAddress() {
		return this.webAddress;
	}

	/**
	 * 設置屬性the sinosoft web address.
	 * 
	 * @param webAddress
	 *            待設置的the sinosoft web address的值
	 */
	public void setWebAddress(String webAddress) {
		this.webAddress = webAddress;
	}

	/**
	 * 獲取屬性the sinosoft service phone.
	 * 
	 * @return 屬性the sinosoft service phone的值
	 */
	@Column(name = "SERVICEPHONE", length = 20)
	public String getServicePhone() {
		return this.servicePhone;
	}

	/**
	 * 設置屬性the sinosoft service phone.
	 * 
	 * @param servicePhone
	 *            待設置的the sinosoft service phone的值
	 */
	public void setServicePhone(String servicePhone) {
		this.servicePhone = servicePhone;
	}

	/**
	 * 獲取屬性the sinosoft report phone.
	 * 
	 * @return 屬性the sinosoft report phone的值
	 */
	@Column(name = "REPORTPHONE", length = 20)
	public String getReportPhone() {
		return this.reportPhone;
	}

	/**
	 * 設置屬性the sinosoft report phone.
	 * 
	 * @param reportPhone
	 *            待設置的the sinosoft report phone的值
	 */
	public void setReportPhone(String reportPhone) {
		this.reportPhone = reportPhone;
	}

	/**
	 * 獲取屬性the sinosoft agent code.
	 * 
	 * @return 屬性the sinosoft agent code的值
	 */
	@Column(name = "AGENTCODE", length = 30)
	public String getAgentCode() {
		return this.agentCode;
	}

	/**
	 * 設置屬性the sinosoft agent code.
	 * 
	 * @param agentCode
	 *            待設置的the sinosoft agent code的值
	 */
	public void setAgentCode(String agentCode) {
		this.agentCode = agentCode;
	}

	/**
	 * 獲取屬性the sinosoft agreement no.
	 * 
	 * @return 屬性the sinosoft agreement no的值
	 */
	@Column(name = "AGREEMENTNO", length = 20)
	public String getAgreementNo() {
		return this.agreementNo;
	}

	/**
	 * 設置屬性the sinosoft agreement no.
	 * 
	 * @param agreementNo
	 *            待設置的the sinosoft agreement no的值
	 */
	public void setAgreementNo(String agreementNo) {
		this.agreementNo = agreementNo;
	}

	/**
	 * 獲取屬性the sinosoft sys area code.
	 * 
	 * @return 屬性the sinosoft sys area code的值
	 */
	@Column(name = "SYSAREACODE", length = 6)
	public String getSysAreaCode() {
		return this.sysAreaCode;
	}

	/**
	 * 設置屬性the sinosoft sys area code.
	 * 
	 * @param sysAreaCode
	 *            待設置的the sinosoft sys area code的值
	 */
	public void setSysAreaCode(String sysAreaCode) {
		this.sysAreaCode = sysAreaCode;
	}

	/**
	 * 獲取屬性the sinosoft comb visit rate.
	 * 
	 * @return 屬性the sinosoft comb visit rate的值
	 */
	@Column(name = "COMBVISITRATE", precision = 4, scale = 1)
	public Double getCombVisitRate() {
		return this.combVisitRate;
	}

	/**
	 * 設置屬性the sinosoft comb visit rate.
	 * 
	 * @param combVisitRate
	 *            待設置的the sinosoft comb visit rate的值
	 */
	public void setCombVisitRate(Double combVisitRate) {
		this.combVisitRate = combVisitRate;
	}

	/**
	 * 獲取屬性the sinosoft prints the com name.
	 * 
	 * @return 屬性the sinosoft prints the com name的值
	 */
	@Column(name = "PRINTCOMNAME")
	public String getPrintComName() {
		return this.printComName;
	}

	/**
	 * 設置屬性the sinosoft prints the com name.
	 * 
	 * @param printComName
	 *            待設置的the sinosoft prints the com name的值
	 */
	public void setPrintComName(String printComName) {
		this.printComName = printComName;
	}

	/**
	 * 獲取屬性the sinosoft prints the address.
	 * 
	 * @return 屬性the sinosoft prints the address的值
	 */
	@Column(name = "PRINTADDRESS")
	public String getPrintAddress() {
		return this.printAddress;
	}

	/**
	 * 設置屬性the sinosoft prints the address.
	 * 
	 * @param printAddress
	 *            待設置的the sinosoft prints the address的值
	 */
	public void setPrintAddress(String printAddress) {
		this.printAddress = printAddress;
	}

	/**
	 * 獲取屬性the sinosoft pring post code.
	 * 
	 * @return 屬性the sinosoft pring post code的值
	 */
	@Column(name = "PRINGPOSTCODE")
	public String getPringPostCode() {
		return this.pringPostCode;
	}

	/**
	 * 設置屬性the sinosoft pring post code.
	 * 
	 * @param pringPostCode
	 *            待設置的the sinosoft pring post code的值
	 */
	public void setPringPostCode(String pringPostCode) {
		this.pringPostCode = pringPostCode;
	}

	/**
	 * 獲取屬性the sinosoft upper claim com code.
	 * 
	 * @return 屬性the sinosoft upper claim com code的值
	 */
	@Column(name = "UPPERCLAIMCOMCODE", length = 10)
	public String getUpperClaimComCode() {
		return this.upperClaimComCode;
	}

	/**
	 * 設置屬性the sinosoft upper claim com code.
	 * 
	 * @param upperClaimComCode
	 *            待設置的the sinosoft upper claim com code的值
	 */
	public void setUpperClaimComCode(String upperClaimComCode) {
		this.upperClaimComCode = upperClaimComCode;
	}

	/**
	 * 獲取屬性the sinosoft sap com code.
	 * 
	 * @return 屬性the sinosoft sap com code的值
	 */
	@Column(name = "SAPCOMCODE", length = 4)
	public String getSapComCode() {
		return this.sapComCode;
	}

	/**
	 * 設置屬性the sinosoft sap com code.
	 * 
	 * @param sapComCode
	 *            待設置的the sinosoft sap com code的值
	 */
	public void setSapComCode(String sapComCode) {
		this.sapComCode = sapComCode;
	}

	/**
	 * 獲取屬性the sinosoft cost center code.
	 * 
	 * @return 屬性the sinosoft cost center code的值
	 */
	@Column(name = "COSTCENTERCODE", length = 10)
	public String getCostCenterCode() {
		return this.costCenterCode;
	}

	/**
	 * 設置屬性the sinosoft cost center code.
	 * 
	 * @param costCenterCode
	 *            待設置的the sinosoft cost center code的值
	 */
	public void setCostCenterCode(String costCenterCode) {
		this.costCenterCode = costCenterCode;
	}

	/**
	 * 獲取屬性the sinosoft group nature.
	 * 
	 * @return 屬性the sinosoft group nature的值
	 */
	@Column(name = "GROUPNATURE", length = 4)
	public String getGroupNature() {
		return this.groupNature;
	}

	/**
	 * 設置屬性the sinosoft group nature.
	 * 
	 * @param groupNature
	 *            待設置的the sinosoft group nature的值
	 */
	public void setGroupNature(String groupNature) {
		this.groupNature = groupNature;
	}

	/**
	 * 獲取屬性the sinosoft group level.
	 * 
	 * @return 屬性the sinosoft group level的值
	 */
	@Column(name = "GROUPLEVEL", length = 4)
	public String getGroupLevel() {
		return this.groupLevel;
	}

	/**
	 * 設置屬性the sinosoft group level.
	 * 
	 * @param groupLevel
	 *            待設置的the sinosoft group level的值
	 */
	public void setGroupLevel(String groupLevel) {
		this.groupLevel = groupLevel;
	}

	/**
	 * 獲取屬性the sinosoft sales channel code.
	 * 
	 * @return 屬性the sinosoft sales channel code的值
	 */
	@Column(name = "SALESCHANNELCODE", length = 30)
	public String getSalesChannelCode() {
		return this.salesChannelCode;
	}

	/**
	 * 設置屬性the sinosoft sales channel code.
	 * 
	 * @param salesChannelCode
	 *            待設置的the sinosoft sales channel code的值
	 */
	public void setSalesChannelCode(String salesChannelCode) {
		this.salesChannelCode = salesChannelCode;
	}

	/**
	 * 獲取屬性the sinosoft group nature detail.
	 * 
	 * @return 屬性the sinosoft group nature detail的值
	 */
	@Column(name = "GROUPNATUREDETAIL")
	public String getGroupNatureDetail() {
		return this.groupNatureDetail;
	}

	/**
	 * 設置屬性the sinosoft group nature detail.
	 * 
	 * @param groupNatureDetail
	 *            待設置的the sinosoft group nature detail的值
	 */
	public void setGroupNatureDetail(String groupNatureDetail) {
		this.groupNatureDetail = groupNatureDetail;
	}

	/**
	 * 獲取屬性the sinosoft taxi den no.
	 * 
	 * @return 屬性the sinosoft taxi den no的值
	 */
	@Column(name = "TAXIDENNO", length = 20)
	public String getTaxiDenNo() {
		return this.taxiDenNo;
	}

	/**
	 * 設置屬性the sinosoft taxi den no.
	 * 
	 * @param taxiDenNo
	 *            待設置的the sinosoft taxi den no的值
	 */
	public void setTaxiDenNo(String taxiDenNo) {
		this.taxiDenNo = taxiDenNo;
	}

	/**
	 * 獲取屬性the sinosoft prp dusers for make com.
	 * 
	 * @return 屬性the sinosoft prp dusers for make com的值
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prpDcompanyByMakeCom")
	public Set<PrpDuser> getPrpDusersForMakeCom() {
		return this.prpDusersForMakeCom;
	}

	/**
	 * 設置屬性the sinosoft prp dusers for make com.
	 * 
	 * @param prpDusersForMakeCom
	 *            待設置的the sinosoft prp dusers for make com的值
	 */
	public void setPrpDusersForMakeCom(Set<PrpDuser> prpDusersForMakeCom) {
		this.prpDusersForMakeCom = prpDusersForMakeCom;
	}

	/**
	 * 獲取屬性the sinosoft prp dcompanies.
	 * 
	 * @return 屬性the sinosoft prp dcompanies的值
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prpDcompany")
	public Set<PrpDcompany> getPrpDcompanies() {
		return this.prpDcompanies;
	}

	/**
	 * 設置屬性the sinosoft prp dcompanies.
	 * 
	 * @param prpDcompanies
	 *            待設置的the sinosoft prp dcompanies的值
	 */
	public void setPrpDcompanies(Set<PrpDcompany> prpDcompanies) {
		this.prpDcompanies = prpDcompanies;
	}

	/**
	 * 獲取屬性the sinosoft prp dusers for comcode.
	 * 
	 * @return 屬性the sinosoft prp dusers for comcode的值
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prpDcompanyByComCode")
	public Set<PrpDuser> getPrpDusersForComcode() {
		return this.prpDusersForComCode;
	}

	/**
	 * 設置屬性the sinosoft prp dusers for comcode.
	 * 
	 * @param prpDusersForComCode
	 *            待設置的the sinosoft prp dusers for comcode的值
	 */
	public void setPrpDusersForComcode(Set<PrpDuser> prpDusersForComCode) {
		this.prpDusersForComCode = prpDusersForComCode;
	}

}
