package com.tlg.msSqlMob.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

/** mantis：MOB0008，處理人員：BJ016，需求單編號：MOB0008 將安達提供的銷帳回饋檔記錄到AC_FILE資料表 */
@SuppressWarnings("serial")
public class AcFile extends IBatisBaseEntity<BigDecimal>{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.transaction_id
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String transactionId;
    
    private String fileName;
    
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.ac001
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String ac001;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.ac002
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String ac002;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.ac003
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String ac003;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.ac004
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String ac004;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.ac005
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String ac005;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.ac006
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String ac006;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.ac007
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String ac007;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.ac008
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String ac008;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.ac009
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String ac009;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.ac010
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String ac010;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.ac011
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String ac011;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.ac012
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String ac012;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.ac013
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String ac013;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.ac014
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String ac014;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.ac015
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String ac015;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.ac016
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String ac016;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.ac017
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String ac017;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.ac018
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String ac018;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.ac019
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String ac019;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.ac020
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String ac020;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.ac021
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String ac021;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.ac022
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String ac022;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.ac023
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String ac023;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.ac024
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String ac024;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.ac025
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String ac025;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.ac026
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String ac026;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.ac027
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String ac027;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.ac028
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String ac028;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.ac029
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String ac029;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.created_by
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.created_time
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.modified_by
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String modifiedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_FILE.modified_time
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private Date modifiedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.transaction_id
     *
     * @return the value of AC_FILE.transaction_id
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.transaction_id
     *
     * @param transactionId the value for AC_FILE.transaction_id
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.ac001
     *
     * @return the value of AC_FILE.ac001
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getAc001() {
        return ac001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.ac001
     *
     * @param ac001 the value for AC_FILE.ac001
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setAc001(String ac001) {
        this.ac001 = ac001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.ac002
     *
     * @return the value of AC_FILE.ac002
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getAc002() {
        return ac002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.ac002
     *
     * @param ac002 the value for AC_FILE.ac002
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setAc002(String ac002) {
        this.ac002 = ac002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.ac003
     *
     * @return the value of AC_FILE.ac003
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getAc003() {
        return ac003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.ac003
     *
     * @param ac003 the value for AC_FILE.ac003
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setAc003(String ac003) {
        this.ac003 = ac003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.ac004
     *
     * @return the value of AC_FILE.ac004
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getAc004() {
        return ac004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.ac004
     *
     * @param ac004 the value for AC_FILE.ac004
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setAc004(String ac004) {
        this.ac004 = ac004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.ac005
     *
     * @return the value of AC_FILE.ac005
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getAc005() {
        return ac005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.ac005
     *
     * @param ac005 the value for AC_FILE.ac005
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setAc005(String ac005) {
        this.ac005 = ac005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.ac006
     *
     * @return the value of AC_FILE.ac006
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getAc006() {
        return ac006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.ac006
     *
     * @param ac006 the value for AC_FILE.ac006
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setAc006(String ac006) {
        this.ac006 = ac006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.ac007
     *
     * @return the value of AC_FILE.ac007
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getAc007() {
        return ac007;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.ac007
     *
     * @param ac007 the value for AC_FILE.ac007
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setAc007(String ac007) {
        this.ac007 = ac007;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.ac008
     *
     * @return the value of AC_FILE.ac008
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getAc008() {
        return ac008;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.ac008
     *
     * @param ac008 the value for AC_FILE.ac008
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setAc008(String ac008) {
        this.ac008 = ac008;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.ac009
     *
     * @return the value of AC_FILE.ac009
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getAc009() {
        return ac009;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.ac009
     *
     * @param ac009 the value for AC_FILE.ac009
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setAc009(String ac009) {
        this.ac009 = ac009;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.ac010
     *
     * @return the value of AC_FILE.ac010
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getAc010() {
        return ac010;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.ac010
     *
     * @param ac010 the value for AC_FILE.ac010
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setAc010(String ac010) {
        this.ac010 = ac010;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.ac011
     *
     * @return the value of AC_FILE.ac011
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getAc011() {
        return ac011;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.ac011
     *
     * @param ac011 the value for AC_FILE.ac011
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setAc011(String ac011) {
        this.ac011 = ac011;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.ac012
     *
     * @return the value of AC_FILE.ac012
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getAc012() {
        return ac012;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.ac012
     *
     * @param ac012 the value for AC_FILE.ac012
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setAc012(String ac012) {
        this.ac012 = ac012;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.ac013
     *
     * @return the value of AC_FILE.ac013
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getAc013() {
        return ac013;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.ac013
     *
     * @param ac013 the value for AC_FILE.ac013
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setAc013(String ac013) {
        this.ac013 = ac013;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.ac014
     *
     * @return the value of AC_FILE.ac014
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getAc014() {
        return ac014;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.ac014
     *
     * @param ac014 the value for AC_FILE.ac014
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setAc014(String ac014) {
        this.ac014 = ac014;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.ac015
     *
     * @return the value of AC_FILE.ac015
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getAc015() {
        return ac015;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.ac015
     *
     * @param ac015 the value for AC_FILE.ac015
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setAc015(String ac015) {
        this.ac015 = ac015;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.ac016
     *
     * @return the value of AC_FILE.ac016
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getAc016() {
        return ac016;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.ac016
     *
     * @param ac016 the value for AC_FILE.ac016
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setAc016(String ac016) {
        this.ac016 = ac016;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.ac017
     *
     * @return the value of AC_FILE.ac017
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getAc017() {
        return ac017;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.ac017
     *
     * @param ac017 the value for AC_FILE.ac017
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setAc017(String ac017) {
        this.ac017 = ac017;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.ac018
     *
     * @return the value of AC_FILE.ac018
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getAc018() {
        return ac018;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.ac018
     *
     * @param ac018 the value for AC_FILE.ac018
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setAc018(String ac018) {
        this.ac018 = ac018;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.ac019
     *
     * @return the value of AC_FILE.ac019
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getAc019() {
        return ac019;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.ac019
     *
     * @param ac019 the value for AC_FILE.ac019
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setAc019(String ac019) {
        this.ac019 = ac019;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.ac020
     *
     * @return the value of AC_FILE.ac020
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getAc020() {
        return ac020;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.ac020
     *
     * @param ac020 the value for AC_FILE.ac020
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setAc020(String ac020) {
        this.ac020 = ac020;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.ac021
     *
     * @return the value of AC_FILE.ac021
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getAc021() {
        return ac021;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.ac021
     *
     * @param ac021 the value for AC_FILE.ac021
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setAc021(String ac021) {
        this.ac021 = ac021;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.ac022
     *
     * @return the value of AC_FILE.ac022
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getAc022() {
        return ac022;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.ac022
     *
     * @param ac022 the value for AC_FILE.ac022
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setAc022(String ac022) {
        this.ac022 = ac022;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.ac023
     *
     * @return the value of AC_FILE.ac023
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getAc023() {
        return ac023;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.ac023
     *
     * @param ac023 the value for AC_FILE.ac023
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setAc023(String ac023) {
        this.ac023 = ac023;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.ac024
     *
     * @return the value of AC_FILE.ac024
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getAc024() {
        return ac024;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.ac024
     *
     * @param ac024 the value for AC_FILE.ac024
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setAc024(String ac024) {
        this.ac024 = ac024;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.ac025
     *
     * @return the value of AC_FILE.ac025
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getAc025() {
        return ac025;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.ac025
     *
     * @param ac025 the value for AC_FILE.ac025
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setAc025(String ac025) {
        this.ac025 = ac025;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.ac026
     *
     * @return the value of AC_FILE.ac026
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getAc026() {
        return ac026;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.ac026
     *
     * @param ac026 the value for AC_FILE.ac026
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setAc026(String ac026) {
        this.ac026 = ac026;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.ac027
     *
     * @return the value of AC_FILE.ac027
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getAc027() {
        return ac027;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.ac027
     *
     * @param ac027 the value for AC_FILE.ac027
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setAc027(String ac027) {
        this.ac027 = ac027;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.ac028
     *
     * @return the value of AC_FILE.ac028
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getAc028() {
        return ac028;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.ac028
     *
     * @param ac028 the value for AC_FILE.ac028
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setAc028(String ac028) {
        this.ac028 = ac028;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.ac029
     *
     * @return the value of AC_FILE.ac029
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getAc029() {
        return ac029;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.ac029
     *
     * @param ac029 the value for AC_FILE.ac029
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setAc029(String ac029) {
        this.ac029 = ac029;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.created_by
     *
     * @return the value of AC_FILE.created_by
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.created_by
     *
     * @param createdBy the value for AC_FILE.created_by
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.created_time
     *
     * @return the value of AC_FILE.created_time
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.created_time
     *
     * @param createdTime the value for AC_FILE.created_time
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.modified_by
     *
     * @return the value of AC_FILE.modified_by
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.modified_by
     *
     * @param modifiedBy the value for AC_FILE.modified_by
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_FILE.modified_time
     *
     * @return the value of AC_FILE.modified_time
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_FILE.modified_time
     *
     * @param modifiedTime the value for AC_FILE.modified_time
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
}