package com.tlg.msSqlMob.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

/** mantis：MOB0008，處理人員：BJ016，需求單編號：MOB0008 將安達提供的佣金回饋檔記錄到CM_FILE資料表 */
@SuppressWarnings("serial")
public class CmFile extends IBatisBaseEntity<BigDecimal>{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.transaction_id
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String transactionId;
    
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm001
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm001;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm002
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm002;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm003
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm003;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm004
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm004;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm005
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm005;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm006
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm006;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm007
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm007;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm008
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm008;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm009
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm009;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm010
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm010;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm011
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm011;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm012
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm012;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm013
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm013;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm014
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm014;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm015
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm015;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm016
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm016;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm017
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm017;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm018
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm018;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm019
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm019;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm020
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm020;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm021
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm021;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm022
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm022;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm023
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm023;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm024
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm024;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm025
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm025;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm026
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm026;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm027
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm027;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm028
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm028;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm029
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm029;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm030
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm030;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm031
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm031;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm032
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm032;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm033
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm033;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm034
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm034;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm035
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm035;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm036
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm036;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.cm037
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String cm037;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.created_by
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.created_time
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.modified_by
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private String modifiedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CM_FILE.modified_time
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    private Date modifiedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.transaction_id
     *
     * @return the value of CM_FILE.transaction_id
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.transaction_id
     *
     * @param transactionId the value for CM_FILE.transaction_id
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm001
     *
     * @return the value of CM_FILE.cm001
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm001() {
        return cm001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm001
     *
     * @param cm001 the value for CM_FILE.cm001
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm001(String cm001) {
        this.cm001 = cm001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm002
     *
     * @return the value of CM_FILE.cm002
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm002() {
        return cm002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm002
     *
     * @param cm002 the value for CM_FILE.cm002
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm002(String cm002) {
        this.cm002 = cm002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm003
     *
     * @return the value of CM_FILE.cm003
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm003() {
        return cm003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm003
     *
     * @param cm003 the value for CM_FILE.cm003
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm003(String cm003) {
        this.cm003 = cm003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm004
     *
     * @return the value of CM_FILE.cm004
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm004() {
        return cm004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm004
     *
     * @param cm004 the value for CM_FILE.cm004
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm004(String cm004) {
        this.cm004 = cm004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm005
     *
     * @return the value of CM_FILE.cm005
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm005() {
        return cm005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm005
     *
     * @param cm005 the value for CM_FILE.cm005
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm005(String cm005) {
        this.cm005 = cm005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm006
     *
     * @return the value of CM_FILE.cm006
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm006() {
        return cm006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm006
     *
     * @param cm006 the value for CM_FILE.cm006
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm006(String cm006) {
        this.cm006 = cm006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm007
     *
     * @return the value of CM_FILE.cm007
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm007() {
        return cm007;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm007
     *
     * @param cm007 the value for CM_FILE.cm007
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm007(String cm007) {
        this.cm007 = cm007;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm008
     *
     * @return the value of CM_FILE.cm008
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm008() {
        return cm008;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm008
     *
     * @param cm008 the value for CM_FILE.cm008
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm008(String cm008) {
        this.cm008 = cm008;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm009
     *
     * @return the value of CM_FILE.cm009
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm009() {
        return cm009;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm009
     *
     * @param cm009 the value for CM_FILE.cm009
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm009(String cm009) {
        this.cm009 = cm009;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm010
     *
     * @return the value of CM_FILE.cm010
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm010() {
        return cm010;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm010
     *
     * @param cm010 the value for CM_FILE.cm010
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm010(String cm010) {
        this.cm010 = cm010;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm011
     *
     * @return the value of CM_FILE.cm011
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm011() {
        return cm011;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm011
     *
     * @param cm011 the value for CM_FILE.cm011
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm011(String cm011) {
        this.cm011 = cm011;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm012
     *
     * @return the value of CM_FILE.cm012
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm012() {
        return cm012;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm012
     *
     * @param cm012 the value for CM_FILE.cm012
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm012(String cm012) {
        this.cm012 = cm012;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm013
     *
     * @return the value of CM_FILE.cm013
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm013() {
        return cm013;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm013
     *
     * @param cm013 the value for CM_FILE.cm013
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm013(String cm013) {
        this.cm013 = cm013;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm014
     *
     * @return the value of CM_FILE.cm014
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm014() {
        return cm014;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm014
     *
     * @param cm014 the value for CM_FILE.cm014
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm014(String cm014) {
        this.cm014 = cm014;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm015
     *
     * @return the value of CM_FILE.cm015
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm015() {
        return cm015;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm015
     *
     * @param cm015 the value for CM_FILE.cm015
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm015(String cm015) {
        this.cm015 = cm015;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm016
     *
     * @return the value of CM_FILE.cm016
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm016() {
        return cm016;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm016
     *
     * @param cm016 the value for CM_FILE.cm016
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm016(String cm016) {
        this.cm016 = cm016;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm017
     *
     * @return the value of CM_FILE.cm017
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm017() {
        return cm017;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm017
     *
     * @param cm017 the value for CM_FILE.cm017
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm017(String cm017) {
        this.cm017 = cm017;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm018
     *
     * @return the value of CM_FILE.cm018
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm018() {
        return cm018;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm018
     *
     * @param cm018 the value for CM_FILE.cm018
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm018(String cm018) {
        this.cm018 = cm018;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm019
     *
     * @return the value of CM_FILE.cm019
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm019() {
        return cm019;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm019
     *
     * @param cm019 the value for CM_FILE.cm019
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm019(String cm019) {
        this.cm019 = cm019;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm020
     *
     * @return the value of CM_FILE.cm020
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm020() {
        return cm020;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm020
     *
     * @param cm020 the value for CM_FILE.cm020
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm020(String cm020) {
        this.cm020 = cm020;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm021
     *
     * @return the value of CM_FILE.cm021
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm021() {
        return cm021;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm021
     *
     * @param cm021 the value for CM_FILE.cm021
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm021(String cm021) {
        this.cm021 = cm021;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm022
     *
     * @return the value of CM_FILE.cm022
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm022() {
        return cm022;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm022
     *
     * @param cm022 the value for CM_FILE.cm022
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm022(String cm022) {
        this.cm022 = cm022;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm023
     *
     * @return the value of CM_FILE.cm023
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm023() {
        return cm023;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm023
     *
     * @param cm023 the value for CM_FILE.cm023
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm023(String cm023) {
        this.cm023 = cm023;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm024
     *
     * @return the value of CM_FILE.cm024
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm024() {
        return cm024;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm024
     *
     * @param cm024 the value for CM_FILE.cm024
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm024(String cm024) {
        this.cm024 = cm024;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm025
     *
     * @return the value of CM_FILE.cm025
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm025() {
        return cm025;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm025
     *
     * @param cm025 the value for CM_FILE.cm025
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm025(String cm025) {
        this.cm025 = cm025;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm026
     *
     * @return the value of CM_FILE.cm026
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm026() {
        return cm026;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm026
     *
     * @param cm026 the value for CM_FILE.cm026
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm026(String cm026) {
        this.cm026 = cm026;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm027
     *
     * @return the value of CM_FILE.cm027
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm027() {
        return cm027;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm027
     *
     * @param cm027 the value for CM_FILE.cm027
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm027(String cm027) {
        this.cm027 = cm027;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm028
     *
     * @return the value of CM_FILE.cm028
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm028() {
        return cm028;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm028
     *
     * @param cm028 the value for CM_FILE.cm028
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm028(String cm028) {
        this.cm028 = cm028;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm029
     *
     * @return the value of CM_FILE.cm029
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm029() {
        return cm029;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm029
     *
     * @param cm029 the value for CM_FILE.cm029
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm029(String cm029) {
        this.cm029 = cm029;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm030
     *
     * @return the value of CM_FILE.cm030
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm030() {
        return cm030;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm030
     *
     * @param cm030 the value for CM_FILE.cm030
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm030(String cm030) {
        this.cm030 = cm030;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm031
     *
     * @return the value of CM_FILE.cm031
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm031() {
        return cm031;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm031
     *
     * @param cm031 the value for CM_FILE.cm031
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm031(String cm031) {
        this.cm031 = cm031;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm032
     *
     * @return the value of CM_FILE.cm032
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm032() {
        return cm032;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm032
     *
     * @param cm032 the value for CM_FILE.cm032
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm032(String cm032) {
        this.cm032 = cm032;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm033
     *
     * @return the value of CM_FILE.cm033
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm033() {
        return cm033;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm033
     *
     * @param cm033 the value for CM_FILE.cm033
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm033(String cm033) {
        this.cm033 = cm033;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm034
     *
     * @return the value of CM_FILE.cm034
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm034() {
        return cm034;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm034
     *
     * @param cm034 the value for CM_FILE.cm034
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm034(String cm034) {
        this.cm034 = cm034;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm035
     *
     * @return the value of CM_FILE.cm035
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm035() {
        return cm035;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm035
     *
     * @param cm035 the value for CM_FILE.cm035
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm035(String cm035) {
        this.cm035 = cm035;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm036
     *
     * @return the value of CM_FILE.cm036
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm036() {
        return cm036;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm036
     *
     * @param cm036 the value for CM_FILE.cm036
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm036(String cm036) {
        this.cm036 = cm036;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.cm037
     *
     * @return the value of CM_FILE.cm037
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCm037() {
        return cm037;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.cm037
     *
     * @param cm037 the value for CM_FILE.cm037
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCm037(String cm037) {
        this.cm037 = cm037;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.created_by
     *
     * @return the value of CM_FILE.created_by
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.created_by
     *
     * @param createdBy the value for CM_FILE.created_by
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.created_time
     *
     * @return the value of CM_FILE.created_time
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.created_time
     *
     * @param createdTime the value for CM_FILE.created_time
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.modified_by
     *
     * @return the value of CM_FILE.modified_by
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.modified_by
     *
     * @param modifiedBy the value for CM_FILE.modified_by
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_FILE.modified_time
     *
     * @return the value of CM_FILE.modified_time
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_FILE.modified_time
     *
     * @param modifiedTime the value for CM_FILE.modified_time
     *
     * @mbg.generated Wed May 17 11:13:04 CST 2023
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}
}