package com.tlg.msSqlMob.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

/** mantis：MOB0001，處理人員：CC009，需求單編號：MOB0001 遠傳手機保險投保&批改作業 */
@SuppressWarnings("serial")
public class ExtCol extends IBatisBaseEntity<BigDecimal>{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_COL.transaction_id
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    private String transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_COL.rpt_batch_no
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    private String rptBatchNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_COL.contract_id
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    private String contractId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_COL.application_id
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    private String applicationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_COL.key
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    private String objectKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_COL.value
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_COL.created_by
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_COL.created_time
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_COL.modified_by
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    private String modifiedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_COL.modified_time
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    private Date modifiedTime;
    
    @Override
	public String toString() {
		return "ExtCol [transactionId=" + transactionId + ", rptBatchNo=" + rptBatchNo + ", contractId=" + contractId
				+ ", applicationId=" + applicationId + ", objectKey=" + objectKey + ", value=" + value + ", createdBy=" + createdBy
				+ ", createdTime=" + createdTime + ", modifiedBy=" + modifiedBy + ", modifiedTime=" + modifiedTime
				+ "]";
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_COL.transaction_id
     *
     * @return the value of EXT_COL.transaction_id
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_COL.transaction_id
     *
     * @param transactionId the value for EXT_COL.transaction_id
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_COL.rpt_batch_no
     *
     * @return the value of EXT_COL.rpt_batch_no
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public String getRptBatchNo() {
        return rptBatchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_COL.rpt_batch_no
     *
     * @param rptBatchNo the value for EXT_COL.rpt_batch_no
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public void setRptBatchNo(String rptBatchNo) {
        this.rptBatchNo = rptBatchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_COL.contract_id
     *
     * @return the value of EXT_COL.contract_id
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public String getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_COL.contract_id
     *
     * @param contractId the value for EXT_COL.contract_id
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public void setContractId(String contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_COL.application_id
     *
     * @return the value of EXT_COL.application_id
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public String getApplicationId() {
        return applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_COL.application_id
     *
     * @param applicationId the value for EXT_COL.application_id
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public void setApplicationId(String applicationId) {
        this.applicationId = applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_COL.key
     *
     * @return the value of EXT_COL.key
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public String getObjectKey() {
        return objectKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_COL.key
     *
     * @param key the value for EXT_COL.key
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public void setObjectKey(String objectKey) {
        this.objectKey = objectKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_COL.value
     *
     * @return the value of EXT_COL.value
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_COL.value
     *
     * @param value the value for EXT_COL.value
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_COL.created_by
     *
     * @return the value of EXT_COL.created_by
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_COL.created_by
     *
     * @param createdBy the value for EXT_COL.created_by
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_COL.created_time
     *
     * @return the value of EXT_COL.created_time
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_COL.created_time
     *
     * @param createdTime the value for EXT_COL.created_time
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_COL.modified_by
     *
     * @return the value of EXT_COL.modified_by
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_COL.modified_by
     *
     * @param modifiedBy the value for EXT_COL.modified_by
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_COL.modified_time
     *
     * @return the value of EXT_COL.modified_time
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_COL.modified_time
     *
     * @param modifiedTime the value for EXT_COL.modified_time
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }
}