package com.tlg.msSqlMob.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.tlg.iBatis.IBatisBaseEntity;

/** mantis：MOB0020，處理人員：BI086，需求單編號：MOB0020 理賠盜打詐騙API及XML作業 */
@SuppressWarnings("serial")
public class FetclaimTypecm extends IBatisBaseEntity<BigDecimal> {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.OID
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonIgnore
	private BigDecimal oid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.MTN_NO
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonProperty("MTN_NO")
	private String mtnNo;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.CONTRACT_ID
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonProperty("CONTRACT_ID")
	private String contractId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.MATNR_NO
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonProperty("MATNR_NO")
	private String matnrNo;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.IMEI
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonProperty("IMEI")
	private String imei;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.CLAIM_TYPE
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonProperty("CLAIM_TYPE")
	private String claimType;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.NOTIF_DATE
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonProperty("NOTIF_DATE")
	private String notifDate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.LISTPRICE1
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonProperty("LISTPRICE1")
	private Integer listprice1;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.CAUSE_DESCRIPTION1
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonProperty("CAUSE_DESCRIPTION1")
	private String causeDescription1;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.FINAL_AUTH
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonProperty("FINAL_AUTH")
	private String finalAuth;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.SPECIAL_APPROVAL
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonProperty("SPECIAL_APPROVAL")
	private String specialApproval;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.EVENT_DATE
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonProperty("EVENT_DATE")
	private String eventDate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.EVENT_CAUSE
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonProperty("EVENT_CAUSE")
	private String eventCause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.POLICY_NO
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonProperty("POLICY_NO")
	private String policyNo;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.ASU_CLAIM_AMOUNT
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonProperty("ASU_CLAIM_AMOUNT")
	private Integer asuClaimAmount;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.ER_DATE
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonProperty("ER_DATE")
	private String erDate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.FINISH_DATE
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonProperty("FINISH_DATE")
	private String finishDate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.PART_DESCRIPTION1
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonProperty("PART_DESCRIPTION1")
	private String partDescription1;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.PART_DESCRIPTION2
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonProperty("PART_DESCRIPTION2")
	private String partDescription2;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.PART_DESCRIPTION3
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonProperty("PART_DESCRIPTION3")
	private String partDescription3;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.PART_DESCRIPTION4
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonProperty("PART_DESCRIPTION4")
	private String partDescription4;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.PART_DESCRIPTION5
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonProperty("PART_DESCRIPTION5")
	private String partDescription5;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.PART_DESCRIPTION6
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonProperty("PART_DESCRIPTION6")
	private String partDescription6;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.PART_DESCRIPTION7
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonProperty("PART_DESCRIPTION7")
	private String partDescription7;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.PART_DESCRIPTION8
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonProperty("PART_DESCRIPTION8")
	private String partDescription8;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.PART_DESCRIPTION9
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonProperty("PART_DESCRIPTION9")
	private String partDescription9;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.PART_DESCRIPTION10
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonProperty("PART_DESCRIPTION10")
	private String partDescription10;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.API_STATUS
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonIgnore
	private String apiStatus;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.XML_STATUS
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonIgnore
	private String xmlStatus;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.CREATER
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonIgnore
	private String creater;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.CREATDATE
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonIgnore
	private Date creatdate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.ICLAIMNO
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonIgnore
	private String iclaimno;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.RETCODE
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonIgnore
	private String retcode;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column FETCLAIM_TYPECM.MESSAGE
	 * 
	 * @ibatorgenerated Thu Nov 09 10:27:59 CST 2023
	 */
	@JsonIgnore
	private String message;

	public BigDecimal getOid() {
		return oid;
	}

	public void setOid(BigDecimal oid) {
		this.oid = oid;
	}

	public String getMtnNo() {
		return mtnNo;
	}

	public void setMtnNo(String mtnNo) {
		this.mtnNo = mtnNo;
	}

	public String getContractId() {
		return contractId;
	}

	public void setContractId(String contractId) {
		this.contractId = contractId;
	}

	public String getMatnrNo() {
		return matnrNo;
	}

	public void setMatnrNo(String matnrNo) {
		this.matnrNo = matnrNo;
	}

	public String getImei() {
		return imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	public String getClaimType() {
		return claimType;
	}

	public void setClaimType(String claimType) {
		this.claimType = claimType;
	}

	public String getNotifDate() {
		return notifDate;
	}

	public void setNotifDate(String notifDate) {
		this.notifDate = notifDate;
	}

	public Integer getListprice1() {
		return listprice1;
	}

	public void setListprice1(Integer listprice1) {
		this.listprice1 = listprice1;
	}

	public String getCauseDescription1() {
		return causeDescription1;
	}

	public void setCauseDescription1(String causeDescription1) {
		this.causeDescription1 = causeDescription1;
	}

	public String getFinalAuth() {
		return finalAuth;
	}

	public void setFinalAuth(String finalAuth) {
		this.finalAuth = finalAuth;
	}

	public String getSpecialApproval() {
		return specialApproval;
	}

	public void setSpecialApproval(String specialApproval) {
		this.specialApproval = specialApproval;
	}

	public String getEventCause() {
		return eventCause;
	}

	public void setEventCause(String eventCause) {
		this.eventCause = eventCause;
	}

	public String getPolicyNo() {
		return policyNo;
	}

	public void setPolicyNo(String policyNo) {
		this.policyNo = policyNo;
	}

	public Integer getAsuClaimAmount() {
		return asuClaimAmount;
	}

	public void setAsuClaimAmount(Integer asuClaimAmount) {
		this.asuClaimAmount = asuClaimAmount;
	}

	public String getPartDescription1() {
		return partDescription1;
	}

	public void setPartDescription1(String partDescription1) {
		this.partDescription1 = partDescription1;
	}

	public String getPartDescription2() {
		return partDescription2;
	}

	public void setPartDescription2(String partDescription2) {
		this.partDescription2 = partDescription2;
	}

	public String getPartDescription3() {
		return partDescription3;
	}

	public void setPartDescription3(String partDescription3) {
		this.partDescription3 = partDescription3;
	}

	public String getPartDescription4() {
		return partDescription4;
	}

	public void setPartDescription4(String partDescription4) {
		this.partDescription4 = partDescription4;
	}

	public String getPartDescription5() {
		return partDescription5;
	}

	public void setPartDescription5(String partDescription5) {
		this.partDescription5 = partDescription5;
	}

	public String getPartDescription6() {
		return partDescription6;
	}

	public void setPartDescription6(String partDescription6) {
		this.partDescription6 = partDescription6;
	}

	public String getPartDescription7() {
		return partDescription7;
	}

	public void setPartDescription7(String partDescription7) {
		this.partDescription7 = partDescription7;
	}

	public String getPartDescription8() {
		return partDescription8;
	}

	public void setPartDescription8(String partDescription8) {
		this.partDescription8 = partDescription8;
	}

	public String getPartDescription9() {
		return partDescription9;
	}

	public void setPartDescription9(String partDescription9) {
		this.partDescription9 = partDescription9;
	}

	public String getPartDescription10() {
		return partDescription10;
	}

	public void setPartDescription10(String partDescription10) {
		this.partDescription10 = partDescription10;
	}

	public String getApiStatus() {
		return apiStatus;
	}

	public void setApiStatus(String apiStatus) {
		this.apiStatus = apiStatus;
	}

	public String getXmlStatus() {
		return xmlStatus;
	}

	public void setXmlStatus(String xmlStatus) {
		this.xmlStatus = xmlStatus;
	}

	public String getCreater() {
		return creater;
	}

	public void setCreater(String creater) {
		this.creater = creater;
	}

	public Date getCreatdate() {
		return creatdate;
	}

	public void setCreatdate(Date creatdate) {
		this.creatdate = creatdate;
	}

	public String getIclaimno() {
		return iclaimno;
	}

	public void setIclaimno(String iclaimno) {
		this.iclaimno = iclaimno;
	}

	public String getRetcode() {
		return retcode;
	}

	public void setRetcode(String retcode) {
		this.retcode = retcode;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getEventDate() {
		return eventDate;
	}

	public void setEventDate(String eventDate) {
		this.eventDate = eventDate;
	}

	public String getErDate() {
		return erDate;
	}

	public void setErDate(String erDate) {
		this.erDate = erDate;
	}

	public String getFinishDate() {
		return finishDate;
	}

	public void setFinishDate(String finishDate) {
		this.finishDate = finishDate;
	}
}