package com.tlg.msSqlMob.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

public class FetPayable  extends IBatisBaseEntity<BigDecimal>{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FET_PAYABLE.transaction_id
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    private String transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FET_PAYABLE.file_name
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FET_PAYABLE.pb001
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    private String pb001;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FET_PAYABLE.pb002
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    private String pb002;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FET_PAYABLE.pb003
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    private String pb003;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FET_PAYABLE.pb004
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    private String pb004;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FET_PAYABLE.pb005
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    private String pb005;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FET_PAYABLE.pb006
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    private String pb006;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FET_PAYABLE.pb007
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    private String pb007;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FET_PAYABLE.pb008
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    private String pb008;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FET_PAYABLE.created_by
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FET_PAYABLE.created_time
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FET_PAYABLE.modified_by
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    private String modifiedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FET_PAYABLE.modified_time
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    private Date modifiedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FET_PAYABLE.transaction_id
     *
     * @return the value of FET_PAYABLE.transaction_id
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FET_PAYABLE.transaction_id
     *
     * @param transactionId the value for FET_PAYABLE.transaction_id
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FET_PAYABLE.file_name
     *
     * @return the value of FET_PAYABLE.file_name
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FET_PAYABLE.file_name
     *
     * @param fileName the value for FET_PAYABLE.file_name
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FET_PAYABLE.pb001
     *
     * @return the value of FET_PAYABLE.pb001
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    public String getPb001() {
        return pb001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FET_PAYABLE.pb001
     *
     * @param pb001 the value for FET_PAYABLE.pb001
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    public void setPb001(String pb001) {
        this.pb001 = pb001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FET_PAYABLE.pb002
     *
     * @return the value of FET_PAYABLE.pb002
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    public String getPb002() {
        return pb002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FET_PAYABLE.pb002
     *
     * @param pb002 the value for FET_PAYABLE.pb002
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    public void setPb002(String pb002) {
        this.pb002 = pb002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FET_PAYABLE.pb003
     *
     * @return the value of FET_PAYABLE.pb003
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    public String getPb003() {
        return pb003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FET_PAYABLE.pb003
     *
     * @param pb003 the value for FET_PAYABLE.pb003
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    public void setPb003(String pb003) {
        this.pb003 = pb003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FET_PAYABLE.pb004
     *
     * @return the value of FET_PAYABLE.pb004
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    public String getPb004() {
        return pb004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FET_PAYABLE.pb004
     *
     * @param pb004 the value for FET_PAYABLE.pb004
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    public void setPb004(String pb004) {
        this.pb004 = pb004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FET_PAYABLE.pb005
     *
     * @return the value of FET_PAYABLE.pb005
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    public String getPb005() {
        return pb005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FET_PAYABLE.pb005
     *
     * @param pb005 the value for FET_PAYABLE.pb005
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    public void setPb005(String pb005) {
        this.pb005 = pb005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FET_PAYABLE.pb006
     *
     * @return the value of FET_PAYABLE.pb006
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    public String getPb006() {
        return pb006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FET_PAYABLE.pb006
     *
     * @param pb006 the value for FET_PAYABLE.pb006
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    public void setPb006(String pb006) {
        this.pb006 = pb006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FET_PAYABLE.pb007
     *
     * @return the value of FET_PAYABLE.pb007
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    public String getPb007() {
        return pb007;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FET_PAYABLE.pb007
     *
     * @param pb007 the value for FET_PAYABLE.pb007
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    public void setPb007(String pb007) {
        this.pb007 = pb007;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FET_PAYABLE.pb008
     *
     * @return the value of FET_PAYABLE.pb008
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    public String getPb008() {
        return pb008;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FET_PAYABLE.pb008
     *
     * @param pb008 the value for FET_PAYABLE.pb008
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    public void setPb008(String pb008) {
        this.pb008 = pb008;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FET_PAYABLE.created_by
     *
     * @return the value of FET_PAYABLE.created_by
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FET_PAYABLE.created_by
     *
     * @param createdBy the value for FET_PAYABLE.created_by
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FET_PAYABLE.created_time
     *
     * @return the value of FET_PAYABLE.created_time
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FET_PAYABLE.created_time
     *
     * @param createdTime the value for FET_PAYABLE.created_time
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FET_PAYABLE.modified_by
     *
     * @return the value of FET_PAYABLE.modified_by
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FET_PAYABLE.modified_by
     *
     * @param modifiedBy the value for FET_PAYABLE.modified_by
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FET_PAYABLE.modified_time
     *
     * @return the value of FET_PAYABLE.modified_time
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FET_PAYABLE.modified_time
     *
     * @param modifiedTime the value for FET_PAYABLE.modified_time
     *
     * @mbg.generated Fri Dec 22 14:15:18 CST 2023
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }
}