package com.tlg.msSqlMob.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

/** mantis：MOB0001，處理人員：CC009，需求單編號：MOB0001 遠傳手機保險投保&批改作業 */
@SuppressWarnings("serial")
public class MobileInsBatchInfo extends IBatisBaseEntity<BigDecimal>{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE_INS_BATCH_INFO.oid
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    private BigDecimal oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE_INS_BATCH_INFO.batch_date
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    private String batchDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE_INS_BATCH_INFO.batch_status
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    private String batchStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE_INS_BATCH_INFO.batch_check_status
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    private String batchCheckStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE_INS_BATCH_INFO.rpt_batch_no
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    private String rptBatchNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE_INS_BATCH_INFO.total_count
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    private String totalCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE_INS_BATCH_INFO.total_record
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    private String totalRecord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE_INS_BATCH_INFO.created_by
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE_INS_BATCH_INFO.created_time
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE_INS_BATCH_INFO.modified_by
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    private String modifiedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE_INS_BATCH_INFO.modified_time
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE_INS_BATCH_INFO.current_record
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    private String currentRecord;
    /** mantis：MOB0031，處理人員：CE035，需求單編號：MOB0031 行動裝置險estore網投案開發 出單流程 START*/
    private String dataSrc;
    public String getDataSrc() {
        return dataSrc;
    }

    public void setDataSrc(String dataSrc) {
        this.dataSrc = dataSrc == null ? null : dataSrc.trim();
    }
    /** mantis：MOB0031，處理人員：CE035，需求單編號：MOB0031 行動裝置險estore網投案開發 出單流程 END*/

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE_INS_BATCH_INFO.oid
     *
     * @return the value of MOBILE_INS_BATCH_INFO.oid
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public BigDecimal getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE_INS_BATCH_INFO.oid
     *
     * @param oid the value for MOBILE_INS_BATCH_INFO.oid
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public void setOid(BigDecimal oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE_INS_BATCH_INFO.batch_date
     *
     * @return the value of MOBILE_INS_BATCH_INFO.batch_date
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public String getBatchDate() {
        return batchDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE_INS_BATCH_INFO.batch_date
     *
     * @param batchDate the value for MOBILE_INS_BATCH_INFO.batch_date
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public void setBatchDate(String batchDate) {
        this.batchDate = batchDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE_INS_BATCH_INFO.batch_status
     *
     * @return the value of MOBILE_INS_BATCH_INFO.batch_status
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public String getBatchStatus() {
        return batchStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE_INS_BATCH_INFO.batch_status
     *
     * @param batchStatus the value for MOBILE_INS_BATCH_INFO.batch_status
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public void setBatchStatus(String batchStatus) {
        this.batchStatus = batchStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE_INS_BATCH_INFO.batch_check_status
     *
     * @return the value of MOBILE_INS_BATCH_INFO.batch_check_status
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public String getBatchCheckStatus() {
        return batchCheckStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE_INS_BATCH_INFO.batch_check_status
     *
     * @param batchCheckStatus the value for MOBILE_INS_BATCH_INFO.batch_check_status
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public void setBatchCheckStatus(String batchCheckStatus) {
        this.batchCheckStatus = batchCheckStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE_INS_BATCH_INFO.rpt_batch_no
     *
     * @return the value of MOBILE_INS_BATCH_INFO.rpt_batch_no
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public String getRptBatchNo() {
        return rptBatchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE_INS_BATCH_INFO.rpt_batch_no
     *
     * @param rptBatchNo the value for MOBILE_INS_BATCH_INFO.rpt_batch_no
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public void setRptBatchNo(String rptBatchNo) {
        this.rptBatchNo = rptBatchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE_INS_BATCH_INFO.total_count
     *
     * @return the value of MOBILE_INS_BATCH_INFO.total_count
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public String getTotalCount() {
        return totalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE_INS_BATCH_INFO.total_count
     *
     * @param totalCount the value for MOBILE_INS_BATCH_INFO.total_count
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public void setTotalCount(String totalCount) {
        this.totalCount = totalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE_INS_BATCH_INFO.total_record
     *
     * @return the value of MOBILE_INS_BATCH_INFO.total_record
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public String getTotalRecord() {
        return totalRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE_INS_BATCH_INFO.total_record
     *
     * @param totalRecord the value for MOBILE_INS_BATCH_INFO.total_record
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public void setTotalRecord(String totalRecord) {
        this.totalRecord = totalRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE_INS_BATCH_INFO.created_by
     *
     * @return the value of MOBILE_INS_BATCH_INFO.created_by
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE_INS_BATCH_INFO.created_by
     *
     * @param createdBy the value for MOBILE_INS_BATCH_INFO.created_by
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE_INS_BATCH_INFO.created_time
     *
     * @return the value of MOBILE_INS_BATCH_INFO.created_time
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE_INS_BATCH_INFO.created_time
     *
     * @param createdTime the value for MOBILE_INS_BATCH_INFO.created_time
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE_INS_BATCH_INFO.modified_by
     *
     * @return the value of MOBILE_INS_BATCH_INFO.modified_by
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE_INS_BATCH_INFO.modified_by
     *
     * @param modifiedBy the value for MOBILE_INS_BATCH_INFO.modified_by
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE_INS_BATCH_INFO.modified_time
     *
     * @return the value of MOBILE_INS_BATCH_INFO.modified_time
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE_INS_BATCH_INFO.modified_time
     *
     * @param modifiedTime the value for MOBILE_INS_BATCH_INFO.modified_time
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE_INS_BATCH_INFO.current_record
     *
     * @return the value of MOBILE_INS_BATCH_INFO.current_record
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public String getCurrentRecord() {
        return currentRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE_INS_BATCH_INFO.current_record
     *
     * @param currentRecord the value for MOBILE_INS_BATCH_INFO.current_record
     *
     * @mbg.generated Wed May 10 09:34:49 CST 2023
     */
    public void setCurrentRecord(String currentRecord) {
        this.currentRecord = currentRecord;
    }
}