package com.tlg.msSqlMob.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

/** mantis：MOB0003，處理人員：CC009，需求單編號：MOB0003 從遠傳抓取要保書檔作業 */
@SuppressWarnings("serial")
public class ProposalFile extends IBatisBaseEntity<BigDecimal>{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROPOSAL_FILE.transaction_id
     *
     * @mbg.generated Wed May 17 14:17:39 CST 2023
     */
    private String transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROPOSAL_FILE.zip_file_name
     *
     * @mbg.generated Wed May 17 14:17:39 CST 2023
     */
    private String zipFileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROPOSAL_FILE.rpt_batch_no
     *
     * @mbg.generated Wed May 17 14:17:39 CST 2023
     */
    private String rptBatchNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROPOSAL_FILE.application_id
     *
     * @mbg.generated Wed May 17 14:17:39 CST 2023
     */
    private String applicationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROPOSAL_FILE.file_name
     *
     * @mbg.generated Wed May 17 14:17:39 CST 2023
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROPOSAL_FILE.download_date
     *
     * @mbg.generated Wed May 17 14:17:39 CST 2023
     */
    private String downloadDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROPOSAL_FILE.created_by
     *
     * @mbg.generated Wed May 17 14:17:39 CST 2023
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROPOSAL_FILE.created_time
     *
     * @mbg.generated Wed May 17 14:17:39 CST 2023
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROPOSAL_FILE.modified_by
     *
     * @mbg.generated Wed May 17 14:17:39 CST 2023
     */
    private String modifiedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROPOSAL_FILE.modified_time
     *
     * @mbg.generated Wed May 17 14:17:39 CST 2023
     */
    private Date modifiedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROPOSAL_FILE.transaction_id
     *
     * @return the value of PROPOSAL_FILE.transaction_id
     *
     * @mbg.generated Wed May 17 14:17:39 CST 2023
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROPOSAL_FILE.transaction_id
     *
     * @param transactionId the value for PROPOSAL_FILE.transaction_id
     *
     * @mbg.generated Wed May 17 14:17:39 CST 2023
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROPOSAL_FILE.zip_file_name
     *
     * @return the value of PROPOSAL_FILE.zip_file_name
     *
     * @mbg.generated Wed May 17 14:17:39 CST 2023
     */
    public String getZipFileName() {
        return zipFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROPOSAL_FILE.zip_file_name
     *
     * @param zipFileName the value for PROPOSAL_FILE.zip_file_name
     *
     * @mbg.generated Wed May 17 14:17:39 CST 2023
     */
    public void setZipFileName(String zipFileName) {
        this.zipFileName = zipFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROPOSAL_FILE.rpt_batch_no
     *
     * @return the value of PROPOSAL_FILE.rpt_batch_no
     *
     * @mbg.generated Wed May 17 14:17:39 CST 2023
     */
    public String getRptBatchNo() {
        return rptBatchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROPOSAL_FILE.rpt_batch_no
     *
     * @param rptBatchNo the value for PROPOSAL_FILE.rpt_batch_no
     *
     * @mbg.generated Wed May 17 14:17:39 CST 2023
     */
    public void setRptBatchNo(String rptBatchNo) {
        this.rptBatchNo = rptBatchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROPOSAL_FILE.application_id
     *
     * @return the value of PROPOSAL_FILE.application_id
     *
     * @mbg.generated Wed May 17 14:17:39 CST 2023
     */
    public String getApplicationId() {
        return applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROPOSAL_FILE.application_id
     *
     * @param applicationId the value for PROPOSAL_FILE.application_id
     *
     * @mbg.generated Wed May 17 14:17:39 CST 2023
     */
    public void setApplicationId(String applicationId) {
        this.applicationId = applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROPOSAL_FILE.file_name
     *
     * @return the value of PROPOSAL_FILE.file_name
     *
     * @mbg.generated Wed May 17 14:17:39 CST 2023
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROPOSAL_FILE.file_name
     *
     * @param fileName the value for PROPOSAL_FILE.file_name
     *
     * @mbg.generated Wed May 17 14:17:39 CST 2023
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROPOSAL_FILE.download_date
     *
     * @return the value of PROPOSAL_FILE.download_date
     *
     * @mbg.generated Wed May 17 14:17:39 CST 2023
     */
    public String getDownloadDate() {
        return downloadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROPOSAL_FILE.download_date
     *
     * @param downloadDate the value for PROPOSAL_FILE.download_date
     *
     * @mbg.generated Wed May 17 14:17:39 CST 2023
     */
    public void setDownloadDate(String downloadDate) {
        this.downloadDate = downloadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROPOSAL_FILE.created_by
     *
     * @return the value of PROPOSAL_FILE.created_by
     *
     * @mbg.generated Wed May 17 14:17:39 CST 2023
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROPOSAL_FILE.created_by
     *
     * @param createdBy the value for PROPOSAL_FILE.created_by
     *
     * @mbg.generated Wed May 17 14:17:39 CST 2023
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROPOSAL_FILE.created_time
     *
     * @return the value of PROPOSAL_FILE.created_time
     *
     * @mbg.generated Wed May 17 14:17:39 CST 2023
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROPOSAL_FILE.created_time
     *
     * @param createdTime the value for PROPOSAL_FILE.created_time
     *
     * @mbg.generated Wed May 17 14:17:39 CST 2023
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROPOSAL_FILE.modified_by
     *
     * @return the value of PROPOSAL_FILE.modified_by
     *
     * @mbg.generated Wed May 17 14:17:39 CST 2023
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROPOSAL_FILE.modified_by
     *
     * @param modifiedBy the value for PROPOSAL_FILE.modified_by
     *
     * @mbg.generated Wed May 17 14:17:39 CST 2023
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROPOSAL_FILE.modified_time
     *
     * @return the value of PROPOSAL_FILE.modified_time
     *
     * @mbg.generated Wed May 17 14:17:39 CST 2023
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROPOSAL_FILE.modified_time
     *
     * @param modifiedTime the value for PROPOSAL_FILE.modified_time
     *
     * @mbg.generated Wed May 17 14:17:39 CST 2023
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }
}