<script language="Javascript" src="/product/common/js/Common.js" ></script>
<script language="Javascript" src="/product/common/js/CodeSelect.js" ></script>
<script language="Javascript" src="/product/common/js/MulLine.js" ></script>
<script language="Javascript" src="/product/common/js/Process.js" ></script>
<script language="Javascript" src="/product/common/js/productDataDefine.js" ></script>
<script language="Javascript" src="/product/common/js/PlatformDataDefine.js" ></script>
<script language="Javascript" src="/product/common/js/CustomDataDefine.js" ></script>
<script language="Javascript" src="/product/common/js/Application.js" ></script>
<script language="Javascript" src="/product/common/js/PopCalendarB.js" ></script>
<script language="Javascript" src="/product/common/js/SpecialValidate.js" ></script>
<script language="Javascript" src="/product/common/js/SpecialValidateDataDefine.js" ></script>
<script language="Javascript" src="/product/common/js/sortabletable.js" ></script>
<script language="Javascript" src="/product/common/js/PrpAll/UICommon.js" ></script>
<script language="Javascript" src="/product/common/js/productCustom.js" ></script>