package com.sinosoft.undwrt.undwrtBase.model;

// Generated 2012-12-29 17:02:41 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SwfCondition generated by hbm2java.
 */
@Entity(name = "SWFCONDITION_UNDWRT")
@Table(name = "SWFCONDITION")
public class SwfCondition implements java.io.Serializable {

	/** 屬性id. */
	private SwfConditionId id;
	
	/** 屬性路徑條件實體類. */
	private SwfPath swfPath;
	
	/** 屬性機構代碼. */
	private String comCode;
	
	/** 屬性生效標識. */
	private String validStatus;
	
	/** 屬性配置類型. */
	private String configType;
	
	/** 屬性配置描述. */
	private String configText;
	
	/** 屬性業務鍵值. */
	private String businessKey;
	
	/** 屬性資料庫名稱. */
	private String dbName;
	
	/** 屬性表名. */
	private String tableName;
	
	/** 屬性資料欄位資料類型. */
	private String dataType;
	
	/** 屬性資料欄位名. */
	private String columnName;
	
	/** 屬性資料欄位描述. */
	private String columnDesc;
	
	/** 屬性運算符. */
	private String operator;
	
	/** 屬性值. */
	private String value;
	
	/** 屬性標志. */
	private String flag;

	/**
	 * Instantiates a new swf condition.
	 */
	public SwfCondition() {
	}

	/**
	 * Instantiates a new swf condition.
	 * 
	 * @param id
	 *            id
	 * @param swfPath
	 *            工作流路徑
	 * @param validStatus
	 *            生效標誌
	 * @param configtype
	 *            配置類型
	 */
	public SwfCondition(SwfConditionId id, SwfPath swfPath, String validStatus,
			String configtype) {
		this.id = id;
		this.swfPath = swfPath;
		this.validStatus = validStatus;
		this.configType = configtype;
	}

	/**
	 * Instantiates a new swf condition.
	 * 
	 * @param id
	 *            id
	 * @param swfPath
	 *            工作流路徑
	 * @param comcode
	 *            歸屬部門
	 * @param validStatus
	 *            生效標誌
	 * @param configtype
	 *            配置類型
	 * @param configtext
	 *            配置描述
	 * @param businesskey
	 *            業務鍵值
	 * @param dbname
	 *            資料庫名稱
	 * @param tablename
	 *            表名
	 * @param datatype
	 *            資料欄位資料類型
	 * @param columnname
	 *            資料欄位名
	 * @param columndesc
	 *            資料欄位描述
	 * @param operator
	 *            運算符
	 * @param value
	 *            值
	 * @param flag
	 *            標誌
	 */
	public SwfCondition(SwfConditionId id, SwfPath swfPath, String comcode,
			String validStatus, String configtype, String configtext,
			String businesskey, String dbname, String tablename,
			String datatype, String columnname, String columndesc,
			String operator, String value, String flag) {
		this.id = id;
		this.swfPath = swfPath;
		this.comCode = comcode;
		this.validStatus = validStatus;
		this.configType = configtype;
		this.configText = configtext;
		this.businessKey = businesskey;
		this.dbName = dbname;
		this.tableName = tablename;
		this.dataType = datatype;
		this.columnName = columnname;
		this.columnDesc = columndesc;
		this.operator = operator;
		this.value = value;
		this.flag = flag;
	}

	/**
	 * 獲取屬性id.
	 * 
	 * @return 屬性id的值
	 */
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "modelNo", column = @Column(name = "MODELNO", nullable = false, precision = 15, scale = 0)),
			@AttributeOverride(name = "pathNo", column = @Column(name = "PATHNO", nullable = false, precision = 15, scale = 0)),
			@AttributeOverride(name = "conditionNo", column = @Column(name = "CONDITIONNO", nullable = false, precision = 15, scale = 0)),
			@AttributeOverride(name = "serialNo", column = @Column(name = "SERIALNO", nullable = false, precision = 15, scale = 0)) })
	public SwfConditionId getId() {
		return this.id;
	}

	/**
	 * 設置屬性id.
	 * 
	 * @param id
	 *            待設置的id的值
	 */
	public void setId(SwfConditionId id) {
		this.id = id;
	}

	/**
	 * 獲取屬性路徑條件實體類.
	 * 
	 * @return 屬性路徑條件實體類的值
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "MODELNO", referencedColumnName = "MODELNO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "PATHNO", referencedColumnName = "PATHNO", nullable = false, insertable = false, updatable = false) })
	public SwfPath getSwfPath() {
		return this.swfPath;
	}

	/**
	 * 設置屬性路徑條件實體類.
	 * 
	 * @param swfPath
	 *            待設置的路徑條件實體類的值
	 */
	public void setSwfPath(SwfPath swfPath) {
		this.swfPath = swfPath;
	}

	/**
	 * 獲取屬性機構代碼.
	 * 
	 * @return 屬性機構代碼的值
	 */
	@Column(name = "COMCODE", length = 10)
	public String getComCode() {
		return this.comCode;
	}

	/**
	 * 設置屬性機構代碼.
	 * 
	 * @param comCode
	 *            待設置的機構代碼的值
	 */
	public void setComCode(String comCode) {
		this.comCode = comCode;
	}

	/**
	 * 獲取屬性生效標誌.
	 * 
	 * @return 屬性生效標誌的值
	 */
	@Column(name = "VALIDSTATUS", nullable = false, length = 1)
	public String getValidStatus() {
		return this.validStatus;
	}

	/**
	 * 設置屬性生效標誌.
	 * 
	 * @param validStatus
	 *            待設置的生效標誌的值
	 */
	public void setValidStatus(String validStatus) {
		this.validStatus = validStatus;
	}

	/**
	 * 獲取屬性配置類型.
	 * 
	 * @return 屬性配置類型的值
	 */
	@Column(name = "CONFIGTYPE", nullable = false, length = 1)
	public String getConfigType() {
		return this.configType;
	}

	/**
	 * 設置屬性配置類型.
	 * 
	 * @param configType
	 *            待設置的配置類型的值
	 */
	public void setConfigType(String configType) {
		this.configType = configType;
	}

	/**
	 * 獲取屬性配置描述.
	 * 
	 * @return 屬性配置描述的值
	 */
	@Column(name = "CONFIGTEXT")
	public String getConfigText() {
		return this.configText;
	}

	/**
	 * 設置屬性配置描述.
	 * 
	 * @param configText
	 *            待設置的配置描述的值
	 */
	public void setConfigText(String configText) {
		this.configText = configText;
	}

	/**
	 * 獲取屬性業務鍵值.
	 * 
	 * @return 屬性業務鍵值的值
	 */
	@Column(name = "BUSINESSKEY", length = 18)
	public String getBusinessKey() {
		return this.businessKey;
	}

	/**
	 * 設置屬性業務鍵值.
	 * 
	 * @param businessKey
	 *            待設置的業務鍵值的值
	 */
	public void setBusinessKey(String businessKey) {
		this.businessKey = businessKey;
	}

	/**
	 * 獲取屬性資料庫名稱.
	 * 
	 * @return 屬性資料庫名稱的值
	 */
	@Column(name = "DBNAME", length = 20)
	public String getDbName() {
		return this.dbName;
	}

	/**
	 * 設置屬性資料庫名稱.
	 * 
	 * @param dbName
	 *            待設置的資料庫名稱的值
	 */
	public void setDbName(String dbName) {
		this.dbName = dbName;
	}

	/**
	 * 獲取屬性表名.
	 * 
	 * @return 屬性表名的值
	 */
	@Column(name = "TABLENAME", length = 60)
	public String getTableName() {
		return this.tableName;
	}

	/**
	 * 設置屬性表名.
	 * 
	 * @param tableName
	 *            待設置的表名的值
	 */
	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	/**
	 * 獲取屬性資料欄位資料類型.
	 * 
	 * @return 屬性資料欄位資料類型的值
	 */
	@Column(name = "DATATYPE", length = 100)
	public String getDataType() {
		return this.dataType;
	}

	/**
	 * 設置屬性資料欄位資料類型.
	 * 
	 * @param dataType
	 *            待設置的資料欄位資料類型的值
	 */
	public void setDataType(String dataType) {
		this.dataType = dataType;
	}

	/**
	 * 獲取屬性資料欄位名.
	 * 
	 * @return 屬性資料欄位名的值
	 */
	@Column(name = "COLUMNNAME", length = 20)
	public String getColumnName() {
		return this.columnName;
	}

	/**
	 * 設置屬性資料欄位名.
	 * 
	 * @param columnName
	 *            待設置的資料欄位名的值
	 */
	public void setColumnName(String columnName) {
		this.columnName = columnName;
	}

	/**
	 * 獲取屬性資料欄位描述.
	 * 
	 * @return 屬性資料欄位描述的值
	 */
	@Column(name = "COLUMNDESC", length = 60)
	public String getColumnDesc() {
		return this.columnDesc;
	}

	/**
	 * 設置屬性資料欄位描述.
	 * 
	 * @param columnDesc
	 *            待設置的資料欄位描述的值
	 */
	public void setColumnDesc(String columnDesc) {
		this.columnDesc = columnDesc;
	}

	/**
	 * 獲取屬性運算符.
	 * 
	 * @return 屬性運算符的值
	 */
	@Column(name = "OPERATOR", length = 30)
	public String getOperator() {
		return this.operator;
	}

	/**
	 * 設置屬性運算符.
	 * 
	 * @param operator
	 *            待設置的運算符的值
	 */
	public void setOperator(String operator) {
		this.operator = operator;
	}

	/**
	 * 獲取屬性值.
	 * 
	 * @return 屬性值的值
	 */
	@Column(name = "VALUE")
	public String getValue() {
		return this.value;
	}

	/**
	 * 設置屬性值.
	 * 
	 * @param value
	 *            待設置的值的值
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * 獲取屬性標志.
	 * 
	 * @return 屬性標志的值
	 */
	@Column(name = "FLAG", length = 10)
	public String getFlag() {
		return this.flag;
	}

	/**
	 * 設置屬性標志.
	 * 
	 * @param flag
	 *            待設置的標志的值
	 */
	public void setFlag(String flag) {
		this.flag = flag;
	}

}
