package com.sinosoft.undwrt.undwrtBase.model;

// Generated 2012-12-29 17:02:41 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SwfModelMain generated by hbm2java.
 */
@Entity(name = "SWFMODELMAIN_UNDWRT")
@Table(name = "SWFMODELMAIN")
public class SwfModelMain implements java.io.Serializable {

	/** 屬性模板號. */
	private int modelNo;
	
	/** 屬性模板名稱. */
	private String modelName;
	
	/** 屬性創建人代碼. */
	private String authorCode;
	
	/** 屬性使用範圍. */
	private String rightId;
	
	/** 屬性創建日期. */
	private Date createDate;
	
	/** 屬性最近一次修改日期. */
	private Date modifyDate;
	
	/** 屬性模板類型 11人工核保 12 自動核保. */
	private String modelType;
	
	/** 屬性模板業務屬性. */
	private String modelAttr;
	
	/** 屬性模板狀態. */
	private String modelStatus;
	
	/** 屬性定義整個流程結束調用的服務. */
	private String closeService;
	
	/** 屬性重新流轉需調用的業務服務. */
	private String activeService;
	
	/** 屬性標志. */
	private String flag;
	
	/** 屬性工作流節點. */
	private Set<SwfNode> swfNodes = new HashSet<SwfNode>(0);

	/**
	 * Instantiates a new swf model main.
	 */
	public SwfModelMain() {
	}
	
	

	/**
	 * Instantiates a new swf model main.
	 * 
	 * @param modelNo
	 *            模板號
	 * @param modelName
	 *            模板名稱
	 * @param createDate
	 *            創建日期
	 */
	public SwfModelMain(int modelNo, String modelName, Date createDate) {
		super();
		this.modelNo = modelNo;
		this.modelName = modelName;
		this.createDate = createDate;
	}


	/**
	 * Instantiates a new swf model main.
	 * 
	 * @param modelNo
	 *            模板號
	 * @param modelName
	 *            模板名稱
	 * @param authorCode
	 *            創建人代碼
	 * @param rightId
	 *            使用範圍
	 * @param createDate
	 *            創建日期
	 * @param modifyDate
	 *            最近一次修改日期
	 * @param modelType
	 *            模板類型
	 * @param modelAttr
	 *            模板業務屬性
	 * @param modelStatus
	 *            模板狀態
	 * @param closeService
	 *            定義整個流程結束調用的服務
	 * @param activeService
	 *            重新流轉需調用的業務服務
	 * @param flag
	 *            標志
	 * @param swfNodes
	 *            節點對象
	 */
	public SwfModelMain(int modelNo, String modelName, String authorCode,
			String rightId, Date createDate, Date modifyDate, String modelType,
			String modelAttr, String modelStatus, String closeService,
			String activeService, String flag, Set<SwfNode> swfNodes) {
		super();
		this.modelNo = modelNo;
		this.modelName = modelName;
		this.authorCode = authorCode;
		this.rightId = rightId;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.modelType = modelType;
		this.modelAttr = modelAttr;
		this.modelStatus = modelStatus;
		this.closeService = closeService;
		this.activeService = activeService;
		this.flag = flag;
		this.swfNodes = swfNodes;
	}



	/**
	 * 獲取屬性模板號.
	 * 
	 * @return 屬性模板號的值
	 */
	@Id
	@Column(name = "MODELNO", unique = true, nullable = false, precision = 15, scale = 0)
	public int getModelNo() {
		return this.modelNo;
	}

	/**
	 * 設置屬性模板號.
	 * 
	 * @param modelNo
	 *            待設置的模板號的值
	 */
	public void setModelNo(int modelNo) {
		this.modelNo = modelNo;
	}

	/**
	 * 獲取屬性模板名稱.
	 * 
	 * @return 屬性模板名稱的值
	 */
	@Column(name = "MODELNAME", nullable = false, length = 100)
	public String getModelName() {
		return this.modelName;
	}

	/**
	 * 設置屬性模板名稱.
	 * 
	 * @param modelName
	 *            待設置的模板名稱的值
	 */
	public void setModelName(String modelName) {
		this.modelName = modelName;
	}

	/**
	 * 獲取屬性創建人代碼.
	 * 
	 * @return 屬性創建人代碼的值
	 */
	@Column(name = "AUTHORCODE", length = 10)
	public String getAuthorCode() {
		return this.authorCode;
	}

	/**
	 * 設置屬性創建人代碼.
	 * 
	 * @param authorCode
	 *            待設置的創建人代碼的值
	 */
	public void setAuthorCode(String authorCode) {
		this.authorCode = authorCode;
	}

	/**
	 * 獲取屬性使用範圍.
	 * 
	 * @return 屬性使用範圍的值
	 */
	@Column(name = "RIGHTID", length = 20)
	public String getRightId() {
		return this.rightId;
	}

	/**
	 * 設置屬性使用範圍.
	 * 
	 * @param rightId
	 *            待設置的使用範圍的值
	 */
	public void setRightId(String rightId) {
		this.rightId = rightId;
	}

	/**
	 * 獲取屬性創建日期.
	 * 
	 * @return 屬性創建日期的值
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "CREATEDATE", nullable = false, length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	/**
	 * 設置屬性創建日期.
	 * 
	 * @param createDate
	 *            待設置的創建日期的值
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * 獲取屬性最近一次修改日期.
	 * 
	 * @return 屬性最近一次修改日期的值
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFYDATE", length = 7)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	/**
	 * 設置屬性最近一次修改日期.
	 * 
	 * @param modifyDate
	 *            待設置的最近一次修改日期的值
	 */
	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	/**
	 * 獲取屬性模板類型.
	 * 
	 * @return 屬性模板類型的值
	 */
	@Column(name = "MODELTYPE", length = 2)
	public String getModelType() {
		return this.modelType;
	}

	/**
	 * 設置屬性模板類型.
	 * 
	 * @param modelType
	 *            待設置的模板類型的值
	 */
	public void setModelType(String modelType) {
		this.modelType = modelType;
	}

	/**
	 * 獲取屬性模板業務屬性.
	 * 
	 * @return 屬性模板業務屬性的值
	 */
	@Column(name = "MODELATTR", length = 2)
	public String getModelAttr() {
		return this.modelAttr;
	}

	/**
	 * 設置屬性模板業務屬性.
	 * 
	 * @param modelAttr
	 *            待設置的模板業務屬性的值
	 */
	public void setModelAttr(String modelAttr) {
		this.modelAttr = modelAttr;
	}

	/**
	 * 獲取屬性模板狀態.
	 * 
	 * @return 屬性模板狀態的值
	 */
	@Column(name = "MODELSTATUS", length = 1)
	public String getModelStatus() {
		return this.modelStatus;
	}

	/**
	 * 設置屬性模板狀態.
	 * 
	 * @param modelStatus
	 *            待設置的模板狀態的值
	 */
	public void setModelStatus(String modelStatus) {
		this.modelStatus = modelStatus;
	}

	/**
	 * 獲取屬性定義整個流程結束調用的服務.
	 * 
	 * @return 屬性定義整個流程結束調用的服務的值
	 */
	@Column(name = "CLOSESERVICE", length = 20)
	public String getCloseService() {
		return this.closeService;
	}

	/**
	 * 設置屬性定義整個流程結束調用的服務.
	 * 
	 * @param closeService
	 *            待設置的定義整個流程結束調用的服務的值
	 */
	public void setCloseService(String closeService) {
		this.closeService = closeService;
	}

	/**
	 * 獲取屬性重新流轉需調用的業務服務.
	 * 
	 * @return 屬性重新流轉需調用的業務服務的值
	 */
	@Column(name = "ACTIVESERVICE", length = 20)
	public String getActiveService() {
		return this.activeService;
	}

	/**
	 * 設置屬性重新流轉需調用的業務服務.
	 * 
	 * @param activeService
	 *            待設置的重新流轉需調用的業務服務的值
	 */
	public void setActiveService(String activeService) {
		this.activeService = activeService;
	}

	/**
	 * 獲取屬性標志.
	 * 
	 * @return 屬性標志的值
	 */
	@Column(name = "FLAG", length = 2)
	public String getFlag() {
		return this.flag;
	}

	/**
	 * 設置屬性標志.
	 * 
	 * @param flag
	 *            待設置的標志的值
	 */
	public void setFlag(String flag) {
		this.flag = flag;
	}

	/**
	 * 獲取屬性節點對象.
	 * 
	 * @return 屬性節點對象的值
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "swfModelMain")
	public Set<SwfNode> getSwfNodes() {
		return this.swfNodes;
	}

	/**
	 * 設置屬性節點對象.
	 * 
	 * @param swfNodes
	 *            待設置的節點對象的值
	 */
	public void setSwfNodes(Set<SwfNode> swfNodes) {
		this.swfNodes = swfNodes;
	}

}
