package com.sinosoft.undwrt.undwrtBase.model;

// Generated 2012-12-29 17:02:41 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SwfModelUse generated by hbm2java.
 */
@Entity(name = "SWFMODELUSE_UNDWRT")
@Table(name = "SWFMODELUSE")
public class SwfModelUse implements java.io.Serializable {

	/** The Constant serialVersionUID. */
    private static final long serialVersionUID = 1L;
    
    /** 屬性id. */
    private SwfModelUseId id;
	
	/** 屬性模板狀態 0無效 1有效. */
	private String modelStatus;
	
	/** 屬性標志. */
	private String flag;
	
	private String classCode;

	/**
	 * Instantiates a new swf model use.
	 */
	public SwfModelUse() {
	}

	/**
	 * Instantiates a new swf model use.
	 * 
	 * @param id
	 *           id
	 */
	public SwfModelUse(SwfModelUseId id) {
		this.id = id;
	}

	/**
	 * Instantiates a new swf model use.
	 * 
	 * @param id
	 *            id
	 * @param modelStatus
	 *            模板狀態
	 * @param flag
	 *            標志
	 */
	public SwfModelUse(SwfModelUseId id, String modelStatus, String flag) {
		this.id = id;
		this.modelStatus = modelStatus;
		this.flag = flag;
	}

	/**
	 * 獲取屬性id.
	 * 
	 * @return 屬性id的值
	 */
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "modelNo", column = @Column(name = "MODELNO", nullable = false, precision = 15, scale = 0)),
			@AttributeOverride(name = "riskCode", column = @Column(name = "RISKCODE", nullable = false, length = 4)),
			@AttributeOverride(name = "comCode", column = @Column(name = "COMCODE", nullable = false, length = 10)),
			@AttributeOverride(name = "modelType", column = @Column(name = "MODELTYPE", nullable = false, length = 2)) })
	public SwfModelUseId getId() {
		return this.id;
	}

	/**
	 * 設置屬性id.
	 * 
	 * @param id
	 *            待設置的id的值
	 */
	public void setId(SwfModelUseId id) {
		this.id = id;
	}

	/**
	 * 獲取屬性模板狀態.
	 * 
	 * @return 屬性模板狀態的值
	 */
	@Column(name = "MODELSTATUS", length = 2)
	public String getModelStatus() {
		return this.modelStatus;
	}

	/**
	 * 設置屬性模板狀態.
	 * 
	 * @param modelStatus
	 *            待設置的模板狀態的值
	 */
	public void setModelStatus(String modelStatus) {
		this.modelStatus = modelStatus;
	}

	/**
	 * 獲取屬性標志.
	 * 
	 * @return 屬性標志的值
	 */
	@Column(name = "FLAG", length = 2)
	public String getFlag() {
		return this.flag;
	}

	/**
	 * 設置屬性標志.
	 * 
	 * @param flag
	 *            待設置的標志的值
	 */
	public void setFlag(String flag) {
		this.flag = flag;
	}
	@Column(name = "CLASSCODE", length = 10)
	public String getClassCode() {
		return classCode;
	}

	public void setClassCode(String classCode) {
		this.classCode = classCode;
	}

}
