package com.sinosoft.undwrt.undwrtBase.model;

// Generated 2013-1-24 21:39:17 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UtiUwFactor generated by hbm2java.
 */
@Entity(name = "UTIUWFACTOR_UNDWRT")
@Table(name = "UTIUWFACTOR")
public class UtiUwFactor implements java.io.Serializable {

	/** 屬性The sinosoft id. */
	private UtiUwFactorId id;
	
	/** 屬性險種大類 code. */
	private String riskCategoryCode;
	
	/** 屬性The sinosoft factor name. */
	private String factorName;
	
	/** 屬性The sinosoft factor attr. */
	private String factorAttr;
	
	/** 屬性The sinosoft multi select flag. */
	private String multiSelectFlag;
	
	/** 屬性The sinosoft is code flag. */
	private String isCodeFlag;
	
	/** 屬性The sinosoft remark. */
	private String remark;
	
	/** 屬性The sinosoft valid status. */
	private String validStatus;
	
	/** 屬性The sinosoft example value. */
	private String exampleValue;
	
	/** 屬性The sinosoft value desc. */
	private String valueDesc;
	
	/** 屬性The sinosoft operator. */
	private String operator;
	
	/** 屬性The sinosoft uti uw conditions. */
	private Set<UtiUwCondition> utiUwConditions = new HashSet<UtiUwCondition>(0);

	/**
	 * Instantiates a new uti uw factor.
	 */
	public UtiUwFactor() {
	}

	/**
	 * Instantiates a new uti uw factor.
	 * 
	 * @param id
	 *            the id
	 * @param riskcategorycode
	 *            the riskcategorycode
	 * @param factorname
	 *            the factorname
	 * @param factorattr
	 *            the factorattr
	 * @param multiselectflag
	 *            the multiselectflag
	 * @param iscodeflag
	 *            the iscodeflag
	 * @param validstatus
	 *            the validstatus
	 * @param examplevalue
	 *            the examplevalue
	 * @param valuedesc
	 *            the valuedesc
	 * @param operator
	 *            the operator
	 */
	public UtiUwFactor(UtiUwFactorId id, String riskcategorycode,
			String factorname, String factorattr, String multiselectflag,
			String iscodeflag, String validstatus, String examplevalue,
			String valuedesc, String operator) {
		this.id = id;
		this.riskCategoryCode = riskcategorycode;
		this.factorName = factorname;
		this.factorAttr = factorattr;
		this.multiSelectFlag = multiselectflag;
		this.isCodeFlag = iscodeflag;
		this.validStatus = validstatus;
		this.exampleValue = examplevalue;
		this.valueDesc = valuedesc;
		this.operator = operator;
	}

	/**
	 * Instantiates a new uti uw factor.
	 * 
	 * @param id
	 *            the id
	 * @param riskcategorycode
	 *            the riskcategorycode
	 * @param factorname
	 *            the factorname
	 * @param factorattr
	 *            the factorattr
	 * @param multiselectflag
	 *            the multiselectflag
	 * @param iscodeflag
	 *            the iscodeflag
	 * @param remark
	 *            the remark
	 * @param validstatus
	 *            the validstatus
	 * @param examplevalue
	 *            the examplevalue
	 * @param valuedesc
	 *            the valuedesc
	 * @param operator
	 *            the operator
	 * @param utiUwConditions
	 *            the uti uw conditions
	 */
	public UtiUwFactor(UtiUwFactorId id, String riskcategorycode,
			String factorname, String factorattr, String multiselectflag,
			String iscodeflag, String remark, String validstatus,
			String examplevalue, String valuedesc, String operator,
			Set<UtiUwCondition> utiUwConditions) {
		this.id = id;
		this.riskCategoryCode = riskcategorycode;
		this.factorName = factorname;
		this.factorAttr = factorattr;
		this.multiSelectFlag = multiselectflag;
		this.isCodeFlag = iscodeflag;
		this.remark = remark;
		this.validStatus = validstatus;
		this.exampleValue = examplevalue;
		this.valueDesc = valuedesc;
		this.operator = operator;
		this.utiUwConditions = utiUwConditions;
	}

	/**
	 * 獲取屬性the sinosoft id.
	 * 
	 * @return 屬性the sinosoft id的值
	 */
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "uwType", column = @Column(name = "UWTYPE", nullable = false, length = 1)),
			@AttributeOverride(name = "factorCode", column = @Column(name = "FACTORCODE", nullable = false, length = 60)),
			@AttributeOverride(name = "classCode", column = @Column(name = "CLASSCODE", nullable = false, length = 3)) })
	public UtiUwFactorId getId() {
		return this.id;
	}

	/**
	 * 設置屬性the sinosoft id.
	 * 
	 * @param id
	 *            待設置的the sinosoft id的值
	 */
	public void setId(UtiUwFactorId id) {
		this.id = id;
	}

	/**
	 * 獲取屬性險種大類 code.
	 * 
	 * @return 屬性險種大類 code的值
	 */
	@Column(name = "RISKCATEGORYCODE", nullable = false, length = 3)
	public String getRiskCategoryCode() {
		return this.riskCategoryCode;
	}

	/**
	 * 設置屬性險種大類 code.
	 * 
	 * @param riskcategorycode
	 *            待設置的險種大類 code的值
	 */
	public void setRiskCategoryCode(String riskcategorycode) {
		this.riskCategoryCode = riskcategorycode;
	}

	/**
	 * 獲取屬性the sinosoft factor name.
	 * 
	 * @return 屬性the sinosoft factor name的值
	 */
	@Column(name = "FACTORNAME", nullable = false, length = 120)
	public String getFactorName() {
		return this.factorName;
	}

	/**
	 * 設置屬性the sinosoft factor name.
	 * 
	 * @param factorname
	 *            待設置的the sinosoft factor name的值
	 */
	public void setFactorName(String factorname) {
		this.factorName = factorname;
	}

	/**
	 * 獲取屬性the sinosoft factor attr.
	 * 
	 * @return 屬性the sinosoft factor attr的值
	 */
	@Column(name = "FACTORATTR", nullable = false, length = 1)
	public String getFactorAttr() {
		return this.factorAttr;
	}

	/**
	 * 設置屬性the sinosoft factor attr.
	 * 
	 * @param factorattr
	 *            待設置的the sinosoft factor attr的值
	 */
	public void setFactorAttr(String factorattr) {
		this.factorAttr = factorattr;
	}

	/**
	 * 獲取屬性the sinosoft multi select flag.
	 * 
	 * @return 屬性the sinosoft multi select flag的值
	 */
	@Column(name = "MULTISELECTFLAG", nullable = false, length = 1)
	public String getMultiSelectFlag() {
		return this.multiSelectFlag;
	}

	/**
	 * 設置屬性the sinosoft multi select flag.
	 * 
	 * @param multiselectflag
	 *            待設置的the sinosoft multi select flag的值
	 */
	public void setMultiSelectFlag(String multiselectflag) {
		this.multiSelectFlag = multiselectflag;
	}

	/**
	 * 獲取屬性the sinosoft checks if is code flag.
	 * 
	 * @return 屬性the sinosoft checks if is code flag的值
	 */
	@Column(name = "ISCODEFLAG", nullable = false, length = 1)
	public String getIsCodeFlag() {
		return this.isCodeFlag;
	}

	/**
	 * 設置屬性the sinosoft checks if is code flag.
	 * 
	 * @param iscodeflag
	 *            待設置的the sinosoft checks if is code flag的值
	 */
	public void setIsCodeFlag(String iscodeflag) {
		this.isCodeFlag = iscodeflag;
	}

	/**
	 * 獲取屬性the sinosoft remark.
	 * 
	 * @return 屬性the sinosoft remark的值
	 */
	@Column(name = "REMARK")
	public String getRemark() {
		return this.remark;
	}

	/**
	 * 設置屬性the sinosoft remark.
	 * 
	 * @param remark
	 *            待設置的the sinosoft remark的值
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * 獲取屬性the sinosoft valid status.
	 * 
	 * @return 屬性the sinosoft valid status的值
	 */
	@Column(name = "VALIDSTATUS", nullable = false, length = 1)
	public String getValidStatus() {
		return this.validStatus;
	}

	/**
	 * 設置屬性the sinosoft valid status.
	 * 
	 * @param validstatus
	 *            待設置的the sinosoft valid status的值
	 */
	public void setValidStatus(String validstatus) {
		this.validStatus = validstatus;
	}

	/**
	 * 獲取屬性the sinosoft example value.
	 * 
	 * @return 屬性the sinosoft example value的值
	 */
	@Column(name = "EXAMPLEVALUE", nullable = false, length = 120)
	public String getExampleValue() {
		return this.exampleValue;
	}

	/**
	 * 設置屬性the sinosoft example value.
	 * 
	 * @param examplevalue
	 *            待設置的the sinosoft example value的值
	 */
	public void setExampleValue(String examplevalue) {
		this.exampleValue = examplevalue;
	}

	/**
	 * 獲取屬性the sinosoft value desc.
	 * 
	 * @return 屬性the sinosoft value desc的值
	 */
	@Column(name = "VALUEDESC", nullable = false, length = 512)
	public String getValueDesc() {
		return this.valueDesc;
	}

	/**
	 * 設置屬性the sinosoft value desc.
	 * 
	 * @param valuedesc
	 *            待設置的the sinosoft value desc的值
	 */
	public void setValueDesc(String valuedesc) {
		this.valueDesc = valuedesc;
	}

	/**
	 * 獲取屬性the sinosoft operator.
	 * 
	 * @return 屬性the sinosoft operator的值
	 */
	@Column(name = "OPERATOR", nullable = false, length = 30)
	public String getOperator() {
		return this.operator;
	}

	/**
	 * 設置屬性the sinosoft operator.
	 * 
	 * @param operator
	 *            待設置的the sinosoft operator的值
	 */
	public void setOperator(String operator) {
		this.operator = operator;
	}

	/**
	 * 獲取屬性the sinosoft uti uw conditions.
	 * 
	 * @return 屬性the sinosoft uti uw conditions的值
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utiUwFactor")
	public Set<UtiUwCondition> getUtiUwConditions() {
		return this.utiUwConditions;
	}

	/**
	 * 設置屬性the sinosoft uti uw conditions.
	 * 
	 * @param utiUwConditions
	 *            待設置的the sinosoft uti uw conditions的值
	 */
	public void setUtiUwConditions(Set<UtiUwCondition> utiUwConditions) {
		this.utiUwConditions = utiUwConditions;
	}

}
