package com.sinosoft.undwrt.undwrtBase.model;

// Generated 2013-1-24 21:39:17 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UtiUwCondition generated by hbm2java.
 */
@Entity(name = "UTIUWCONDITION_UNDWRT")
@Table(name = "UTIUWCONDITION")
public class UtiUwCondition implements java.io.Serializable {

	/** 屬性id. */
	private UtiUwConditionId id;
	
	/** 屬性The sinosoft uti uw factor. */
	private UtiUwFactor utiUwFactor;
	
	/** 屬性險種大類 code. */
	private String riskCategoryCode;
	
	/** 屬性The sinosoft factor value. */
	private String factorValue;
	
	/** 屬性The sinosoft remark. */
	private String remark;
	
	/** 屬性The sinosoft create time. */
	private String createTime;
	
	/** 屬性The sinosoft valid status. */
	private String validStatus;
	
	/** 屬性The sinosoft code type value. */
	private String codeTypeValue;
	
	/** 屬性處理人員代碼. */
	private String operatorCode;
	
	/** 屬性The sinosoft operator name. */
	private String operatorName;

	/**
	 * Instantiates a new uti uw condition.
	 */
	public UtiUwCondition() {
	}

	/**
	 * Instantiates a new uti uw condition.
	 * 
	 * @param id
	 *            the id
	 * @param utiUwFactor
	 *            the uti uw factor
	 * @param riskcategorycode
	 *            the riskcategorycode
	 * @param factorvalue
	 *            the factorvalue
	 * @param createtime
	 *            the createtime
	 * @param validstatus
	 *            the validstatus
	 */
	public UtiUwCondition(UtiUwConditionId id, UtiUwFactor utiUwFactor,
			String riskcategorycode, String factorvalue, String createtime,
			String validstatus) {
		this.id = id;
		this.utiUwFactor = utiUwFactor;
		this.riskCategoryCode = riskcategorycode;
		this.factorValue = factorvalue;
		this.createTime = createtime;
		this.validStatus = validstatus;
	}

	/**
	 * Instantiates a new uti uw condition.
	 * 
	 * @param id
	 *            the id
	 * @param utiUwFactor
	 *            the uti uw factor
	 * @param riskcategorycode
	 *            the riskcategorycode
	 * @param factorvalue
	 *            the factorvalue
	 * @param remark
	 *            the remark
	 * @param createtime
	 *            the createtime
	 * @param validstatus
	 *            the validstatus
	 * @param codetypevalue
	 *            the codetypevalue
	 * @param operatorcode
	 *            the operatorcode
	 * @param operatorname
	 *            the operatorname
	 */
	public UtiUwCondition(UtiUwConditionId id, UtiUwFactor utiUwFactor,
			String riskcategorycode, String factorvalue, String remark,
			String createtime, String validstatus, String codetypevalue,
			String operatorcode, String operatorname) {
		this.id = id;
		this.utiUwFactor = utiUwFactor;
		this.riskCategoryCode = riskcategorycode;
		this.factorValue = factorvalue;
		this.remark = remark;
		this.createTime = createtime;
		this.validStatus = validstatus;
		this.codeTypeValue = codetypevalue;
		this.operatorCode = operatorcode;
		this.operatorName = operatorname;
	}

	/**
	 * 獲取屬性the sinosoft id.
	 * 
	 * @return 屬性the sinosoft id的值
	 */
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "comCode", column = @Column(name = "COMCODE", nullable = false, length = 10)),
			@AttributeOverride(name = "modelNo", column = @Column(name = "MODELNO", nullable = false, precision = 15, scale = 0)),
			@AttributeOverride(name = "nodeNo", column = @Column(name = "NODENO", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "riskCode", column = @Column(name = "RISKCODE", nullable = false, length = 10)),
			@AttributeOverride(name = "uwType", column = @Column(name = "UWTYPE", nullable = false, length = 1)),
			@AttributeOverride(name = "classCode", column = @Column(name = "CLASSCODE", nullable = false, length = 3)),
			@AttributeOverride(name = "factorCode", column = @Column(name = "FACTORCODE", nullable = false, length = 60)),
			@AttributeOverride(name = "factorValueNo", column = @Column(name = "FACTORVALUENO", nullable = false, precision = 22, scale = 0)) })
	public UtiUwConditionId getId() {
		return this.id;
	}

	/**
	 * 設置屬性the sinosoft id.
	 * 
	 * @param id
	 *            待設置的the sinosoft id的值
	 */
	public void setId(UtiUwConditionId id) {
		this.id = id;
	}

	/**
	 * 獲取屬性the sinosoft uti uw factor.
	 * 
	 * @return 屬性the sinosoft uti uw factor的值
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "UWTYPE", referencedColumnName = "UWTYPE", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "FACTORCODE", referencedColumnName = "FACTORCODE", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CLASSCODE", referencedColumnName = "CLASSCODE", nullable = false, insertable = false, updatable = false) })
	public UtiUwFactor getUtiUwFactor() {
		return this.utiUwFactor;
	}

	/**
	 * 設置屬性the sinosoft uti uw factor.
	 * 
	 * @param utiUwFactor
	 *            待設置的the sinosoft uti uw factor的值
	 */
	public void setUtiUwFactor(UtiUwFactor utiUwFactor) {
		this.utiUwFactor = utiUwFactor;
	}

	/**
	 * 獲取屬性險種大類 code.
	 * 
	 * @return 屬性險種大類 code的值
	 */
	@Column(name = "RISKCATEGORYCODE", nullable = false, length = 3)
	public String getRiskCategoryCode() {
		return this.riskCategoryCode;
	}

	/**
	 * 設置屬性險種大類 code.
	 * 
	 * @param riskcategorycode
	 *            待設置的險種大類 code的值
	 */
	public void setRiskCategoryCode(String riskcategorycode) {
		this.riskCategoryCode = riskcategorycode;
	}

	/**
	 * 獲取屬性the sinosoft factor value.
	 * 
	 * @return 屬性the sinosoft factor value的值
	 */
	@Column(name = "FACTORVALUE", nullable = false)
	public String getFactorValue() {
		return this.factorValue;
	}

	/**
	 * 設置屬性the sinosoft factor value.
	 * 
	 * @param factorvalue
	 *            待設置的the sinosoft factor value的值
	 */
	public void setFactorValue(String factorvalue) {
		this.factorValue = factorvalue;
	}

	/**
	 * 獲取屬性the sinosoft remark.
	 * 
	 * @return 屬性the sinosoft remark的值
	 */
	@Column(name = "REMARK")
	public String getRemark() {
		return this.remark;
	}

	/**
	 * 設置屬性the sinosoft remark.
	 * 
	 * @param remark
	 *            待設置的the sinosoft remark的值
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * 獲取屬性the sinosoft creates the time.
	 * 
	 * @return 屬性the sinosoft creates the time的值
	 */
	@Column(name = "CREATETIME", nullable = false, length = 23)
	public String getCreateTime() {
		return this.createTime;
	}

	/**
	 * 設置屬性the sinosoft creates the time.
	 * 
	 * @param createtime
	 *            待設置的the sinosoft creates the time的值
	 */
	public void setCreateTime(String createtime) {
		this.createTime = createtime;
	}

	/**
	 * 獲取屬性the sinosoft valid status.
	 * 
	 * @return 屬性the sinosoft valid status的值
	 */
	@Column(name = "VALIDSTATUS", nullable = false, length = 1)
	public String getValidStatus() {
		return this.validStatus;
	}

	/**
	 * 設置屬性the sinosoft valid status.
	 * 
	 * @param validstatus
	 *            待設置的the sinosoft valid status的值
	 */
	public void setValidStatus(String validstatus) {
		this.validStatus = validstatus;
	}

	/**
	 * 獲取屬性the sinosoft code type value.
	 * 
	 * @return 屬性the sinosoft code type value的值
	 */
	@Column(name = "CODETYPEVALUE", length = 20)
	public String getCodeTypeValue() {
		return this.codeTypeValue;
	}

	/**
	 * 設置屬性the sinosoft code type value.
	 * 
	 * @param codetypevalue
	 *            待設置的the sinosoft code type value的值
	 */
	public void setCodeTypeValue(String codetypevalue) {
		this.codeTypeValue = codetypevalue;
	}

	/**
	 * 獲取屬性處理人員代碼.
	 * 
	 * @return 屬性處理人員代碼的值
	 */
	@Column(name = "OPERATORCODE", length = 18)
	public String getOperatorCode() {
		return this.operatorCode;
	}

	/**
	 * 設置屬性處理人員代碼.
	 * 
	 * @param operatorcode
	 *            待設置的處理人員代碼的值
	 */
	public void setOperatorCode(String operatorcode) {
		this.operatorCode = operatorcode;
	}

	/**
	 * 獲取屬性the sinosoft operator name.
	 * 
	 * @return 屬性the sinosoft operator name的值
	 */
	@Column(name = "OPERATORNAME", length = 18)
	public String getOperatorName() {
		return this.operatorName;
	}

	/**
	 * 設置屬性the sinosoft operator name.
	 * 
	 * @param operatorname
	 *            待設置的the sinosoft operator name的值
	 */
	public void setOperatorName(String operatorname) {
		this.operatorName = operatorname;
	}

}
