package com.sinosoft.undwrt.undwrtBase.model;

// Generated 2013-1-23 17:09:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * WfLogExt generated by hbm2java.
 */
@Entity(name = "WFLOGEXT_UNDWRT")
@Table(name = "WFLOGEXT")
public class WfLogExt implements java.io.Serializable {

	/** 屬性The sinosoft id. */
	private WfLogExtId id;
	
	/** 屬性The sinosoft result content. */
	private String resultContent;
	
	/** 屬性The sinosoft authority level. */
	private String authorityLevel;
	
	/** 屬性標志. */
	private String flag;

	/**
	 * Instantiates a new wf log ext.
	 */
	public WfLogExt() {
	}

	/**
	 * Instantiates a new wf log ext.
	 * 
	 * @param id
	 *            the id
	 */
	public WfLogExt(WfLogExtId id) {
		this.id = id;
	}

	/**
	 * Instantiates a new wf log ext.
	 * 
	 * @param id
	 *            the id
	 * @param resultcontent
	 *            the resultcontent
	 * @param authoritylevel
	 *            the authoritylevel
	 * @param flag
	 *            the flag
	 */
	public WfLogExt(WfLogExtId id, String resultcontent, String authoritylevel,
			String flag) {
		this.id = id;
		this.resultContent = resultcontent;
		this.authorityLevel = authoritylevel;
		this.flag = flag;
	}

	/**
	 * 獲取屬性the sinosoft id.
	 * 
	 * @return 屬性the sinosoft id的值
	 */
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "flowid", column = @Column(name = "FLOWID", nullable = false, length = 27)),
			@AttributeOverride(name = "logno", column = @Column(name = "LOGNO", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "lineno", column = @Column(name = "LINENO", nullable = false, precision = 22, scale = 0)) })
	public WfLogExtId getId() {
		return this.id;
	}

	/**
	 * 設置屬性the sinosoft id.
	 * 
	 * @param id
	 *            待設置的the sinosoft id的值
	 */
	public void setId(WfLogExtId id) {
		this.id = id;
	}

	/**
	 * 獲取屬性the sinosoft result content.
	 * 
	 * @return 屬性the sinosoft result content的值
	 */
	@Column(name = "RESULTCONTENT", length = 2000)
	public String getResultContent() {
		return this.resultContent;
	}

	/**
	 * 設置屬性the sinosoft result content.
	 * 
	 * @param resultcontent
	 *            待設置的the sinosoft result content的值
	 */
	public void setResultContent(String resultcontent) {
		this.resultContent = resultcontent;
	}

	/**
	 * 獲取屬性the sinosoft authority level.
	 * 
	 * @return 屬性the sinosoft authority level的值
	 */
	@Column(name = "AUTHORITYLEVEL", length = 2)
	public String getAuthorityLevel() {
		return this.authorityLevel;
	}

	/**
	 * 設置屬性the sinosoft authority level.
	 * 
	 * @param authoritylevel
	 *            待設置的the sinosoft authority level的值
	 */
	public void setAuthorityLevel(String authoritylevel) {
		this.authorityLevel = authoritylevel;
	}

	/**
	 * 獲取屬性標志.
	 * 
	 * @return 屬性標志的值
	 */
	@Column(name = "FLAG", length = 10)
	public String getFlag() {
		return this.flag;
	}

	/**
	 * 設置屬性標志.
	 * 
	 * @param flag
	 *            待設置的標志的值
	 */
	public void setFlag(String flag) {
		this.flag = flag;
	}

}
