package com.sinosoft.undwrt.undwrtBase.model;
// default package
// Generated 2012-12-29 17:02:41 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.springframework.transaction.annotation.Transactional;

import com.sinosoft.sysframework.common.util.StringUtils;
import com.sinosoft.undwrt.pub.InternationalizationUtil;

/**
 * Wflog generated by hbm2java.
 */
@Entity(name = "WFLOG_UNDWRT")
@Table(name = "WFLOG")
public class WfLog implements java.io.Serializable {

	/** 屬性id. */
	private WfLogId id;
	
	/** 屬性模板號. */
	private int modelNo;
	
	/** 屬性節點號. */
	private int nodeNo;
	
	/** 屬性當前節點名稱. */
	private String nodeName;
	
	/** 屬性處理部門代碼. */
	private String deptCode;
	
	/** 屬性處理部門名稱. */
	private String deptName;
	
	/** 屬性處理人員代碼. */
	private String operatorCode;
	
	/** 屬性處理人員名稱. */
	private String operatorName;
	
	/** 屬性流入時間. */
	private String flowInTime;
	
	/** 屬性處理時限. */
	private int timeLimit;
	
	/** 屬性處理時間. */
	private String handleTime;
	
	/** 屬性提交時間. */
	private String submitTime;
	
	/** 屬性節點狀態. */
	private String nodeStatus;
	
	/** 屬性流狀態. */
	private String flowStatus;
	
	/** 屬性包號. */
	private String packageId;
	
	/** 屬性業務類型. */
	private String businessType;
	
	/** 屬性業務號. */
	private String businessNo;
	
	/** 屬性合約號. */
	private String contractNo;
	
	/** 屬性險類代碼. */
	private String classCode;
	
	/** 屬性險種代碼. */
	private String riskCode;
	
	/** 屬性出單機構. */
	private String makeCom;
	
	/** 屬性機構代碼. */
	private String comCode;
	
	/** 屬性經辦人代碼. */
	private String handlerCode;
	
	/** 屬性歸屬業務員代碼. */
	private String handler1Code;
	
	/** 屬性歸屬業務員名称. */
	private String handler1Name;
	
	/** 屬性相關工作流號. */
	private String relateFlowId;
	
	/** 屬性相關工作流序號. */
	private int relateLogNo;
	
	/** 屬性節點X坐標. */
	private int posX;
	
	/** 屬性節點Y坐標. */
	private int posY;
	
	/** 屬性標志. */
	private String flag;
	
	/** 屬性牌照號碼. */
	private String licenseNo;
	
	/** 屬性關聯預約協議號. */
	private String relateContractNo;
	
	/** 屬性險種大類. */
	private String riskCategory;
	
	/** 屬性被保險人代碼. */
	private String insuredCode;
	
	/** 屬性被保險人名稱. */
	private String insuredName;
	
	/** 屬性證件類型. */
	private String identifyType;
	
	/** 屬性證件號碼. */
	private String identifyNumber;
	
	/** 屬性再保狀態 0-已分保 1-未分保. */
	private String reinsStatus;
	
	/** 屬性保單號. */
	private String policyNo;
	
	/** 屬性理賠號. */
	private String claimNo;
	
	/** 屬性總保額. */
	private double sumAmount;
	
	/** 屬性總保費. */
	private double sumPremium;
	/** 屬性總保費. */
	private int premium;// 用于页面取整
	
	/** 屬性操作類型. */
	private String resultCode;
	
	/** 屬性下發或者人工的原因. */
	private String resultContent;
	
	/** 屬性核保通過級別. */
	private String passLevel;
	
	/** 屬性出單員代碼. */
	private String singleCode;
	
	/** 屬性出單員名稱. */
	private String singleMember;
	
	/** 屬性機構名稱. */
	private String comName = null;
	
	/** 屬性The sinosoft prior type. */
	private String priorType;
	
	/** 用户代码. */
    private String userCode = "";
    
    /** 报价单任务状态. */
    private String qtaNodeStatusName = "";
    
    //add by xuhuiling 需求150 添加字段 begin
    private String refuseLimiteInsurance;
    private String listDetection;
    private String riskRating;
    private String workStatus;
    //add by xuhuiling 需求150 添加字段 end
    
    //add by songxin 新增繳費模塊輸入模塊 start
    private String underwriteflag;
    private String jfeeflag;
    private String realpayrefflag;
    private String superpay;//add by xuhuiling 需求165 20161226
    //add by songxin 新增繳費模塊輸入模塊 start
    
	/**
	 * Instantiates a new wf log.
	 */
    
    private String appliName = "";
    
    private String normastatus;//核心擴增欄位：地址正規化狀態，mantis： CAR0369，處理人員：BI086，需求單編號：CAR0369:核心車險地址正規化作業
    
	public WfLog() {
	}

	/**
	 * Instantiates a new wf log.
	 * 
	 * @param id
	 *            id
	 * @param modelno
	 *            模板號
	 * @param nodeno
	 *            節點號
	 * @param nodename
	 *            節點名稱
	 * @param nodestatus
	 *            節點狀態
	 * @param flowstatus
	 *            流狀態
	 * @param packageid
	 *            明細訊息表
	 * @param businesstype
	 *            業務類型
	 * @param businessno
	 *            業務號
	 * @param makecom
	 *            出單機構
	 * @param comcode
	 *            歸屬機構
	 * @param handlercode
	 *            經辦人代碼
	 */
	public WfLog(WfLogId id, int modelno, int nodeno,
			String nodename, String nodestatus, String flowstatus,
			String packageid, String businesstype, String businessno,
			String makecom, String comcode, String handlercode) {
		this.id = id;
		this.modelNo = modelno;
		this.nodeNo = nodeno;
		this.nodeName = nodename;
		this.nodeStatus = nodestatus;
		this.flowStatus = flowstatus;
		this.packageId = packageid;
		this.businessType = businesstype;
		this.businessNo = businessno;
		this.makeCom = makecom;
		this.comCode = comcode;
		this.handlerCode = handlercode;
	}

	/**
	 * Instantiates a new wf log.
	 * 
	 * @param id
	 *            id
	 * @param modelno
	 *            模板號
	 * @param nodeno
	 *            節點號
	 * @param nodename
	 *            節點名稱
	 * @param deptcode
	 *            處理部門代碼
	 * @param deptname
	 *            處理部門名稱
	 * @param operatorcode
	 *            處理人代碼
	 * @param operatorname
	 *            處理人名稱
	 * @param flowintime
	 *            流入時間
	 * @param timelimit
	 *            處理時限
	 * @param handletime
	 *            處理時間
	 * @param submittime
	 *            提交時間
	 * @param nodestatus
	 *            節點狀態
	 * @param flowstatus
	 *            流狀態
	 * @param packageid
	 *            明細訊息表
	 * @param businesstype
	 *            業務類型
	 * @param businessno
	 *            業務號
	 * @param contractno
	 *            合約號
	 * @param classcode
	 *            險類代碼
	 * @param riskcode
	 *            險種代碼
	 * @param makecom
	 *            出單機構
	 * @param comcode
	 *            歸屬機構
	 * @param handlercode
	 *            經辦人代碼
	 * @param handler1code
	 *            歸屬業務員代碼
	 * @param relateflowid
	 *            相關工作流號
	 * @param relatelogno
	 *            相關工作流序號
	 * @param posx
	 *            節點X坐標
	 * @param posy
	 *            節點Y坐標
	 * @param flag
	 *            標志
	 * @param licenseno
	 *            牌照號碼
	 * @param relatecontractno
	 *            關聯預約協議號
	 * @param riskcategory
	 *            險種大類代碼
	 * @param insuredcode
	 *            被保人代碼
	 * @param insuredname
	 *            被保人名稱
	 * @param identifytype
	 *            證件類型
	 * @param identifynumber
	 *            證件號碼
	 * @param reinsstatus
	 *            再保狀態
	 * @param policyno
	 *            保單號
	 * @param claimno
	 *            理賠號
	 * @param sumamount
	 *            總保額
	 * @param sumpremium
	 *            總保費
	 * @param resultcode
	 *            操作類型
	 * @param resultcontent
	 *            下發或者人工的原因
	 * @param passlevel
	 *            核保通過級別
	 * @param singlecode
	 *            出單員代碼
	 * @param singlemember
	 *            出單元名稱
	 */
	//mantis： CAR0369，處理人員：BI086，需求單編號：CAR0369:核心車險地址正規化作業 START
	public WfLog(WfLogId id, int modelno, int nodeno,
			String nodename, String deptcode, String deptname,
			String operatorcode, String operatorname, String flowintime,
			int timelimit, String handletime, String submittime,
			String nodestatus, String flowstatus, String packageid,
			String businesstype, String businessno, String contractno,
			String classcode, String riskcode, String makecom, String comcode,
			String handlercode, String handler1code, String handler1name,String relateflowid,
			int relatelogno, int posx, int posy, String flag,
			String licenseno, String relatecontractno, String riskcategory,
			String insuredcode, String insuredname, String identifytype,
			String identifynumber, String reinsstatus, String policyno,
			String claimno, double sumamount, double sumpremium,int premium,
			String resultcode, String resultcontent, String passlevel,String appliName,
			String singlecode, String singlemember, String normastatus) {
		this.id = id;
		this.modelNo = modelno;
		this.nodeNo = nodeno;
		this.nodeName = nodename;
		this.deptCode = deptcode;
		this.deptName = deptname;
		this.operatorCode = operatorcode;
		this.operatorName = operatorname;
		this.flowInTime = flowintime;
		this.timeLimit = timelimit;
		this.handleTime = handletime;
		this.submitTime = submittime;
		this.nodeStatus = nodestatus;
		this.flowStatus = flowstatus;
		this.packageId = packageid;
		this.businessType = businesstype;
		this.businessNo = businessno;
		this.contractNo = contractno;
		this.classCode = classcode;
		this.riskCode = riskcode;
		this.makeCom = makecom;
		this.comCode = comcode;
		this.handlerCode = handlercode;
		this.handler1Code = handler1code;
		this.handler1Name = handler1Name;
		this.relateFlowId = relateflowid;
		this.relateLogNo = relatelogno;
		this.posX = posx;
		this.posY = posy;
		this.flag = flag;
		this.licenseNo = licenseno;
		this.relateContractNo = relatecontractno;
		this.riskCategory = riskcategory;
		this.insuredCode = insuredcode;
		this.insuredName = insuredname;
		this.identifyType = identifytype;
		this.identifyNumber = identifynumber;
		this.reinsStatus = reinsstatus;
		this.policyNo = policyno;
		this.claimNo = claimno;
		this.sumAmount = sumamount;
		this.sumPremium = sumpremium;
		this.premium = premium;
		this.resultCode = resultcode;
		this.resultContent = resultcontent;
		this.passLevel = passlevel;
		this.singleCode = singlecode;
		this.singleMember = singlemember;
		this.appliName = appliName;
		this.normastatus = normastatus;
	}
	//mantis： CAR0369，處理人員：BI086，需求單編號：CAR0369:核心車險地址正規化作業 END

	/**
	 * 獲取屬性id.
	 * 
	 * @return 屬性id的值
	 */
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "flowId", column = @Column(name = "FLOWID", nullable = false, length = 27)),
			@AttributeOverride(name = "logNo", column = @Column(name = "LOGNO", nullable = false, precision = 22, scale = 0)) })
	public WfLogId getId() {
		return this.id;
	}

	/**
	 * 設置屬性id.
	 * 
	 * @param id
	 *            待設置的id的值
	 */
	public void setId(WfLogId id) {
		this.id = id;
	}

	/**
	 * 獲取屬性模板號.
	 * 
	 * @return 屬性模板號的值
	 */
	@Column(name = "MODELNO", nullable = false, precision = 22, scale = 0)
	public int getModelNo() {
		return this.modelNo;
	}

	/**
	 * 設置屬性模板號.
	 * 
	 * @param modelno
	 *            待設置的模板號的值
	 */
	public void setModelNo(int modelno) {
		this.modelNo = modelno;
	}

	/**
	 * 獲取屬性節點號.
	 * 
	 * @return 屬性節點號的值
	 */
	@Column(name = "NODENO", nullable = false, precision = 22, scale = 0)
	public int getNodeNo() {
		return this.nodeNo;
	}

	/**
	 * 設置屬性節點號.
	 * 
	 * @param nodeno
	 *            待設置的節點號的值
	 */
	public void setNodeNo(int nodeno) {
		this.nodeNo = nodeno;
	}

	/**
	 * 獲取屬性節點名稱.
	 * 
	 * @return 屬性節點名稱的值
	 */
	@Column(name = "NODENAME", nullable = false, length = 100)
	public String getNodeName() {
		return this.nodeName;
	}

	/**
	 * 設置屬性節點名稱.
	 * 
	 * @param nodename
	 *            待設置的節點名稱的值
	 */
	public void setNodeName(String nodename) {
		this.nodeName = nodename;
	}

	/**
	 * 獲取屬性處理部門代碼.
	 * 
	 * @return 屬性處理部門代碼的值
	 */
	@Column(name = "DEPTCODE", length = 10)
	public String getDeptCode() {
		return this.deptCode;
	}

	/**
	 * 設置屬性處理部門代碼.
	 * 
	 * @param deptcode
	 *            待設置的處理部門代碼的值
	 */
	public void setDeptCode(String deptcode) {
		this.deptCode = deptcode;
	}

	/**
	 * 獲取屬性處理部門名稱.
	 * 
	 * @return 屬性處理部門名稱的值
	 */
	@Column(name = "DEPTNAME", length = 60)
	public String getDeptName() {
		return this.deptName;
	}

	/**
	 * 設置屬性處理部門名稱.
	 * 
	 * @param deptname
	 *            待設置的處理部門名稱的值
	 */
	public void setDeptName(String deptname) {
		this.deptName = deptname;
	}

	/**
	 * 獲取屬性處理人員代碼.
	 * 
	 * @return 屬性處理人員代碼的值
	 */
	@Column(name = "OPERATORCODE", length = 18)
	public String getOperatorCode() {
		return this.operatorCode;
	}

	/**
	 * 設置屬性處理人員代碼.
	 * 
	 * @param operatorcode
	 *            待設置的處理人員代碼的值
	 */
	public void setOperatorCode(String operatorcode) {
		this.operatorCode = operatorcode;
	}

	/**
	 * 獲取屬性處理人員名稱.
	 * 
	 * @return 屬性處理人員名稱的值
	 */
	@Column(name = "OPERATORNAME", length = 30)
	public String getOperatorName() {
		return this.operatorName;
	}

	/**
	 * 設置屬性處理人員名稱.
	 * 
	 * @param operatorname
	 *            待設置的處理人員名稱的值
	 */
	public void setOperatorName(String operatorname) {
		this.operatorName = operatorname;
	}

	/**
	 * 獲取屬性流入時間.
	 * 
	 * @return 屬性流入時間的值
	 */
	@Column(name = "FLOWINTIME", length = 19)
	public String getFlowInTime() {
		return this.flowInTime;
	}

	/**
	 * 設置屬性流入時間.
	 * 
	 * @param flowintime
	 *            待設置的流入時間的值
	 */
	public void setFlowInTime(String flowintime) {
		this.flowInTime = flowintime;
	}

	/**
	 * 獲取屬性處理時限.
	 * 
	 * @return 屬性處理時限的值
	 */
	@Column(name = "TIMELIMIT", precision = 22, scale = 0)
	public int getTimeLimit() {
		return this.timeLimit;
	}

	/**
	 * 設置屬性處理時限.
	 * 
	 * @param timelimit
	 *            待設置的處理時限的值
	 */
	public void setTimeLimit(int timelimit) {
		this.timeLimit = timelimit;
	}

	/**
	 * 獲取屬性處理時間.
	 * 
	 * @return 屬性處理時間的值
	 */
	@Column(name = "HANDLETIME", length = 19)
	public String getHandleTime() {
		return this.handleTime;
	}

	/**
	 * 設置屬性處理時間.
	 * 
	 * @param handletime
	 *            待設置的處理時間的值
	 */
	public void setHandleTime(String handletime) {
		this.handleTime = handletime;
	}

	/**
	 * 獲取屬性提交時間.
	 * 
	 * @return 屬性提交時間的值
	 */
	@Column(name = "SUBMITTIME", length = 19)
	public String getSubmitTime() {
		return this.submitTime;
	}

	/**
	 * 設置屬性提交時間.
	 * 
	 * @param submittime
	 *            待設置的提交時間的值
	 */
	public void setSubmitTime(String submittime) {
		this.submitTime = submittime;
	}

	/**
	 * 獲取屬性節點狀態.
	 * 
	 * @return 屬性節點狀態的值
	 */
	@Column(name = "NODESTATUS", nullable = false, length = 1)
	public String getNodeStatus() {
		return this.nodeStatus;
	}

	/**
	 * 設置屬性節點狀態.
	 * 
	 * @param nodestatus
	 *            待設置的節點狀態的值
	 */
	public void setNodeStatus(String nodestatus) {
		this.nodeStatus = nodestatus;
	}

	/**
	 * 獲取屬性流狀態.
	 * 
	 * @return 屬性流狀態的值
	 */
	@Column(name = "FLOWSTATUS", nullable = false, length = 1)
	public String getFlowStatus() {
		return this.flowStatus;
	}

	/**
	 * 設置屬性流狀態.
	 * 
	 * @param flowstatus
	 *            待設置的流狀態的值
	 */
	public void setFlowStatus(String flowstatus) {
		this.flowStatus = flowstatus;
	}

	/**
	 * 獲取屬性包號.
	 * 
	 * @return 屬性包號的值
	 */
	@Column(name = "PACKAGEID", nullable = false, length = 27)
	public String getPackageId() {
		return this.packageId;
	}

	/**
	 * 設置屬性包號.
	 * 
	 * @param packageid
	 *            待設置的包號的值
	 */
	public void setPackageId(String packageid) {
		this.packageId = packageid;
	}

	/**
	 * 獲取屬性業務類型.
	 * 
	 * @return 屬性業務類型的值
	 */
	@Column(name = "BUSINESSTYPE", nullable = false, length = 1)
	public String getBusinessType() {
		return this.businessType;
	}

	/**
	 * 設置屬性業務類型.
	 * 
	 * @param businesstype
	 *            待設置的業務類型的值
	 */
	public void setBusinessType(String businesstype) {
		this.businessType = businesstype;
	}

	/**
	 * 獲取屬性業務號.
	 * 
	 * @return 屬性業務號的值
	 */
	@Column(name = "BUSINESSNO", nullable = false, length = 25)
	public String getBusinessNo() {
		return this.businessNo;
	}

	/**
	 * 設置屬性業務號.
	 * 
	 * @param businessno
	 *            待設置的業務號的值
	 */
	public void setBusinessNo(String businessno) {
		this.businessNo = businessno;
	}

	/**
	 * 獲取屬性合約號.
	 * 
	 * @return 屬性合約號的值
	 */
	@Column(name = "CONTRACTNO", length = 22)
	public String getContractNo() {
		return this.contractNo;
	}

	/**
	 * 設置屬性合約號.
	 * 
	 * @param contractno
	 *            待設置的合約號的值
	 */
	public void setContractNo(String contractno) {
		this.contractNo = contractno;
	}

	/**
	 * 獲取屬性險類代碼.
	 * 
	 * @return 屬性險類代碼的值
	 */
	@Column(name = "CLASSCODE", length = 3)
	public String getClassCode() {
		return this.classCode;
	}

	/**
	 * 設置屬性險類代碼.
	 * 
	 * @param classcode
	 *            待設置的險類代碼的值
	 */
	public void setClassCode(String classcode) {
		this.classCode = classcode;
	}

	/**
	 * 獲取屬性險種代碼.
	 * 
	 * @return 屬性險種代碼的值
	 */
	@Column(name = "RISKCODE", length = 4)
	public String getRiskCode() {
		return this.riskCode;
	}

	/**
	 * 設置屬性險種代碼.
	 * 
	 * @param riskcode
	 *            待設置的險種代碼的值
	 */
	public void setRiskCode(String riskcode) {
		this.riskCode = riskcode;
	}

	/**
	 * 獲取屬性出單機構.
	 * 
	 * @return 屬性出單機構的值
	 */
	@Column(name = "MAKECOM", nullable = false, length = 10)
	public String getMakeCom() {
		return this.makeCom;
	}

	/**
	 * 設置屬性出單機構.
	 * 
	 * @param makecom
	 *            待設置的出單機構的值
	 */
	public void setMakeCom(String makecom) {
		this.makeCom = makecom;
	}

	/**
	 * 獲取屬性機構代碼.
	 * 
	 * @return 屬性機構代碼的值
	 */
	@Column(name = "COMCODE", nullable = false, length = 10)
	public String getComCode() {
		return this.comCode;
	}

	/**
	 * 設置屬性機構代碼.
	 * 
	 * @param comcode
	 *            待設置的機構代碼的值
	 */
	public void setComCode(String comcode) {
		this.comCode = comcode;
	}

	/**
	 * 獲取屬性經辦人代碼.
	 * 
	 * @return 屬性經辦人代碼的值
	 */
	@Column(name = "HANDLERCODE", nullable = false, length = 18)
	public String getHandlerCode() {
		return this.handlerCode;
	}

	/**
	 * 設置屬性經辦人代碼.
	 * 
	 * @param handlercode
	 *            待設置的經辦人代碼的值
	 */
	public void setHandlerCode(String handlercode) {
		this.handlerCode = handlercode;
	}

	/**
	 * 獲取屬性歸屬業務員代碼.
	 * 
	 * @return 屬性歸屬業務員代碼的值
	 */
	@Column(name = "HANDLER1CODE", length = 18)
	public String getHandler1Code() {
		return this.handler1Code;
	}

	/**
	 * 設置屬性歸屬業務員代碼.
	 * 
	 * @param handler1code
	 *            待設置的歸屬業務員代碼的值
	 */
	public void setHandler1Code(String handler1code) {
		this.handler1Code = handler1code;
	}
	
	/**
	 * 設置屬性歸屬業務員名称.
	 * 
	 * @param handler1name
	 *            待設置的歸屬業務員代碼的值
	 */
	@Transient
	public String getHandler1Name() {
		return handler1Name;
	}

	public void setHandler1Name(String handler1Name) {
		this.handler1Name = handler1Name;
	}

	/**
	 * 獲取屬性相關工作流號.
	 * 
	 * @return 屬性相關工作流號的值
	 */
	@Column(name = "RELATEFLOWID", length = 27)
	public String getRelateFlowId() {
		return this.relateFlowId;
	}

	/**
	 * 設置屬性相關工作流號.
	 * 
	 * @param relateflowid
	 *            待設置的相關工作流號的值
	 */
	public void setRelateFlowId(String relateflowid) {
		this.relateFlowId = relateflowid;
	}

	/**
	 * 獲取屬性相關工作流序號.
	 * 
	 * @return 屬性相關工作流序號的值
	 */
	@Column(name = "RELATELOGNO", precision = 15, scale = 0)
	public int getRelateLogNo() {
		return this.relateLogNo;
	}

	/**
	 * 設置屬性相關工作流序號.
	 * 
	 * @param relatelogno
	 *            待設置的相關工作流序號的值
	 */
	public void setRelateLogNo(int relatelogno) {
		this.relateLogNo = relatelogno;
	}

	/**
	 * 獲取屬性節點X坐標.
	 * 
	 * @return 屬性節點X坐標的值
	 */
	@Column(name = "POSX", precision = 22, scale = 0)
	public int getPosX() {
		return this.posX;
	}

	/**
	 * 設置屬性節點X坐標.
	 * 
	 * @param posx
	 *            待設置的節點X坐標的值
	 */
	public void setPosX(int posx) {
		this.posX = posx;
	}

	/**
	 * 獲取屬性節點Y坐標.
	 * 
	 * @return 屬性節點Y坐標的值
	 */
	@Column(name = "POSY", precision = 22, scale = 0)
	public int getPosY() {
		return this.posY;
	}

	/**
	 * 設置屬性節點Y坐標.
	 * 
	 * @param posy
	 *            待設置的節點Y坐標的值
	 */
	public void setPosY(int posy) {
		this.posY = posy;
	}

	/**
	 * 獲取屬性標志.
	 * 
	 * @return 屬性標志的值
	 */
	@Column(name = "FLAG", length = 10)
	public String getFlag() {
		return this.flag;
	}

	/**
	 * 設置屬性標志.
	 * 
	 * @param flag
	 *            待設置的標志的值
	 */
	public void setFlag(String flag) {
		this.flag = flag;
	}

	/**
	 * 獲取屬性牌照號碼.
	 * 
	 * @return 屬性牌照號碼的值
	 */
	@Column(name = "LICENSENO", length = 20)
	public String getLicenseNo() {
		return this.licenseNo;
	}

	/**
	 * 設置屬性牌照號碼.
	 * 
	 * @param licenseno
	 *            待設置的牌照號碼的值
	 */
	public void setLicenseNo(String licenseno) {
		this.licenseNo = licenseno;
	}

	/**
	 * 獲取屬性相關預約協議號.
	 * 
	 * @return 屬性相關預約協議號的值
	 */
	@Column(name = "RELATECONTRACTNO", length = 22)
	public String getRelateContractNo() {
		return this.relateContractNo;
	}

	/**
	 * 設置屬性相關預約協議號.
	 * 
	 * @param relatecontractno
	 *            待設置的相關預約協議號的值
	 */
	public void setRelateContractNo(String relatecontractno) {
		this.relateContractNo = relatecontractno;
	}

	/**
	 * 獲取屬性險種大類.
	 * 
	 * @return 屬性險種大類的值
	 */
	@Column(name = "RISKCATEGORY", length = 1)
	public String getRiskCategory() {
		return this.riskCategory;
	}

	/**
	 * 設置屬性險種大類.
	 * 
	 * @param riskcategory
	 *            待設置的險種大類的值
	 */
	public void setRiskCategory(String riskcategory) {
		this.riskCategory = riskcategory;
	}

	/**
	 * 獲取屬性被保人代碼.
	 * 
	 * @return 屬性被保人代碼的值
	 */
	@Column(name = "INSUREDCODE", length = 20)
	public String getInsuredCode() {
		return this.insuredCode;
	}

	/**
	 * 設置屬性被保人代碼.
	 * 
	 * @param insuredcode
	 *            待設置的被保人代碼的值
	 */
	public void setInsuredCode(String insuredcode) {
		this.insuredCode = insuredcode;
	}

	/**
	 * 獲取屬性被保人名稱.
	 * 
	 * @return 屬性被保人名稱的值
	 */
	@Column(name = "INSUREDNAME", length = 120)
	public String getInsuredName() {
		return this.insuredName;
	}

	/**
	 * 設置屬性被保人名稱.
	 * 
	 * @param insuredname
	 *            待設置的被保人名稱的值
	 */
	public void setInsuredName(String insuredname) {
		this.insuredName = insuredname;
	}

	/**
	 * 獲取屬性證件類型.
	 * 
	 * @return 屬性證件類型的值
	 */
	@Column(name = "IDENTIFYTYPE", length = 2)
	public String getIdentifyType() {
		return this.identifyType;
	}

	/**
	 * 設置屬性證件類型.
	 * 
	 * @param identifytype
	 *            待設置的證件類型的值
	 */
	public void setIdentifyType(String identifytype) {
		this.identifyType = identifytype;
	}

	/**
	 * 獲取屬性證件號碼.
	 * 
	 * @return 屬性證件號碼的值
	 */
	@Column(name = "IDENTIFYNUMBER", length = 20)
	public String getIdentifyNumber() {
		return this.identifyNumber;
	}

	/**
	 * 設置屬性證件號碼.
	 * 
	 * @param identifynumber
	 *            待設置的證件號碼的值
	 */
	public void setIdentifyNumber(String identifynumber) {
		this.identifyNumber = identifynumber;
	}

	/**
	 * 獲取屬性再保狀態.
	 * 
	 * @return 屬性再保狀態的值
	 */
	@Column(name = "REINSSTATUS", length = 1)
	public String getReinsStatus() {
		return this.reinsStatus;
	}

	/**
	 * 設置屬性再保狀態.
	 * 
	 * @param reinsstatus
	 *            待設置的再保狀態的值
	 */
	public void setReinsStatus(String reinsstatus) {
		this.reinsStatus = reinsstatus;
	}

	/**
	 * 獲取屬性保單號.
	 * 
	 * @return 屬性保單號的值
	 */
	@Column(name = "POLICYNO", length = 22)
	public String getPolicyNo() {
		return this.policyNo;
	}

	/**
	 * 設置屬性保單號.
	 * 
	 * @param policyno
	 *            待設置的保單號的值
	 */
	public void setPolicyNo(String policyno) {
		this.policyNo = policyno;
	}

	/**
	 * 獲取屬性立案號.
	 * 
	 * @return 屬性立案號的值
	 */
	@Column(name = "CLAIMNO", length = 22)
	public String getClaimNo() {
		return this.claimNo;
	}

	/**
	 * 設置屬性立案號.
	 * 
	 * @param claimno
	 *            待設置的立案號的值
	 */
	public void setClaimNo(String claimno) {
		this.claimNo = claimno;
	}

	/**
	 * 獲取屬性總保額.
	 * 
	 * @return 屬性總保額的值
	 */
	@Column(name = "SUMAMOUNT", precision = 14)
	public double getSumAmount() {
		return this.sumAmount;
	}

	/**
	 * 設置屬性總保額.
	 * 
	 * @param sumamount
	 *            待設置的總保額的值
	 */
	public void setSumAmount(double sumamount) {
		this.sumAmount = sumamount;
	}

	/**
	 * 獲取屬性總保費.
	 * 
	 * @return 屬性總保費的值
	 */
	@Column(name = "SUMPREMIUM", precision = 14)
	public double getSumPremium() {
		return this.sumPremium;
	}

	/**
	 * 設置屬性總保費.
	 * 
	 * @param sumpremium
	 *            待設置的總保費的值
	 */
	public void setSumPremium(double sumpremium) {
		this.sumPremium = sumpremium;
	}

	/**
	 * 獲取屬性操作類型.
	 * 
	 * @return 屬性操作類型的值
	 */
	@Column(name = "RESULTCODE", length = 2)
	public String getResultCode() {
		return this.resultCode;
	}

	/**
	 * 設置屬性操作類型.
	 * 
	 * @param resultcode
	 *            待設置的操作類型的值
	 */
	public void setResultCode(String resultcode) {
		this.resultCode = resultcode;
	}

	/**
	 * 獲取屬性下發或者人工的原因.
	 * 
	 * @return 屬性下發或者人工的原因的值
	 */
	@Column(name = "RESULTCONTENT", length = 4000)
	public String getResultContent() {
		return this.resultContent;
	}

	/**
	 * 設置屬性下發或者人工的原因.
	 * 
	 * @param resultcontent
	 *            待設置的下發或者人工的原因的值
	 */
	public void setResultContent(String resultcontent) {
		this.resultContent = resultcontent;
	}

	/**
	 * 獲取屬性核保通過級別.
	 * 
	 * @return 屬性核保通過級別的值
	 */
	@Column(name = "PASSLEVEL", length = 2)
	public String getPassLevel() {
		return this.passLevel;
	}

	/**
	 * 設置屬性核保通過級別.
	 * 
	 * @param passlevel
	 *            待設置的核保通過級別的值
	 */
	public void setPassLevel(String passlevel) {
		this.passLevel = passlevel;
	}

	/**
	 * 獲取屬性出單員代碼.
	 * 
	 * @return 屬性出單員代碼的值
	 */
	@Column(name = "SINGLECODE", length = 30)
	public String getSingleCode() {
		return this.singleCode;
	}

	/**
	 * 設置屬性出單員代碼.
	 * 
	 * @param singlecode
	 *            待設置的出單員代碼的值
	 */
	public void setSingleCode(String singlecode) {
		this.singleCode = singlecode;
	}

	/**
	 * 獲取屬性出單員名稱.
	 * 
	 * @return 屬性出單員名稱的值
	 */
	@Column(name = "SINGLEMEMBER", length = 30)
	public String getSingleMember() {
		return this.singleMember;
	}

	/**
	 * 設置屬性出單員名稱.
	 * 
	 * @param singlemember
	 *            待設置的出單員名稱的值
	 */
	public void setSingleMember(String singlemember) {
		this.singleMember = singlemember;
	}
	
	//@Column(name = "PRIORTYPE", length = 30)
	/**
	 * 獲取屬性the sinosoft prior type.
	 * 
	 * @return 屬性the sinosoft prior type的值
	 */
	@Transient
	public String getPriorType() {
        return priorType;
    }

    /**
	 * 設置屬性the sinosoft prior type.
	 * 
	 * @param priorType
	 *            待設置的the sinosoft prior type的值
	 */
    public void setPriorType(String priorType) {
        this.priorType = priorType;
    }
    
    /**
	 * 獲取屬性機構名稱.
	 * 
	 * @return 屬性機構名稱的值
	 */
    @Transient
    public String getComName() {
        return comName;
    }

    /**
	 * 設置屬性機構名稱.
	 * 
	 * @param comName
	 *            待設置的機構名稱的值
	 */
    public void setComName(String comName) {
        this.comName = comName;
    }
    
    /**
	 * Gets the 用户代码.
	 * 
	 * @return the 用户代码
	 */
    @Transient
    public String getUserCode() {
		return userCode;
	}

	/**
	 * Sets the 用户代码.
	 * 
	 * @param userCode
	 *            the new 用户代码
	 */
	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}
	
	/**
	 * Gets the 报价单任务状态.
	 * 
	 * @return the 报价单任务状态
	 */
	@Transient
    public String getQtaNodeStatusName()
    {
        String strNodeStatus = this.getNodeStatus();
        InternationalizationUtil internal = new InternationalizationUtil();
        if (strNodeStatus.equals("0"))
        	qtaNodeStatusName = internal.getText("undwrt.HebaoQueryQtaStats.tempSave");
        if (strNodeStatus.equals("1"))
        	qtaNodeStatusName = internal.getText("undwrt.HebaoQueryQtaStats.auditPass");
        if (strNodeStatus.equals("2"))
        	qtaNodeStatusName = internal.getText("undwrt.HebaoQueryQtaStats.auditHitBack");
        if (strNodeStatus.equals("3"))
        	qtaNodeStatusName = internal.getText("undwrt.HebaoQueryQtaStats.automaticPass");
        if (strNodeStatus.equals("4"))
        	qtaNodeStatusName = internal.getText("undwrt.HebaoQueryQtaStats.backAlter");
        if (strNodeStatus.equals("5"))
        	qtaNodeStatusName = internal.getText("undwrt.HebaoQueryQtaStats.alreadyPrint");
        if (strNodeStatus.equals("6"))
        	qtaNodeStatusName = internal.getText("undwrt.HebaoQueryQtaStats.policyConfirm");
        if (strNodeStatus.equals("7"))
        	qtaNodeStatusName = internal.getText("undwrt.HebaoQueryQtaStats.produceThrowPolicy");
        if (strNodeStatus.equals("8"))
        	qtaNodeStatusName = internal.getText("undwrt.HebaoQueryQtaStats.throwPolicyUndwortPass");
        if (strNodeStatus.equals("9"))
        	qtaNodeStatusName = internal.getText("undwrt.HebaoQueryQtaStats.waitAudit");
        return qtaNodeStatusName;
    }
    
    /**
	 * Sets the 报价单任务状态.
	 * 
	 * @param qtaNodeStatusName
	 *            the new 报价单任务状态
	 */
    public void setQtaNodeStatusName(String qtaNodeStatusName)
    {
        this.qtaNodeStatusName = StringUtils.rightTrim(qtaNodeStatusName);
    }
    
    
    /**
	 * 要保人
	 * 
	 */
       
	@Transient
	public String getAppliName() {
		return appliName;
	}

	public void setAppliName(String appliName) {
		this.appliName = appliName;
	}
	/**
	 * 保费
	 * 
	 */
	@Transient
	public int getPremium() {
		return premium;
	}

	public void setPremium(int premium) {
		this.premium = premium;
	}
	@Transient
	public String getRefuseLimiteInsurance() {
		return refuseLimiteInsurance;
	}

	public void setRefuseLimiteInsurance(String refuseLimiteInsurance) {
		this.refuseLimiteInsurance = refuseLimiteInsurance;
	}
	@Transient
	public String getListDetection() {
		return listDetection;
	}
    
	public void setListDetection(String listDetection) {
		this.listDetection = listDetection;
	}
	@Transient
	public String getRiskRating() {
		return riskRating;
	}

	public void setRiskRating(String riskRating) {
		this.riskRating = riskRating;
	}
	@Transient
	public String getWorkStatus() {
		return workStatus;
	}

	public void setWorkStatus(String workStatus) {
		this.workStatus = workStatus;
	}
	@Transient
	public String getUnderwriteflag() {
		return underwriteflag;
	}

	public void setUnderwriteflag(String underwriteflag) {
		this.underwriteflag = underwriteflag;
	}
	@Transient
	public String getJfeeflag() {
		return jfeeflag;
	}

	public void setJfeeflag(String jfeeflag) {
		this.jfeeflag = jfeeflag;
	}
	@Transient
	public String getRealpayrefflag() {
		return realpayrefflag;
	}

	public void setRealpayrefflag(String realpayrefflag) {
		this.realpayrefflag = realpayrefflag;
	}

	@Transient
	public String getSuperpay() {
		return superpay;
	}

	public void setSuperpay(String superpay) {
		this.superpay = superpay;
	}

	//mantis： CAR0369，處理人員：BI086，需求單編號：CAR0369:核心車險地址正規化作業 START
	@Transient
	public String getNormastatus() {
		return normastatus;
	}

	public void setNormastatus(String normastatus) {
		this.normastatus = normastatus;
	}
	//mantis： CAR0369，處理人員：BI086，需求單編號：CAR0369:核心車險地址正規化作業 END
}
