package com.sinosoft.undwrt.undwrtBase.model;

// Generated 2013-1-16 9:42:09 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * WfotherFees generated by hbm2java.
 */
@Entity(name = "WFOTHERFEES_UNDWRT")
@Table(name = "WFOTHERFEES")
public class WfOtherFees implements java.io.Serializable {

	/** 屬性The sinosoft id. */
	private WfOtherFeesId id;
	
	/** 屬性The sinosoft proposal no. */
	private String proposalNo;
	
	/** 屬性The sinosoft policy no. */
	private String policyNo;
	
	/** 屬性The sinosoft endorse no. */
	private String endorseNo;
	
	/** 屬性The sinosoft other fee. */
	private String otherFee;
	
	/** 屬性The sinosoft last other fee. */
	private String lastOtherFee;
	
	/** 屬性The sinosoft operate time. */
	private String operateTime;
	
	/** 屬性處理人員代碼. */
	private String operatorCode;
	
	/** 屬性The sinosoft operator name. */
	private String operatorName;
	
	/** 屬性標志. */
	private String flag;

	/**
	 * Instantiates a new wf other fees.
	 */
	public WfOtherFees() {
	}

	/**
	 * Instantiates a new wf other fees.
	 * 
	 * @param id
	 *            the id
	 * @param otherfee
	 *            the otherfee
	 * @param lastotherfee
	 *            the lastotherfee
	 * @param operatetime
	 *            the operatetime
	 * @param operatorcode
	 *            the operatorcode
	 * @param operatorname
	 *            the operatorname
	 */
	public WfOtherFees(WfOtherFeesId id, String otherfee, String lastotherfee,
			String operatetime, String operatorcode, String operatorname) {
		this.id = id;
		this.otherFee = otherfee;
		this.lastOtherFee = lastotherfee;
		this.operateTime = operatetime;
		this.operatorCode = operatorcode;
		this.operatorName = operatorname;
	}

	/**
	 * Instantiates a new wf other fees.
	 * 
	 * @param id
	 *            the id
	 * @param proposalno
	 *            the proposalno
	 * @param policyno
	 *            the policyno
	 * @param endorseno
	 *            the endorseno
	 * @param otherfee
	 *            the otherfee
	 * @param lastotherfee
	 *            the lastotherfee
	 * @param operatetime
	 *            the operatetime
	 * @param operatorcode
	 *            the operatorcode
	 * @param operatorname
	 *            the operatorname
	 * @param flag
	 *            the flag
	 */
	public WfOtherFees(WfOtherFeesId id, String proposalno, String policyno,
			String endorseno, String otherfee, String lastotherfee,
			String operatetime, String operatorcode, String operatorname,
			String flag) {
		this.id = id;
		this.proposalNo = proposalno;
		this.policyNo = policyno;
		this.endorseNo = endorseno;
		this.otherFee = otherfee;
		this.lastOtherFee = lastotherfee;
		this.operateTime = operatetime;
		this.operatorCode = operatorcode;
		this.operatorName = operatorname;
		this.flag = flag;
	}

	/**
	 * 獲取屬性the sinosoft id.
	 * 
	 * @return 屬性the sinosoft id的值
	 */
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "businessno", column = @Column(name = "BUSINESSNO", nullable = false, length = 25)),
			@AttributeOverride(name = "serialno", column = @Column(name = "SERIALNO", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "lineno", column = @Column(name = "LINENO", nullable = false, precision = 22, scale = 0)) })
	public WfOtherFeesId getId() {
		return this.id;
	}

	/**
	 * 設置屬性the sinosoft id.
	 * 
	 * @param id
	 *            待設置的the sinosoft id的值
	 */
	public void setId(WfOtherFeesId id) {
		this.id = id;
	}

	/**
	 * 獲取屬性the sinosoft proposalno.
	 * 
	 * @return 屬性the sinosoft proposalno的值
	 */
	@Column(name = "PROPOSALNO", length = 25)
	public String getProposalno() {
		return this.proposalNo;
	}

	/**
	 * 設置屬性the sinosoft proposalno.
	 * 
	 * @param proposalno
	 *            待設置的the sinosoft proposalno的值
	 */
	public void setProposalno(String proposalno) {
		this.proposalNo = proposalno;
	}

	/**
	 * 獲取屬性the sinosoft policyno.
	 * 
	 * @return 屬性the sinosoft policyno的值
	 */
	@Column(name = "POLICYNO", length = 25)
	public String getPolicyno() {
		return this.policyNo;
	}

	/**
	 * 設置屬性the sinosoft policyno.
	 * 
	 * @param policyno
	 *            待設置的the sinosoft policyno的值
	 */
	public void setPolicyno(String policyno) {
		this.policyNo = policyno;
	}

	/**
	 * 獲取屬性the sinosoft endorseno.
	 * 
	 * @return 屬性the sinosoft endorseno的值
	 */
	@Column(name = "ENDORSENO", length = 25)
	public String getEndorseno() {
		return this.endorseNo;
	}

	/**
	 * 設置屬性the sinosoft endorseno.
	 * 
	 * @param endorseno
	 *            待設置的the sinosoft endorseno的值
	 */
	public void setEndorseno(String endorseno) {
		this.endorseNo = endorseno;
	}

	/**
	 * 獲取屬性the sinosoft otherfee.
	 * 
	 * @return 屬性the sinosoft otherfee的值
	 */
	@Column(name = "OTHERFEE", nullable = false, length = 30)
	public String getOtherfee() {
		return this.otherFee;
	}

	/**
	 * 設置屬性the sinosoft otherfee.
	 * 
	 * @param otherfee
	 *            待設置的the sinosoft otherfee的值
	 */
	public void setOtherfee(String otherfee) {
		this.otherFee = otherfee;
	}

	/**
	 * 獲取屬性the sinosoft lastotherfee.
	 * 
	 * @return 屬性the sinosoft lastotherfee的值
	 */
	@Column(name = "LASTOTHERFEE", nullable = false, length = 30)
	public String getLastotherfee() {
		return this.lastOtherFee;
	}

	/**
	 * 設置屬性the sinosoft lastotherfee.
	 * 
	 * @param lastotherfee
	 *            待設置的the sinosoft lastotherfee的值
	 */
	public void setLastotherfee(String lastotherfee) {
		this.lastOtherFee = lastotherfee;
	}

	/**
	 * 獲取屬性the sinosoft operatetime.
	 * 
	 * @return 屬性the sinosoft operatetime的值
	 */
	@Column(name = "OPERATETIME", nullable = false, length = 19)
	public String getOperatetime() {
		return this.operateTime;
	}

	/**
	 * 設置屬性the sinosoft operatetime.
	 * 
	 * @param operatetime
	 *            待設置的the sinosoft operatetime的值
	 */
	public void setOperatetime(String operatetime) {
		this.operateTime = operatetime;
	}

	/**
	 * 獲取屬性the sinosoft operatorcode.
	 * 
	 * @return 屬性the sinosoft operatorcode的值
	 */
	@Column(name = "OPERATORCODE", nullable = false, length = 10)
	public String getOperatorcode() {
		return this.operatorCode;
	}

	/**
	 * 設置屬性the sinosoft operatorcode.
	 * 
	 * @param operatorcode
	 *            待設置的the sinosoft operatorcode的值
	 */
	public void setOperatorcode(String operatorcode) {
		this.operatorCode = operatorcode;
	}

	/**
	 * 獲取屬性the sinosoft operatorname.
	 * 
	 * @return 屬性the sinosoft operatorname的值
	 */
	@Column(name = "OPERATORNAME", nullable = false, length = 30)
	public String getOperatorname() {
		return this.operatorName;
	}

	/**
	 * 設置屬性the sinosoft operatorname.
	 * 
	 * @param operatorname
	 *            待設置的the sinosoft operatorname的值
	 */
	public void setOperatorname(String operatorname) {
		this.operatorName = operatorname;
	}

	/**
	 * 獲取屬性標志.
	 * 
	 * @return 屬性標志的值
	 */
	@Column(name = "FLAG", length = 2)
	public String getFlag() {
		return this.flag;
	}

	/**
	 * 設置屬性標志.
	 * 
	 * @param flag
	 *            待設置的標志的值
	 */
	public void setFlag(String flag) {
		this.flag = flag;
	}

}
