package com.sinosoft.undwrt.undwrtBase.model;

// Generated 2013-1-23 17:09:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * WfPackage generated by hbm2java.
 */
@Entity(name = "WFPACKAGE_UNDWRT")
@Table(name = "WFPACKAGE")
public class WfPackage implements java.io.Serializable {

	/** 屬性id. */
	private WfPackageId id;
	
	/** 屬性明細項內容. */
	private String detailContent;
	
	/** 屬性標志. */
	private String flag;

	/**
	 * Instantiates a new wf package.
	 */
	public WfPackage() {
	}

	/**
	 * Instantiates a new wf package.
	 * 
	 * @param id
	 *            id
	 * @param detailcontent
	 *            明細項內容
	 */
	public WfPackage(WfPackageId id, String detailcontent) {
		this.id = id;
		this.detailContent = detailcontent;
	}

	/**
	 * Instantiates a new wf package.
	 * 
	 * @param id
	 *            id
	 * @param detailcontent
	 *            明細項內容
	 * @param flag
	 *            標志
	 */
	public WfPackage(WfPackageId id, String detailcontent, String flag) {
		this.id = id;
		this.detailContent = detailcontent;
		this.flag = flag;
	}

	/**
	 * 獲取屬性id.
	 * 
	 * @return 屬性id的值
	 */
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "packageid", column = @Column(name = "PACKAGEID", nullable = false, length = 27)),
			@AttributeOverride(name = "detailno", column = @Column(name = "DETAILNO", nullable = false, precision = 15, scale = 0)) })
	public WfPackageId getId() {
		return this.id;
	}

	/**
	 * 設置屬性id.
	 * 
	 * @param id
	 *            待設置的id的值
	 */
	public void setId(WfPackageId id) {
		this.id = id;
	}

	/**
	 * 獲取屬性明細項內容.
	 * 
	 * @return 屬性明細項內容的值
	 */
	@Column(name = "DETAILCONTENT", nullable = false, length = 76)
	public String getDetailContent() {
		return this.detailContent;
	}

	/**
	 * 設置屬性明細項內容.
	 * 
	 * @param detailcontent
	 *            待設置的明細項內容的值
	 */
	public void setDetailContent(String detailcontent) {
		this.detailContent = detailcontent;
	}

	/**
	 * 獲取屬性標志.
	 * 
	 * @return 屬性標志的值
	 */
	@Column(name = "FLAG", length = 10)
	public String getFlag() {
		return this.flag;
	}

	/**
	 * 設置屬性標志.
	 * 
	 * @param flag
	 *            待設置的標志的值
	 */
	public void setFlag(String flag) {
		this.flag = flag;
	}

}
