package com.tlg.db2.entity;

import java.math.BigDecimal;

import com.tlg.iBatis.IBatisBaseEntity;

public class Com051we extends IBatisBaseEntity<BigDecimal>{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COM051WE.WE01
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    private String we01;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COM051WE.WE02
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    private String we02;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COM051WE.WE03
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    private String we03;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COM051WE.WE04
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    private String we04;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COM051WE.WE05
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    private String we05;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COM051WE.WE06
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    private String we06;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COM051WE.WE07
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    private String we07;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COM051WE.WE08
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    private String we08;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COM051WE.WE09
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    private String we09;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COM051WE.WE11
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    private String we11;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COM051WE.WE12
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    private String we12;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COM051WE.WE13
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    private String we13;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COM051WE.WE14
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    private String we14;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COM051WE.WE15
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    private String we15;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COM051WE.WE16
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    private String we16;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COM051WE.WE17
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    private String we17;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COM051WE.WE18
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    private String we18;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COM051WE.WE20
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    private String we20;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COM051WE.WE21
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    private Integer we21;
    
    private String we22;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COM051WE.WE01
     *
     * @return the value of COM051WE.WE01
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public String getWe01() {
        return we01;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COM051WE.WE01
     *
     * @param we01 the value for COM051WE.WE01
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public void setWe01(String we01) {
        this.we01 = we01;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COM051WE.WE02
     *
     * @return the value of COM051WE.WE02
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public String getWe02() {
        return we02;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COM051WE.WE02
     *
     * @param we02 the value for COM051WE.WE02
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public void setWe02(String we02) {
        this.we02 = we02;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COM051WE.WE03
     *
     * @return the value of COM051WE.WE03
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public String getWe03() {
        return we03;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COM051WE.WE03
     *
     * @param we03 the value for COM051WE.WE03
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public void setWe03(String we03) {
        this.we03 = we03;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COM051WE.WE04
     *
     * @return the value of COM051WE.WE04
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public String getWe04() {
        return we04;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COM051WE.WE04
     *
     * @param we04 the value for COM051WE.WE04
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public void setWe04(String we04) {
        this.we04 = we04;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COM051WE.WE05
     *
     * @return the value of COM051WE.WE05
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public String getWe05() {
        return we05;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COM051WE.WE05
     *
     * @param we05 the value for COM051WE.WE05
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public void setWe05(String we05) {
        this.we05 = we05;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COM051WE.WE06
     *
     * @return the value of COM051WE.WE06
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public String getWe06() {
        return we06;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COM051WE.WE06
     *
     * @param we06 the value for COM051WE.WE06
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public void setWe06(String we06) {
        this.we06 = we06;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COM051WE.WE07
     *
     * @return the value of COM051WE.WE07
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public String getWe07() {
        return we07;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COM051WE.WE07
     *
     * @param we07 the value for COM051WE.WE07
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public void setWe07(String we07) {
        this.we07 = we07;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COM051WE.WE08
     *
     * @return the value of COM051WE.WE08
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public String getWe08() {
        return we08;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COM051WE.WE08
     *
     * @param we08 the value for COM051WE.WE08
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public void setWe08(String we08) {
        this.we08 = we08;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COM051WE.WE09
     *
     * @return the value of COM051WE.WE09
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public String getWe09() {
        return we09;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COM051WE.WE09
     *
     * @param we09 the value for COM051WE.WE09
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public void setWe09(String we09) {
        this.we09 = we09;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COM051WE.WE11
     *
     * @return the value of COM051WE.WE11
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public String getWe11() {
        return we11;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COM051WE.WE11
     *
     * @param we11 the value for COM051WE.WE11
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public void setWe11(String we11) {
        this.we11 = we11;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COM051WE.WE12
     *
     * @return the value of COM051WE.WE12
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public String getWe12() {
        return we12;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COM051WE.WE12
     *
     * @param we12 the value for COM051WE.WE12
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public void setWe12(String we12) {
        this.we12 = we12;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COM051WE.WE13
     *
     * @return the value of COM051WE.WE13
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public String getWe13() {
        return we13;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COM051WE.WE13
     *
     * @param we13 the value for COM051WE.WE13
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public void setWe13(String we13) {
        this.we13 = we13;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COM051WE.WE14
     *
     * @return the value of COM051WE.WE14
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public String getWe14() {
        return we14;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COM051WE.WE14
     *
     * @param we14 the value for COM051WE.WE14
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public void setWe14(String we14) {
        this.we14 = we14;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COM051WE.WE15
     *
     * @return the value of COM051WE.WE15
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public String getWe15() {
        return we15;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COM051WE.WE15
     *
     * @param we15 the value for COM051WE.WE15
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public void setWe15(String we15) {
        this.we15 = we15;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COM051WE.WE16
     *
     * @return the value of COM051WE.WE16
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public String getWe16() {
        return we16;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COM051WE.WE16
     *
     * @param we16 the value for COM051WE.WE16
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public void setWe16(String we16) {
        this.we16 = we16;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COM051WE.WE17
     *
     * @return the value of COM051WE.WE17
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public String getWe17() {
        return we17;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COM051WE.WE17
     *
     * @param we17 the value for COM051WE.WE17
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public void setWe17(String we17) {
        this.we17 = we17;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COM051WE.WE18
     *
     * @return the value of COM051WE.WE18
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public String getWe18() {
        return we18;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COM051WE.WE18
     *
     * @param we18 the value for COM051WE.WE18
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public void setWe18(String we18) {
        this.we18 = we18;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COM051WE.WE20
     *
     * @return the value of COM051WE.WE20
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public String getWe20() {
        return we20;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COM051WE.WE20
     *
     * @param we20 the value for COM051WE.WE20
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public void setWe20(String we20) {
        this.we20 = we20;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COM051WE.WE21
     *
     * @return the value of COM051WE.WE21
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public Integer getWe21() {
        return we21;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COM051WE.WE21
     *
     * @param we21 the value for COM051WE.WE21
     *
     * @ibatorgenerated Fri Feb 18 14:53:44 CST 2022
     */
    public void setWe21(Integer we21) {
        this.we21 = we21;
    }

	public String getWe22() {
		return we22;
	}

	public void setWe22(String we22) {
		this.we22 = we22;
	}
}