package com.tlg.db2.entity;

import com.tlg.iBatis.IBatisBaseEntity;

@SuppressWarnings("serial")
public class Com910wb extends IBatisBaseEntity<String>{

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column COM910WB.WB01
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	private String wb01;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column COM910WB.WB02
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	private String wb02;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column COM910WB.WB03
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	private String wb03;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column COM910WB.WB04
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	private String wb04;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column COM910WB.WB05
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	private String wb05;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column COM910WB.WB06
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	private String wb06;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column COM910WB.WB07
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	private String wb07;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column COM910WB.WB08
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	private String wb08;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column COM910WB.WB09
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	private String wb09;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column COM910WB.WB10
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	private String wb10;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column COM910WB.WB11
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	private String wb11;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column COM910WB.WB12
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	private String wb12;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column COM910WB.WB13
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	private String wb13;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column COM910WB.WB14
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	private String wb14;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column COM910WB.WB15
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	private String wb15;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column COM910WB.WB16
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	private String wb16;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column COM910WB.WB17
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	private String wb17;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column COM910WB.WB18
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	private String wb18;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column COM910WB.WB19
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	private String wb19;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column COM910WB.WB20
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	private String wb20;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column COM910WB.WB21
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	private String wb21;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column COM910WB.WB22
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	private String wb22;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column COM910WB.WB23
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	private String wb23;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column COM910WB.WB01
	 * @return  the value of COM910WB.WB01
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public String getWb01() {
		return wb01;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column COM910WB.WB01
	 * @param wb01  the value for COM910WB.WB01
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public void setWb01(String wb01) {
		this.wb01 = wb01;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column COM910WB.WB02
	 * @return  the value of COM910WB.WB02
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public String getWb02() {
		return wb02;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column COM910WB.WB02
	 * @param wb02  the value for COM910WB.WB02
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public void setWb02(String wb02) {
		this.wb02 = wb02;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column COM910WB.WB03
	 * @return  the value of COM910WB.WB03
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public String getWb03() {
		return wb03;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column COM910WB.WB03
	 * @param wb03  the value for COM910WB.WB03
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public void setWb03(String wb03) {
		this.wb03 = wb03;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column COM910WB.WB04
	 * @return  the value of COM910WB.WB04
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public String getWb04() {
		return wb04;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column COM910WB.WB04
	 * @param wb04  the value for COM910WB.WB04
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public void setWb04(String wb04) {
		this.wb04 = wb04;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column COM910WB.WB05
	 * @return  the value of COM910WB.WB05
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public String getWb05() {
		return wb05;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column COM910WB.WB05
	 * @param wb05  the value for COM910WB.WB05
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public void setWb05(String wb05) {
		this.wb05 = wb05;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column COM910WB.WB06
	 * @return  the value of COM910WB.WB06
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public String getWb06() {
		return wb06;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column COM910WB.WB06
	 * @param wb06  the value for COM910WB.WB06
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public void setWb06(String wb06) {
		this.wb06 = wb06;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column COM910WB.WB07
	 * @return  the value of COM910WB.WB07
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public String getWb07() {
		return wb07;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column COM910WB.WB07
	 * @param wb07  the value for COM910WB.WB07
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public void setWb07(String wb07) {
		this.wb07 = wb07;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column COM910WB.WB08
	 * @return  the value of COM910WB.WB08
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public String getWb08() {
		return wb08;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column COM910WB.WB08
	 * @param wb08  the value for COM910WB.WB08
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public void setWb08(String wb08) {
		this.wb08 = wb08;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column COM910WB.WB09
	 * @return  the value of COM910WB.WB09
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public String getWb09() {
		return wb09;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column COM910WB.WB09
	 * @param wb09  the value for COM910WB.WB09
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public void setWb09(String wb09) {
		this.wb09 = wb09;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column COM910WB.WB10
	 * @return  the value of COM910WB.WB10
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public String getWb10() {
		return wb10;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column COM910WB.WB10
	 * @param wb10  the value for COM910WB.WB10
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public void setWb10(String wb10) {
		this.wb10 = wb10;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column COM910WB.WB11
	 * @return  the value of COM910WB.WB11
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public String getWb11() {
		return wb11;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column COM910WB.WB11
	 * @param wb11  the value for COM910WB.WB11
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public void setWb11(String wb11) {
		this.wb11 = wb11;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column COM910WB.WB12
	 * @return  the value of COM910WB.WB12
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public String getWb12() {
		return wb12;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column COM910WB.WB12
	 * @param wb12  the value for COM910WB.WB12
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public void setWb12(String wb12) {
		this.wb12 = wb12;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column COM910WB.WB13
	 * @return  the value of COM910WB.WB13
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public String getWb13() {
		return wb13;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column COM910WB.WB13
	 * @param wb13  the value for COM910WB.WB13
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public void setWb13(String wb13) {
		this.wb13 = wb13;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column COM910WB.WB14
	 * @return  the value of COM910WB.WB14
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public String getWb14() {
		return wb14;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column COM910WB.WB14
	 * @param wb14  the value for COM910WB.WB14
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public void setWb14(String wb14) {
		this.wb14 = wb14;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column COM910WB.WB15
	 * @return  the value of COM910WB.WB15
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public String getWb15() {
		return wb15;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column COM910WB.WB15
	 * @param wb15  the value for COM910WB.WB15
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public void setWb15(String wb15) {
		this.wb15 = wb15;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column COM910WB.WB16
	 * @return  the value of COM910WB.WB16
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public String getWb16() {
		return wb16;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column COM910WB.WB16
	 * @param wb16  the value for COM910WB.WB16
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public void setWb16(String wb16) {
		this.wb16 = wb16;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column COM910WB.WB17
	 * @return  the value of COM910WB.WB17
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public String getWb17() {
		return wb17;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column COM910WB.WB17
	 * @param wb17  the value for COM910WB.WB17
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public void setWb17(String wb17) {
		this.wb17 = wb17;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column COM910WB.WB18
	 * @return  the value of COM910WB.WB18
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public String getWb18() {
		return wb18;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column COM910WB.WB18
	 * @param wb18  the value for COM910WB.WB18
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public void setWb18(String wb18) {
		this.wb18 = wb18;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column COM910WB.WB19
	 * @return  the value of COM910WB.WB19
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public String getWb19() {
		return wb19;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column COM910WB.WB19
	 * @param wb19  the value for COM910WB.WB19
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public void setWb19(String wb19) {
		this.wb19 = wb19;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column COM910WB.WB20
	 * @return  the value of COM910WB.WB20
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public String getWb20() {
		return wb20;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column COM910WB.WB20
	 * @param wb20  the value for COM910WB.WB20
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public void setWb20(String wb20) {
		this.wb20 = wb20;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column COM910WB.WB21
	 * @return  the value of COM910WB.WB21
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public String getWb21() {
		return wb21;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column COM910WB.WB21
	 * @param wb21  the value for COM910WB.WB21
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public void setWb21(String wb21) {
		this.wb21 = wb21;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column COM910WB.WB22
	 * @return  the value of COM910WB.WB22
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public String getWb22() {
		return wb22;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column COM910WB.WB22
	 * @param wb22  the value for COM910WB.WB22
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public void setWb22(String wb22) {
		this.wb22 = wb22;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column COM910WB.WB23
	 * @return  the value of COM910WB.WB23
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public String getWb23() {
		return wb23;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column COM910WB.WB23
	 * @param wb23  the value for COM910WB.WB23
	 * @ibatorgenerated  Fri Jul 07 14:17:21 CST 2023
	 */
	public void setWb23(String wb23) {
		this.wb23 = wb23;
	}
}