#drools agent configuration
drools.agent.newInstance=false
drools.agent.scanDirectories=true

#drools resource configuration
drools.resource.scanner.interval=3
drools.resource.urlcache=C:/Users/icer/temp