package com.tlg.aps.vo;

import java.util.Date;

public class Aps002DetailVo {
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_CTBC_BATCH_DTL.ORDER_SEQ_STATUS
    *
    * @mbg.generated Thu Mar 19 17:18:25 CST 2020
    */
   private String orderSeqStatus;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_CTBC_BATCH_DTL.FK_STATUS
    *
    * @mbg.generated Thu Mar 19 17:18:25 CST 2020
    */
   private String fkStatus;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_CTBC_BATCH_DTL.DQUAKE_STATUS
    *
    * @mbg.generated Thu Mar 19 17:18:25 CST 2020
    */
   private String dquakeStatus;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_CTBC_BATCH_DTL.DQUAKE_NO
    *
    * @mbg.generated Thu Mar 19 17:18:25 CST 2020
    */
   private String dquakeNo;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_CTBC_BATCH_DTL.OID_FIR_PREMCALC_TMP
    *
    * @mbg.generated Thu Mar 19 17:18:25 CST 2020
    */
   private Long oidFirPremcalcTmp;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_CTBC_BATCH_DTL.FAMT_STATUS
    *
    * @mbg.generated Thu Mar 19 17:18:25 CST 2020
    */
   private String famtStatus;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_CTBC_BATCH_DTL.WS_FIR_AMT
    *
    * @mbg.generated Thu Mar 19 17:18:25 CST 2020
    */
   private Long wsFirAmt;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_CTBC_BATCH_DTL.QAMT_STATUS
    *
    * @mbg.generated Thu Mar 19 17:18:25 CST 2020
    */
   private String qamtStatus;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_CTBC_BATCH_DTL.WS_QUAKE_AMT
    *
    * @mbg.generated Thu Mar 19 17:18:25 CST 2020
    */
   private Integer wsQuakeAmt;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_CTBC_BATCH_DTL.ADDR_STATUS
    *
    * @mbg.generated Thu Mar 19 17:18:25 CST 2020
    */
   private String addrStatus;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_CTBC_BATCH_DTL.ADDR_DETAIL
    *
    * @mbg.generated Thu Mar 19 17:18:25 CST 2020
    */
   private String addrDetail;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_CTBC_BATCH_DTL.IS_TIFF
    *
    * @mbg.generated Thu Mar 19 17:18:25 CST 2020
    */
   private String isTiff;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_CTBC_BATCH_DTL.FILENAME_TIFF
    *
    * @mbg.generated Thu Mar 19 17:18:25 CST 2020
    */
   private String filenameTiff;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_CTBC_BATCH_DTL.CHECK_ERR_MSG
    *
    * @mbg.generated Thu Mar 19 17:18:25 CST 2020
    */
   private String checkErrMsg;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_CTBC_BATCH_DTL.CHECK_WARN_MSG
    *
    * @mbg.generated Thu Mar 19 17:18:25 CST 2020
    */
   private String checkWarnMsg;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_CTBC_BATCH_DTL.TRANS_TMP_TIME
    *
    * @mbg.generated Thu Mar 19 17:18:25 CST 2020
    */
   private Date transTmpTime;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_CTBC_BATCH_DTL.TRANS_PPS_TIME
    *
    * @mbg.generated Thu Mar 19 17:18:25 CST 2020
    */
   private Date transPpsTime;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_CTBC_BATCH_DTL.PRINT_CTF_TIME
    *
    * @mbg.generated Thu Mar 19 17:18:25 CST 2020
    */
   private Date printCtfTime;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_CTBC_BATCH_DTL.POLICYNO
    *
    * @mbg.generated Thu Mar 19 17:18:25 CST 2020
    */
   private String policyno;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_CTBC_BATCH_DTL.CORE_CANCEL_USER
    *
    * @mbg.generated Thu Mar 19 17:18:25 CST 2020
    */
   private String coreCancelUser;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_CTBC_BATCH_DTL.CORE_CANCEL_TIME
    *
    * @mbg.generated Thu Mar 19 17:18:25 CST 2020
    */
   private Date coreCancelTime;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_CTBC_BATCH_DTL.BK_TIME
    *
    * @mbg.generated Thu Mar 19 17:18:25 CST 2020
    */
   private Date bkTime;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_CTBC_BATCH_DTL.BK_FILENAME
    *
    * @mbg.generated Thu Mar 19 17:18:25 CST 2020
    */
   private String bkFilename;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_CTBC_BATCH_DTL.BK_TYPE
    *
    * @mbg.generated Thu Mar 19 17:18:25 CST 2020
    */
   private String bkType;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_CTBC_BATCH_DTL.DELETE_FLAG
    *
    * @mbg.generated Thu Mar 19 17:18:25 CST 2020
    */
   private String deleteFlag;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_CTBC_BATCH_DTL.ICREATE
    *
    * @mbg.generated Thu Mar 19 17:18:25 CST 2020
    */
   private String icreate;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_CTBC_BATCH_DTL.DCREATE
    *
    * @mbg.generated Thu Mar 19 17:18:25 CST 2020
    */
   private Date dcreate;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_CTBC_BATCH_DTL.IUPDATE
    *
    * @mbg.generated Thu Mar 19 17:18:25 CST 2020
    */
   private String iupdate;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column FIR_CTBC_BATCH_DTL.DUPDATE
    *
    * @mbg.generated Thu Mar 19 17:18:25 CST 2020
    */
   private Date dupdate;
   
   /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column FIR_CTBC_BATCH_DTL.BATCH_NO
   *
   * @mbg.generated Thu Mar 19 17:18:25 CST 2020
   */
  private String batchNo;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column FIR_CTBC_BATCH_DTL.BATCH_SEQ
   *
   * @mbg.generated Thu Mar 19 17:18:25 CST 2020
   */
  private String batchSeq;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column FIR_CTBC_BATCH_DTL.FK_ORDER_SEQ
   *
   * @mbg.generated Thu Mar 19 17:18:25 CST 2020
   */
  private String fkOrderSeq;
  
  private String prpinsBatchNo;
  private String prpinsBatchStatus;
  private String prpinsBatchErrmsg;
  private String spBatchNo;
  private String proposalno;
  private String ctfOid;
  private String sendType;
  private String commCenterCode;
  /*mantis：FIR0181， 中信新件流程-排程查詢作業(含產生查詢及回饋查詢) start*/
  private String appliname;
  private String insuredname;
  private String handler1code;
  private String comcode;
  private String handleridentifynumber;
  private String handlername;
  private String coreComcode;
  /*mantis：FIR0181， 中信新件流程-排程查詢作業(含產生查詢及回饋查詢) end*/
  
	public String getOrderSeqStatus() {
		return orderSeqStatus;
	}
	public void setOrderSeqStatus(String orderSeqStatus) {
		this.orderSeqStatus = orderSeqStatus;
	}
	public String getFkStatus() {
		return fkStatus;
	}
	public void setFkStatus(String fkStatus) {
		this.fkStatus = fkStatus;
	}
	public String getDquakeStatus() {
		return dquakeStatus;
	}
	public void setDquakeStatus(String dquakeStatus) {
		this.dquakeStatus = dquakeStatus;
	}
	public String getDquakeNo() {
		return dquakeNo;
	}
	public void setDquakeNo(String dquakeNo) {
		this.dquakeNo = dquakeNo;
	}
	public Long getOidFirPremcalcTmp() {
		return oidFirPremcalcTmp;
	}
	public void setOidFirPremcalcTmp(Long oidFirPremcalcTmp) {
		this.oidFirPremcalcTmp = oidFirPremcalcTmp;
	}
	public String getFamtStatus() {
		return famtStatus;
	}
	public void setFamtStatus(String famtStatus) {
		this.famtStatus = famtStatus;
	}
	public Long getWsFirAmt() {
		return wsFirAmt;
	}
	public void setWsFirAmt(Long wsFirAmt) {
		this.wsFirAmt = wsFirAmt;
	}
	public String getQamtStatus() {
		return qamtStatus;
	}
	public void setQamtStatus(String qamtStatus) {
		this.qamtStatus = qamtStatus;
	}
	public Integer getWsQuakeAmt() {
		return wsQuakeAmt;
	}
	public void setWsQuakeAmt(Integer wsQuakeAmt) {
		this.wsQuakeAmt = wsQuakeAmt;
	}
	public String getAddrStatus() {
		return addrStatus;
	}
	public void setAddrStatus(String addrStatus) {
		this.addrStatus = addrStatus;
	}
	public String getAddrDetail() {
		return addrDetail;
	}
	public void setAddrDetail(String addrDetail) {
		this.addrDetail = addrDetail;
	}
	public String getIsTiff() {
		return isTiff;
	}
	public void setIsTiff(String isTiff) {
		this.isTiff = isTiff;
	}
	public String getFilenameTiff() {
		return filenameTiff;
	}
	public void setFilenameTiff(String filenameTiff) {
		this.filenameTiff = filenameTiff;
	}
	public String getCheckErrMsg() {
		return checkErrMsg;
	}
	public void setCheckErrMsg(String checkErrMsg) {
		this.checkErrMsg = checkErrMsg;
	}
	public String getCheckWarnMsg() {
		return checkWarnMsg;
	}
	public void setCheckWarnMsg(String checkWarnMsg) {
		this.checkWarnMsg = checkWarnMsg;
	}
	public Date getTransTmpTime() {
		return transTmpTime;
	}
	public void setTransTmpTime(Date transTmpTime) {
		this.transTmpTime = transTmpTime;
	}
	public Date getTransPpsTime() {
		return transPpsTime;
	}
	public void setTransPpsTime(Date transPpsTime) {
		this.transPpsTime = transPpsTime;
	}
	public Date getPrintCtfTime() {
		return printCtfTime;
	}
	public void setPrintCtfTime(Date printCtfTime) {
		this.printCtfTime = printCtfTime;
	}
	public String getPolicyno() {
		return policyno;
	}
	public void setPolicyno(String policyno) {
		this.policyno = policyno;
	}
	public String getCoreCancelUser() {
		return coreCancelUser;
	}
	public void setCoreCancelUser(String coreCancelUser) {
		this.coreCancelUser = coreCancelUser;
	}
	public Date getCoreCancelTime() {
		return coreCancelTime;
	}
	public void setCoreCancelTime(Date coreCancelTime) {
		this.coreCancelTime = coreCancelTime;
	}
	public Date getBkTime() {
		return bkTime;
	}
	public void setBkTime(Date bkTime) {
		this.bkTime = bkTime;
	}
	public String getBkFilename() {
		return bkFilename;
	}
	public void setBkFilename(String bkFilename) {
		this.bkFilename = bkFilename;
	}
	public String getBkType() {
		return bkType;
	}
	public void setBkType(String bkType) {
		this.bkType = bkType;
	}
	public String getDeleteFlag() {
		return deleteFlag;
	}
	public void setDeleteFlag(String deleteFlag) {
		this.deleteFlag = deleteFlag;
	}
	public String getIcreate() {
		return icreate;
	}
	public void setIcreate(String icreate) {
		this.icreate = icreate;
	}
	public Date getDcreate() {
		return dcreate;
	}
	public void setDcreate(Date dcreate) {
		this.dcreate = dcreate;
	}
	public String getIupdate() {
		return iupdate;
	}
	public void setIupdate(String iupdate) {
		this.iupdate = iupdate;
	}
	public Date getDupdate() {
		return dupdate;
	}
	public void setDupdate(Date dupdate) {
		this.dupdate = dupdate;
	}
	public String getBatchNo() {
		return batchNo;
	}
	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}
	public String getBatchSeq() {
		return batchSeq;
	}
	public void setBatchSeq(String batchSeq) {
		this.batchSeq = batchSeq;
	}
	public String getFkOrderSeq() {
		return fkOrderSeq;
	}
	public void setFkOrderSeq(String fkOrderSeq) {
		this.fkOrderSeq = fkOrderSeq;
	}
	public String getPrpinsBatchNo() {
		return prpinsBatchNo;
	}
	public void setPrpinsBatchNo(String prpinsBatchNo) {
		this.prpinsBatchNo = prpinsBatchNo;
	}
	public String getPrpinsBatchStatus() {
		return prpinsBatchStatus;
	}
	public void setPrpinsBatchStatus(String prpinsBatchStatus) {
		this.prpinsBatchStatus = prpinsBatchStatus;
	}
	public String getPrpinsBatchErrmsg() {
		return prpinsBatchErrmsg;
	}
	public void setPrpinsBatchErrmsg(String prpinsBatchErrmsg) {
		this.prpinsBatchErrmsg = prpinsBatchErrmsg;
	}
	public String getSpBatchNo() {
		return spBatchNo;
	}
	public void setSpBatchNo(String spBatchNo) {
		this.spBatchNo = spBatchNo;
	}
	public String getProposalno() {
		return proposalno;
	}
	public void setProposalno(String proposalno) {
		this.proposalno = proposalno;
	}
	public String getCtfOid() {
		return ctfOid;
	}
	public void setCtfOid(String ctfOid) {
		this.ctfOid = ctfOid;
	}
	public String getSendType() {
		return sendType;
	}
	public void setSendType(String sendType) {
		this.sendType = sendType;
	}
	public String getCommCenterCode() {
		return commCenterCode;
	}
	public void setCommCenterCode(String commCenterCode) {
		this.commCenterCode = commCenterCode;
	}
	/*mantis：FIR0181， 中信新件流程-排程查詢作業(含產生查詢及回饋查詢) start*/
	public String getAppliname() {
		return appliname;
	}
	public void setAppliname(String appliname) {
		this.appliname = appliname;
	}
	public String getInsuredname() {
		return insuredname;
	}
	public void setInsuredname(String insuredname) {
		this.insuredname = insuredname;
	}
	public String getHandler1code() {
		return handler1code;
	}
	public void setHandler1code(String handler1code) {
		this.handler1code = handler1code;
	}
	public String getComcode() {
		return comcode;
	}
	public void setComcode(String comcode) {
		this.comcode = comcode;
	}
	public String getHandleridentifynumber() {
		return handleridentifynumber;
	}
	public void setHandleridentifynumber(String handleridentifynumber) {
		this.handleridentifynumber = handleridentifynumber;
	}
	public String getHandlername() {
		return handlername;
	}
	public void setHandlername(String handlername) {
		this.handlername = handlername;
	}
	public String getCoreComcode() {
		return coreComcode;
	}
	public void setCoreComcode(String coreComcode) {
		this.coreComcode = coreComcode;
	}
	/*mantis：FIR0181， 中信新件流程-排程查詢作業(含產生查詢及回饋查詢) end*/
}
