
package com.tlg.aps.webService.firCalPremService.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2021-05-31T10:13:11.302+08:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "Exception", targetNamespace = "http://server.firCalService.webService.cwp.tlg.com/")
public class Exception_Exception extends java.lang.Exception {
    
    private com.tlg.aps.webService.firCalPremService.client.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, com.tlg.aps.webService.firCalPremService.client.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, com.tlg.aps.webService.firCalPremService.client.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.tlg.aps.webService.firCalPremService.client.Exception getFaultInfo() {
        return this.exception;
    }
}
