#\u914d\u7f6e\u6587\u4ef6\uff08log.properties \uff09
#\u914d\u7f6e\u6587\u4ef6\u5b58\u653e\u8def\u5f84D:\Workarea
log4j.rootLogger=info,stdout,Rfile
log4j.logger.com.sinosoft=info,stdout,Rfile
log4j.logger.com.sinosoft.undwrt.undwrtDeal.web.CommonDealSubmitAction=INFO, debug
log4j.logger.com.sinosoft.undwrt.undwrtDeal.service.spring.CommonDealSubmitServiceSpringImpl=INFO, debug
log4j.logger.com.sinosoft.undwrt.undwrtDeal.service.spring.CommonDealSubmitServiceSpringImpl=INFO,loggerRenewal
log4j.logger.com.sinosoft.undwrt.undwrtInterface.service.spring.TaskServiceSpringImpl=INFO,undwrt
log4j.logger.com.sinosoft.undwrt.undwrtDeal.service.spring.PrpFeedBackServiceSpringImpl=INFO,undwrt
log4j.logger.com.sinosoft.undwrt.undwrtDeal.service.spring.CommonDealSubmitServiceSpringImpl=INFO, undwrt
log4j.logger.com.sinosoft.undwrt.undwrtInterface.servlet.UndwrtTaskSubmitServlet=INFO,loggerRenewal
log4j.logger.com.sinosoft.undwrt.undwrtInterface.service.spring.TaskServiceSpringImpl=INFO,loggerRenewal
#first appender writes to console
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern= %-4r - %m%n

#second appender writes to file
log4j.appender.Rfile=org.apache.log4j.DailyRollingFileAppender
log4j.appender.Rfile.file=uwweb.log
log4j.appender.Rfile.layout=org.apache.log4j.PatternLayout
log4j.appender.Rfile.layout.ConversionPattern=%10d %-4r %-5p %c %x - %m%n

#logs for genDummyCode debug
log4j.appender.debug=org.apache.log4j.DailyRollingFileAppender
log4j.appender.debug.File=genDummyCode.log
log4j.appender.debug.layout=org.apache.log4j.PatternLayout
log4j.appender.debug.layout.ConversionPattern=%10d %-4r %-5p %c %x - %m%n

#logs for TtoUndwrt undwrt
log4j.appender.undwrt=org.apache.log4j.DailyRollingFileAppender
log4j.appender.undwrt.File=TtoUndwrt.log
log4j.appender.undwrt.layout=org.apache.log4j.PatternLayout
log4j.appender.undwrt.layout.ConversionPattern=%10d %-4r %-5p %c %x - %m%n  

 #logs for renewal loggerRenewal
log4j.appender.loggerRenewal=org.apache.log4j.DailyRollingFileAppender
log4j.appender.loggerRenewal.File=renewalListenUndwrt.log
log4j.appender.loggerRenewal.layout=org.apache.log4j.PatternLayout
log4j.appender.loggerRenewal.layout.ConversionPattern=[%-5p] %d{yyyy-MM-dd HH:mm:ss,SSS} method:%l%n%m%n