package cn.com.sinosoft.dms.vo;

// Generated by Hibernate Tools 3.2.0.b9 (sinosoft version)
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PrpDplane generated by Tools.Don't edit.
 */
@Entity
@Table(name = "PRPDPLANE")
public class PrpDplane implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    /** ע��� */
    private String            licenceNo;
    /** �ɻ�����(1�����2խ���3�����) */
    private String            planeType;
    /** ����/�㱸���ͺ� */
    private String            model;
    /** ��� */
    private String            factoryNo;
    /** ������ */
    private Date              factoryDate;
    /** ������� */
    private Date              makeYear;
    /** ���չ�˾������ */
    private String            airlineCname;
    /** ���չ�˾Ӣ���� */
    private String            airlineEname;
    /** ���з�Χ��W-WIDE��DOME�� */
    private String            range;
    /** ��λ�� */
    private BigDecimal        seatCount;
    /** �������L���⣬P������ */
    private String            loanStaus;
    /** �ɻ���;��1 CARGO��2 PASSENGER��3 BOTH�� */
    private String            planeUsage;
    /** ��ԪͶ����� */
    private BigDecimal        usdAmount;
    /** ��ԪͶ����� */
    private BigDecimal        jpyAmount;
    /** ��Ч��־ */
    private String            validStatus;
    /** ��ע */
    private String            remark;
    /** ��־�ֶ� */
    private String            flag;

    public PrpDplane() {
    }

    /**       
     * ע���
     */
    @Id
    @Column(name = "LICENCENO")
    public String getLicenceNo() {
        return this.licenceNo;
    }

    public void setLicenceNo(String licenceNo) {
        this.licenceNo = licenceNo;
    }

    /**       
     * �ɻ�����(1�����2խ���3�����)
     */
    @Column(name = "PLANETYPE")
    public String getPlaneType() {
        return this.planeType;
    }

    public void setPlaneType(String planeType) {
        this.planeType = planeType;
    }

    /**       
     * ����/�㱸���ͺ�
     */
    @Column(name = "MODEL")
    public String getModel() {
        return this.model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    /**       
     * ���
     */
    @Column(name = "FACTORYNO")
    public String getFactoryNo() {
        return this.factoryNo;
    }

    public void setFactoryNo(String factoryNo) {
        this.factoryNo = factoryNo;
    }

    /**       
     * ������
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "FACTORYDATE")
    public Date getFactoryDate() {
        return this.factoryDate;
    }

    public void setFactoryDate(Date factoryDate) {
        this.factoryDate = factoryDate;
    }

    /**       
     * �������
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "MAKEYEAR")
    public Date getMakeYear() {
        return this.makeYear;
    }

    public void setMakeYear(Date makeYear) {
        this.makeYear = makeYear;
    }

    /**       
     * ���չ�˾������
     */
    @Column(name = "AIRLINECNAME")
    public String getAirlineCname() {
        return this.airlineCname;
    }

    public void setAirlineCname(String airlineCname) {
        this.airlineCname = airlineCname;
    }

    /**       
     * ���չ�˾Ӣ����
     */
    @Column(name = "AIRLINEENAME")
    public String getAirlineEname() {
        return this.airlineEname;
    }

    public void setAirlineEname(String airlineEname) {
        this.airlineEname = airlineEname;
    }

    /**       
     * ���з�Χ��W-WIDE��DOME��
     */
    @Column(name = "RANGE")
    public String getRange() {
        return this.range;
    }

    public void setRange(String range) {
        this.range = range;
    }

    /**       
     * ��λ��
     */
    @Column(name = "SEATCOUNT")
    public BigDecimal getSeatCount() {
        return this.seatCount;
    }

    public void setSeatCount(BigDecimal seatCount) {
        this.seatCount = seatCount;
    }

    /**       
     * �������L���⣬P������
     */
    @Column(name = "LOANSTAUS")
    public String getLoanStaus() {
        return this.loanStaus;
    }

    public void setLoanStaus(String loanStaus) {
        this.loanStaus = loanStaus;
    }

    /**       
     * �ɻ���;��1 CARGO��2 PASSENGER��3 BOTH��
     */
    @Column(name = "PLANEUSAGE")
    public String getPlaneUsage() {
        return this.planeUsage;
    }

    public void setPlaneUsage(String planeUsage) {
        this.planeUsage = planeUsage;
    }

    /**       
     * ��ԪͶ�����
     */
    @Column(name = "USDAMOUNT")
    public BigDecimal getUsdAmount() {
        return this.usdAmount;
    }

    public void setUsdAmount(BigDecimal usdAmount) {
        this.usdAmount = usdAmount;
    }

    /**       
     * ��ԪͶ�����
     */
    @Column(name = "JPYAMOUNT")
    public BigDecimal getJpyAmount() {
        return this.jpyAmount;
    }

    public void setJpyAmount(BigDecimal jpyAmount) {
        this.jpyAmount = jpyAmount;
    }

    /**       
     * ��Ч��־
     */
    @Column(name = "VALIDSTATUS")
    public String getValidStatus() {
		return validStatus;
	}

	public void setValidStatus(String validStatus) {
		this.validStatus = validStatus;
	}
    /**       
     * ��ע
     */
    @Column(name = "REMARK")
    public String getRemark() {
        return this.remark;
    }



	public void setRemark(String remark) {
        this.remark = remark;
    }

    /**       
     * ��־�ֶ�
     */
    @Column(name = "FLAG")
    public String getFlag() {
        return this.flag;
    }

    public void setFlag(String flag) {
        this.flag = flag;
    }
}
