--´ú¸ÕCAR0377 CAR0379 CHANGE_PROJECTCODE  CHANGE_PROJECTCODE2 START
CALL CHANGE_PROJECTCODE2.SP_GENAGENTCODE(:P_HANDLERIDENTIFYNUMBER,:P_CHANNELTYPE,?);

DECLARE
output1 varchar2(255);
BEGIN
BUSINESS.CHANGE_PROJECTCODE2.SP_GENPROJECTCODE('B','11','000900','C18D622174','N',to_date('2021-12-01','yyyy-MM-dd'),output1);
dbms_output.put_line(output1);
END;

DECLARE
output1 varchar2(255);
BEGIN
BUSINESS.CHANGE_PROJECTCODE2.SP_GENPROJECTCODE('B','11','000900','C18D622174','Y',to_date('2021-12-01','yyyy-MM-dd'),output1);
dbms_output.put_line(output1);
END;

DECLARE
output1 varchar2(255);
BEGIN
CHANGE_PROJECTCODE2.SP_GENAGENTCODE('C18D622174','11',output1);
dbms_output.put_line(output1);
END;

CREATE OR REPLACE PACKAGE package_test AS
  PROCEDURE procedure_test(v1 VARCHAR2);
  FUNCTION function_test(v2 VARCHAR2) RETURN VARCHAR2;
END;
--´ú¸ÕCAR0377 CAR0379 CHANGE_PROJECTCODE  CHANGE_PROJECTCODE2 END 


CREATE OR REPLACE PACKAGE BODY package_test AS
  PROCEDURE procedure_test(v1 VARCHAR2) IS
   BEGIN
    dbms_output.put_line(v1);
  END ;
  
  FUNCTION function_test(v2 VARCHAR2) RETURN VARCHAR2 IS
    v3 VARCHAR2(50);
  BEGIN
    v3 := ' This is a sample function';
    RETURN V2 || V3;
  END ;
END;
