--## prpins 核心
-->>--JSP模板對應表
SELECT * FROM BUSINESS.PRPDRISKTEMPLATE WHERE RISKCODE in ('F01','CL')
SELECT * FROM BUSINESS.PRPDRISKTEMPLATE WHERE TEMPLATECODE in ('m30002')
SELECT * FROM BUSINESS.PRPDRISKTEMPLATE WHERE TEMPLATECODE in ('m01001')
SELECT DISTINCT a.TEMPLATECODE,a.RISKCODE FROM BUSINESS.PRPDRISKTEMPLATE a ORDER BY a.TEMPLATECODE
-->>--破洗錢
SELECT WORKSTATUS FROM BUSINESS.PRPTMAIN WHERE PROPOSALNO in ('9PB202205000003');
update BUSINESS.PRPTMAIN set WORKSTATUS='04' WHERE PROPOSALNO in ('9PB202205000003');
--驗證=======================================================================================================================
--PRPC
SELECT pckf.AMOUNTCOEFFI,pc.*
FROM 
BUSINESS.PRPCMAIN pc 
LEFT JOIN BUSINESS.PRPCITEMKIND pck ON pc.POLICYNO = pck.POLICYNO 
LEFT JOIN BUSINESS.PRPCITEMKINDFACTOR pckf ON pck.POLICYNO = pckf.POLICYNO WHERE pc.POLICYNO='180522PB0000003'

--驗證=======================================================================================================================
SELECT * FROM BUSINESS.PRPTMAIN pc WHERE pc.POLICYNO='180522PB0000003'
--PRPT
SELECT pckf.AMOUNTCOEFFI
,pckf.DEDUCTIBLECOEFFIIDCODE,pckf.DEDUCTIBLECOEFFIIDRATE
,pckf.OTHERS1COEFFICODE,pckf.OTHERS1COEFFIRATE
,pckf.OTHERS2COEFFICODE,pckf.OTHERS2COEFFIRATE
,pckf.OTHERS3COEFFICODE,pckf.OTHERS3COEFFIRATE
,pc.*
FROM 
BUSINESS.PRPTMAIN pc 
LEFT JOIN BUSINESS.PRPTITEMKIND pck ON pc.PROPOSALNO = pck.PROPOSALNO 
LEFT JOIN BUSINESS.PRPTITEMKINDFACTOR pckf ON pck.PROPOSALNO = pckf.PROPOSALNO WHERE pc.POLICYNO='180522PB0000003'

--驗證=======================================================================================================================
SELECT * FROM BUSINESS.PRPQMAIN pc WHERE pc.POLICYNO='180522PB0000003'
--PRPQ POLICYNO=>PROPOSALNO(180522PBE000007)=>PROPOSALNO
SELECT 
pckf.AMOUNTCOEFFI
,pckf.DEDUCTIBLECOEFFIIDCODE,pckf.DEDUCTIBLECOEFFIIDRATE
,pckf.OTHERS1COEFFICODE,pckf.OTHERS1COEFFIRATE
,pckf.OTHERS2COEFFICODE,pckf.OTHERS2COEFFIRATE
,pckf.OTHERS3COEFFICODE,pckf.OTHERS3COEFFIRATE
,pc.*
FROM 
BUSINESS.PRPQMAIN pc 
LEFT JOIN BUSINESS.PRPQITEMKIND pck ON pc.PROPOSALNO = pck.PROPOSALNO 
LEFT JOIN BUSINESS.PRPQITEMKINDFACTOR pckf ON pck.PROPOSALNO = pckf.PROPOSALNO WHERE pc.POLICYNO='180522PB0000003'

--驗證=======================================================================================================================
SELECT * FROM BUSINESS.PRPPMAIN pc WHERE pc.POLICYNO='180522PB0000003'
--PRPP POLICYNO=>POLICYNO=>POLICYNO
SELECT 
pckf.AMOUNTCOEFFI
,pckf.DEDUCTIBLECOEFFIIDCODE,pckf.DEDUCTIBLECOEFFIIDRATE
,pckf.OTHERS1COEFFICODE,pckf.OTHERS1COEFFIRATE
,pckf.OTHERS2COEFFICODE,pckf.OTHERS2COEFFIRATE
,pckf.OTHERS3COEFFICODE,pckf.OTHERS3COEFFIRATE
,pc.*
FROM 
BUSINESS.PRPPMAIN pc 
LEFT JOIN BUSINESS.PRPPITEMKIND pck ON pc.POLICYNO = pck.POLICYNO 
LEFT JOIN BUSINESS.PRPPITEMKINDFACTOR pckf ON pck.POLICYNO = pckf.POLICYNO WHERE pc.POLICYNO='180522PB0000003'

--驗證=======================================================================================================================
SELECT * FROM BUSINESS.PRPCPMAIN pc WHERE pc.POLICYNO='180522PB0000003'
--PRPCP POLICYNO=>POLICYNO=>POLICYNO
SELECT 
pckf.AMOUNTCOEFFI
,pckf.DEDUCTIBLECOEFFIIDCODE,pckf.DEDUCTIBLECOEFFIIDRATE
,pckf.OTHERS1COEFFICODE,pckf.OTHERS1COEFFIRATE
,pckf.OTHERS2COEFFICODE,pckf.OTHERS2COEFFIRATE
,pckf.OTHERS3COEFFICODE,pckf.OTHERS3COEFFIRATE
,pc.*
FROM 
BUSINESS.PRPCPMAIN pc 
LEFT JOIN BUSINESS.PRPCPITEMKIND pck ON pc.POLICYNO = pck.POLICYNO 
LEFT JOIN BUSINESS.PRPCPITEMKINDFACTOR pckf ON pck.POLICYNO = pckf.POLICYNO WHERE pc.POLICYNO='180522PB0000003'

--驗證=======================================================================================================================
SELECT * FROM BUSINESS.PRPCOPYMAIN pc WHERE pc.POLICYNO='180522PB0000003'
--PRPCOPY POLICYNO=>POLICYNO=>POLICYNO
SELECT 
pckf.AMOUNTCOEFFI
,pckf.DEDUCTIBLECOEFFIIDCODE,pckf.DEDUCTIBLECOEFFIIDRATE
,pckf.OTHERS1COEFFICODE,pckf.OTHERS1COEFFIRATE
,pckf.OTHERS2COEFFICODE,pckf.OTHERS2COEFFIRATE
,pckf.OTHERS3COEFFICODE,pckf.OTHERS3COEFFIRATE
,pc.*
FROM 
BUSINESS.PRPCOPYMAIN pc 
LEFT JOIN BUSINESS.PRPCOPYITEMKIND pck ON pc.POLICYNO = pck.POLICYNO 
LEFT JOIN BUSINESS.PRPCOPYITEMKINDFACTOR pckf ON pck.POLICYNO = pckf.POLICYNO WHERE pc.POLICYNO='180522PB0000003'
--驗證END=======================================================================================================================

 
--#interface #if #CAR0288
  SELECT i.DRAWOUTDATE ,i.* FROM BUSINESS.INTFPRPJPAYREFREC i  where i.policyno in ('180020D00050','180020C1D00041');
  SELECT * FROM BUSINESS.PRPCOPYINSURED WHERE POLICYNO IN ('180020D00050','180020C1D00041');
  
--更新
  --update BUSINESS.intfprpjpayrefrec set DRAWOUTDATE ='' where policyno in ('180020D00050','180020C1D00041');
  --PRPCOPYINSURED email
 
 SELECT * FROM BUSINESS.PRPCLIMIT WHERE POLICYNO = '180120FAH00002'
 
 --CAR0341 排程欄位新增  ENFVRULECNT, ENFVADDPRICE
 SELECT * FROM BUSINESS.INTFPRPBITEMKIND i WHERE policyno in ('180021D00096','180021C1D00020');


UPDATE BUSINESS.INTFPRPBITEMKIND SET KINDCODE='21', DEDUCTIBLE=0, AMOUNT=2200000, MODEL=NULL, MODECODE=NULL, QUANTITY=0, PREMIUM=1019, BENCHMARKPREMIUM=1019, DISCOUNTCHARGE=0, RATE=0.0005, BASEPREMIUM=1019, PUREPREMIUM=0, LASTPUREPREMIUM=0, PURERATE=0, RATEVALIDDATE=NULL, ADDCOSTRATE=0, RELIEFFUND=30.57, RELIEFFUNDRATE=0.03, STABILITYFUND=2.04, STABILITYFUNDRATE=0.002, MANAGECHARGE=381.94, SPECIALCHARGE=5.86, COSTRATE=0, COSTFEE=270, FYCPROPORATION=0, FYCFEE=0, RECRUITFEE=0, RECRUITRATE=0, ENFVRULECNT=13, ENFVADDPRICE=3013 WHERE POLICYNO='180021C1D00020' AND SERIALNO='01';
UPDATE BUSINESS.INTFPRPBITEMKIND SET KINDCODE='27', DEDUCTIBLE=0, AMOUNT=200000, MODEL='5/10', MODECODE=NULL, QUANTITY=0, PREMIUM=200, BENCHMARKPREMIUM=0, DISCOUNTCHARGE=0, RATE=0, BASEPREMIUM=0, PUREPREMIUM=130, LASTPUREPREMIUM=0, PURERATE=0, RATEVALIDDATE=NULL, ADDCOSTRATE=0.35, RELIEFFUND=NULL, RELIEFFUNDRATE=NULL, STABILITYFUND=NULL, STABILITYFUNDRATE=NULL, MANAGECHARGE=NULL, SPECIALCHARGE=NULL, COSTRATE=18.4, COSTFEE=37, FYCPROPORATION=0, FYCFEE=0, RECRUITFEE=0, RECRUITRATE=0, ENFVRULECNT=14, ENFVADDPRICE=3014 WHERE POLICYNO='180021D00096' AND SERIALNO='01';
UPDATE BUSINESS.INTFPRPBITEMKIND SET KINDCODE='31', DEDUCTIBLE=0, AMOUNT=25000000, MODEL='500/1000', MODECODE=NULL, QUANTITY=5, PREMIUM=1824, BENCHMARKPREMIUM=0, DISCOUNTCHARGE=0, RATE=0, BASEPREMIUM=0, PUREPREMIUM=1895.2, LASTPUREPREMIUM=0, PURERATE=0, RATEVALIDDATE='11005', ADDCOSTRATE=0.35, RELIEFFUND=NULL, RELIEFFUNDRATE=NULL, STABILITYFUND=NULL, STABILITYFUNDRATE=NULL, MANAGECHARGE=NULL, SPECIALCHARGE=NULL, COSTRATE=18.4, COSTFEE=336, FYCPROPORATION=0, FYCFEE=0, RECRUITFEE=0, RECRUITRATE=0, ENFVRULECNT=15, ENFVADDPRICE=3015 WHERE POLICYNO='180021D00096' AND SERIALNO='02';
UPDATE BUSINESS.INTFPRPBITEMKIND SET KINDCODE='32', DEDUCTIBLE=0, AMOUNT=500000, MODEL='50', MODECODE=NULL, QUANTITY=0, PREMIUM=2112, BENCHMARKPREMIUM=0, DISCOUNTCHARGE=0, RATE=0, BASEPREMIUM=0, PUREPREMIUM=2288.4, LASTPUREPREMIUM=0, PURERATE=0, RATEVALIDDATE=NULL, ADDCOSTRATE=0.35, RELIEFFUND=NULL, RELIEFFUNDRATE=NULL, STABILITYFUND=NULL, STABILITYFUNDRATE=NULL, MANAGECHARGE=NULL, SPECIALCHARGE=NULL, COSTRATE=18.4, COSTFEE=389, FYCPROPORATION=0, FYCFEE=0, RECRUITFEE=0, RECRUITRATE=0, ENFVRULECNT=16, ENFVADDPRICE=3016 WHERE POLICYNO='180021D00096' AND SERIALNO='03';
UPDATE BUSINESS.INTFPRPBITEMKIND SET KINDCODE='3N', DEDUCTIBLE=0, AMOUNT=100000, MODEL=NULL, MODECODE=NULL, QUANTITY=0, PREMIUM=397, BENCHMARKPREMIUM=0, DISCOUNTCHARGE=0, RATE=0, BASEPREMIUM=0, PUREPREMIUM=258, LASTPUREPREMIUM=0, PURERATE=0, RATEVALIDDATE=NULL, ADDCOSTRATE=0.35, RELIEFFUND=NULL, RELIEFFUNDRATE=NULL, STABILITYFUND=NULL, STABILITYFUNDRATE=NULL, MANAGECHARGE=NULL, SPECIALCHARGE=NULL, COSTRATE=18.4, COSTFEE=73, FYCPROPORATION=0, FYCFEE=0, RECRUITFEE=0, RECRUITRATE=0, ENFVRULECNT=17, ENFVADDPRICE=3017 WHERE POLICYNO='180021D00096' AND SERIALNO='04';
UPDATE BUSINESS.INTFPRPBITEMKIND SET KINDCODE='48', DEDUCTIBLE=0, AMOUNT=2200000, MODEL='20/200', MODECODE=NULL, QUANTITY=0, PREMIUM=289, BENCHMARKPREMIUM=0, DISCOUNTCHARGE=0, RATE=0, BASEPREMIUM=0, PUREPREMIUM=187.85, LASTPUREPREMIUM=0, PURERATE=0, RATEVALIDDATE='11005', ADDCOSTRATE=0.35, RELIEFFUND=NULL, RELIEFFUNDRATE=NULL, STABILITYFUND=NULL, STABILITYFUNDRATE=NULL, MANAGECHARGE=NULL, SPECIALCHARGE=NULL, COSTRATE=18.4, COSTFEE=53, FYCPROPORATION=0, FYCFEE=0, RECRUITFEE=0, RECRUITRATE=0, ENFVRULECNT=18, ENFVADDPRICE=3018 WHERE POLICYNO='180021D00096' AND SERIALNO='05';
UPDATE BUSINESS.INTFPRPBITEMKIND SET KINDCODE='49', DEDUCTIBLE=0, AMOUNT=2000, MODEL='2000', MODECODE=NULL, QUANTITY=0, PREMIUM=2, BENCHMARKPREMIUM=0, DISCOUNTCHARGE=0, RATE=0, BASEPREMIUM=0, PUREPREMIUM=1.44, LASTPUREPREMIUM=0, PURERATE=0, RATEVALIDDATE='11005', ADDCOSTRATE=0.35, RELIEFFUND=NULL, RELIEFFUNDRATE=NULL, STABILITYFUND=NULL, STABILITYFUNDRATE=NULL, MANAGECHARGE=NULL, SPECIALCHARGE=NULL, COSTRATE=18.4, COSTFEE=0, FYCPROPORATION=0, FYCFEE=0, RECRUITFEE=0, RECRUITRATE=0, ENFVRULECNT=19, ENFVADDPRICE=3019 WHERE POLICYNO='180021D00096' AND SERIALNO='06';
UPDATE BUSINESS.INTFPRPBITEMKIND SET KINDCODE='50', DEDUCTIBLE=0, AMOUNT=2000000, MODEL='200', MODECODE=NULL, QUANTITY=0, PREMIUM=371, BENCHMARKPREMIUM=0, DISCOUNTCHARGE=0, RATE=0, BASEPREMIUM=0, PUREPREMIUM=241.2, LASTPUREPREMIUM=0, PURERATE=0, RATEVALIDDATE='11005', ADDCOSTRATE=0.35, RELIEFFUND=NULL, RELIEFFUNDRATE=NULL, STABILITYFUND=NULL, STABILITYFUNDRATE=NULL, MANAGECHARGE=NULL, SPECIALCHARGE=NULL, COSTRATE=18.4, COSTFEE=68, FYCPROPORATION=0, FYCFEE=0, RECRUITFEE=0, RECRUITRATE=0, ENFVRULECNT=20, ENFVADDPRICE=3020 WHERE POLICYNO='180021D00096' AND SERIALNO='07';
UPDATE BUSINESS.INTFPRPBITEMKIND SET KINDCODE='51', DEDUCTIBLE=0, AMOUNT=8000000, MODEL='200/400', MODECODE=NULL, QUANTITY=4, PREMIUM=733, BENCHMARKPREMIUM=0, DISCOUNTCHARGE=0, RATE=0, BASEPREMIUM=0, PUREPREMIUM=110.3, LASTPUREPREMIUM=0, PURERATE=0, RATEVALIDDATE='11005', ADDCOSTRATE=0.35, RELIEFFUND=NULL, RELIEFFUNDRATE=NULL, STABILITYFUND=NULL, STABILITYFUNDRATE=NULL, MANAGECHARGE=NULL, SPECIALCHARGE=NULL, COSTRATE=18.4, COSTFEE=135, FYCPROPORATION=0, FYCFEE=0, RECRUITFEE=0, RECRUITRATE=0, ENFVRULECNT=21, ENFVADDPRICE=3021 WHERE POLICYNO='180021D00096' AND SERIALNO='08';
UPDATE BUSINESS.INTFPRPBITEMKIND SET KINDCODE='E1', DEDUCTIBLE=0, AMOUNT=10000000, MODEL=NULL, MODECODE=NULL, QUANTITY=0, PREMIUM=2066, BENCHMARKPREMIUM=0, DISCOUNTCHARGE=0, RATE=0, BASEPREMIUM=0, PUREPREMIUM=1342.9, LASTPUREPREMIUM=0, PURERATE=0, RATEVALIDDATE=NULL, ADDCOSTRATE=0.35, RELIEFFUND=NULL, RELIEFFUNDRATE=NULL, STABILITYFUND=NULL, STABILITYFUNDRATE=NULL, MANAGECHARGE=NULL, SPECIALCHARGE=NULL, COSTRATE=18.4, COSTFEE=380, FYCPROPORATION=0, FYCFEE=0, RECRUITFEE=0, RECRUITRATE=0, ENFVRULECNT=22, ENFVADDPRICE=3022 WHERE POLICYNO='180021D00096' AND SERIALNO='09';
UPDATE BUSINESS.INTFPRPBITEMKIND SET KINDCODE='Y1', DEDUCTIBLE=0, AMOUNT=30000, MODEL=NULL, MODECODE=NULL, QUANTITY=0, PREMIUM=264, BENCHMARKPREMIUM=0, DISCOUNTCHARGE=0, RATE=0, BASEPREMIUM=0, PUREPREMIUM=171.6, LASTPUREPREMIUM=0, PURERATE=0, RATEVALIDDATE='11005', ADDCOSTRATE=0.35, RELIEFFUND=NULL, RELIEFFUNDRATE=NULL, STABILITYFUND=NULL, STABILITYFUNDRATE=NULL, MANAGECHARGE=NULL, SPECIALCHARGE=NULL, COSTRATE=18.4, COSTFEE=49, FYCPROPORATION=0, FYCFEE=0, RECRUITFEE=0, RECRUITRATE=0, ENFVRULECNT=23, ENFVADDPRICE=3023 WHERE POLICYNO='180021D00096' AND SERIALNO='10';

SELECT * FROM BUSINESS.PRPDPRINT WHERE RISKCODE = 'B01' AND PRINTVIRTUALCODE = '43824115700011'
SELECT * FROM BUSINESS.PRPDPRINT WHERE 9B01202100001840

select
    prpdprint_.PRINTVIRTUALCODE,
    prpdprint_.PROPOSALNO,
    prpdprint_.FLAG as FLAG447_,
    prpdprint_.PRINTDATE as PRINTDATE447_,
    prpdprint_.RISKCODE as RISKCODE447_,
    prpdprint_.VALIDSTATUS as VALIDSTA6_447_,
    prpdprint_.VALIDDATE as VALIDDATE447_ 
from
    BUSINESS.PRPDPRINT prpdprint_ 
WHERE RISKCODE = 'B01' AND PRINTVIRTUALCODE = '43824115700011' --43824115700011
    
    
SELECT * FROM BUSINESS.INTFPRPBMAIN i WHERE POLICYNO IN ('180021D00096','180021C1D00020');
   
  UPDATE BUSINESS.INTFPRPBMAIN SET CHANNELTYPE='12', DIRECTBUSINESS='0', PROJECTCODE=NULL, AGENTCODE='0201201105', COMCODE='00', BUSINESSNATURE='B88801', HANDLERIDENTIFYNUMBER='A05C183306', HANDLER1CODE='BF075', ASPOLICYNO=NULL, STARTDATE=TIMESTAMP '2021-06-06 00:00:00.000000', ENDDATE=TIMESTAMP '2022-06-06 00:00:00.000000', ENROLLDATE=TIMESTAMP '2006-06-01 00:00:00.000000', MAKEDATE=TIMESTAMP '2006-06-01 00:00:00.000000', MODELCODE='C8000000', PURCHASEPRICE=0, ACTUALVALUE=0, CARKINDCODE='03', EXHAUSTSCALE=1998, LICENSENO='0230-PM', ENGINENO='K20A44864173', RUNAREACODE='01', SEATCOUNT=5, TONCOUNT=0, SHORTRATEFLAG='1', CARDEALERCODE='C1', RATEPERIODTYPE='1', RATEPERIOD='44', TRADEVANID='210306C9225212', LASTDAMAGEDB='1', FLOATRATEG=-0.3, LASTDAMAGEDA=NULL, FLOATRATEA=NULL, GOVPURCHASEFLAG='0', FYCFLAG='0', PRINTNO='180010CD04800', CIINSURETYPE='1', CIINSUREDNEWFLAG='1', CIINSURERBIZNO=NULL, CIINSURERCOMPANYNAME=NULL, ISMOTORCADE='2', STATUS='1', VIRTUALCODE='43824115700011', PRINTTIMES=1, PRINTDATE=TIMESTAMP '2021-04-14 00:00:00.000000', INTRODUCERID=NULL, INTRODUCERNAME=NULL, EXTRACOMCODE='320049', EXTRACOMNAME='業務行政部', AGENT1CODE=NULL, AGENT1NAME=NULL, EPOLICY='Y', STARTHOUR=NULL, ENDHOUR=NULL, NOTIFYORNOT='Y', MANAGEERCOEFF=0, SERIESCODE=NULL, ORDERSEQ=0020 WHERE POLICYNO='180021C1D00020';
UPDATE BUSINESS.INTFPRPBMAIN SET CHANNELTYPE='12', DIRECTBUSINESS='0', PROJECTCODE=NULL, AGENTCODE='0201201105', COMCODE='00', BUSINESSNATURE='B88801', HANDLERIDENTIFYNUMBER='A05C183306', HANDLER1CODE='BF075', ASPOLICYNO=NULL, STARTDATE=TIMESTAMP '2021-06-06 00:00:00.000000', ENDDATE=TIMESTAMP '2022-06-06 00:00:00.000000', ENROLLDATE=TIMESTAMP '2006-06-01 00:00:00.000000', MAKEDATE=TIMESTAMP '2006-06-01 00:00:00.000000', MODELCODE='C8000000', PURCHASEPRICE=0, ACTUALVALUE=0, CARKINDCODE='03', EXHAUSTSCALE=1998, LICENSENO='0230-PM', ENGINENO='K20A44864173', RUNAREACODE='01', SEATCOUNT=5, TONCOUNT=0, SHORTRATEFLAG='1', CARDEALERCODE='C1', RATEPERIODTYPE='1', RATEPERIOD='44', TRADEVANID='20210306CC095078', LASTDAMAGEDB='1', FLOATRATEG=-0.3, LASTDAMAGEDA='0', FLOATRATEA=0, GOVPURCHASEFLAG='0', FYCFLAG='0', PRINTNO='180010CD04800', CIINSURETYPE='1', CIINSUREDNEWFLAG='1', CIINSURERBIZNO='180021C1D00020', CIINSURERCOMPANYNAME=NULL, ISMOTORCADE='2', STATUS='1', VIRTUALCODE='43824115700011', PRINTTIMES=1, PRINTDATE=TIMESTAMP '2021-04-14 00:00:00.000000', INTRODUCERID=NULL, INTRODUCERNAME=NULL, EXTRACOMCODE='320049', EXTRACOMNAME='業務行政部', AGENT1CODE=NULL, AGENT1NAME=NULL, EPOLICY='Y', STARTHOUR=NULL, ENDHOUR=NULL, NOTIFYORNOT='Y', MANAGEERCOEFF=0, SERIESCODE=NULL, ORDERSEQ=0096 WHERE POLICYNO='180021D00096';

--CAR0341 結果驗證 核心排程 executeB2CImport 中介轉入核心
SELECT p2.ORDERSEQ,p.ENFVRULECNT,p.ENFVADDPRICE,p2.*,p.* 
FROM BUSINESS.PRPTITEMKIND p LEFT JOIN BUSINESS.PRPTMAIN p2 on p2.PROPOSALNO = p.PROPOSALNO 
WHERE p2.POLICYNO IN ('180021D00096','180021C1D00020');

SELECT p.FLAG,p.* FROM BUSINESS.prptitemkind p WHERE p.POLICYNO IN ('180021D00096','180021C1D00020');

SELECT * FROM BUSINESS.INTFPRPBMAIN WHERE STATUS = '0'
SELECT p.STATUS,p.* FROM BUSINESS.INTFPRPBMAIN p WHERE POLICYNO = '180021C1D00020'
--update BUSINESS.INTFPRPBMAIN set status = '0' where POLICYNO = '180021C1B00002'
--update BUSINESS.INTFPRPBMAIN set status = '2' where POLICYNO = '180021C1B00002'
--update BUSINESS.INTFPRPBMAIN set status = '1' where POLICYNO = '180021C1D00020'
SELECT * FROM BUSINESS.INTFPRPBMAIN WHERE POLICYNO IN ('180021D00096','180021C1D00020');

SELECT * FROM BUSINESS.INTFPRPBMAIN WHERE POLICYNO IN ('180021C1D00023','180021D00100','180021D00091','180021C1D00017');
 SELECT * FROM BUSINESS.INTFPRPBITEMKIND i WHERE policyno in ('180021C1D00023','180021D00100','180021D00091','180021C1D00017');

--prpC(OK)
SELECT p.ORDERSEQ,p.* FROM BUSINESS.PRPCMAIN p WHERE p.POLICYNO IN ('180021C1D00023','180021D00100','180021D00091','180021C1D00017');
SELECT p.ENFVRULECNT,p.ENFVADDPRICE,p.* FROM business.PRPCITEMKIND p WHERE p.POLICYNO IN ('180021C1D00023','180021D00100','180021D00091','180021C1D00017');
--prpT(OK)
SELECT p2.ORDERSEQ,p.ENFVRULECNT,p.ENFVADDPRICE,p.PROPOSALNO,p2.*,p.* 
FROM BUSINESS.PRPTITEMKIND p LEFT JOIN BUSINESS.PRPTMAIN p2 on p2.PROPOSALNO = p.PROPOSALNO 
WHERE p2.POLICYNO IN ('180021C1D00023','180021D00100','180021D00091','180021C1D00017');
--PRPCOPY(OK)
SELECT p.ORDERSEQ,p.* FROM BUSINESS.PRPCOPYMAIN p WHERE p.POLICYNO IN ('180021C1D00023','180021D00100','180021D00091','180021C1D00017');
SELECT p.ENFVRULECNT,p.ENFVADDPRICE,p.* FROM business.PRPCOPYITEMKIND p WHERE p.POLICYNO IN ('180021C1D00023','180021D00100','180021D00091','180021C1D00017');
--PRPP(OK，It should be emply by 雅雲)
SELECT p.ORDERSEQ,p.* FROM BUSINESS.PRPPMAIN p WHERE p.POLICYNO IN ('180021C1D00023','180021D00100','180021D00091','180021C1D00017');
--PRPQ
SELECT p.ORDERSEQ,p.* FROM BUSINESS.PRPQMAIN p WHERE p.POLICYNO IN ('180021C1D00023','180021D00100','180021D00091','180021C1D00017');

SELECT * FROM BUSINESS.PRPQMAIN p2 WHERE p2.PROPOSALNO  IN ('9B01202100001851','9B01202100001852','9A01202100001718','9A01202100001719');
SELECT * FROM BUSINESS.PRPQMAIN p2 WHERE p2.PROPOSALNO = '9B01202100001851'


----第三波測試 主要測試prpQmain為何沒寫入
--準備資料確認 CAR0341 CAR0349
SELECT * FROM BUSINESS.INTFPRPBMAIN i WHERE POLICYNO IN ('180021D00032','180021C1D00008');
SELECT * FROM BUSINESS.INTFPRPBITEMKIND i WHERE policyno in ('180021D00096','180021C1D00020');
--CAR0349
SELECT * FROM BUSINESS.INTFPRPBMAIN i WHERE policyno in ('180021D00096','180021C1D00020');
SELECT i.STARTDATE,i.* FROM BUSINESS.INTFPRPBMAIN i WHERE policyno = '180021C1D00020';
Select RATEPERIOD from prpdriskrate where (intfprpbmain.STARTDATE)>= VALIDDATE and  (intfprpbmain.STARTDATE)<= INVALIDDATE;
--會跑 觸發 的資料輛 http://localhost:7001/prpins/policyImport/executeB2CImport.do?systemCode=commonview
select count(*) as y0_  from  INTFPRPBMAIN this_  where this_.STATUS='1'

SELECT i.RATEPERIOD,i.STATUS,i.* FROM INTFPRPBMAIN i WHERE i.POLICYNO = '180021C1D00008'
Select i.RATEPERIOD,i.VALIDDATE,i.INVALIDDATE,i.* from prpdriskrate i  
WHERE  to_date('2021-01-31', 'YYYY-MM-DD')  >= i.VALIDDATE AND  to_date('2021-01-31', 'YYYY-MM-DD')  <= i.INVALIDDATE

Select i.RATEPERIOD,i.VALIDDATE,i.INVALIDDATE,i.* from prpdriskrate i  
WHERE  to_date('2021-01-31', 'YYYY-MM-DD')  >= i.VALIDDATE AND  to_date('2021-01-31', 'YYYY-MM-DD')  <= i.INVALIDDATE and i.id.riskcode in ('A01','B01')



SELECT p2.ORDERSEQ,p.ENFVRULECNT,p.ENFVADDPRICE,p2.*,p.* 
FROM BUSINESS.PRPTITEMKIND p LEFT JOIN BUSINESS.PRPTMAIN p2 on p2.PROPOSALNO = p.PROPOSALNO 
WHERE p2.POLICYNO IN ('180021D00032','180021C1D00008');

--codeType
select * from
        CCICDMS.prpdnewcode prpdnewcod0_ 
    where
        prpdnewcod0_.codetype='BankCode1' 
        AND
        (
            prpdnewcod0_.codecode like '%'
        ) 
        and (
            prpdnewcod0_.codecname like '%' 
            or prpdnewcod0_.codeename like '%'
        ) 
        and prpdnewcod0_.validstatus=1
        
    select
        *
    from
        CCICDMS.PRPDRATION prpdration0_ 
    where
        prpdration0_.VALIDIND='1' 
        and prpdration0_.VALIDDATE<=to_date('2021-06-10', 'YYYY-MM-DD') 
        and prpdration0_.plancode='MC' 
        and prpdration0_.RATIONTYPE='0'
        
   select
        prpdstartp0_.CODECODE as CODECODE135_,
        prpdstartp0_.FLAG as FLAG135_,
        prpdstartp0_.PORTNAME as PORTNAME135_,
        prpdstartp0_.VALIDSTATUS as VALIDSTA4_135_,
        prpdstartp0_.COUNTRIES as COUNTRIES135_ 
    from
        CCICDMS.PrpDstartPlace prpdstartp0_ 
    where
        prpdstartp0_.CODECODE like '%' 
        or prpdstartp0_.PORTNAME like '%%' 
        or prpdstartp0_.COUNTRIES like '%%' 
    order by
        prpdstartp0_.CODECODE ASC
        
    select
        prpdstartp0_.CODECODE as CODECODE135_,
        prpdstartp0_.FLAG as FLAG135_,
        prpdstartp0_.PORTNAME as PORTNAME135_,
        prpdstartp0_.VALIDSTATUS as VALIDSTA4_135_,
        prpdstartp0_.COUNTRIES as COUNTRIES135_ 
    from
        CCICDMS.PrpDstartPlace prpdstartp0_ 
    where
        prpdstartp0_.CODECODE like '010101%' 
        or prpdstartp0_.PORTNAME like '%010101%' 
        or prpdstartp0_.COUNTRIES like '%010101%' 
    order by
        prpdstartp0_.CODECODE asc
    
        
        
    select
       *
    from
        BUSINESS.PRPDAGREEMENT prpdagreem0_,
        BUSINESS.PRPDAGREEDETAIL prpdagreed1_ 
    where
        prpdagreem0_.AGREEMENTNO=prpdagreed1_.AGREEMENTNO 
        and (
            prpdagreem0_.AGENTCODE in (
                '0201201439'
            ) 
            or prpdagreem0_.AGENTCODE='*'
        ) 
        and (
            prpdagreed1_.RISKCODE='MC' 
            or prpdagreed1_.RISKCODE='*'
        ) 
        and prpdagreem0_.VALIDSTATUS='1' 
        and prpdagreem0_.ENDDATE>to_date('2021-06-10', 'yyyy-mm-dd') 
        and (
            prpdagreem0_.businessSourceCode='B88801' 
            or prpdagreem0_.businessSourceCode='*'
        ) 
        and (
            prpdagreem0_.CLIENTUNITCODE='F124478999' 
            or prpdagreem0_.CLIENTUNITCODE is null
        ) 
        and (
            prpdagreem0_.CLIENTCODE='F124478999' 
            or prpdagreem0_.CLIENTCODE is null
        ) 
        and (
            prpdagreem0_.projectCode='' 
            or prpdagreem0_.projectCode='*'
        ) 
        and (
            prpdagreem0_.CLASSCODE='M' 
            or prpdagreem0_.CLASSCODE='*'
        )
        
        
select
        *
    from
        prpdriskclausekind prpdriskcl0_ 
    where
        1=1 
        and prpdriskcl0_.riskcode='MC' 
        and (
            prpdriskcl0_.kindcode like 'AC0'
        ) 
        and prpdriskcl0_.validind=1 
        and (
            sysdate between validdate and invaliddate 
            or sysdate>=validdate 
            and (
                invaliddate is null
            )
        )
        
        SELECT p.CUSTOMERCNAME,p.CUSTOMERCLASS FROM BUSINESS.PRPDAGENTUNIT p WHERE EACHDISTRICT = '010105'
        
        
        select
        *
    from
        prpdriskclausekind prpdriskcl0_ 
    where
        1=1 
        and prpdriskcl0_.riskcode='TB' 
        and prpdriskcl0_.validind=1 
        and (
            sysdate between validdate and invaliddate 
            or sysdate>=validdate 
            and (
                invaliddate is null
            )
        ) 
        and prpdriskcl0_.tcol1='1'
--這裡沒有新險種不會產生
SELECT * FROM CCICDMS.PRPDNEWCODERISK WHERE CODETYPE = 'Sex'

--LIA0170 checkIdentifynumberExist 驗證 重復 投保
    select
        count(*) 
    from
        BUSINESS.prpcmain m,
        BUSINESS.prpcinsured i  
    where
        m.policyno=i.policyno   
        and m.enddate > to_date('110-05-28','yyyy/MM/dd')  
        and i.identifynumber= 'A121121121'
        
        
SELECT * FROM BUSINESS.PRPCINSURED p WHERE p.POLICYNO = '180024AB0000006'

SELECT * FROM BUSINESS.PRPTINSURED p WHERE p.PROPOSALNO = '9AB202500000007'

    SELECT
        H1.insuredName AS INSURED2NAME,
        H1.POSTADDRESS AS POSTADDRESS,
        H2.insuredName AS INSURED1NAME,
        C.licenseNo AS LICENSENO,
        M.BUSINESSNATURE AS BUSINESSNATURE,
        M.EXTRACOMCODE AS EXTRACOMCODE,
        LISTAGG(CASE WHEN M.riskcode = 'A01' THEN M.POLICYNO END, '&') WITHIN GROUP (ORDER BY M.POLICYNO) AS VPLYNO,
        MAX(CASE WHEN M.riskcode = 'A01' THEN TO_NUMBER(TO_CHAR(M.ENDDATE, 'YYYYMMDD') ) END) AS VENDDATE,
        LISTAGG(CASE WHEN M.riskcode = 'B01' THEN M.POLICYNO END, '&') WITHIN GROUP (ORDER BY M.POLICYNO) AS CPLYNO,
        MAX(CASE WHEN M.riskcode = 'B01' THEN TO_NUMBER(TO_CHAR(M.ENDDATE, 'YYYYMMDD') ) END) AS CENDDATE,
        M.comCode AS COMCODE,
        M.handler1Code AS HANDLER1CODE,
        M.handler1Name AS HANDLER1NAME,
        M.handlerIdentifyNumber AS HANDLERIDENTIFYNUMBER,
        M.handlerName AS HANDLERNAME
    FROM
        PRPCMAIN M
    INNER JOIN prpCinsured H1 ON H1.policyno = M.policyno AND H1.INSUREDFLAG = '2'
    INNER JOIN prpCinsured H2 ON H2.policyno = M.policyno AND H2.INSUREDFLAG = '1'
    INNER JOIN prpCitemCar C ON C.policyno = M.policyno
    WHERE
        TO_CHAR(M.ENDDATE, 'YYYYMMDD') BETWEEN '20250201' and '20250204'
        AND M.riskcode IN ('A01', 'B01')
    GROUP BY
        H1.insuredName, H1.POSTADDRESS, H2.insuredName, C.licenseNo, M.BUSINESSNATURE, M.EXTRACOMCODE,
        M.comCode, M.handler1Code, M.handler1Name, M.handlerIdentifyNumber, M.handlerName,M.ENDDATE
        
        
        SELECT * from CAR_POSTCARD_VO WHERE  BATCHNO = '20250201_20250206'
        
        SELECT		        H1.insuredName AS INSURED2NAME,		        H1.POSTADDRESS AS POSTADDRESS,		        H2.insuredName AS INSURED1NAME,		        C.licenseNo AS LICENSENO,		        M.BUSINESSNATURE AS BUSINESSNATURE,		        M.EXTRACOMCODE AS EXTRACOMCODE,		        LISTAGG(CASE WHEN M.riskcode = 'A01' THEN M.POLICYNO END, '&') WITHIN GROUP (ORDER BY M.POLICYNO) AS VPLYNO,		        MAX(CASE WHEN M.riskcode = 'A01' THEN TO_NUMBER(TO_CHAR(M.STARTDATE, 'YYYYMMDD') - 19110000) END) AS VENDDATE,		        LISTAGG(CASE WHEN M.riskcode = 'B01' THEN M.POLICYNO END, '&') WITHIN GROUP (ORDER BY M.POLICYNO) AS CPLYNO,		        MAX(CASE WHEN M.riskcode = 'B01' THEN TO_NUMBER(TO_CHAR(M.STARTDATE, 'YYYYMMDD') - 19110000) END) AS CENDDATE,		        M.comCode AS COMCODE,		        M.handler1Code AS HANDLER1CODE,		        M.handler1Name AS HANDLER1NAME,		        M.handlerIdentifyNumber AS HANDLERIDENTIFYNUMBER,		        M.handlerName AS HANDLERNAME		    FROM		        PRPCMAIN M		    INNER JOIN prpCinsured H1 ON H1.policyno = M.policyno AND H1.INSUREDFLAG = '2'		    INNER JOIN prpCinsured H2 ON H2.policyno = M.policyno AND H2.INSUREDFLAG = '1'		    INNER JOIN prpCitemCar C ON C.policyno = M.policyno		    WHERE		        TO_CHAR(M.ENDDATE, 'YYYYMMDD') BETWEEN '20250201' and '20250206'		        AND M.riskcode IN ('A01', 'B01')		    GROUP BY		        H1.insuredName, H1.POSTADDRESS, H2.insuredName, C.licenseNo, M.BUSINESSNATURE, M.EXTRACOMCODE,		        M.comCode, M.handler1Code, M.handler1Name, M.handlerIdentifyNumber, M.handlerName,M.ENDDATE
        
        DELETE CAR_POSTCARD_VO WHERE  BATCHNO = '20250201_20250206'
        SELECT REGEXP_SUBSTR(BATCHNO, '[^_]+', 1, 1) AS startDate,REGEXP_SUBSTR(BATCHNO, '[^_]+', 1, 2) AS endDate ,cpv.*
        FROM CAR_POSTCARD_VO cpv WHERE BATCHNO = '20250201_20250206'
        
        DELETE FROM CAR_POSTCARD_VO cpv WHERE  cpv.VENDDATE BETWEEN '20250201' and '20250206' OR cpv.CENDDATE BETWEEN '20250201' and '20250206' 
        
        DELETE FROM CAR_POSTCARD_VO cpv WHERE  cpv.VENDDATE BETWEEN '"+startDate+"' and '"+endDate+"' OR cpv.CENDDATE BETWEEN '"+startDate+"' and '"+endDate+"'
        
        SELECT * FROM UTIUSERGRADE WHERE USERCODE = 'BL011' AND GRADECODE IN ('009','010','006');
        
       
       SELECT * FROM prplclaimloss WHERE INPUTDATE > to_date('09-06-2025', 'dd-MM-yyyy') AND INPUTDATE < to_date('31-12-9999', 'dd-MM-yyyy')
       
       
          SELECT *  FROM  (  
          SELECT   DISTINCT WFLOG.*   FROM   WFLOG   WHERE   (  (  WFLOG.NODENO <= 5   AND (  1 = 1   
          AND (  WFLOG.CLASSCODE IN ('A', 'B') OR WFLOG.RISKCODE IN ('B01')  )  )  )  )   AND WFLOG.LOGNO <> 1   
          AND WFLOG.NODENO <> 1   AND (    WFLOG.BUSINESSTYPE = 'C' OR WFLOG.BUSINESSTYPE = 'Y'  )   AND RISKCATEGORY = 'D'  
          AND RISKCODE IN('B01')   AND NODESTATUS IN('0','1','2','3')  AND FLOWINTIME >= '2024-12-19 00:00:00'  
          AND FLOWINTIME <= '2025-02-19 23:59:59'   )   WHERE (OPERATORCODE IS NULL OR OPERATORCODE = 'BL011' )  
          ORDER BY FLOWINTIME DESC 
       
          SELECT * FROM PRPLCOMPENSATE p WHERE p.COMPENSATENO = 'C180024AL0006302'
          
          SELECT * FROM PRPLDRIVER p WHERE p.POLICYNO = '180024003217'
          
          SELECT * FROM PRPLTHIRDPARTY p WHERE p.CLAIMNO= '180024AL00063'
          
SELECT 
PRPLCOMPENSATE.COMPENSATENO AS 計算書號,PRPLCOMPENSATE.PAYSITUATION AS 給付追償情況,PRPLCOMPENSATE.PAYCODE AS 賠付代號,
PRPLCOMPENSATE.INDEMNITYDUTY AS 本車肇事責任,PRPLCOMPENSATE.INDEMNITYDUTYRATE AS 保車肇責比率,
PRPLCOMPENSATE.ACCIDENTTYPE AS 肇責類型,PRPLCOMPENSATE.SUBROGATION AS 第29條代位情形,PRPLCLAIM.REPLEVYFLAG AS 是否追償註記,
PRPLPAYOBJECTINFO.PAYCODETYPE AS賠款給付對象訊息,PRPLPAYOBJECTINFO.PAYMENTKIND AS 費用類型 ,PRPLPERSONLOSS.CHASINGLOSSESSTATUS AS 健保追償狀況,
PRPLPERSONLOSS.ENDCASEANDRECOVERFLAG AS 是否結案待健保追償,PRPLPERSONLOSS.PERSONNO AS 受害人序號,PRPLPERSONLOSS.IDENTIFYNUMBER AS 受害人ID,
PRPLPERSONLOSS.MEDICALCODE AS 費用代碼,PRPLPERSONLOSS.SUMREALPAY AS 實賠金額
FROM PRPLCOMPENSATE
INNER JOIN PRPLCLAIM ON PRPLCOMPENSATE.POLICYNO = PRPLCLAIM.POLICYNO
INNER JOIN PRPLPERSONLOSS ON PRPLCOMPENSATE.COMPENSATENO = PRPLPERSONLOSS.COMPENSATENO
INNER JOIN PRPLPAYOBJECTINFO ON PRPLCOMPENSATE.COMPENSATENO = PRPLPAYOBJECTINFO.COMPENSATENO
WHERE PRPLCLAIM.CLAIMNO = '180024AL00063'

SELECT * FROM SALES.PRPDAGENTDATECHANGE



SELECT PRPLTHIRDPARTY.SERIALNO,
PRPLCOMPENSATE.COMPENSATENO AS 計算書號,PRPLCLAIM.REPLEVYFLAG AS 是否追償註記,PRPLCOMPENSATE.SPEEDFLAG AS 賠款速度,
PRPLCOMPENSATE.LOSSTYPE AS 本車損失,PRPLCOMPENSATE.PROPACCIDENTTYPE AS 車體險肇責,PRPLCOMPENSATE.INDEMNITYDUTYRATE AS 保車肇責比率,
PRPLCOMPENSATE.OPPOSITEINDEMNITYDUTY AS 對車肇責比率,PRPLCOMPENSATE.OTHERINDEMNITYDUTY AS 其他肇責比率,PRPLCOMPENSATE.SUMPAID 賠付總額,
PRPLCLAIM.INSUREDNAME AS 被保險人姓名,PRPLTHIRDPARTY.RELATIONSHIP AS 與被保險人關係,PRPLCLAIM.DAMAGECODE AS 出險原因代碼, PRPLCLAIM.DAMAGENAME AS 出險原因名稱,
PRPLDRIVER.DRIVERNAME AS 肇事駕駛人姓名,PRPLDRIVER.IDENTIFYNUMBER AS 肇事駕駛人ID, PRPLDRIVER.BIRTHDAY AS 肇事駕駛人生日,PRPLDRIVER.DRIVERSEX AS 肇事駕駛人性別,PRPLDRIVER.LICENSENO AS 肇事車牌照號碼,
PRPLCARINSURANCE.DEDUCTIBLEINVOICE AS 自負額發票號碼,PRPLLOSS.KINDCODE AS 賠付種類代號, 
PRPLPAYOBJECTINFO.PAYCODETYPE AS 賠付代號,PRPLPAYOBJECTINFO.PAYMENTKIND AS 費用類型 ,PRPLPAYOBJECTINFO.OWNERNAME AS 受款人姓名 ,PRPLPAYOBJECTINFO.UNIFORMNO AS 受款人ID ,PRPLPAYOBJECTINFO.AMLFLAG AS 洗錢回傳註記
FROM PRPLCOMPENSATE
INNER JOIN PRPLCLAIM ON PRPLCOMPENSATE.POLICYNO = PRPLCLAIM.POLICYNO
INNER JOIN PRPLDRIVER ON PRPLCOMPENSATE.POLICYNO = PRPLDRIVER.POLICYNO
INNER JOIN PRPLLOSS ON PRPLCOMPENSATE.COMPENSATENO = PRPLLOSS.COMPENSATENO
INNER JOIN PRPLPAYOBJECTINFO ON PRPLCOMPENSATE.COMPENSATENO = PRPLPAYOBJECTINFO.COMPENSATENO
LEFT JOIN PRPLTHIRDPARTY ON PRPLTHIRDPARTY.CLAIMNO = PRPLCLAIM.CLAIMNO --and PRPLTHIRDPARTY.SERIALNO = '1'
LEFT JOIN PRPLCARINSURANCE ON PRPLCOMPENSATE.COMPENSATENO = PRPLCARINSURANCE.COMPENSATENO
WHERE PRPLCLAIM.CLAIMNO IN (
'180124AL00002',
'180023AL00066'
);

SELECT p.AGENTCODE,p.LOGINCODE,p.CERTINO,p.LOGINDATE,p.LOGINENDDATE,p.* FROM SALES.PRPDAGENTIDV p

SELECT p.LOGINCODE,p.BUSINESSSOURCE,p.* FROM SALES.PRPDAGENT p

(不通耶)SELECT agidv.AGENTCODE,ag.LOGINCODE,agidv.CERTINO,agidv.LOGINDATE,agidv.LOGINENDDATE,agidv.* FROM SALES.PRPDAGENTIDV agidv LEFT JOIN SALES.PRPDAGENT ag ON ag.LOGINCODE = agidv.LOGINCODE

--DROP TABLE "SALES"."PRPDAGENTLOGINDATERESERVE" 

   CREATE TABLE "SALES"."PRPDAGENTLOGINDATERESERVE" 
   (	
    "AGENTCODE" VARCHAR2(40) NOT NULL ENABLE, 
	"CERTINO" VARCHAR2(44), 
	"LOGINCODE" VARCHAR2(20), 
	"BUSINESSSOURCE" VARCHAR2(20),
	"LOGINDATE" DATE, 
	"LOGINENDDATE" DATE,
	"CREATEDATE" DATE,
	"RUNDATE" DATE,
	 PRIMARY KEY ("AGENTCODE")
	);

   COMMENT ON COLUMN "SALES"."PRPDAGENTLOGINDATERESERVE"."AGENTCODE" IS '中介代碼';
   COMMENT ON COLUMN "SALES"."PRPDAGENTLOGINDATERESERVE"."CERTINO" IS '證件號碼';
   COMMENT ON COLUMN "SALES"."PRPDAGENTLOGINDATERESERVE"."LOGINCODE" IS '登錄代碼';
   COMMENT ON COLUMN "SALES"."PRPDAGENTLOGINDATERESERVE"."BUSINESSSOURCE" IS '業務來源代碼';
   COMMENT ON COLUMN "SALES"."PRPDAGENTLOGINDATERESERVE"."LOGINDATE" IS '登錄日期';
   COMMENT ON COLUMN "SALES"."PRPDAGENTLOGINDATERESERVE"."LOGINENDDATE" IS '登錄到日期';
   COMMENT ON COLUMN "SALES"."PRPDAGENTLOGINDATERESERVE"."CREATEDATE" IS '接單日期';
   COMMENT ON COLUMN "SALES"."PRPDAGENTLOGINDATERESERVE"."RUNDATE" IS '覆蓋時間後戳記時間';
   
  
  SELECT p.* FROM SALES.PRPDAGENTLOGINDATERESERVE p
  
  SELECT p.DUPDATE,p.* FROM sales.PRPDAGENT p
  
  SELECT   TO_DATE(TO_CHAR(ADD_MONTHS(SYSDATE,3),'YYYY/MM/DD'),'YYYY/MM/DD') FROM SALES.PRPDAGENTLOGINDATERESERVE p
  
  SELECT TO_DATE(SYSDATE,'YYYY/MM/DD') FROM SALES.PRPDAGENTLOGINDATERESERVE p
  TO_DATE(TO_CHAR(ADD_MONTHS(SYSDATE:TIMESTAMP#,3),'YYYY/MM/DD'),'YYYY/MM/DD')
  TO_DATE(TO_CHAR(ADD_MONTHS(#sysdate:TIMESTAMP#,3),'YYYY/MM/DD'),'YYYY/MM/DD')
  
  
  SELECT RECEIPTDATE,c.HANDLER1CODE,c.HANDLERCODE,c.* FROM prplclaim c WHERE CLAIMNO = '181224AL00026';
  UPDATE prplclaim c SET RECEIPTDATE = '2025-01-01 12:66'  WHERE CLAIMNO = '181224AL00026';
 UPDATE prplclaim c SET HANDLER1CODE = 'BH168',HANDLERCODE = 'BG142'  WHERE CLAIMNO = '181224AL00026';
  
 SELECT * FROM SWFLOG s WHERE POLICYNO = '181224000132';
SELECT * FROM SWFLOG s WHERE POLICYNO = '181224000132'AND HANDLERCODE = 'CC026';
 UPDATE SWFLOG SET HANDLERCODE = 'CC027'WHERE POLICYNO = '181224000132'AND HANDLERCODE = 'CC026'
 SELECT p.HANDLER1CODE,p.HANDLERCODE,p.* FROM PRPLCOMPENSATE p WHERE p.COMPENSATENO = 'C181224AL0002602'
 UPDATE PRPLCOMPENSATE SET HANDLER1CODE = 'BH168',HANDLERCODE = 'BG142' WHERE COMPENSATENO = 'C181224AL0002602'
 SELECT 
 
 
 
 SELECT NVL(MAX(VALUE),0) VALUE FROM (   SELECT GRADECODE,MIN(TO_NUMBER(VALUE)) VALUE FROM (    
 SELECT UG.COMCODE,UG.USERCODE,GT.GRADECODE, GT.TASKCODE, null GRANTLEVEL,null GRANTVALUE,GT.VALUE, GT.REMARK, GT.FLAG FROM UTIUSERGRADE UG    
 LEFT JOIN UTIGRADETASK GT ON GT.GRADECODE = UG.GRADECODE    
 WHERE UG.USERCODE = 'CC027' AND UG.COMCODE = '00' AND TASKCODE = 'claim.compensate.exceeding'    UNION ALL    
 SELECT COMCODE, USERCODE, GRADECODE, TASKCODE, GRANTLEVEL, GRANTVALUE, VALUE, REMARK, FLAG FROM UTIUSERGRADETASK    
 WHERE USERCODE = 'BH168' AND COMCODE = '00' AND TASKCODE = 'claim.compensate.exceeding'   )   GROUP BY GRADECODE  ) 
 
  SELECT NVL(MAX(VALUE),0) VALUE FROM (   SELECT GRADECODE,MIN(TO_NUMBER(VALUE)) VALUE FROM (    
 SELECT UG.COMCODE,UG.USERCODE,GT.GRADECODE, GT.TASKCODE, null GRANTLEVEL,null GRANTVALUE,GT.VALUE, GT.REMARK, GT.FLAG 
 FROM business.UTIUSERGRADE@PROD UG    
 LEFT JOIN business.UTIGRADETASK@PROD GT ON GT.GRADECODE = UG.GRADECODE    
 WHERE UG.USERCODE = 'CD077' AND UG.COMCODE = '00' AND TASKCODE = 'claim.compensate.exceeding'    UNION ALL    
 SELECT COMCODE, USERCODE, GRADECODE, TASKCODE, GRANTLEVEL, GRANTVALUE, VALUE, REMARK, FLAG FROM business.UTIUSERGRADETASK@PROD    
 WHERE USERCODE = 'CD077' AND COMCODE = '00' AND TASKCODE = 'claim.compensate.exceeding'   )   GROUP BY GRADECODE  ) 


 
 SELECT * FROM prptmain
WHERE EXISTS(SELECT * FROM ccicdms.prpdnewcode WHERE prptmain.BusinessNature= ccicdms.prpdnewcode.CODECODE
AND ccicdms.prpdnewcode.CODETYPE='CheckBusinessNature'
AND ccicdms.prpdnewcode.VALIDSTATUS='1')
	AND prptmain.PROPOSALNO = '9B01202500000063'
	
	
 SELECT * FROM prptmain
WHERE EXISTS(SELECT * FROM ccicdms.prpdnewcode WHERE prptmain.BusinessNature= ccicdms.prpdnewcode.CODECODE
AND ccicdms.prpdnewcode.CODETYPE='CheckBusinessNature'
AND ccicdms.prpdnewcode.VALIDSTATUS='1')
	AND prptmain.PROPOSALNO = '9B01202500000064'

	
SELECT p.APPLICANTBIRTHDAY,p.* FROM PRPLPERSONTRACE p WHERE REGISTNO = '6BL000000000230000015'

6BL000000000230000015


select this_.CLAIMNO as CLAIMNO264_0_, this_.SERIALNO as SERIALNO264_0_, this_.ACCIDEDUCTIBLEPAY as ACCIDEDU3_264_0_, this_.ACCIDEDUCTIBLERATE as ACCIDEDU4_264_0_, this_.amount as amount264_0_, this_.CURRENCY as CURRENCY264_0_, this_.DANGERNO as DANGERNO264_0_, this_.datafrom as datafrom264_0_, this_.DEDUCTIBLE as DEDUCTIBLE264_0_, this_.DEDUCTIBLERATE as DEDUCTI10_264_0_, this_.FEECATEGORY as FEECATE11_264_0_, this_.FLAG as FLAG264_0_, this_.handlerCode as handler13_264_0_, this_.INPUTDATE as INPUTDATE264_0_, this_.ITEMCODE as ITEMCODE264_0_, this_.ITEMDETAILNAME as ITEMDET16_264_0_, this_.ITEMKINDNO as ITEMKINDNO264_0_, this_.KINDCODE as KINDCODE264_0_, this_.KINDCODESUB as KINDCOD19_264_0_, this_.KINDLOSS as KINDLOSS264_0_, this_.KINDREST as KINDREST264_0_, this_.LOSSFEETYPE as LOSSFEE22_264_0_, this_.registNo as registNo264_0_, this_.REMARKFLAG as REMARKFLAG264_0_, this_.REPORTSUMCLAIM as REPORTS25_264_0_, this_.RISKCODE as RISKCODE264_0_, this_.SUMCLAIM as SUMCLAIM264_0_ 
from PRPLCLAIMLOSS this_ where this_.CLAIMNO='180025ML5001' order by this_.SERIALNO ASC

SELECT DISTINCT(KINDCODE),KINDNAME,familyno,ITEMKINDNO,amount,VALUE,itemCode,itemName,itemDetailName FROM PRPCITEMKIND WHERE  KindCode LIKE 'A03%'  AND POLICYNO ='180025MC500002'
select count(1) from ( SELECT DISTINCT(KINDCODE),KINDNAME,familyno,ITEMKINDNO,amount,VALUE,itemCode,itemName,itemDetailName FROM PRPCITEMKIND WHERE  KindCode LIKE 'A03%'  AND POLICYNO ='180025MC500002' Order By KindCode ) num
select prpdriskco0_.COMCODE as COMCODE219_0_, prpdriskco0_.CONFIGCODE as CONFIGCODE219_0_, prpdriskco0_.RISKCODE as RISKCODE219_0_, prpdriskco0_.CONFIGNAME as CONFIGNAME219_0_, prpdriskco0_.CONFIGVALUE as CONFIGVA5_219_0_, prpdriskco0_.CONFIGVALUEDESC as CONFIGVA6_219_0_ from PRPDRISKCONFIG prpdriskco0_ where prpdriskco0_.COMCODE=? and prpdriskco0_.CONFIGCODE=? and prpdriskco0_.RISKCODE=?
select this_.ENDORSENO as ENDORSENO177_0_, this_.ITEMKINDNO as ITEMKINDNO177_0_, this_.ADDRESSNO as ADDRESSNO177_0_, this_.ADJUSTRATE as ADJUSTRATE177_0_, this_.AMOUNT as AMOUNT177_0_, this_.BASEPREMIUM as BASEPREM6_177_0_, this_.BENCHMARKPREMIUM as BENCHMAR7_177_0_, this_.buildingNo as buildingNo177_0_, this_.BUYDATE as BUYDATE177_0_, this_.CALCULATEFLAG as CALCULA10_177_0_, this_.CURRENCY as CURRENCY177_0_, this_.CURRENCY2 as CURRENCY12_177_0_, this_.DEDUCTIBLE as DEDUCTIBLE177_0_, this_.DEDUCTIBLERATE as DEDUCTI14_177_0_, this_.DEDUCTIBLETYPE as DEDUCTI15_177_0_, this_.DISCOUNT as DISCOUNT177_0_, this_.ENDDATE as ENDDATE177_0_, this_.ENDHOUR as ENDHOUR177_0_, this_.EXCHANGERATE2 as EXCHANG19_177_0_, this_.EXCHANGERATECNY as EXCHANG20_177_0_, this_.FAMILYNAME as FAMILYNAME177_0_, this_.FAMILYNO as FAMILYNO177_0_, this_.FLAG as FLAG177_0_, this_.INSUREDVALUETYPE as INSURED24_177_0_, this_.INSUREDVALUETYPENAME as INSURED25_177_0_, this_.ITEMCODE as ITEMCODE177_0_, this_.ITEMDETAILNAME as ITEMDET27_177_0_, this_.itemName as itemName177_0_, this_.ITEMNO as ITEMNO177_0_, this_.KINDCODE as KINDCODE177_0_, this_.KINDNAME as KINDNAME177_0_, this_.MODECODE as MODECODE177_0_, this_.MODENAME as MODENAME177_0_, this_.MODEL as MODEL177_0_, this_.NEWENDDATE as NEWENDDATE177_0_, this_.NEWSTARTDATE as NEWSTAR36_177_0_, this_.perAccidentDamage as perAcci37_177_0_, this_.perAccidentDeaths as perAcci38_177_0_, this_.perHumanDeath as perHuma39_177_0_, this_.perHumanInjury as perHuma40_177_0_, this_.periodMaxAmount as periodM41_177_0_, this_.POLICYNO as POLICYNO177_0_, this_.PREMIUM as PREMIUM177_0_, this_.PREMIUM2 as PREMIUM44_177_0_, this_.PREMIUMCNY as PREMIUMCNY177_0_, this_.PROFITSCALE as PROFITS46_177_0_, this_.QUANTITY as QUANTITY177_0_, this_.RATE as RATE177_0_, this_.RATEPERIOD as RATEPERIOD177_0_, this_.RATIONTYPE as RATIONTYPE177_0_, this_.RISKCODE as RISKCODE177_0_, this_.SHORTRATE as SHORTRATE177_0_, this_.SHORTRATEFLAG as SHORTRA53_177_0_, this_.STARTDATE as STARTDATE177_0_, this_.STARTHOUR as STARTHOUR177_0_, this_.STORAGERATE as STORAGE56_177_0_, this_.UNIT as UNIT177_0_, this_.UNITAMOUNT as UNITAMOUNT177_0_, this_.VALUE as VALUE177_0_ from prpcopyitemkind this_ where this_.ENDORSENO=?




select this_.ENDORSENO as ENDORSENO60_0_, this_.AGENTCODE as AGENTCODE60_0_, this_.AGENTFLAG as AGENTFLAG60_0_, this_.APPROVERCODE as APPROVER6_60_0_, this_.CLASSCODE as CLASSCODE60_0_, this_.COMCODE as COMCODE60_0_, this_.COMPENSATENO as COMPENS11_60_0_, this_.ENDORDATE as ENDORDATE60_0_, this_.ENDORREASON as ENDORRE16_60_0_, this_.ENDORSEAPPLI as ENDORSE18_60_0_, this_.ENDORTYPE as ENDORTYPE60_0_, this_.ENDORSETIMES as ENDORSE21_60_0_, this_.FLAG as FLAG60_0_, this_.HANDLER1CODE as HANDLER23_60_0_, this_.HANDLER1NAME as HANDLER24_60_0_, this_.HANDLERCODE as HANDLER25_60_0_, this_.HANDLERNAME as HANDLER26_60_0_, this_.INPUTDATE as INPUTDATE60_0_, this_.INPUTHOUR as INPUTHOUR60_0_, this_.INSUREDCODE as INSURED29_60_0_, this_.INSUREDNAME as INSURED30_60_0_, this_.JFEEFLAG as JFEEFLAG60_0_, this_.LANGUAGE as LANGUAGE60_0_, this_.MAKECOM as MAKECOM60_0_, this_.NEWVALIDDATE as NEWVALI37_60_0_, this_.OPERATORCODE as OPERATO38_60_0_, this_.PAYREFCODE as PAYREFCODE60_0_, this_.PAYREFNAME as PAYREFNAME60_0_, this_.POLICYNO as POLICYNO60_0_, this_.POLICYTYPE as POLICYTYPE60_0_, this_.PRECHECKDATE as PRECHEC44_60_0_, this_.PRINTNO as PRINTNO60_0_, this_.RISKCODE as RISKCODE60_0_, this_.STATISTICSYM as STATIST52_60_0_, this_.SUBBUSINESSNATURE as SUBBUSI53_60_0_, this_.UNDERWRITECODE as UNDERWR54_60_0_, this_.UNDERWRITEENDDATE as UNDERWR55_60_0_, this_.UNDERWRITEFLAG as UNDERWR56_60_0_, this_.UNDERWRITENAME as UNDERWR57_60_0_, this_.UPDATEDATE as UPDATEDATE60_0_, this_.UPDATEHOUR as UPDATEHOUR60_0_, this_.UPDATERCODE as UPDATER60_60_0_, this_.VALIDDATE as VALIDDATE60_0_, this_.VALIDHOUR as VALIDHOUR60_0_, this_.VISACODE as VISACODE60_0_ 
from PRPPHEAD this_ where PolicyNo = '180025000094' AND (ValidDate <to_date('2025-04-18','yyyy-MM-dd') OR (ValidDate=to_date('2025-04-18','yyyy-MM-dd') AND ValidHour<=11)) AND UnderWriteFlag in ('1', '3')  ORDER BY InputDate DESC,EndorseTimes DESC


SELECT p.INSUREDCODE,p.* FROM PRPCOPYMAIN p WHERE p.ENDORSENO = '180025000094' 

SELECT p.INSUREDCODE,p.* FROM PRPCOPYMAIN p WHERE p.ENDORSENO = '180025C1000017'
