package com.tlg.sales.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

/** mantis：SALES0007，處理人員：BJ085，需求單編號：SALES0007 新增業務人員所屬服務人員維護*/
@SuppressWarnings("serial")
public class HandlercodeTmp extends IBatisBaseEntity<BigDecimal> {
	 /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HANDLERCODE_TMP.HANDLERCODE
     *
     * @ibatorgenerated Thu Sep 30 17:03:20 CST 2021
     */
    private String handlercode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HANDLERCODE_TMP.ORGICODE
     *
     * @ibatorgenerated Thu Sep 30 17:03:20 CST 2021
     */
    private String orgicode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HANDLERCODE_TMP.HANDLERNAME
     *
     * @ibatorgenerated Thu Sep 30 17:03:20 CST 2021
     */
    private Object handlername;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HANDLERCODE_TMP.AMT
     *
     * @ibatorgenerated Thu Sep 30 17:03:20 CST 2021
     */
    private Long amt;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HANDLERCODE_TMP.VALIDSTATUS
     *
     * @ibatorgenerated Thu Sep 30 17:03:20 CST 2021
     */
    private String validstatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HANDLERCODE_TMP.ICREATE
     *
     * @ibatorgenerated Thu Sep 30 17:03:20 CST 2021
     */
    private Object icreate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HANDLERCODE_TMP.DCREATE
     *
     * @ibatorgenerated Thu Sep 30 17:03:20 CST 2021
     */
    private Date dcreate;
    
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HANDLERCODE_TMP.HANDLERCODE
     *
     * @return the value of HANDLERCODE_TMP.HANDLERCODE
     *
     * @ibatorgenerated Thu Sep 30 17:03:20 CST 2021
     */
    public String getHandlercode() {
        return handlercode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HANDLERCODE_TMP.HANDLERCODE
     *
     * @param handlercode the value for HANDLERCODE_TMP.HANDLERCODE
     *
     * @ibatorgenerated Thu Sep 30 17:03:20 CST 2021
     */
    public void setHandlercode(String handlercode) {
        this.handlercode = handlercode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HANDLERCODE_TMP.ORGICODE
     *
     * @return the value of HANDLERCODE_TMP.ORGICODE
     *
     * @ibatorgenerated Thu Sep 30 17:03:20 CST 2021
     */
    public String getOrgicode() {
        return orgicode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HANDLERCODE_TMP.ORGICODE
     *
     * @param orgicode the value for HANDLERCODE_TMP.ORGICODE
     *
     * @ibatorgenerated Thu Sep 30 17:03:20 CST 2021
     */
    public void setOrgicode(String orgicode) {
        this.orgicode = orgicode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HANDLERCODE_TMP.HANDLERNAME
     *
     * @return the value of HANDLERCODE_TMP.HANDLERNAME
     *
     * @ibatorgenerated Thu Sep 30 17:03:20 CST 2021
     */
    public Object getHandlername() {
        return handlername;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HANDLERCODE_TMP.HANDLERNAME
     *
     * @param handlername the value for HANDLERCODE_TMP.HANDLERNAME
     *
     * @ibatorgenerated Thu Sep 30 17:03:20 CST 2021
     */
    public void setHandlername(Object handlername) {
        this.handlername = handlername;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HANDLERCODE_TMP.AMT
     *
     * @return the value of HANDLERCODE_TMP.AMT
     *
     * @ibatorgenerated Thu Sep 30 17:03:20 CST 2021
     */
    public Long getAmt() {
        return amt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HANDLERCODE_TMP.AMT
     *
     * @param amt the value for HANDLERCODE_TMP.AMT
     *
     * @ibatorgenerated Thu Sep 30 17:03:20 CST 2021
     */
    public void setAmt(Long amt) {
        this.amt = amt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HANDLERCODE_TMP.VALIDSTATUS
     *
     * @return the value of HANDLERCODE_TMP.VALIDSTATUS
     *
     * @ibatorgenerated Thu Sep 30 17:03:20 CST 2021
     */
    public String getValidstatus() {
        return validstatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HANDLERCODE_TMP.VALIDSTATUS
     *
     * @param validstatus the value for HANDLERCODE_TMP.VALIDSTATUS
     *
     * @ibatorgenerated Thu Sep 30 17:03:20 CST 2021
     */
    public void setValidstatus(String validstatus) {
        this.validstatus = validstatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HANDLERCODE_TMP.ICREATE
     *
     * @return the value of HANDLERCODE_TMP.ICREATE
     *
     * @ibatorgenerated Thu Sep 30 17:03:20 CST 2021
     */
    public Object getIcreate() {
        return icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HANDLERCODE_TMP.ICREATE
     *
     * @param icreate the value for HANDLERCODE_TMP.ICREATE
     *
     * @ibatorgenerated Thu Sep 30 17:03:20 CST 2021
     */
    public void setIcreate(Object icreate) {
        this.icreate = icreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HANDLERCODE_TMP.DCREATE
     *
     * @return the value of HANDLERCODE_TMP.DCREATE
     *
     * @ibatorgenerated Thu Sep 30 17:03:20 CST 2021
     */
    public Date getDcreate() {
        return dcreate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HANDLERCODE_TMP.DCREATE
     *
     * @param dcreate the value for HANDLERCODE_TMP.DCREATE
     *
     * @ibatorgenerated Thu Sep 30 17:03:20 CST 2021
     */
    public void setDcreate(Date dcreate) {
        this.dcreate = dcreate;
    }
}