jdbc.driverClassName=oracle.jdbc.driver.OracleDriver
#jdbc.url=jdbc:oracle:thin:@10.63.205.110:1521:oadbdev
jdbc.url=jdbc:oracle:thin:@192.168.19.17:1521:tlgins_int
#jdbc.username=oadev
#jdbc.password=oadev
jdbc.username=business
jdbc.password=business0415
jdbc.maxActive=5
hibernate.dialect=org.hibernate.dialect.OracleDialect

#jdbc.driverClassName=com.informix.jdbc.IfxDriver
#jdbc.url=jdbc:informix-sqli:192.168.2.250:20004/zgs_pnadb:INFORMIXSERVER=test_dbs;NEWCODESET=gbk,8859-1,819;user=tpall
#jdbc.username=tpall
#jdbc.password=tpall
#jdbc.maxActive=5
#hibernate.dialect=ins.framework.dialect.InformixDialect

#jdbc.driverClassName=com.informix.jdbc.IfxDriver
#jdbc.url=jdbc:informix-sqli:192.168.2.250:20004/arch4platform:INFORMIXSERVER=test_dbs;NEWCODESET=gbk,8859-1,819;username=piccpnc
#jdbc.username=piccpnc
#jdbc.password=sinosoft
#jdbc.maxActive=5
#hibernate.dialect=ins.framework.dialect.InformixDialect