package cn.com.sinosoft.dms.model;

// Generated by Hibernate Tools 3.2.0.b9 (sinosoft version)

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PrpDplanClauseKindId generated by Tools.Don't edit.
 */
@Embeddable
public class PrpDplanClauseKindId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private String planCode;
	private Integer planKCSerialNo;
	private String clauseCode;

	public PrpDplanClauseKindId() {
	}

	@Column(name = "plancode")
	public String getPlanCode() {
		return this.planCode;
	}

	public void setPlanCode(String planCode) {
		this.planCode = planCode;
	}

	@Column(name = "plankcserialno")
	public Integer getPlanKCSerialNo() {
		return this.planKCSerialNo;
	}

	public void setPlanKCSerialNo(Integer planKCSerialNo) {
		this.planKCSerialNo = planKCSerialNo;
	}

	@Column(name = "clausecode")
	public String getClauseCode() {
		return this.clauseCode;
	}

	public void setClauseCode(String clauseCode) {
		this.clauseCode = clauseCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrpDplanClauseKindId))
			return false;
		PrpDplanClauseKindId castOther = (PrpDplanClauseKindId) other;

		return ((this.getPlanCode() == castOther.getPlanCode()) || (this
				.getPlanCode() != null
				&& castOther.getPlanCode() != null && this.getPlanCode()
				.equals(castOther.getPlanCode())))
				&& ((this.getPlanKCSerialNo() == castOther.getPlanKCSerialNo()) || (this
						.getPlanKCSerialNo() != null
						&& castOther.getPlanKCSerialNo() != null && this
						.getPlanKCSerialNo().equals(
								castOther.getPlanKCSerialNo())))
				&& ((this.getClauseCode() == castOther.getClauseCode()) || (this
						.getClauseCode() != null
						&& castOther.getClauseCode() != null && this
						.getClauseCode().equals(castOther.getClauseCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPlanCode() == null ? 0 : this.getPlanCode().hashCode());
		result = 37
				* result
				+ (getPlanKCSerialNo() == null ? 0 : this.getPlanKCSerialNo()
						.hashCode());
		result = 37
				* result
				+ (getClauseCode() == null ? 0 : this.getClauseCode()
						.hashCode());
		return result;
	}

}
