package cn.com.sinosoft.dms.model;

// Generated by Hibernate Tools 3.2.0.b9 (sinosoft version)

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Type;

/**
 * PrpDplan generated by Tools.Don't edit.
 */
@Entity
@Table(name = "prpdplan")
public class PrpDplan implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	/** 方案代码 */
	private String planCode;
	/** 旧方案代码 */
	private String oldPlanCode;
	/** 方案简体中文名称 */
	private String planCName;
	/** 方案繁体中文名称 */
	private String planTName;
	/** 方案简称名称 */
	private String planSName;
	/** 方案英文名称 */
	private String planEName;
	/** 是否定额 */
	private String isFixedFlag;
	/** 框架代码 */
	private String frameCode;
	/** 产品代码 */
	private String riskCode;
	/** 产品属性 */
	private String riskAttribute;
	/** 销售区域层级 */
	private String saleAreaLevel;
	/** 销售区域代码(用逗号分隔) */
	private String saleAreaCode;
	/** 销售区域名???(用逗号分隔) */
	private String saleAreaName;
	/** 方案是否可修改 */
	private String updateFlag;
	/** 出单方案时是否一份 */
	private String uniqueFlag;
	/** 方案允许最大份数 */
	private String maxCount;
	/** 创建人 */
	private String createrCode;
	/** 创建时间 */
	private Date createTime;
	/** 最后修改人 */
	private String updaterCode;
	/** 最后修改时间 */
	private Date updateTime;
	/** 文本内容（预留） */
	private String contentNumber;
	/** 生效日期 */
	private Date validDate;
	/** 失效日期 */
	private Date invalidDate;
	/** 有效标志 */
	private String validInd;
	/** 预留字段1 */
	private String tcol1;
	/** 预留字段2 */
	private String tcol2;
	/** 预留字段3 */
	private String tcol3;
	/** 备注 */
	private String remark;
	/** 标志字段 */
	private String flag;

	public PrpDplan() {
	}

	/**       
	 * 方案代码
	 */
	@Id
	@Column(name = "plancode")
	public String getPlanCode() {
		return this.planCode;
	}

	public void setPlanCode(String planCode) {
		this.planCode = planCode;
	}

	/**       
	 * 旧方案代码
	 */

	@Column(name = "oldplancode")
	public String getOldPlanCode() {
		return this.oldPlanCode;
	}

	public void setOldPlanCode(String oldPlanCode) {
		this.oldPlanCode = oldPlanCode;
	}

	/**       
	 * 方案简体中文名称
	 */

	@Column(name = "plancname")
	public String getPlanCName() {
		return this.planCName;
	}

	public void setPlanCName(String planCName) {
		this.planCName = planCName;
	}

	/**       
	 * 方案繁体中文名称
	 */

	@Column(name = "plantname")
	public String getPlanTName() {
		return this.planTName;
	}

	public void setPlanTName(String planTName) {
		this.planTName = planTName;
	}

	/**       
	 * 方案简称名称
	 */

	@Column(name = "plansname")
	public String getPlanSName() {
		return this.planSName;
	}

	public void setPlanSName(String planSName) {
		this.planSName = planSName;
	}

	/**       
	 * 方案英文名称
	 */

	@Column(name = "planename")
	public String getPlanEName() {
		return this.planEName;
	}

	public void setPlanEName(String planEName) {
		this.planEName = planEName;
	}

	/**       
	 * 是否定额
	 */

	@Column(name = "isfixedflag")
	public String getIsFixedFlag() {
		return this.isFixedFlag;
	}

	public void setIsFixedFlag(String isFixedFlag) {
		this.isFixedFlag = isFixedFlag;
	}

	/**       
	 * 框架代码
	 */

	@Column(name = "framecode")
	public String getFrameCode() {
		return this.frameCode;
	}

	public void setFrameCode(String frameCode) {
		this.frameCode = frameCode;
	}

	/**       
	 * 产品代码
	 */

	@Column(name = "riskcode")
	public String getRiskCode() {
		return this.riskCode;
	}

	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}

	/**       
	 * 产品属性
	 */

	@Column(name = "riskattribute")
	public String getRiskAttribute() {
		return this.riskAttribute;
	}

	public void setRiskAttribute(String riskAttribute) {
		this.riskAttribute = riskAttribute;
	}

	/**       
	 * 销售区域层级
	 */

	@Column(name = "salearealevel")
	public String getSaleAreaLevel() {
		return this.saleAreaLevel;
	}

	public void setSaleAreaLevel(String saleAreaLevel) {
		this.saleAreaLevel = saleAreaLevel;
	}

	/**       
	 * 销售区域代码(用逗号分隔)
	 */

	@Column(name = "saleareacode")
	@Basic(fetch = FetchType.LAZY)
	@Type(type = "org.springframework.orm.hibernate3.support.ClobStringType")
	public String getSaleAreaCode() {
		return this.saleAreaCode;
	}

	public void setSaleAreaCode(String saleAreaCode) {
		this.saleAreaCode = saleAreaCode;
	}

	/**       
	 * 销售区域名???(用逗号分隔)
	 */

	@Column(name = "saleareaname")
	@Basic(fetch = FetchType.LAZY)
	@Type(type = "org.springframework.orm.hibernate3.support.ClobStringType")
	public String getSaleAreaName() {
		return this.saleAreaName;
	}

	public void setSaleAreaName(String saleAreaName) {
		this.saleAreaName = saleAreaName;
	}

	/**       
	 * 方案是否可修改
	 */

	@Column(name = "updateflag")
	public String getUpdateFlag() {
		return this.updateFlag;
	}

	public void setUpdateFlag(String updateFlag) {
		this.updateFlag = updateFlag;
	}

	/**       
	 * 出单方案时是否一份
	 */

	@Column(name = "uniqueflag")
	public String getUniqueFlag() {
		return this.uniqueFlag;
	}

	public void setUniqueFlag(String uniqueFlag) {
		this.uniqueFlag = uniqueFlag;
	}

	/**       
	 * 方案允许最大份数
	 */

	@Column(name = "maxCount")
	public String getMaxCount() {
		return this.maxCount;
	}

	public void setMaxCount(String maxCount) {
		this.maxCount = maxCount;
	}
	
	/**       
	 * 创建人
	 */

	@Column(name = "creatercode")
	public String getCreaterCode() {
		return this.createrCode;
	}

	public void setCreaterCode(String createrCode) {
		this.createrCode = createrCode;
	}

	/**       
	 * 创建时间
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "createtime")
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**       
	 * 最后修改人
	 */

	@Column(name = "updatercode")
	public String getUpdaterCode() {
		return this.updaterCode;
	}

	public void setUpdaterCode(String updaterCode) {
		this.updaterCode = updaterCode;
	}

	/**       
	 * 最后修改时间
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "updatetime")
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**       
	 * 文本内容（预留）
	 */

	@Column(name = "contentnumber")
	public String getContentNumber() {
		return this.contentNumber;
	}

	public void setContentNumber(String contentNumber) {
		this.contentNumber = contentNumber;
	}

	/**       
	 * 生效日期
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "validdate")
	public Date getValidDate() {
		return this.validDate;
	}

	public void setValidDate(Date validDate) {
		this.validDate = validDate;
	}

	/**       
	 * 失效日期
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "invaliddate")
	public Date getInvalidDate() {
		return this.invalidDate;
	}

	public void setInvalidDate(Date invalidDate) {
		this.invalidDate = invalidDate;
	}

	/**       
	 * 有效标志
	 */

	@Column(name = "validind")
	public String getValidInd() {
		return this.validInd;
	}

	public void setValidInd(String validInd) {
		this.validInd = validInd;
	}

	/**       
	 * 预留字段1
	 */

	@Column(name = "tcol1")
	public String getTcol1() {
		return this.tcol1;
	}

	public void setTcol1(String tcol1) {
		this.tcol1 = tcol1;
	}

	/**       
	 * 预留字段2
	 */

	@Column(name = "tcol2")
	public String getTcol2() {
		return this.tcol2;
	}

	public void setTcol2(String tcol2) {
		this.tcol2 = tcol2;
	}

	/**       
	 * 预留字段3
	 */

	@Column(name = "tcol3")
	public String getTcol3() {
		return this.tcol3;
	}

	public void setTcol3(String tcol3) {
		this.tcol3 = tcol3;
	}

	/**       
	 * 备注
	 */

	@Column(name = "remark")
	@Basic(fetch = FetchType.LAZY)
	@Type(type = "org.springframework.orm.hibernate3.support.ClobStringType")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**       
	 * 标志字段
	 */

	@Column(name = "flag")
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

}
