package cn.com.sinosoft.dms.model;

// Generated 2013-2-21 20:26:58 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PrpDclauseKind generated by hbm2java
 */
@Entity
@Table(name = "PRPDCLAUSEKIND")
public class PrpDclauseKind implements java.io.Serializable {

	private PrpDclauseKindId id;
	private String flag;

	public PrpDclauseKind() {
	}

	public PrpDclauseKind(PrpDclauseKindId id) {
		this.id = id;
	}

	public PrpDclauseKind(PrpDclauseKindId id, String flag) {
		this.id = id;
		this.flag = flag;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "riskCode", column = @Column(name = "RISKCODE", nullable = false, length = 4)),
			@AttributeOverride(name = "clauseType", column = @Column(name = "CLAUSETYPE", nullable = false, length = 3)),
			@AttributeOverride(name = "kindCode", column = @Column(name = "KINDCODE", nullable = false, length = 7)),
			@AttributeOverride(name = "relateKindCode", column = @Column(name = "RELATEKINDCODE", nullable = false, length = 50)) })
	public PrpDclauseKindId getId() {
		return this.id;
	}

	public void setId(PrpDclauseKindId id) {
		this.id = id;
	}

	@Column(name = "FLAG", length = 2)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

}
