log4j.rootLogger=OFF
log4j.logger.com.sinosoft.claim.resource.dtofactory.domain=error,ErrorFile
log4j.logger.com.sinosoft.claim.resource.dtofactory.custom=error,ErrorFile
log4j.logger.com.sinosoft.claim.bl=error,stdout,ErrorFile
log4j.logger.com.sinosoft.claim.ui=error,stdout,ErrorFile

#first appender writes to console
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%5p [%d{HH:mm:ss}] (%c:%M:%L) - %m%n
#log4j.appender.stdout.layout.ConversionPattern=%d{MM-dd HH:mm:ss} [%t] %-5p %c - %m%n
#log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %p %t %c - %m%n
#log4j.appender.stdout.layout.ConversionPattern= %-4r - %m%n
#log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss,SSS} [%c]-[%p] %m%n
#log4j.appender.stdout.layout.ConversionPattern=%d %5p [%t] (%F:%L) - %m%n 

#second appender writes to file
log4j.appender.WarnFile=org.apache.log4j.DailyRollingFileAppender
log4j.appender.WarnFile.file=claimWarn.log
log4j.appender.WarnFile.layout=org.apache.log4j.PatternLayout
log4j.appender.WarnFile.layout.ConversionPattern=%10d %-4r %-5p %c %x - %m%n
#log4j.appender.WarnFile.MaxFileSize=1KB 
#log4j.appender.WarnFile.MaxBackupIndex=2

 
log4j.appender.DebugFile=org.apache.log4j.DailyRollingFileAppender
log4j.appender.DebugFile.file=claimDebug.log
log4j.appender.DebugFile.layout=org.apache.log4j.PatternLayout
log4j.appender.DebugFile.layout.ConversionPattern=%10d %-4r %-5p %c %x - %m%n
#log4j.appender.DebugFile.MaxFileSize=1KB 
#log4j.appender.DebugFile.MaxBackupIndex=2


log4j.appender.ErrorFile=org.apache.log4j.DailyRollingFileAppender
log4j.appender.ErrorFile.file=claimError.log
log4j.appender.ErrorFile.layout=org.apache.log4j.PatternLayout
log4j.appender.ErrorFile.layout.ConversionPattern=%10d %-4r %-5p %c %x - %m%n
#log4j.appender.ErrorFile.MaxFileSize=1KB 
#log4j.appender.ErrorFile.MaxBackupIndex=2