package com.tlg.msSqlRdcB2b.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

/**
 * mantis：OTH0175，處理人員：DP0706，需求單編號：OTH0175_APS-收件收件報備系統 已出單資料回拋B2B
 * @author dp0706
 *
 */
public class RptCoredata  extends IBatisBaseEntity<BigDecimal>{
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RptCoredata.PolDate
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    private Date poldate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RptCoredata.InsType
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    private String instype;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RptCoredata.InsuId
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    private String insuid;
	
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RptCoredata.PolicyNo
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    private String policyno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RptCoredata.EndorseNo
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    private String endorseno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RptCoredata.InsuName
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    private String insuname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RptCoredata.EffDate
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    private Date effdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RptCoredata.StartPeriodDate
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    private Date startperioddate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RptCoredata.EndPeriodDate
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    private Date endperioddate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RptCoredata.TotalPrem
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    private BigDecimal totalprem;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RptCoredata.ChannelId
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    private String channelid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RptCoredata.ChannelName
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    private String channelname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RptCoredata.ChnlAgentBussNo
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    private String chnlagentbussno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RptCoredata.ChnlAgentName
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    private String chnlagentname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RptCoredata.PolAgentId
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    private String polagentid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RptCoredata.PolAgentName
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    private String polagentname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RptCoredata.CreateDate
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    private Date createdate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RptCoredata.PolicyNo
     *
     * @return the value of RptCoredata.PolicyNo
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    public String getPolicyno() {
        return policyno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RptCoredata.PolicyNo
     *
     * @param policyno the value for RptCoredata.PolicyNo
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    public void setPolicyno(String policyno) {
        this.policyno = policyno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RptCoredata.EndorseNo
     *
     * @return the value of RptCoredata.EndorseNo
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    public String getEndorseno() {
        return endorseno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RptCoredata.EndorseNo
     *
     * @param endorseno the value for RptCoredata.EndorseNo
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    public void setEndorseno(String endorseno) {
        this.endorseno = endorseno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RptCoredata.InsuName
     *
     * @return the value of RptCoredata.InsuName
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    public String getInsuname() {
        return insuname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RptCoredata.InsuName
     *
     * @param insuname the value for RptCoredata.InsuName
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    public void setInsuname(String insuname) {
        this.insuname = insuname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RptCoredata.EffDate
     *
     * @return the value of RptCoredata.EffDate
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    public Date getEffdate() {
        return effdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RptCoredata.EffDate
     *
     * @param effdate the value for RptCoredata.EffDate
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    public void setEffdate(Date effdate) {
        this.effdate = effdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RptCoredata.StartPeriodDate
     *
     * @return the value of RptCoredata.StartPeriodDate
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    public Date getStartperioddate() {
        return startperioddate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RptCoredata.StartPeriodDate
     *
     * @param startperioddate the value for RptCoredata.StartPeriodDate
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    public void setStartperioddate(Date startperioddate) {
        this.startperioddate = startperioddate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RptCoredata.EndPeriodDate
     *
     * @return the value of RptCoredata.EndPeriodDate
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    public Date getEndperioddate() {
        return endperioddate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RptCoredata.EndPeriodDate
     *
     * @param endperioddate the value for RptCoredata.EndPeriodDate
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    public void setEndperioddate(Date endperioddate) {
        this.endperioddate = endperioddate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RptCoredata.TotalPrem
     *
     * @return the value of RptCoredata.TotalPrem
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    public BigDecimal getTotalprem() {
        return totalprem;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RptCoredata.TotalPrem
     *
     * @param totalprem the value for RptCoredata.TotalPrem
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    public void setTotalprem(BigDecimal totalprem) {
        this.totalprem = totalprem;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RptCoredata.ChannelId
     *
     * @return the value of RptCoredata.ChannelId
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    public String getChannelid() {
        return channelid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RptCoredata.ChannelId
     *
     * @param channelid the value for RptCoredata.ChannelId
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    public void setChannelid(String channelid) {
        this.channelid = channelid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RptCoredata.ChannelName
     *
     * @return the value of RptCoredata.ChannelName
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    public String getChannelname() {
        return channelname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RptCoredata.ChannelName
     *
     * @param channelname the value for RptCoredata.ChannelName
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    public void setChannelname(String channelname) {
        this.channelname = channelname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RptCoredata.ChnlAgentBussNo
     *
     * @return the value of RptCoredata.ChnlAgentBussNo
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    public String getChnlagentbussno() {
        return chnlagentbussno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RptCoredata.ChnlAgentBussNo
     *
     * @param chnlagentbussno the value for RptCoredata.ChnlAgentBussNo
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    public void setChnlagentbussno(String chnlagentbussno) {
        this.chnlagentbussno = chnlagentbussno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RptCoredata.ChnlAgentName
     *
     * @return the value of RptCoredata.ChnlAgentName
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    public String getChnlagentname() {
        return chnlagentname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RptCoredata.ChnlAgentName
     *
     * @param chnlagentname the value for RptCoredata.ChnlAgentName
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    public void setChnlagentname(String chnlagentname) {
        this.chnlagentname = chnlagentname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RptCoredata.PolAgentId
     *
     * @return the value of RptCoredata.PolAgentId
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    public String getPolagentid() {
        return polagentid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RptCoredata.PolAgentId
     *
     * @param polagentid the value for RptCoredata.PolAgentId
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    public void setPolagentid(String polagentid) {
        this.polagentid = polagentid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RptCoredata.PolAgentName
     *
     * @return the value of RptCoredata.PolAgentName
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    public String getPolagentname() {
        return polagentname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RptCoredata.PolAgentName
     *
     * @param polagentname the value for RptCoredata.PolAgentName
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    public void setPolagentname(String polagentname) {
        this.polagentname = polagentname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RptCoredata.CreateDate
     *
     * @return the value of RptCoredata.CreateDate
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RptCoredata.CreateDate
     *
     * @param createdate the value for RptCoredata.CreateDate
     *
     * @ibatorgenerated Thu Jun 12 15:17:34 CST 2025
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

	public Date getPoldate() {
		return poldate;
	}

	public void setPoldate(Date poldate) {
		this.poldate = poldate;
	}

	public String getInstype() {
		return instype;
	}

	public void setInstype(String instype) {
		this.instype = instype;
	}

	public String getInsuid() {
		return insuid;
	}

	public void setInsuid(String insuid) {
		this.insuid = insuid;
	}
}