package com.sinosoft.claim.schema.model;

// Generated 2010-4-1 9:33:00 by Hibernate Tools 3.2.0.b9-sinosoft1.1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PrpCinvestRedeem generated by Tools.Don't edit.
 */
@Entity
@Table(name = "prpcinvestredeem")
public class PrpCinvestRedeem implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	/** SerialNo */
	private PrpCinvestRedeemId id;
	/** 投保单号码 */
	private PrpCmain prpCmain;
	/** 险种代码 */
	private String riskCode;
	/** 批单号 */
	private String endorseNo;
	/** 申请赎回笔数 */
	private Integer applyQuantity;
	/** 实际赎回笔数 */
	private Integer redeemQuantity;
	/** 实际赎回金额 */
	private Double redeemFee;
	/** 操作员代码 */
	private String operatorCode;
	/** 归属机构 */
	private String comCode;
	/** 输入日期 */
	private Date inputDate;
	/** 顺延标志 */
	private String delayFlag;
	/** 短信转存後是否删除标记 */
	private String flag;
	/** 插入时间 */
	private Date insertTimeForHis;
	/** 更新时间 */
	private Date operateTimeForHis;

	public PrpCinvestRedeem() {
	}

	/**
	 * SerialNo
	 */
	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "policyNo", column = @Column(name = "policyNo", nullable = false)), @AttributeOverride(name = "serialNo", column = @Column(name = "serialno", nullable = false)) })
	public PrpCinvestRedeemId getId() {
		return this.id;
	}

	public void setId(PrpCinvestRedeemId id) {
		this.id = id;
	}

	/**
	 * 投保单号码
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "policyNo", nullable = false, insertable = false, updatable = false)
	public PrpCmain getPrpCmain() {
		return this.prpCmain;
	}

	public void setPrpCmain(PrpCmain prpCmain) {
		this.prpCmain = prpCmain;
	}

	/**
	 * 险种代码
	 */

	@Column(name = "riskcode", nullable = false)
	public String getRiskCode() {
		return this.riskCode;
	}

	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}

	/**
	 * 批单号
	 */

	@Column(name = "endorseno")
	public String getEndorseNo() {
		return this.endorseNo;
	}

	public void setEndorseNo(String endorseNo) {
		this.endorseNo = endorseNo;
	}

	/**
	 * 申请赎回笔数
	 */

	@Column(name = "applyquantity", nullable = false)
	public Integer getApplyQuantity() {
		return this.applyQuantity;
	}

	public void setApplyQuantity(Integer applyQuantity) {
		this.applyQuantity = applyQuantity;
	}

	/**
	 * 实际赎回笔数
	 */

	@Column(name = "redeemquantity")
	public Integer getRedeemQuantity() {
		return this.redeemQuantity;
	}

	public void setRedeemQuantity(Integer redeemQuantity) {
		this.redeemQuantity = redeemQuantity;
	}

	/**
	 * 实际赎回金额
	 */

	@Column(name = "redeemfee")
	public Double getRedeemFee() {
		return this.redeemFee;
	}

	public void setRedeemFee(Double redeemFee) {
		this.redeemFee = redeemFee;
	}

	/**
	 * 操作员代码
	 */

	@Column(name = "operatorcode", nullable = false)
	public String getOperatorCode() {
		return this.operatorCode;
	}

	public void setOperatorCode(String operatorCode) {
		this.operatorCode = operatorCode;
	}

	/**
	 * 归属机构
	 */

	@Column(name = "comcode")
	public String getComCode() {
		return this.comCode;
	}

	public void setComCode(String comCode) {
		this.comCode = comCode;
	}

	/**
	 * 输入日期
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "inputdate")
	public Date getInputDate() {
		return this.inputDate;
	}

	public void setInputDate(Date inputDate) {
		this.inputDate = inputDate;
	}

	/**
	 * 顺延标志
	 */

	@Column(name = "delayflag")
	public String getDelayFlag() {
		return this.delayFlag;
	}

	public void setDelayFlag(String delayFlag) {
		this.delayFlag = delayFlag;
	}

	/**
	 * 短信转存後是否删除标记
	 */

	@Column(name = "flag")
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	/**
	 * 插入时间
	 */

	@Column(name = "inserttimeforhis", insertable = false, updatable = false)
	public Date getInsertTimeForHis() {
		return this.insertTimeForHis;
	}

	public void setInsertTimeForHis(Date insertTimeForHis) {
		this.insertTimeForHis = insertTimeForHis;
	}

	/**
	 * 更新时间
	 */

	@Column(name = "operatetimeforhis", insertable = false)
	public Date getOperateTimeForHis() {
		return this.operateTimeForHis;
	}

	public void setOperateTimeForHis(Date operateTimeForHis) {
		this.operateTimeForHis = operateTimeForHis;
	}

}
