package com.sinosoft.claim.schema.model;

// Generated 2010-4-1 9:33:00 by Hibernate Tools 3.2.0.b9-sinosoft1.1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PrpCinsuredIdvListNature generated by Tools.Don't edit.
 */
@Entity
@Table(name = "prpcinsuredidvlistnature")
public class PrpCinsuredIdvListNature implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	/** SerialNo */
	public PrpCinsuredIdvListNatureId id;
	/** 投保单号码 */
	private PrpCinsuredIdvList prpCinsuredIdvList;
	/** 关系人角色标志 */
	private String insuredFlag;
	/** 职称 */
	private String jobTitle;
	/** 在本地工作年限 */
	private Integer localWorkYears;
	/** 总工龄 */
	private Integer totalWorkYears;
	/** 担保物计量单位 */
	private String unit;
	/** 单位电话 */
	private String unitPhoneNumber;
	/** 单位地址 */
	private String unitAddress;
	/** 单位邮编 */
	private String unitPostCode;
	/** 单位性质 */
	private String unitType;
	/** 任职级别 */
	private String dutyLevel;
	/** 任职种类 */
	private String dutyType;
	/** 兼业职业 */
	private String occupationCode;
	/** 房产状况 */
	private String houseProperty;
	/** 户口所在地派出所名称 */
	private String localPoliceStation;
	/** 经常住房地 */
	private String roomAddress;
	/** 邮政编码 */
	private String roomPostCode;
	/** 房屋间数 */
	private String roomNumber;
	/** 保险房屋门牌号 */
	private String roomNo;
	/** 被保险人学校/班级 */
	private String schoolInfo;
	/** 本人月收入 */
	private Double selfMonthIncome;
	/** 家庭月收入 */
	private Double familyMonthIncome;
	/** 收入来源 */
	private String incomeSource;
	/** 常住房电话 */
	private String roomPhone;
	/** 移动电话 */
	// private String mobile;
	/** 家庭人口 */
	private Integer familySumQuantity;
	/** 婚姻状况 */
	private String marriage;
	/** 配偶姓名 */
	private String spouseName;
	/** 配偶出生年月 */
	private Date spouseBornDate;
	/** 配偶身份证号码 */
	private String spouseId;
	/** 配偶手机号码 */
	private String spouseMobile;
	/** 配偶单位 */
	private String spouseUnit;
	/** 配偶职务 */
	private String spouseJobTitle;
	/** 配偶单位电话 */
	private String spouseUnitPhone;
	/** 短信转存後是否删除标记 */
	private String flag;
	/** 插入时间 */
	private Date insertTimeForHis;
	/** 更新时间 */
	private Date operateTimeForHis;

	public PrpCinsuredIdvListNature() {
	}

	/**
	 * SerialNo
	 */
	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "policyNo", column = @Column(name = "policyNo", nullable = false)), @AttributeOverride(name = "serialNo", column = @Column(name = "serialno", nullable = false)) })
	public PrpCinsuredIdvListNatureId getId() {
		return this.id;
	}

	public void setId(PrpCinsuredIdvListNatureId id) {
		this.id = id;
	}

	/**
	 * SerialNo
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "policyNo", nullable = false, insertable = false, updatable = false, referencedColumnName = "policyNo"),
			@JoinColumn(name = "serialno", nullable = false, insertable = false, updatable = false, referencedColumnName = "serialno") })
	public PrpCinsuredIdvList getPrpCinsuredIdvList() {
		return this.prpCinsuredIdvList;
	}

	public void setPrpCinsuredIdvList(PrpCinsuredIdvList prpCinsuredIdvList) {
		this.prpCinsuredIdvList = prpCinsuredIdvList;
	}

	/**
	 * 关系人角色标志
	 */

	@Column(name = "insuredflag")
	public String getInsuredFlag() {
		return this.insuredFlag;
	}

	public void setInsuredFlag(String insuredFlag) {
		this.insuredFlag = insuredFlag;
	}

	/**
	 * 任职种类
	 */

	@Column(name = "dutytype")
	public String getDutyType() {
		return this.dutyType;
	}

	public void setDutyType(String dutyType) {
		this.dutyType = dutyType;
	}

	/**
	 * 移动电话
	 */

	// @Column(name = "mobile")
	// public String getMobile() {
	// return this.mobile;
	// }
	//
	// public void setMobile(String mobile) {
	// this.mobile = mobile;
	// }

	/**
	 * 短信转存後是否删除标记
	 */

	@Column(name = "flag")
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	/**
	 * 插入时间
	 */

	@Column(name = "inserttimeforhis", insertable = false, updatable = false)
	public Date getInsertTimeForHis() {
		return this.insertTimeForHis;
	}

	public void setInsertTimeForHis(Date insertTimeForHis) {
		this.insertTimeForHis = insertTimeForHis;
	}

	/**
	 * 更新时间
	 */

	@Column(name = "operatetimeforhis", insertable = false)
	public Date getOperateTimeForHis() {
		return this.operateTimeForHis;
	}

	public void setOperateTimeForHis(Date operateTimeForHis) {
		this.operateTimeForHis = operateTimeForHis;
	}

	@Column(name = "jobTitle")
	public String getJobTitle() {
		return jobTitle;
	}

	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	@Column(name = "localWorkYears")
	public Integer getLocalWorkYears() {
		return localWorkYears;
	}

	public void setLocalWorkYears(Integer localWorkYears) {
		this.localWorkYears = localWorkYears;
	}

	@Column(name = "totalWorkYears")
	public Integer getTotalWorkYears() {
		return totalWorkYears;
	}

	public void setTotalWorkYears(Integer totalWorkYears) {
		this.totalWorkYears = totalWorkYears;
	}

	@Column(name = "unit")
	public String getUnit() {
		return unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Column(name = "unitPhoneNumber")
	public String getUnitPhoneNumber() {
		return unitPhoneNumber;
	}

	public void setUnitPhoneNumber(String unitPhoneNumber) {
		this.unitPhoneNumber = unitPhoneNumber;
	}

	@Column(name = "unitAddress")
	public String getUnitAddress() {
		return unitAddress;
	}

	public void setUnitAddress(String unitAddress) {
		this.unitAddress = unitAddress;
	}

	@Column(name = "unitPostCode")
	public String getUnitPostCode() {
		return unitPostCode;
	}

	public void setUnitPostCode(String unitPostCode) {
		this.unitPostCode = unitPostCode;
	}

	@Column(name = "unitType")
	public String getUnitType() {
		return unitType;
	}

	public void setUnitType(String unitType) {
		this.unitType = unitType;
	}

	@Column(name = "dutyLevel")
	public String getDutyLevel() {
		return dutyLevel;
	}

	public void setDutyLevel(String dutyLevel) {
		this.dutyLevel = dutyLevel;
	}

	@Column(name = "houseProperty")
	public String getHouseProperty() {
		return houseProperty;
	}

	public void setHouseProperty(String houseProperty) {
		this.houseProperty = houseProperty;
	}

	@Column(name = "localPoliceStation")
	public String getLocalPoliceStation() {
		return localPoliceStation;
	}

	public void setLocalPoliceStation(String localPoliceStation) {
		this.localPoliceStation = localPoliceStation;
	}

	@Column(name = "roomAddress")
	public String getRoomAddress() {
		return roomAddress;
	}

	public void setRoomAddress(String roomAddress) {
		this.roomAddress = roomAddress;
	}

	@Column(name = "roomPostCode")
	public String getRoomPostCode() {
		return roomPostCode;
	}

	public void setRoomPostCode(String roomPostCode) {
		this.roomPostCode = roomPostCode;
	}

	@Column(name = "roomNumber")
	public String getRoomNumber() {
		return roomNumber;
	}

	public void setRoomNumber(String roomNumber) {
		this.roomNumber = roomNumber;
	}

	@Column(name = "roomNo")
	public String getRoomNo() {
		return roomNo;
	}

	public void setRoomNo(String roomNo) {
		this.roomNo = roomNo;
	}

	@Column(name = "schoolInfo")
	public String getSchoolInfo() {
		return schoolInfo;
	}

	public void setSchoolInfo(String schoolInfo) {
		this.schoolInfo = schoolInfo;
	}

	@Column(name = "selfMonthIncome")
	public Double getSelfMonthIncome() {
		return selfMonthIncome;
	}

	public void setSelfMonthIncome(Double selfMonthIncome) {
		this.selfMonthIncome = selfMonthIncome;
	}

	@Column(name = "familyMonthIncome")
	public Double getFamilyMonthIncome() {
		return familyMonthIncome;
	}

	public void setFamilyMonthIncome(Double familyMonthIncome) {
		this.familyMonthIncome = familyMonthIncome;
	}

	@Column(name = "incomeSource")
	public String getIncomeSource() {
		return incomeSource;
	}

	public void setIncomeSource(String incomeSource) {
		this.incomeSource = incomeSource;
	}

	@Column(name = "roomPhone")
	public String getRoomPhone() {
		return roomPhone;
	}

	public void setRoomPhone(String roomPhone) {
		this.roomPhone = roomPhone;
	}

	@Column(name = "familySumQuantity")
	public Integer getFamilySumQuantity() {
		return familySumQuantity;
	}

	public void setFamilySumQuantity(Integer familySumQuantity) {
		this.familySumQuantity = familySumQuantity;
	}

	@Column(name = "marriage")
	public String getMarriage() {
		return marriage;
	}

	public void setMarriage(String marriage) {
		this.marriage = marriage;
	}

	@Column(name = "spouseName")
	public String getSpouseName() {
		return spouseName;
	}

	public void setSpouseName(String spouseName) {
		this.spouseName = spouseName;
	}

	@Column(name = "spouseBornDate")
	public Date getSpouseBornDate() {
		return spouseBornDate;
	}

	public void setSpouseBornDate(Date spouseBornDate) {
		this.spouseBornDate = spouseBornDate;
	}

	@Column(name = "spouseId")
	public String getSpouseId() {
		return spouseId;
	}

	public void setSpouseId(String spouseId) {
		this.spouseId = spouseId;
	}

	@Column(name = "spouseMobile")
	public String getSpouseMobile() {
		return spouseMobile;
	}

	public void setSpouseMobile(String spouseMobile) {
		this.spouseMobile = spouseMobile;
	}

	@Column(name = "spouseUnit")
	public String getSpouseUnit() {
		return spouseUnit;
	}

	public void setSpouseUnit(String spouseUnit) {
		this.spouseUnit = spouseUnit;
	}

	@Column(name = "spouseJobTitle")
	public String getSpouseJobTitle() {
		return spouseJobTitle;
	}

	public void setSpouseJobTitle(String spouseJobTitle) {
		this.spouseJobTitle = spouseJobTitle;
	}

	@Column(name = "spouseUnitPhone")
	public String getSpouseUnitPhone() {
		return spouseUnitPhone;
	}

	public void setSpouseUnitPhone(String spouseUnitPhone) {
		this.spouseUnitPhone = spouseUnitPhone;
	}

	@Column(name = "occupationCode")
	public String getOccupationCode() {
		return occupationCode;
	}

	public void setOccupationCode(String occupationCode) {
		this.occupationCode = occupationCode;
	}

}
