package com.sinosoft.claim.schema.model;

// default package
// Generated 2012-12-29 17:02:41 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.sinosoft.sysframework.common.util.StringUtils;

/**
 * Wflog generated by hbm2java
 */
@Entity
@Table(name = "WFLOG")
public class WfLog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private WfLogId id;
	private Integer modelNo;
	private Integer nodeNo;
	private String nodeName;
	private String deptCode;
	private String deptName;
	private String operatorCode;
	private String operatorName;
	private String flowInTime;
	private Integer timeLimit;
	private String handleTime;
	private String submitTime;
	private String nodeStatus;
	private String flowStatus;
	private String packageId;
	private String businessType;
	private String businessNo;
	private String contractNo;
	private String classCode;
	private String riskCode;
	private String makeCom;
	private String comCode;
	private String handlerCode;
	private String handler1Code;
	private String relateFlowId;
	private Integer relateLogNo;
	private Integer posX;
	private Integer posY;
	private String flag;
	private String licenseNo;
	private String relateContractNo;
	private String riskCategory;
	private String insuredCode;
	private String insuredName;
	private String identifyType;
	private String identifyNumber;
	private String reinsStatus;
	private String policyNo;
	private String claimNo;
	private Double sumAmount;
	private Double sumPremium;
	private String resultCode;
	private String resultContent;
	private String passLevel;
	private String singleCode;
	private String singleMember;
	private String comName = null;
	private String priorType;
	/** 用户代码 */
	private String userCode = "";
	/** 报价单任务状态 */
	private String qtaNodeStatusName = "";
	/** 属性任务状态 */
	private String nodeStatusName = "";
	/** 险种名称 */
	private String riskCodeName = "";

	public WfLog() {
		id = new WfLogId();
	}

	public WfLog(WfLogId id, Integer modelno, Integer nodeno, String nodename, String nodestatus, String flowstatus, String packageid, String businesstype, String businessno, String makecom, String comcode, String handlercode) {
		this.id = id;
		this.modelNo = modelno;
		this.nodeNo = nodeno;
		this.nodeName = nodename;
		this.nodeStatus = nodestatus;
		this.flowStatus = flowstatus;
		this.packageId = packageid;
		this.businessType = businesstype;
		this.businessNo = businessno;
		this.makeCom = makecom;
		this.comCode = comcode;
		this.handlerCode = handlercode;
	}

	public WfLog(WfLogId id, Integer modelno, Integer nodeno, String nodename, String deptcode, String deptname, String operatorcode, String operatorname, String flowintime, int timelimit, String handletime, String submittime, String nodestatus,
			String flowstatus, String packageid, String businesstype, String businessno, String contractno, String classcode, String riskcode, String makecom, String comcode, String handlercode, String handler1code, String relateflowid,
			int relatelogno, Integer posx, Integer posy, String flag, String licenseno, String relatecontractno, String riskcategory, String insuredcode, String insuredname, String identifytype, String identifynumber, String reinsstatus,
			String policyno, String claimno, Double sumamount, Double sumpremium, String resultcode, String resultcontent, String passlevel, String singlecode, String singlemember) {
		this.id = id;
		this.modelNo = modelno;
		this.nodeNo = nodeno;
		this.nodeName = nodename;
		this.deptCode = deptcode;
		this.deptName = deptname;
		this.operatorCode = operatorcode;
		this.operatorName = operatorname;
		this.flowInTime = flowintime;
		this.timeLimit = timelimit;
		this.handleTime = handletime;
		this.submitTime = submittime;
		this.nodeStatus = nodestatus;
		this.flowStatus = flowstatus;
		this.packageId = packageid;
		this.businessType = businesstype;
		this.businessNo = businessno;
		this.contractNo = contractno;
		this.classCode = classcode;
		this.riskCode = riskcode;
		this.makeCom = makecom;
		this.comCode = comcode;
		this.handlerCode = handlercode;
		this.handler1Code = handler1code;
		this.relateFlowId = relateflowid;
		this.relateLogNo = relatelogno;
		this.posX = posx;
		this.posY = posy;
		this.flag = flag;
		this.licenseNo = licenseno;
		this.relateContractNo = relatecontractno;
		this.riskCategory = riskcategory;
		this.insuredCode = insuredcode;
		this.insuredName = insuredname;
		this.identifyType = identifytype;
		this.identifyNumber = identifynumber;
		this.reinsStatus = reinsstatus;
		this.policyNo = policyno;
		this.claimNo = claimno;
		this.sumAmount = sumamount;
		this.sumPremium = sumpremium;
		this.resultCode = resultcode;
		this.resultContent = resultcontent;
		this.passLevel = passlevel;
		this.singleCode = singlecode;
		this.singleMember = singlemember;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "flowId", column = @Column(name = "FLOWID", nullable = false, length = 27)), @AttributeOverride(name = "logNo", column = @Column(name = "LOGNO", nullable = false, precision = 22, scale = 0)) })
	public WfLogId getId() {
		return this.id;
	}

	public void setId(WfLogId id) {
		this.id = id;
	}

	@Column(name = "MODELNO", nullable = false, precision = 22, scale = 0)
	public Integer getModelNo() {
		return this.modelNo;
	}

	public void setModelNo(Integer modelno) {
		this.modelNo = modelno;
	}

	@Column(name = "NODENO", nullable = false, precision = 22, scale = 0)
	public Integer getNodeNo() {
		return this.nodeNo;
	}

	public void setNodeNo(Integer nodeno) {
		this.nodeNo = nodeno;
	}

	@Column(name = "NODENAME", nullable = false, length = 100)
	public String getNodeName() {
		return this.nodeName;
	}

	public void setNodeName(String nodename) {
		this.nodeName = nodename;
	}

	@Column(name = "DEPTCODE", length = 10)
	public String getDeptCode() {
		return this.deptCode;
	}

	public void setDeptCode(String deptcode) {
		this.deptCode = deptcode;
	}

	@Column(name = "DEPTNAME", length = 60)
	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptname) {
		this.deptName = deptname;
	}

	@Column(name = "OPERATORCODE", length = 18)
	public String getOperatorCode() {
		return this.operatorCode;
	}

	public void setOperatorCode(String operatorcode) {
		this.operatorCode = operatorcode;
	}

	@Column(name = "OPERATORNAME", length = 30)
	public String getOperatorName() {
		return this.operatorName;
	}

	public void setOperatorName(String operatorname) {
		this.operatorName = operatorname;
	}

	@Column(name = "FLOWINTIME", length = 19)
	public String getFlowInTime() {
		return this.flowInTime;
	}

	public void setFlowInTime(String flowintime) {
		this.flowInTime = flowintime;
	}

	@Column(name = "TIMELIMIT", precision = 22, scale = 0)
	public Integer getTimeLimit() {
		return this.timeLimit;
	}

	public void setTimeLimit(Integer timelimit) {
		this.timeLimit = timelimit;
	}

	@Column(name = "HANDLETIME", length = 19)
	public String getHandleTime() {
		return this.handleTime;
	}

	public void setHandleTime(String handletime) {
		this.handleTime = handletime;
	}

	@Column(name = "SUBMITTIME", length = 19)
	public String getSubmitTime() {
		return this.submitTime;
	}

	public void setSubmitTime(String submittime) {
		this.submitTime = submittime;
	}

	@Column(name = "NODESTATUS", nullable = false, length = 1)
	public String getNodeStatus() {
		return this.nodeStatus;
	}

	public void setNodeStatus(String nodestatus) {
		this.nodeStatus = nodestatus;
	}

	@Column(name = "FLOWSTATUS", nullable = false, length = 1)
	public String getFlowStatus() {
		return this.flowStatus;
	}

	public void setFlowStatus(String flowstatus) {
		this.flowStatus = flowstatus;
	}

	@Column(name = "PACKAGEID", nullable = false, length = 27)
	public String getPackageId() {
		return this.packageId;
	}

	public void setPackageId(String packageid) {
		this.packageId = packageid;
	}

	@Column(name = "BUSINESSTYPE", nullable = false, length = 1)
	public String getBusinessType() {
		return this.businessType;
	}

	public void setBusinessType(String businesstype) {
		this.businessType = businesstype;
	}

	@Column(name = "BUSINESSNO", nullable = false, length = 25)
	public String getBusinessNo() {
		return this.businessNo;
	}

	public void setBusinessNo(String businessno) {
		this.businessNo = businessno;
	}

	@Column(name = "CONTRACTNO", length = 22)
	public String getContractNo() {
		return this.contractNo;
	}

	public void setContractNo(String contractno) {
		this.contractNo = contractno;
	}

	@Column(name = "CLASSCODE", length = 3)
	public String getClassCode() {
		return this.classCode;
	}

	public void setClassCode(String classcode) {
		this.classCode = classcode;
	}

	@Column(name = "RISKCODE", length = 4)
	public String getRiskCode() {
		return this.riskCode;
	}

	public void setRiskCode(String riskcode) {
		this.riskCode = riskcode;
	}

	@Column(name = "MAKECOM", nullable = false, length = 10)
	public String getMakeCom() {
		return this.makeCom;
	}

	public void setMakeCom(String makecom) {
		this.makeCom = makecom;
	}

	@Column(name = "COMCODE", nullable = false, length = 10)
	public String getComCode() {
		return this.comCode;
	}

	public void setComCode(String comcode) {
		this.comCode = comcode;
	}

	@Column(name = "HANDLERCODE", nullable = false, length = 18)
	public String getHandlerCode() {
		return this.handlerCode;
	}

	public void setHandlerCode(String handlercode) {
		this.handlerCode = handlercode;
	}

	@Column(name = "HANDLER1CODE", length = 18)
	public String getHandler1Code() {
		return this.handler1Code;
	}

	public void setHandler1Code(String handler1code) {
		this.handler1Code = handler1code;
	}

	@Column(name = "RELATEFLOWID", length = 27)
	public String getRelateFlowId() {
		return this.relateFlowId;
	}

	public void setRelateFlowId(String relateflowid) {
		this.relateFlowId = relateflowid;
	}

	@Column(name = "RELATELOGNO", precision = 15, scale = 0)
	public Integer getRelateLogNo() {
		return this.relateLogNo;
	}

	public void setRelateLogNo(Integer relatelogno) {
		this.relateLogNo = relatelogno;
	}

	@Column(name = "POSX", precision = 22, scale = 0)
	public Integer getPosX() {
		return this.posX;
	}

	public void setPosX(Integer posx) {
		this.posX = posx;
	}

	@Column(name = "POSY", precision = 22, scale = 0)
	public Integer getPosY() {
		return this.posY;
	}

	public void setPosY(Integer posy) {
		this.posY = posy;
	}

	@Column(name = "FLAG", length = 10)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Column(name = "LICENSENO", length = 20)
	public String getLicenseNo() {
		return this.licenseNo;
	}

	public void setLicenseNo(String licenseno) {
		this.licenseNo = licenseno;
	}

	@Column(name = "RELATECONTRACTNO", length = 22)
	public String getRelateContractNo() {
		return this.relateContractNo;
	}

	public void setRelateContractNo(String relatecontractno) {
		this.relateContractNo = relatecontractno;
	}

	@Column(name = "RISKCATEGORY", length = 1)
	public String getRiskCategory() {
		return this.riskCategory;
	}

	public void setRiskCategory(String riskcategory) {
		this.riskCategory = riskcategory;
	}

	@Column(name = "INSUREDCODE", length = 20)
	public String getInsuredCode() {
		return this.insuredCode;
	}

	public void setInsuredCode(String insuredcode) {
		this.insuredCode = insuredcode;
	}

	@Column(name = "INSUREDNAME", length = 120)
	public String getInsuredName() {
		return this.insuredName;
	}

	public void setInsuredName(String insuredname) {
		this.insuredName = insuredname;
	}

	@Column(name = "IDENTIFYTYPE", length = 2)
	public String getIdentifyType() {
		return this.identifyType;
	}

	public void setIdentifyType(String identifytype) {
		this.identifyType = identifytype;
	}

	@Column(name = "IDENTIFYNUMBER", length = 20)
	public String getIdentifyNumber() {
		return this.identifyNumber;
	}

	public void setIdentifyNumber(String identifynumber) {
		this.identifyNumber = identifynumber;
	}

	@Column(name = "REINSSTATUS", length = 1)
	public String getReinsStatus() {
		return this.reinsStatus;
	}

	public void setReinsStatus(String reinsstatus) {
		this.reinsStatus = reinsstatus;
	}

	@Column(name = "POLICYNO", length = 22)
	public String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(String policyno) {
		this.policyNo = policyno;
	}

	@Column(name = "CLAIMNO", length = 22)
	public String getClaimNo() {
		return this.claimNo;
	}

	public void setClaimNo(String claimno) {
		this.claimNo = claimno;
	}

	@Column(name = "SUMAMOUNT", precision = 14)
	public Double getSumAmount() {
		return this.sumAmount;
	}

	public void setSumAmount(Double sumamount) {
		this.sumAmount = sumamount;
	}

	@Column(name = "SUMPREMIUM", precision = 14)
	public Double getSumPremium() {
		return this.sumPremium;
	}

	public void setSumPremium(Double sumpremium) {
		this.sumPremium = sumpremium;
	}

	@Column(name = "RESULTCODE", length = 2)
	public String getResultCode() {
		return this.resultCode;
	}

	public void setResultCode(String resultcode) {
		this.resultCode = resultcode;
	}

	@Column(name = "RESULTCONTENT", length = 4000)
	public String getResultContent() {
		return this.resultContent;
	}

	public void setResultContent(String resultcontent) {
		this.resultContent = resultcontent;
	}

	@Column(name = "PASSLEVEL", length = 2)
	public String getPassLevel() {
		return this.passLevel;
	}

	public void setPassLevel(String passlevel) {
		this.passLevel = passlevel;
	}

	@Column(name = "SINGLECODE", length = 30)
	public String getSingleCode() {
		return this.singleCode;
	}

	public void setSingleCode(String singlecode) {
		this.singleCode = singlecode;
	}

	@Column(name = "SINGLEMEMBER", length = 30)
	public String getSingleMember() {
		return this.singleMember;
	}

	public void setSingleMember(String singlemember) {
		this.singleMember = singlemember;
	}

	// @Column(name = "PRIORTYPE", length = 30)
	@Transient
	public String getPriorType() {
		return priorType;
	}

	public void setPriorType(String priorType) {
		this.priorType = priorType;
	}

	@Transient
	public String getComName() {
		return comName;
	}

	public void setComName(String comName) {
		this.comName = comName;
	}

	@Transient
	public String getUserCode() {
		return userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	@Transient
	public String getQtaNodeStatusName() {
		String strNodeStatus = this.getNodeStatus();
		if (strNodeStatus.equals("0"))
			qtaNodeStatusName = "暫存";
		if (strNodeStatus.equals("1"))
			qtaNodeStatusName = "待審核";
		if (strNodeStatus.equals("2"))
			qtaNodeStatusName = "審核駁回";
		if (strNodeStatus.equals("3"))
			qtaNodeStatusName = "審核通過";
		if (strNodeStatus.equals("4"))
			qtaNodeStatusName = "撤回修改";
		if (strNodeStatus.equals("5"))
			qtaNodeStatusName = "已打印";
		if (strNodeStatus.equals("6"))
			qtaNodeStatusName = "投保確認";
		if (strNodeStatus.equals("7"))
			qtaNodeStatusName = "產生要保書";
		if (strNodeStatus.equals("8"))
			qtaNodeStatusName = "核保通過";
		if (strNodeStatus.equals("9"))
			qtaNodeStatusName = "產生保單";
		return qtaNodeStatusName;
	}

	public void setQtaNodeStatusName(String qtaNodeStatusName) {
		this.qtaNodeStatusName = StringUtils.rightTrim(qtaNodeStatusName);
	}

	public void setNodeStatusName(String nodeStatusName) {
		this.nodeStatusName = StringUtils.rightTrim(nodeStatusName);
	}

	@Transient
	public String getNodeStatusName() {
		String strNodeStatus = this.getNodeStatus();
		if (strNodeStatus.equals("1"))
			nodeStatusName = "待處理";
		if (strNodeStatus.equals("2"))
			nodeStatusName = "正在處理";
		if (strNodeStatus.equals("3"))
			nodeStatusName = "已處理未流轉";
		if (strNodeStatus.equals("4"))
			nodeStatusName = "已處理流轉";
		if (strNodeStatus.equals("0"))
			nodeStatusName = "已處理完畢";
		if (strNodeStatus.equals("5"))
			nodeStatusName = "打回";
		return nodeStatusName;
	}
	@Transient
	public String getRiskCodeName() {
		return riskCodeName;
	}

	public void setRiskCodeName(String riskCodeName) {
		this.riskCodeName = riskCodeName;
	}
}
