package com.sinosoft.claim.schema.model;

// Generated 2013-1-10 10:07:17 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Uwmaterial generated by hbm2java
 */
@Entity
@Table(name = "UWMATERIAL")
public class UwMaterial implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private UwMaterialId id;
	private String flowId;
	private String packageId;
	private String fileName;
	private String filePath;
	private String fileType;
	private String description;
	private String operatorCode;
	private String operatorName;
	private String operateTime;
	private String flag;

	public UwMaterial() {
	}

	public UwMaterial(UwMaterialId id, String fileName, String operatorCode, String operateTime) {
		super();
		this.id = id;
		this.fileName = fileName;
		this.operatorCode = operatorCode;
		this.operateTime = operateTime;
	}

	public UwMaterial(UwMaterialId id, String flowId, String packageId, String fileName, String filePath, String fileType, String description, String operatorCode, String operatorName, String operateTime, String flag) {
		super();
		this.id = id;
		this.flowId = flowId;
		this.packageId = packageId;
		this.fileName = fileName;
		this.filePath = filePath;
		this.fileType = fileType;
		this.description = description;
		this.operatorCode = operatorCode;
		this.operatorName = operatorName;
		this.operateTime = operateTime;
		this.flag = flag;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "businessNo", column = @Column(name = "BUSINESSNO", nullable = false, length = 25)), @AttributeOverride(name = "sysfileName", column = @Column(name = "SYSFILENAME", nullable = false, length = 21)) })
	public UwMaterialId getId() {
		return this.id;
	}

	public void setId(UwMaterialId id) {
		this.id = id;
	}

	@Column(name = "FLOWID", length = 25)
	public String getFlowId() {
		return this.flowId;
	}

	public void setFlowId(String flowId) {
		this.flowId = flowId;
	}

	@Column(name = "PACKAGEID", length = 27)
	public String getPackageId() {
		return this.packageId;
	}

	public void setPackageId(String packageId) {
		this.packageId = packageId;
	}

	@Column(name = "FILENAME", nullable = false, length = 50)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "FILEPATH", length = 200)
	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	@Column(name = "FILETYPE", length = 4)
	public String getFileType() {
		return this.fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

	@Column(name = "DESCRIPTION", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "OPERATORCODE", nullable = false, length = 10)
	public String getOperatorCode() {
		return this.operatorCode;
	}

	public void setOperatorCode(String operatorCode) {
		this.operatorCode = operatorCode;
	}

	@Column(name = "OPERATORNAME", length = 30)
	public String getOperatorName() {
		return this.operatorName;
	}

	public void setOperatorName(String operatorName) {
		this.operatorName = operatorName;
	}

	@Column(name = "OPERATETIME", nullable = false, length = 19)
	public String getOperateTime() {
		return this.operateTime;
	}

	public void setOperateTime(String operateTime) {
		this.operateTime = operateTime;
	}

	@Column(name = "FLAG", length = 2)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

}
