package com.sinosoft.claim.schema.model;

// Generated 2013-1-16 9:42:09 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * WfotherFees generated by hbm2java
 */
@Entity
@Table(name = "WFOTHERFEES")
public class WfOtherFees implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private WfOtherFeesId id;
	private String proposalNo;
	private String policyNo;
	private String endorseNo;
	private String otherFee;
	private String lastOtherFee;
	private String operateTime;
	private String operatorCode;
	private String operatorName;
	private String flag;

	public WfOtherFees() {
	}

	public WfOtherFees(WfOtherFeesId id, String otherfee, String lastotherfee, String operatetime, String operatorcode, String operatorname) {
		this.id = id;
		this.otherFee = otherfee;
		this.lastOtherFee = lastotherfee;
		this.operateTime = operatetime;
		this.operatorCode = operatorcode;
		this.operatorName = operatorname;
	}

	public WfOtherFees(WfOtherFeesId id, String proposalno, String policyno, String endorseno, String otherfee, String lastotherfee, String operatetime, String operatorcode, String operatorname, String flag) {
		this.id = id;
		this.proposalNo = proposalno;
		this.policyNo = policyno;
		this.endorseNo = endorseno;
		this.otherFee = otherfee;
		this.lastOtherFee = lastotherfee;
		this.operateTime = operatetime;
		this.operatorCode = operatorcode;
		this.operatorName = operatorname;
		this.flag = flag;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "businessno", column = @Column(name = "BUSINESSNO", nullable = false, length = 25)),
			@AttributeOverride(name = "serialno", column = @Column(name = "SERIALNO", nullable = false, precision = 22, scale = 0)), @AttributeOverride(name = "lineno", column = @Column(name = "LINENO", nullable = false, precision = 22, scale = 0)) })
	public WfOtherFeesId getId() {
		return this.id;
	}

	public void setId(WfOtherFeesId id) {
		this.id = id;
	}

	@Column(name = "PROPOSALNO", length = 25)
	public String getProposalno() {
		return this.proposalNo;
	}

	public void setProposalno(String proposalno) {
		this.proposalNo = proposalno;
	}

	@Column(name = "POLICYNO", length = 25)
	public String getPolicyno() {
		return this.policyNo;
	}

	public void setPolicyno(String policyno) {
		this.policyNo = policyno;
	}

	@Column(name = "ENDORSENO", length = 25)
	public String getEndorseno() {
		return this.endorseNo;
	}

	public void setEndorseno(String endorseno) {
		this.endorseNo = endorseno;
	}

	@Column(name = "OTHERFEE", nullable = false, length = 30)
	public String getOtherfee() {
		return this.otherFee;
	}

	public void setOtherfee(String otherfee) {
		this.otherFee = otherfee;
	}

	@Column(name = "LASTOTHERFEE", nullable = false, length = 30)
	public String getLastotherfee() {
		return this.lastOtherFee;
	}

	public void setLastotherfee(String lastotherfee) {
		this.lastOtherFee = lastotherfee;
	}

	@Column(name = "OPERATETIME", nullable = false, length = 19)
	public String getOperatetime() {
		return this.operateTime;
	}

	public void setOperatetime(String operatetime) {
		this.operateTime = operatetime;
	}

	@Column(name = "OPERATORCODE", nullable = false, length = 10)
	public String getOperatorcode() {
		return this.operatorCode;
	}

	public void setOperatorcode(String operatorcode) {
		this.operatorCode = operatorcode;
	}

	@Column(name = "OPERATORNAME", nullable = false, length = 30)
	public String getOperatorname() {
		return this.operatorName;
	}

	public void setOperatorname(String operatorname) {
		this.operatorName = operatorname;
	}

	@Column(name = "FLAG", length = 2)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

}
