package com.sinosoft.claim.schema.model;

// Generated 2013-1-23 17:09:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * WfPackage generated by hbm2java
 */
@Entity
@Table(name = "WFPACKAGE")
public class WfPackage implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private WfPackageId id;
	private String detailContent;
	private String flag;

	public WfPackage() {
	}

	public WfPackage(WfPackageId id, String detailcontent) {
		this.id = id;
		this.detailContent = detailcontent;
	}

	public WfPackage(WfPackageId id, String detailcontent, String flag) {
		this.id = id;
		this.detailContent = detailcontent;
		this.flag = flag;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "packageid", column = @Column(name = "PACKAGEID", nullable = false, length = 27)),
			@AttributeOverride(name = "detailno", column = @Column(name = "DETAILNO", nullable = false, precision = 15, scale = 0)) })
	public WfPackageId getId() {
		return this.id;
	}

	public void setId(WfPackageId id) {
		this.id = id;
	}

	@Column(name = "DETAILCONTENT", nullable = false, length = 76)
	public String getDetailContent() {
		return this.detailContent;
	}

	public void setDetailContent(String detailcontent) {
		this.detailContent = detailcontent;
	}

	@Column(name = "FLAG", length = 10)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

}
