package com.tlg.msSqlAs400.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.tlg.iBatis.IBatisBaseEntity;

@SuppressWarnings("serial")
public class CtbcClmsmsRm extends IBatisBaseEntity<BigDecimal>{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CTBC_CLMSMS_RM.GOID
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    private String goid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CTBC_CLMSMS_RM.POLICYNO
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    private String policyno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CTBC_CLMSMS_RM.CLAIMNO
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    private String claimno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CTBC_CLMSMS_RM.CLMTIMES
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    private String clmtimes;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CTBC_CLMSMS_RM.INSUREDNAME
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    private String insuredname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CTBC_CLMSMS_RM.DAMAGEDATE
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    private Date damagedate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CTBC_CLMSMS_RM.CLMPAY
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    private Long clmpay;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CTBC_CLMSMS_RM.CLMFEE
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    private Long clmfee;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CTBC_CLMSMS_RM.HANDLERNAME
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    private String handlername;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CTBC_CLMSMS_RM.SUBMITDATE
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    private Date submitdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CTBC_CLMSMS_RM.IMSCHECKDATE
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    private Date imscheckdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CTBC_CLMSMS_RM.MAKEDATE
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    private Date makedate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CTBC_CLMSMS_RM.PAYMETHOD
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    private String paymethod;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CTBC_CLMSMS_RM.PAYACOUNTNAME
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    private String payacountname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CTBC_CLMSMS_RM.PAYACOUNTID
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    private String payacountid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CTBC_CLMSMS_RM.PAYPHONE
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    private String payphone;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CTBC_CLMSMS_RM.PAYACOUNT
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    private String payacount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CTBC_CLMSMS_RM.PAYBANKNAME
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    private String paybankname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CTBC_CLMSMS_RM.CLMPAYDATE
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    private Date clmpaydate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CTBC_CLMSMS_RM.NEWIMS
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    private String newims;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CTBC_CLMSMS_RM.CREATDATE
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    private Date creatdate;
    

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CTBC_CLMSMS_RM.PDFMAKEDATE
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    private Date pdfmakedate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CTBC_CLMSMS_RM.MSGURL
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    private String msgurl;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CTBC_CLMSMS_RM.OUTMSG
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    private String outmsg;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CTBC_CLMSMS_RM.MSGSENDMARK
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    private String msgsendmark;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CTBC_CLMSMS_RM.MSGSENDDATE
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    private Date msgsenddate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CTBC_CLMSMS_RM.GOID
     *
     * @return the value of CTBC_CLMSMS_RM.GOID
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public String getGoid() {
        return goid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CTBC_CLMSMS_RM.GOID
     *
     * @param goid the value for CTBC_CLMSMS_RM.GOID
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public void setGoid(String goid) {
        this.goid = goid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CTBC_CLMSMS_RM.POLICYNO
     *
     * @return the value of CTBC_CLMSMS_RM.POLICYNO
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public String getPolicyno() {
        return policyno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CTBC_CLMSMS_RM.POLICYNO
     *
     * @param policyno the value for CTBC_CLMSMS_RM.POLICYNO
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public void setPolicyno(String policyno) {
        this.policyno = policyno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CTBC_CLMSMS_RM.CLAIMNO
     *
     * @return the value of CTBC_CLMSMS_RM.CLAIMNO
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public String getClaimno() {
        return claimno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CTBC_CLMSMS_RM.CLAIMNO
     *
     * @param claimno the value for CTBC_CLMSMS_RM.CLAIMNO
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public void setClaimno(String claimno) {
        this.claimno = claimno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CTBC_CLMSMS_RM.CLMTIMES
     *
     * @return the value of CTBC_CLMSMS_RM.CLMTIMES
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public String getClmtimes() {
        return clmtimes;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CTBC_CLMSMS_RM.CLMTIMES
     *
     * @param clmtimes the value for CTBC_CLMSMS_RM.CLMTIMES
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public void setClmtimes(String clmtimes) {
        this.clmtimes = clmtimes;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CTBC_CLMSMS_RM.INSUREDNAME
     *
     * @return the value of CTBC_CLMSMS_RM.INSUREDNAME
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public String getInsuredname() {
        return insuredname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CTBC_CLMSMS_RM.INSUREDNAME
     *
     * @param insuredname the value for CTBC_CLMSMS_RM.INSUREDNAME
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public void setInsuredname(String insuredname) {
        this.insuredname = insuredname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CTBC_CLMSMS_RM.DAMAGEDATE
     *
     * @return the value of CTBC_CLMSMS_RM.DAMAGEDATE
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public Date getDamagedate() {
        return damagedate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CTBC_CLMSMS_RM.DAMAGEDATE
     *
     * @param damagedate the value for CTBC_CLMSMS_RM.DAMAGEDATE
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public void setDamagedate(Date damagedate) {
        this.damagedate = damagedate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CTBC_CLMSMS_RM.CLMPAY
     *
     * @return the value of CTBC_CLMSMS_RM.CLMPAY
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public Long getClmpay() {
        return clmpay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CTBC_CLMSMS_RM.CLMPAY
     *
     * @param clmpay the value for CTBC_CLMSMS_RM.CLMPAY
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public void setClmpay(Long clmpay) {
        this.clmpay = clmpay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CTBC_CLMSMS_RM.CLMFEE
     *
     * @return the value of CTBC_CLMSMS_RM.CLMFEE
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public Long getClmfee() {
        return clmfee;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CTBC_CLMSMS_RM.CLMFEE
     *
     * @param clmfee the value for CTBC_CLMSMS_RM.CLMFEE
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public void setClmfee(Long clmfee) {
        this.clmfee = clmfee;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CTBC_CLMSMS_RM.HANDLERNAME
     *
     * @return the value of CTBC_CLMSMS_RM.HANDLERNAME
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public String getHandlername() {
        return handlername;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CTBC_CLMSMS_RM.HANDLERNAME
     *
     * @param handlername the value for CTBC_CLMSMS_RM.HANDLERNAME
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public void setHandlername(String handlername) {
        this.handlername = handlername;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CTBC_CLMSMS_RM.SUBMITDATE
     *
     * @return the value of CTBC_CLMSMS_RM.SUBMITDATE
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public Date getSubmitdate() {
        return submitdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CTBC_CLMSMS_RM.SUBMITDATE
     *
     * @param submitdate the value for CTBC_CLMSMS_RM.SUBMITDATE
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public void setSubmitdate(Date submitdate) {
        this.submitdate = submitdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CTBC_CLMSMS_RM.IMSCHECKDATE
     *
     * @return the value of CTBC_CLMSMS_RM.IMSCHECKDATE
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public Date getImscheckdate() {
        return imscheckdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CTBC_CLMSMS_RM.IMSCHECKDATE
     *
     * @param imscheckdate the value for CTBC_CLMSMS_RM.IMSCHECKDATE
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public void setImscheckdate(Date imscheckdate) {
        this.imscheckdate = imscheckdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CTBC_CLMSMS_RM.MAKEDATE
     *
     * @return the value of CTBC_CLMSMS_RM.MAKEDATE
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public Date getMakedate() {
        return makedate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CTBC_CLMSMS_RM.MAKEDATE
     *
     * @param makedate the value for CTBC_CLMSMS_RM.MAKEDATE
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public void setMakedate(Date makedate) {
        this.makedate = makedate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CTBC_CLMSMS_RM.PAYMETHOD
     *
     * @return the value of CTBC_CLMSMS_RM.PAYMETHOD
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public String getPaymethod() {
        return paymethod;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CTBC_CLMSMS_RM.PAYMETHOD
     *
     * @param paymethod the value for CTBC_CLMSMS_RM.PAYMETHOD
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public void setPaymethod(String paymethod) {
        this.paymethod = paymethod;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CTBC_CLMSMS_RM.PAYACOUNTNAME
     *
     * @return the value of CTBC_CLMSMS_RM.PAYACOUNTNAME
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public String getPayacountname() {
        return payacountname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CTBC_CLMSMS_RM.PAYACOUNTNAME
     *
     * @param payacountname the value for CTBC_CLMSMS_RM.PAYACOUNTNAME
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public void setPayacountname(String payacountname) {
        this.payacountname = payacountname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CTBC_CLMSMS_RM.PAYACOUNTID
     *
     * @return the value of CTBC_CLMSMS_RM.PAYACOUNTID
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public String getPayacountid() {
        return payacountid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CTBC_CLMSMS_RM.PAYACOUNTID
     *
     * @param payacountid the value for CTBC_CLMSMS_RM.PAYACOUNTID
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public void setPayacountid(String payacountid) {
        this.payacountid = payacountid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CTBC_CLMSMS_RM.PAYPHONE
     *
     * @return the value of CTBC_CLMSMS_RM.PAYPHONE
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public String getPayphone() {
        return payphone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CTBC_CLMSMS_RM.PAYPHONE
     *
     * @param payphone the value for CTBC_CLMSMS_RM.PAYPHONE
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public void setPayphone(String payphone) {
        this.payphone = payphone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CTBC_CLMSMS_RM.PAYACOUNT
     *
     * @return the value of CTBC_CLMSMS_RM.PAYACOUNT
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public String getPayacount() {
        return payacount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CTBC_CLMSMS_RM.PAYACOUNT
     *
     * @param payacount the value for CTBC_CLMSMS_RM.PAYACOUNT
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public void setPayacount(String payacount) {
        this.payacount = payacount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CTBC_CLMSMS_RM.PAYBANKNAME
     *
     * @return the value of CTBC_CLMSMS_RM.PAYBANKNAME
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public String getPaybankname() {
        return paybankname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CTBC_CLMSMS_RM.PAYBANKNAME
     *
     * @param paybankname the value for CTBC_CLMSMS_RM.PAYBANKNAME
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public void setPaybankname(String paybankname) {
        this.paybankname = paybankname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CTBC_CLMSMS_RM.CLMPAYDATE
     *
     * @return the value of CTBC_CLMSMS_RM.CLMPAYDATE
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public Date getClmpaydate() {
        return clmpaydate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CTBC_CLMSMS_RM.CLMPAYDATE
     *
     * @param clmpaydate the value for CTBC_CLMSMS_RM.CLMPAYDATE
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public void setClmpaydate(Date clmpaydate) {
        this.clmpaydate = clmpaydate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CTBC_CLMSMS_RM.NEWIMS
     *
     * @return the value of CTBC_CLMSMS_RM.NEWIMS
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public String getNewims() {
        return newims;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CTBC_CLMSMS_RM.NEWIMS
     *
     * @param newims the value for CTBC_CLMSMS_RM.NEWIMS
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public void setNewims(String newims) {
        this.newims = newims;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CTBC_CLMSMS_RM.CREATDATE
     *
     * @return the value of CTBC_CLMSMS_RM.CREATDATE
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public Date getCreatdate() {
        return creatdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CTBC_CLMSMS_RM.CREATDATE
     *
     * @param creatdate the value for CTBC_CLMSMS_RM.CREATDATE
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public void setCreatdate(Date creatdate) {
        this.creatdate = creatdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CTBC_CLMSMS_RM.PDFMAKEDATE
     *
     * @return the value of CTBC_CLMSMS_RM.PDFMAKEDATE
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public Date getPdfmakedate() {
        return pdfmakedate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CTBC_CLMSMS_RM.PDFMAKEDATE
     *
     * @param pdfmakedate the value for CTBC_CLMSMS_RM.PDFMAKEDATE
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public void setPdfmakedate(Date pdfmakedate) {
        this.pdfmakedate = pdfmakedate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CTBC_CLMSMS_RM.MSGURL
     *
     * @return the value of CTBC_CLMSMS_RM.MSGURL
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public String getMsgurl() {
        return msgurl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CTBC_CLMSMS_RM.MSGURL
     *
     * @param msgurl the value for CTBC_CLMSMS_RM.MSGURL
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public void setMsgurl(String msgurl) {
        this.msgurl = msgurl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CTBC_CLMSMS_RM.OUTMSG
     *
     * @return the value of CTBC_CLMSMS_RM.OUTMSG
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public String getOutmsg() {
        return outmsg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CTBC_CLMSMS_RM.OUTMSG
     *
     * @param outmsg the value for CTBC_CLMSMS_RM.OUTMSG
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public void setOutmsg(String outmsg) {
        this.outmsg = outmsg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CTBC_CLMSMS_RM.MSGSENDMARK
     *
     * @return the value of CTBC_CLMSMS_RM.MSGSENDMARK
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public String getMsgsendmark() {
        return msgsendmark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CTBC_CLMSMS_RM.MSGSENDMARK
     *
     * @param msgsendmark the value for CTBC_CLMSMS_RM.MSGSENDMARK
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public void setMsgsendmark(String msgsendmark) {
        this.msgsendmark = msgsendmark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CTBC_CLMSMS_RM.MSGSENDDATE
     *
     * @return the value of CTBC_CLMSMS_RM.MSGSENDDATE
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public Date getMsgsenddate() {
        return msgsenddate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CTBC_CLMSMS_RM.MSGSENDDATE
     *
     * @param msgsenddate the value for CTBC_CLMSMS_RM.MSGSENDDATE
     *
     * @ibatorgenerated Thu Oct 12 18:46:46 CST 2023
     */
    public void setMsgsenddate(Date msgsenddate) {
        this.msgsenddate = msgsenddate;
    }
    
}