# This is the configuring for logging displayed in the Application Server

# *****************console infomation*****************

# *****************log file infomation*****************

# UNCATEGORIZED

log4j.rootCategory=info, UNCATEGORIZED
log4j.appender.UNCATEGORIZED=org.apache.log4j.FileAppender
log4j.appender.UNCATEGORIZED.MaxFileSize=10MB
log4j.appender.UNCATEGORIZED.MaxBackupIndex=5
log4j.appender.UNCATEGORIZED.File=log/uncategorized.log
log4j.appender.UNCATEGORIZED.layout=org.apache.log4j.PatternLayout
log4j.appender.UNCATEGORIZED.layout.ConversionPattern=%d %p [%c %L] - <%m>%n


#Hibernate
log4j.category.org.hibernate=info, HIBERNATE 
log4j.additivity.org.hibernate=false
log4j.appender.HIBERNATE=org.apache.log4j.FileAppender
log4j.appender.HIBERNATE.MaxFileSize=10MB
log4j.appender.HIBERNATE.MaxBackupIndex=5
log4j.appender.HIBERNATE.File=log/hibernate.log
log4j.appender.HIBERNATE.layout=org.apache.log4j.PatternLayout
log4j.appender.HIBERNATE.layout.ConversionPattern=%d %-5p [%t] %c{1}: %m%n

#spring
log4j.category.org.springframework=info, SPRING
log4j.additivity.org.springframework=false
log4j.appender.SPRING=org.apache.log4j.FileAppender
log4j.appender.SPRING.MaxFileSize=10MB
log4j.appender.SPRING.MaxBackupIndex=5
log4j.appender.SPRING.File=log/spring.log
log4j.appender.SPRING.layout=org.apache.log4j.PatternLayout
log4j.appender.SPRING.layout.ConversionPattern=%d %-5p [%t] %c{1}: %m%n

#struts
log4j.category.org.apache.struts2=info, STRUTS 
log4j.additivity.org.apache.struts2=false
log4j.appender.STRUTS=org.apache.log4j.FileAppender
log4j.appender.STRUTS.MaxFileSize=10MB
log4j.appender.STRUTS.MaxBackupIndex=5
log4j.appender.STRUTS.File=log/struts.log
log4j.appender.STRUTS.layout=org.apache.log4j.PatternLayout
log4j.appender.STRUTS.layout.ConversionPattern=%d %-5p [%t] %c{1}: %m%n

#acegi
log4j.category.org.acegisecurity=info, ACEGI 
log4j.additivity.org.acegisecurity=false
log4j.appender.ACEGI=org.apache.log4j.FileAppender
log4j.appender.ACEGI.MaxFileSize=10MB
log4j.appender.ACEGI.MaxBackupIndex=5
log4j.appender.ACEGI.File=log/acegi.log
log4j.appender.ACEGI.layout=org.apache.log4j.PatternLayout
log4j.appender.ACEGI.layout.ConversionPattern=%d %-5p [%t] %c{1}: %m%n

#arch4
log4j.category.ins.framework=info, ARCH4 
log4j.additivity.ins.framework=false
log4j.appender.ARCH4=org.apache.log4j.FileAppender
log4j.appender.ARCH4.MaxFileSize=10MB
log4j.appender.ARCH4.MaxBackupIndex=5
log4j.appender.ARCH4.File=log/arch4.log
log4j.appender.ARCH4.layout=org.apache.log4j.PatternLayout
log4j.appender.ARCH4.layout.ConversionPattern=%d %p [%c %L] - <%m>%n


#xwork2
log4j.category.com.opensymphony.xwork2.interceptor.TimerInterceptor=info, XWORK2
log4j.additivity.com.opensymphony.xwork2.interceptor.TimerInterceptor=false
log4j.appender.XWORK2=org.apache.log4j.FileAppender
log4j.appender.XWORK2.MaxFileSize=10MB
log4j.appender.XWORK2.MaxBackupIndex=5
log4j.appender.XWORK2.File=log/xwork2.log
log4j.appender.XWORK2.layout=org.apache.log4j.PatternLayout
log4j.appender.XWORK2.layout.ConversionPattern=%d %p [%c %L] - <%m>%n

#dwr
log4j.category.org.directwebremoting=info, DWR 
log4j.additivity.org.directwebremoting=false
log4j.appender.DWR=org.apache.log4j.FileAppender
log4j.appender.DWR.MaxFileSize=10MB
log4j.appender.DWR.MaxBackupIndex=5
log4j.appender.DWR.File=log/dwr.log
log4j.appender.DWR.layout=org.apache.log4j.PatternLayout
log4j.appender.DWR.layout.ConversionPattern=%d %p [%c %L] - <%m>%n

#session
log4j.category.cn.com.picc.claim.common.web.ClaimHttpSessionListener=info, SESSION
log4j.additivity.cn.com.picc.claim.common.web.ClaimHttpSessionListener=false
log4j.appender.SESSION=org.apache.log4j.FileAppender
log4j.appender.SESSION.MaxFileSize=10MB
log4j.appender.SESSION.MaxBackupIndex=5
log4j.appender.SESSION.File=log/session.log
log4j.appender.SESSION.layout=org.apache.log4j.PatternLayout
log4j.appender.SESSION.layout.ConversionPattern=%d %p [%c %L] - <%m>%n


#cache
log4j.category.ins.framework.cache=info, CACHE 
log4j.additivity.ins.framework.cache=false
log4j.appender.CACHE=org.apache.log4j.ConsoleAppender
log4j.appender.CACHE.MaxFileSize=10MB
log4j.appender.CACHE.MaxBackupIndex=5
log4j.appender.CACHE.File=log/cache.log
log4j.appender.CACHE.layout=org.apache.log4j.PatternLayout
log4j.appender.CACHE.layout.ConversionPattern=%d %p [%c %L] - <%m>%n

#ehcache
log4j.category.net.sf.ehcache=info, EHCACHE 
log4j.additivity.net.sf.ehcache=false
log4j.appender.EHCACHE=org.apache.log4j.ConsoleAppender
log4j.appender.EHCACHE.layout=org.apache.log4j.PatternLayout
log4j.appender.EHCACHE.layout.ConversionPattern=%d %p [%c %L] - <%m>%n


#exception
log4j.category.ins.arch4platform.common.ExceptionMessageBean=info, EXCEPTION 
log4j.additivity.ins.arch4platform.common.ExceptionMessageBean=false
log4j.appender.EXCEPTION=org.apache.log4j.FileAppender
log4j.appender.EXCEPTION.MaxFileSize=20MB
log4j.appender.EXCEPTION.MaxBackupIndex=5
log4j.appender.EXCEPTION.File=log/exception.log
log4j.appender.EXCEPTION.layout=org.apache.log4j.PatternLayout
log4j.appender.EXCEPTION.layout.ConversionPattern=%d %p [%c %L] - <%m>%n

#jbpm
log4j.category.org.jbpm=info, JBPM 
log4j.additivity.org.jbpm=false
log4j.appender.JBPM=org.apache.log4j.FileAppender
log4j.appender.JBPM.MaxFileSize=20MB
log4j.appender.JBPM.MaxBackupIndex=5
log4j.appender.JBPM.File=log/jbpm.log
log4j.appender.JBPM.layout=org.apache.log4j.PatternLayout
log4j.appender.JBPM.layout.ConversionPattern=%d %p [%c %L] - <%m>%n

#user
log4j.category.cn.com.sinosoft=info, PLATFORM, PLATFORMFILE
log4j.additivity.cn.com.sinosoft=false
log4j.appender.PLATFORM=org.apache.log4j.ConsoleAppender
log4j.appender.PLATFORM.layout=org.apache.log4j.PatternLayout
log4j.appender.PLATFORM.layout.ConversionPattern=%d %p [%c %L] - <%m>%n

log4j.appender.PLATFORMFILE=org.apache.log4j.FileAppender
log4j.appender.PLATFORMFILE.MaxFileSize=20MB
log4j.appender.PLATFORMFILE.MaxBackupIndex=5
log4j.appender.PLATFORMFILE.File=log/console.log
log4j.appender.PLATFORMFILE.layout=org.apache.log4j.PatternLayout
log4j.appender.PLATFORMFILE.layout.ConversionPattern=%d %p [%c %L] - <%m>%n

#dictdriver
#log4j.category.com.sinosoft=info,CONSOLE
#log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender 
#log4j.appender.Threshold=DEBUG 
#log4j.appender.CONSOLE.Target=System.out 
#log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout 
#log4j.appender.CONSOLE.layout.ConversionPattern=[DictDriver:]  %-5p  - %m%n 

#out sql for test
log4j.category.cn.com.sinosoft.inf=info,DMSFILE
log4j.additivity.cn.com.sinosoft.inf=false
log4j.appender.DMSFILE=org.apache.log4j.FileAppender 
log4j.appender.DMSFILE.MaxFileSize=10MB
log4j.appender.DMSFILE.MaxBackupIndex=5
log4j.appender.DMSFILE.File=log/dmsinf.log
log4j.appender.DMSFILE.Append=true
log4j.appender.DMSFILE.layout=org.apache.log4j.PatternLayout 
log4j.appender.DMSFILE.layout.ConversionPattern=[DMSINF] %d - %c -%-4r [%t] %-5p %c %x - %m%n 
