
validator.Required.ClassName=ins.platform.validator.tool.va.RequiredValidator
validator.Required.name=required
validator.Required.Msg=errors.required
validator.Required.Method=validateRequired
validator.Required.MethodParams=java.lang.Object,org.apache.commons.validator.Field