package cn.com.sinosoft.dms.model;

// Generated by Hibernate Tools 3.2.0.b9 (sinosoft version)

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.Type;

/**
 * PrpDriskShortRate generated by Tools.Don't edit.
 */
@Entity
@Table(name = "prpdriskshortrate")
public class PrpDriskShortRate implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	/** 序号 */
	private PrpDriskShortRateId id;
	/** 旧短期费率代码 */
	private String oldShortRateID;
	/** 短期费率名称 */
	private String shortRateName;
	/** 短期费率类型 */
	private String rateType;
	/** 下限计算符 */
	private String lowerOperator;
	/** 下限 */
	private BigDecimal lower;
	/** 上限计算符 */
	private String upperOperator;
	/** 上限 */
	private BigDecimal upper;
	/** 短期费率方式类型 */
	private String modeType;
	/** 实际承保下限计算符 */
	private String actualLowerOperator;
	/** 实际承???时间下限 */
	private BigDecimal actualLower;
	/** 实际承保上限计算符 */
	private String actuaUpperOperator;
	/** 实际承保时间上限 */
	private BigDecimal actuaUpper;
	/** 短期费率分子 */
	private BigDecimal shortRateNumerator;
	/** 短期费率分母 */
	private BigDecimal shortRateDenominator;
	/** 生效日期 */
	private Date validDate;
	/** 失效日期 */
	private Date invalidDate;
	/** 有效标志 */
	private String validInd;
	/** 预留字段1 */
	private String tcol1;
	/** 预留字段2 */
	private String tcol2;
	/** 预留字段3 */
	private String tcol3;
	/** 备注 */
	private String remark;
	/** 标志字段 */
	private String flag;

	public PrpDriskShortRate() {
	}

	/**       
	 * 序号
	 */
	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "riskCode", column = @Column(name = "riskcode")),
			@AttributeOverride(name = "shortRateID", column = @Column(name = "shortrateid")),
			@AttributeOverride(name = "clauseCode", column = @Column(name = "clausecode")),
			@AttributeOverride(name = "serialNo", column = @Column(name = "serialno")) })
	public PrpDriskShortRateId getId() {
		return this.id;
	}

	public void setId(PrpDriskShortRateId id) {
		this.id = id;
	}

	/**       
	 * 旧短期费率代码
	 */

	@Column(name = "oldshortrateid")
	public String getOldShortRateID() {
		return this.oldShortRateID;
	}

	public void setOldShortRateID(String oldShortRateID) {
		this.oldShortRateID = oldShortRateID;
	}

	/**       
	 * 短期费率名称
	 */

	@Column(name = "shortratename")
	public String getShortRateName() {
		return this.shortRateName;
	}

	public void setShortRateName(String shortRateName) {
		this.shortRateName = shortRateName;
	}

	/**       
	 * 短期费率类型
	 */

	@Column(name = "ratetype")
	public String getRateType() {
		return this.rateType;
	}

	public void setRateType(String rateType) {
		this.rateType = rateType;
	}

	/**       
	 * 下限计算符
	 */

	@Column(name = "loweroperator")
	public String getLowerOperator() {
		return this.lowerOperator;
	}

	public void setLowerOperator(String lowerOperator) {
		this.lowerOperator = lowerOperator;
	}

	/**       
	 * 下限
	 */

	@Column(name = "lower")
	public BigDecimal getLower() {
		return this.lower;
	}

	public void setLower(BigDecimal lower) {
		this.lower = lower;
	}

	/**       
	 * 上限计算符
	 */

	@Column(name = "upperoperator")
	public String getUpperOperator() {
		return this.upperOperator;
	}

	public void setUpperOperator(String upperOperator) {
		this.upperOperator = upperOperator;
	}

	/**       
	 * 上限
	 */

	@Column(name = "upper")
	public BigDecimal getUpper() {
		return this.upper;
	}

	public void setUpper(BigDecimal upper) {
		this.upper = upper;
	}

	/**       
	 * 短期费率方式类型
	 */

	@Column(name = "modetype")
	public String getModeType() {
		return this.modeType;
	}

	public void setModeType(String modeType) {
		this.modeType = modeType;
	}

	/**       
	 * 实际承保下限计算符
	 */

	@Column(name = "actualloweroperator")
	public String getActualLowerOperator() {
		return this.actualLowerOperator;
	}

	public void setActualLowerOperator(String actualLowerOperator) {
		this.actualLowerOperator = actualLowerOperator;
	}

	/**       
	 * 实际承???时间下限
	 */

	@Column(name = "actuallower")
	public BigDecimal getActualLower() {
		return this.actualLower;
	}

	public void setActualLower(BigDecimal actualLower) {
		this.actualLower = actualLower;
	}

	/**       
	 * 实际承保上限计算符
	 */

	@Column(name = "actuaupperoperator")
	public String getActuaUpperOperator() {
		return this.actuaUpperOperator;
	}

	public void setActuaUpperOperator(String actuaUpperOperator) {
		this.actuaUpperOperator = actuaUpperOperator;
	}

	/**       
	 * 实际承保时间上限
	 */

	@Column(name = "actuaupper")
	public BigDecimal getActuaUpper() {
		return this.actuaUpper;
	}

	public void setActuaUpper(BigDecimal actuaUpper) {
		this.actuaUpper = actuaUpper;
	}

	/**       
	 * 短期费率分子
	 */

	@Column(name = "shortratenumerator")
	public BigDecimal getShortRateNumerator() {
		return this.shortRateNumerator;
	}

	public void setShortRateNumerator(BigDecimal shortRateNumerator) {
		this.shortRateNumerator = shortRateNumerator;
	}

	/**       
	 * 短期费率分母
	 */

	@Column(name = "shortratedenominator")
	public BigDecimal getShortRateDenominator() {
		return this.shortRateDenominator;
	}

	public void setShortRateDenominator(BigDecimal shortRateDenominator) {
		this.shortRateDenominator = shortRateDenominator;
	}

	/**       
	 * 生效日期
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "validdate")
	public Date getValidDate() {
		return this.validDate;
	}

	public void setValidDate(Date validDate) {
		this.validDate = validDate;
	}

	/**       
	 * 失效日期
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "invaliddate")
	public Date getInvalidDate() {
		return this.invalidDate;
	}

	public void setInvalidDate(Date invalidDate) {
		this.invalidDate = invalidDate;
	}

	/**       
	 * 有效标志
	 */

	@Column(name = "validind")
	public String getValidInd() {
		return this.validInd;
	}

	public void setValidInd(String validInd) {
		this.validInd = validInd;
	}

	/**       
	 * 预留字段1
	 */

	@Column(name = "tcol1")
	public String getTcol1() {
		return this.tcol1;
	}

	public void setTcol1(String tcol1) {
		this.tcol1 = tcol1;
	}

	/**       
	 * 预留字段2
	 */

	@Column(name = "tcol2")
	public String getTcol2() {
		return this.tcol2;
	}

	public void setTcol2(String tcol2) {
		this.tcol2 = tcol2;
	}

	/**       
	 * 预留字段3
	 */

	@Column(name = "tcol3")
	public String getTcol3() {
		return this.tcol3;
	}

	public void setTcol3(String tcol3) {
		this.tcol3 = tcol3;
	}

	/**       
	 * 备注
	 */

	@Column(name = "remark")
	@Basic(fetch = FetchType.LAZY)
	@Type(type = "org.springframework.orm.hibernate3.support.ClobStringType")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**       
	 * 标志字段
	 */

	@Column(name = "flag")
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

}
