
package com.tlg.aps.webService.corePolicyService.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2024-05-15T14:31:36.524+08:00
 * Generated source version: 2.7.10
 * 
 */
public final class CheckPolicyService_CheckPolicyWebServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.webServices.tlg.com/", "CheckPolicyWebServiceService");

    private CheckPolicyService_CheckPolicyWebServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CheckPolicyWebServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CheckPolicyWebServiceService ss = new CheckPolicyWebServiceService(wsdlURL, SERVICE_NAME);
        CheckPolicyService port = ss.getCheckPolicyWebServicePort();  
        
        {
        System.out.println("Invoking checkBusinessSales...");
        BusinessSalesRequestVo _checkBusinessSales_checkBusinessSales = null;
        try {
            BusinessSalesResultVo _checkBusinessSales__return = port.checkBusinessSales(_checkBusinessSales_checkBusinessSales);
            System.out.println("checkBusinessSales.result=" + _checkBusinessSales__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
